Flood: Flood::RandomSearch Class Reference
Flood::RandomSearch Class Reference
#include <RandomSearch.h>
Public Member Functions
RandomSearch (ObjectiveFunctional *)
RandomSearch (void)
virtual ~RandomSearch (void)
Destructor.
Vector< double > getMinimumValueOfFreeParameters (void)
This method returns the minimum values for all the free parameters in the search hypercube.
Vector< double > getMaximumValueOfFreeParameters (void)
This method returns the maximum values for all the free parameters in the search hypercube.
Matrix< double > getMinimumAndMaximumValuesOfFreeParameters (void)
void setMinimumValueOfFreeParameters (Vector< double >)
void setMaximumValueOfFreeParameters (Vector< double >)
void setMinimumAndMaximumValuesOfFreeParameters (Matrix< double >)
void train (void)
void print (void)
void load (char *)
void save (char *)
void resizeTrainingHistory (int)
void setReserveAllTrainingHistory (bool)
void saveTrainingHistory (char *)
Private Attributes
Vector< double > minimumValueOfFreeParameters
Minimum values for all the free parameters in the seach hypercube.
Vector< double > maximumValueOfFreeParameters
Maximum values for all the free parameters in the seach hypercube.
Detailed Description
This concrete class represents a random search training algorithm for an objective functional of a multilayer perceptron.
See also:
TrainingAlgorithm.
Definition at line 30 of file RandomSearch.h.
Constructor & Destructor Documentation
Flood::RandomSearch::RandomSearch (ObjectiveFunctional * newObjectiveFunctional)
General constructor. It creates a random search training algorithm object associated to an objective functional object. It also initializes the class members to their default values:
Training parameters:
Minimum value of free parameters: -1.0.
Maximum value of free parameters: 1.0.
Stopping criteria:
Evaluation goal: -1.0e99.
Maximum time: 1.0e6.
Maximum number of epochs: 100.
User stuff:
Display: true.
Display period: 25.
Parameters:
newObjectiveFunctional Pointer to an objective functional object.
Definition at line 55 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, maximumValueOfFreeParameters, minimumValueOfFreeParameters, and Flood::TrainingAlgorithm::objectiveFunctional.
Flood::RandomSearch::RandomSearch (void)
Default constructor. It creates a random search training algorithm object not associated to any objective functional object. It also initializes the class members to their default values:
Stopping criteria:
Evaluation goal: -1.0e99.
Maximum training time: 1.0e6.
Maximum number of epochs: 100.
User stuff:
Display: true.
Display period: 10.
Definition at line 107 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
Flood::RandomSearch::~RandomSearch (void) [virtual]
Destructor.
Definition at line 125 of file RandomSearch.cpp.
Member Function Documentation
Vector< double > Flood::RandomSearch::getMinimumValueOfFreeParameters (void)
This method returns the minimum values for all the free parameters in the search hypercube.
Definition at line 135 of file RandomSearch.cpp.
References minimumValueOfFreeParameters.
Vector< double > Flood::RandomSearch::getMaximumValueOfFreeParameters (void)
This method returns the maximum values for all the free parameters in the search hypercube.
Definition at line 144 of file RandomSearch.cpp.
References maximumValueOfFreeParameters.
Matrix< double > Flood::RandomSearch::getMinimumAndMaximumValuesOfFreeParameters (void)
This method returns a single matrix containing the maximum and minimum values for all the free parameters in the search hypercube. The first row contains the minimum value of the free parameters. The first row contains the maximum value of the free parameters.
See also:
getMinimumValueOfFreeParameters(void).
getMaximumValueOfFreeParameters(void).
Definition at line 159 of file RandomSearch.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), maximumValueOfFreeParameters, minimumValueOfFreeParameters, Flood::TrainingAlgorithm::objectiveFunctional, and Flood::Matrix< Type >::setRow().
void Flood::RandomSearch::setMinimumValueOfFreeParameters (Vector< double > newMinimumValueOfFreeParameters)
This method sets the minimum values for all the free parameters in the search hypercube.
Parameters:
newMinimumValueOfFreeParameters
Definition at line 182 of file RandomSearch.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), maximumValueOfFreeParameters, minimumValueOfFreeParameters, and Flood::TrainingAlgorithm::objectiveFunctional.
void Flood::RandomSearch::setMaximumValueOfFreeParameters (Vector< double > newMaximumValueOfFreeParameters)
This method sets the maximum values for all the free parameters in the search hypercube.
Parameters:
newMaximumValueOfFreeParameters
Definition at line 236 of file RandomSearch.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), maximumValueOfFreeParameters, minimumValueOfFreeParameters, and Flood::TrainingAlgorithm::objectiveFunctional.
void Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters (Matrix< double > newMinimumAndMaximumValuesOfFreeParameters)
This method sets both the minimum and the maximum values for all the free parameters in the search hypercube from a single matrix. The first row must contain the minimum values for the free parameters. The second row must contain the maximum values for the free parameters.
Parameters:
newMinimumAndMaximumValuesOfFreeParameters Set of minimum and maximum values for the free parameters of the neural network.
See also:
setMinimumValueOfFreeParameters(Vector<double>).
setMaximumValueOfFreeParameters(Vector<double>).
Definition at line 298 of file RandomSearch.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), maximumValueOfFreeParameters, minimumValueOfFreeParameters, and Flood::TrainingAlgorithm::objectiveFunctional.
void Flood::RandomSearch::train (void) [virtual]
This method trains a multilayer perceptron with an associated objective function according to the random search training algorithm. Training occurs according to the training parameters.
Implements Flood::TrainingAlgorithm.
Definition at line 367 of file RandomSearch.cpp.
References Flood::ObjectiveFunctional::calculateEvaluation(), Flood::Vector< Type >::calculateNorm(), Flood::ObjectiveFunctional::calculatePotentialEvaluation(), Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::elapsedTimeHistory, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::evaluationHistory, Flood::TrainingAlgorithm::freeParametersHistory, Flood::TrainingAlgorithm::freeParametersNormHistory, Flood::MultilayerPerceptron::getFreeParameters(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, maximumValueOfFreeParameters, minimumValueOfFreeParameters, Flood::TrainingAlgorithm::objectiveFunctional, Flood::ObjectiveFunctional::print(), Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, Flood::TrainingAlgorithm::reserveFreeParametersNormHistory, resizeTrainingHistory(), Flood::MultilayerPerceptron::setFreeParameters(), Flood::Matrix< Type >::setRow(), and Flood::TrainingAlgorithm::warningFreeParametersNorm.
void Flood::RandomSearch::print (void) [virtual]
This method prints to the screen the training parameters, the stopping criteria and other user stuff concerning the random search object:
Training parameters:
Minimum value of free parameters.
Maximum value of free parameters.
Stopping criteria:
Evaluation goal.
Maximum time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Implements Flood::TrainingAlgorithm.
Definition at line 650 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, maximumValueOfFreeParameters, and minimumValueOfFreeParameters.
void Flood::RandomSearch::load (char * filename) [virtual]
This method loads a random search object from a data file. Please mind about the file format, wich is specified in the User's Guide.
Training parameters:
Minimum value of free parameters.
Maximum value of free parameters.
Stopping criteria:
Evaluation goal.
Maximum training time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Parameters:
filename Filename.
See also:
save(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 806 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, maximumValueOfFreeParameters, and minimumValueOfFreeParameters.
void Flood::RandomSearch::save (char * filename) [virtual]
This method saves the random search object to a data file.
Training parameters:
Minimum value of free parameters.
Maximum value of free parameters.
Stopping criteria:
Evaluation goal.
Maximum time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Parameters:
filename Filename.
See also:
load(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 715 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, maximumValueOfFreeParameters, and minimumValueOfFreeParameters.
void Flood::RandomSearch::resizeTrainingHistory (int newSize)
This method resizes the vectors or matrices containing training history information to a new size:
Elapsed time history vector.
Free parameters history matrix.
Free parameters norm history vector.
Evaluation history vector.
Parameters:
newSize Size of training history.
Definition at line 905 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::elapsedTimeHistory, Flood::TrainingAlgorithm::evaluationHistory, Flood::TrainingAlgorithm::freeParametersHistory, Flood::TrainingAlgorithm::freeParametersNormHistory, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, Flood::TrainingAlgorithm::reserveFreeParametersNormHistory, Flood::Vector< Type >::resize(), and Flood::Matrix< Type >::resize().
Referenced by train().
void Flood::RandomSearch::setReserveAllTrainingHistory (bool newReserveAllTrainingHistory) [virtual]
This method makes the training history of all variables to reseved or not in memory.
Parameters:
newReserveAllTrainingHistory True if the training history of all variables is to be reserved, false otherwise.
Implements Flood::TrainingAlgorithm.
Definition at line 352 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, and Flood::TrainingAlgorithm::reserveFreeParametersNormHistory.
void Flood::RandomSearch::saveTrainingHistory (char * filename) [virtual]
This method saves the training history to a data file.
Parameters:
filename Training history filename.
Implements Flood::TrainingAlgorithm.
Definition at line 947 of file RandomSearch.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::elapsedTimeHistory, Flood::TrainingAlgorithm::evaluationHistory, Flood::TrainingAlgorithm::freeParametersHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, and Flood::TrainingAlgorithm::reserveFreeParametersNormHistory.
Member Data Documentation
Vector<double> Flood::RandomSearch::minimumValueOfFreeParameters [private]
Minimum values for all the free parameters in the seach hypercube.
Definition at line 39 of file RandomSearch.h.
Referenced by getMinimumAndMaximumValuesOfFreeParameters(), getMinimumValueOfFreeParameters(), load(), print(), RandomSearch(), save(), setMaximumValueOfFreeParameters(), setMinimumAndMaximumValuesOfFreeParameters(), setMinimumValueOfFreeParameters(), and train().
Vector<double> Flood::RandomSearch::maximumValueOfFreeParameters [private]
Maximum values for all the free parameters in the seach hypercube.
Definition at line 43 of file RandomSearch.h.
Referenced by getMaximumValueOfFreeParameters(), getMinimumAndMaximumValuesOfFreeParameters(), load(), print(), RandomSearch(), save(), setMaximumValueOfFreeParameters(), setMinimumAndMaximumValuesOfFreeParameters(), setMinimumValueOfFreeParameters(), and train().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/TrainingAlgorithm/RandomSearch.h
G:/Documents/Flood/Flood/TrainingAlgorithm/RandomSearch.cpp