Flood: Flood::Perceptron Class Reference
Flood::Perceptron Class Reference
This class represents the concept of perceptron neuron model.
#include <Perceptron.h>
Public Types
enum ActivationFunction { Logistic, HyperbolicTangent, Linear }
Enumeration of available activation functions for the perceptron neuron model.
Public Member Functions
Perceptron (int)
Perceptron (void)
virtual ~Perceptron (void)
Destructor.
ActivationFunction getActivationFunction (void)
This method returns the activation function of the neuron.
int getNumberOfInputs (void)
This method returns the number of inputs in the neuron.
double getBias (void)
Vector< double > getSynapticWeights (void)
double getSingleSynapticWeight (int)
int getNumberOfNeuronParameters (void)
Vector< double > getNeuronParameters (void)
bool getDisplay (void)
void setActivationFunction (ActivationFunction)
void setNumberOfInputs (int)
void setBias (double)
void setSynapticWeights (Vector< double >)
void setSingleSynapticWeight (int, double)
void setNeuronParameters (Vector< double >)
void setDisplay (bool)
void initBiasUniform (double, double)
void initBiasNormal (double, double)
void initSynapticWeightsUniform (double, double)
void initSynapticWeightsNormal (double, double)
double calculateNetInputSignal (Vector< double >)
double calculateOutputSignal (double)
double calculateOutputSignal (Vector< double >)
double calculateOutputSignalDerivative (double)
double calculateOutputSignalDerivative (Vector< double >)
double calculateOutputSignalSecondDerivative (double)
double calculateOutputSignalSecondDerivative (Vector< double >)
void print (void)
Protected Attributes
ActivationFunction activationFunction
Activation function variable.
int numberOfInputs
Number of inputs in the neuron.
double bias
Bias value.
Vector< double > synapticWeights
Synaptic weight values.
bool display
Display messages to screen.
Detailed Description
This class represents the concept of perceptron neuron model.
Definition at line 26 of file Perceptron.h.
Member Enumeration Documentation
enum Flood::Perceptron::ActivationFunction
Enumeration of available activation functions for the perceptron neuron model.
Enumerator:
Logistic
HyperbolicTangent
Linear
Definition at line 34 of file Perceptron.h.
Constructor & Destructor Documentation
Flood::Perceptron::Perceptron (int newNumberOfInputs)
General constructor. It creates a perceptron object with a given number of inputs. The neuron's free paramameters (bias and synaptic weights) are initialized at random with a normal distribution of mean 0 and standard deviation 1. This constructor also initializes the rest of class members to their default values:
Activation function: Hyperbolic tangent.
Display: True.
Parameters:
newNumberOfInputs Number of inputs in the neuron.
Definition at line 38 of file Perceptron.cpp.
References activationFunction, display, HyperbolicTangent, initBiasNormal(), initSynapticWeightsNormal(), numberOfInputs, Flood::Vector< Type >::setSize(), and synapticWeights.
Flood::Perceptron::Perceptron (void)
Default constructor. It creates a perceptron object with zero inputs. The neuron's bias is initialized to zero. This constructor also initializes the rest of class members to their default values:
Activation function: Hyperbolic tangent.
Display: True.
Definition at line 67 of file Perceptron.cpp.
References activationFunction, bias, display, HyperbolicTangent, and numberOfInputs.
Flood::Perceptron::~Perceptron (void) [virtual]
Destructor.
Definition at line 81 of file Perceptron.cpp.
Member Function Documentation
Perceptron::ActivationFunction Flood::Perceptron::getActivationFunction (void)
This method returns the activation function of the neuron.
Definition at line 93 of file Perceptron.cpp.
References activationFunction.
int Flood::Perceptron::getNumberOfInputs (void)
This method returns the number of inputs in the neuron.
Definition at line 103 of file Perceptron.cpp.
References numberOfInputs.
double Flood::Perceptron::getBias (void)
This method returns the bias value of the neuron.
See also:
getSynapticWeights(void).
getSingleSynapticWeight(int).
Definition at line 116 of file Perceptron.cpp.
References bias.
Vector< double > Flood::Perceptron::getSynapticWeights (void)
This method returns the synaptic weight values of the neuron.
See also:
getBias(void).
getSingleSynapticWeight(int).
Definition at line 129 of file Perceptron.cpp.
References synapticWeights.
double Flood::Perceptron::getSingleSynapticWeight (int i)
This method returns the synaptic weight value with index i of the neuron.
Parameters:
i Synaptic weight index.
See also:
getBias(void).
getSynapticWeights(void).
Definition at line 144 of file Perceptron.cpp.
References numberOfInputs, and synapticWeights.
int Flood::Perceptron::getNumberOfNeuronParameters (void)
Definition at line 313 of file Perceptron.cpp.
References numberOfInputs.
Referenced by getNeuronParameters().
Vector< double > Flood::Perceptron::getNeuronParameters (void)
Definition at line 323 of file Perceptron.cpp.
References bias, getNumberOfNeuronParameters(), numberOfInputs, and synapticWeights.
bool Flood::Perceptron::getDisplay (void)
This method returns true if messages from this class are to be displayed on the screen, or false if messages from this class are not to be displayed on the screen.
Definition at line 174 of file Perceptron.cpp.
References display.
void Flood::Perceptron::setActivationFunction (Perceptron::ActivationFunction newActivationFunction)
This method sets a new activation function in the neuron.
Parameters:
newActivationFunction Activation function.
Definition at line 186 of file Perceptron.cpp.
References activationFunction.
void Flood::Perceptron::setNumberOfInputs (int newNumberOfInputs)
This method sets a new number of inputs in the neuron. The new free paramameters (bias and synaptic weights) are initialized at random with a normal distribution of mean 0 and standard deviation 1.
Parameters:
newNumberOfInputs Number of inputs in the neuton.
Definition at line 298 of file Perceptron.cpp.
References initBiasNormal(), initSynapticWeightsNormal(), numberOfInputs, Flood::Vector< Type >::setSize(), and synapticWeights.
void Flood::Perceptron::setBias (double newBias)
This method sets a new bias value for the perceptron.
Parameters:
newBias Bias value.
See also:
setSynapticWeights(Vector<double>).
setSingleSynapticWeight(i, double).
Definition at line 201 of file Perceptron.cpp.
References bias.
void Flood::Perceptron::setSynapticWeights (Vector< double > newSynapticWeights)
This method a new set of synaptic weights for the perceptron.
Parameters:
newSynapticWeights Synaptic weight values.
See also:
setBias(double).
setSingleSinapticWeight(int, double).
Definition at line 216 of file Perceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfInputs, and synapticWeights.
void Flood::Perceptron::setSingleSynapticWeight (int i, double newSynapticWeight)
This method sets the synaptic weight value with index i for the neuron.
Parameters:
i Synaptic weight index.
newSynapticWeight Synaptic weight value.
See also:
setBias(double).
setSingleSinapticWeight(int, double).
Definition at line 251 of file Perceptron.cpp.
References numberOfInputs, and synapticWeights.
void Flood::Perceptron::setNeuronParameters (Vector< double > newNeuronParameters)
Definition at line 342 of file Perceptron.cpp.
References bias, numberOfInputs, and synapticWeights.
void Flood::Perceptron::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 284 of file Perceptron.cpp.
References display.
void Flood::Perceptron::initBiasUniform (double minimumValue, double maximumValue)
This method initializes the neuron's bias with a random value chosen from a uniform distribution.
Parameters:
minimumValue Minimum initialization value.
maximumValue Maximum initialization value.
See also:
initSynapticWeightsUniform(double, double).
initBiasNormal(double, double).
initSynapticWeightsNormal(double, double).
Definition at line 364 of file Perceptron.cpp.
References bias.
void Flood::Perceptron::initBiasNormal (double mean, double standardDeviation)
This method initializes the neuron's bias with random values chosen from a normal distribution.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
See also:
initBiasUniform(double, double).
initSynapticWeightsUniform(double, double).
initSynapticWeightsNormal(double, double).
Definition at line 441 of file Perceptron.cpp.
References bias.
Referenced by Perceptron(), and setNumberOfInputs().
void Flood::Perceptron::initSynapticWeightsUniform (double minimumValue, double maximumValue)
This method initializes the neuron's synaptic weights with random values chosen from an uniform distribution.
Parameters:
minimumValue Minimum initialization value.
maximumValue Maximum initialization value.
See also:
initBiasUniform(double, double).
initBiasNormal(double, double).
initSynapticWeightsNormal(double, double).
Definition at line 400 of file Perceptron.cpp.
References numberOfInputs, and synapticWeights.
void Flood::Perceptron::initSynapticWeightsNormal (double mean, double standardDeviation)
This method initializes the neuron's synaptic weights with random values chosen from a normal distribution.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
See also:
initBiasUniform(double, double).
initSynapticWeightsUniform(double, double).
initBiasNormal(double, double).
Definition at line 482 of file Perceptron.cpp.
References numberOfInputs, and synapticWeights.
Referenced by Perceptron(), and setNumberOfInputs().
double Flood::Perceptron::calculateNetInputSignal (Vector< double > inputSignal)
This method returns the net input signal to the neuron for a set of input signals, using the dot product combination function.
Parameters:
inputSignal Set of input signals to the neuron.
Definition at line 525 of file Perceptron.cpp.
References bias, Flood::Vector< Type >::dot(), Flood::Vector< Type >::getSize(), numberOfInputs, and synapticWeights.
Referenced by calculateOutputSignal(), calculateOutputSignalDerivative(), and calculateOutputSignalSecondDerivative().
double Flood::Perceptron::calculateOutputSignal (double netInputSignal)
This method returns the output signal from the neuron for a net input signal. The output signal depends on the activation function used.
Parameters:
netInputSignal Net input signal to the neuron.
See also:
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(double).
calculateOutputSignalDerivative(Vector<double>).
getOutputSignaSecondDerivative(double).
getOutputSignaSecondDerivative(Vector<double>).
Definition at line 575 of file Perceptron.cpp.
References activationFunction, HyperbolicTangent, Linear, and Logistic.
Referenced by calculateOutputSignal().
double Flood::Perceptron::calculateOutputSignal (Vector< double > inputSignal)
This method returns the output signal from the neuron for a set of input signals. The output signal depends on the activation function used.
Parameters:
inputSignal Set of input signals to the neuron.
See also:
calculateOutputSignal(double).
calculateOutputSignalDerivative(double).
calculateOutputSignalDerivative(Vector<double>).
getOutputSignaSecondDerivative(double).
getOutputSignaSecondDerivative(Vector<double>).
Definition at line 627 of file Perceptron.cpp.
References calculateNetInputSignal(), calculateOutputSignal(), Flood::Vector< Type >::getSize(), and numberOfInputs.
double Flood::Perceptron::calculateOutputSignalDerivative (double netInputSignal)
This method returns the activation derivative of the neuron for a net input signal. The output signal derivative depends on the activation function used.
Parameters:
netInputSignal Net input signal to the neuron.
See also:
calculateOutputSignal(double).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(Vector<double>).
calculateOutputSignalSecondDerivative(double).
calculateOutputSignalSecondDerivative(Vector<double>).
Definition at line 671 of file Perceptron.cpp.
References activationFunction, HyperbolicTangent, Linear, and Logistic.
Referenced by calculateOutputSignalDerivative().
double Flood::Perceptron::calculateOutputSignalDerivative (Vector< double > inputSignal)
This method returns the activation derivative of the neuron for a set of input signals. The output signal derivative depends on the activation function used.
Parameters:
inputSignal Set of input signals to the neuron.
See also:
calculateOutputSignal(double).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(double).
calculateOutputSignalSecondDerivative(double).
calculateOutputSignalSecondDerivative(Vector<double>).
Definition at line 723 of file Perceptron.cpp.
References calculateNetInputSignal(), calculateOutputSignalDerivative(), Flood::Vector< Type >::getSize(), and numberOfInputs.
double Flood::Perceptron::calculateOutputSignalSecondDerivative (double netInputSignal)
This method returns the activation second derivative of the neuron for a net input signal. The second derivative of the output signal depends on the activation function used.
Parameters:
netInputSignal Net input signal to the neuron.
See also:
calculateOutputSignal(double).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(double).
calculateOutputSignalDerivative(Vector<double>).
calculateOutputSignalSecondDerivative(Vector<double>).
Definition at line 767 of file Perceptron.cpp.
References activationFunction, HyperbolicTangent, Linear, and Logistic.
Referenced by calculateOutputSignalSecondDerivative().
double Flood::Perceptron::calculateOutputSignalSecondDerivative (Vector< double > inputSignal)
This method returns the activation second derivative of the neuron for a set of input signals. The second derivative of the output signal depends on the activation function used.
Parameters:
inputSignal Set of input signals to the neuron.
See also:
calculateOutputSignal(double).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(double).
calculateOutputSignalDerivative(Vector<double>).
calculateOutputSignalSecondDerivative(double).
Definition at line 820 of file Perceptron.cpp.
References calculateNetInputSignal(), calculateOutputSignalSecondDerivative(), Flood::Vector< Type >::getSize(), and numberOfInputs.
void Flood::Perceptron::print (void)
This method prints to the screen the number of inputs, the bias and the synaptic weight values of the perceptron.
Definition at line 856 of file Perceptron.cpp.
References activationFunction, bias, HyperbolicTangent, Linear, Logistic, numberOfInputs, and synapticWeights.
Member Data Documentation
ActivationFunction Flood::Perceptron::activationFunction [protected]
Activation function variable.
Definition at line 42 of file Perceptron.h.
Referenced by calculateOutputSignal(), calculateOutputSignalDerivative(), calculateOutputSignalSecondDerivative(), getActivationFunction(), Perceptron(), print(), and setActivationFunction().
int Flood::Perceptron::numberOfInputs [protected]
Number of inputs in the neuron.
Definition at line 46 of file Perceptron.h.
Referenced by calculateNetInputSignal(), calculateOutputSignal(), calculateOutputSignalDerivative(), calculateOutputSignalSecondDerivative(), getNeuronParameters(), getNumberOfInputs(), getNumberOfNeuronParameters(), getSingleSynapticWeight(), initSynapticWeightsNormal(), initSynapticWeightsUniform(), Perceptron(), print(), setNeuronParameters(), setNumberOfInputs(), setSingleSynapticWeight(), and setSynapticWeights().
double Flood::Perceptron::bias [protected]
Bias value.
Definition at line 50 of file Perceptron.h.
Referenced by calculateNetInputSignal(), getBias(), getNeuronParameters(), initBiasNormal(), initBiasUniform(), Perceptron(), print(), setBias(), and setNeuronParameters().
Vector<double> Flood::Perceptron::synapticWeights [protected]
Synaptic weight values.
Definition at line 54 of file Perceptron.h.
Referenced by calculateNetInputSignal(), getNeuronParameters(), getSingleSynapticWeight(), getSynapticWeights(), initSynapticWeightsNormal(), initSynapticWeightsUniform(), Perceptron(), print(), setNeuronParameters(), setNumberOfInputs(), setSingleSynapticWeight(), and setSynapticWeights().
bool Flood::Perceptron::display [protected]
Display messages to screen.
Definition at line 58 of file Perceptron.h.
Referenced by getDisplay(), Perceptron(), and setDisplay().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Perceptron/Perceptron.h
G:/Documents/Flood/Flood/Perceptron/Perceptron.cpp