Flood: Flood::Vector< Type > Class Template Reference
Flood::Vector< Type > Class Template Reference
#include <Vector.h>
Public Member Functions
Vector (void)
Default constructor. It creates a vector of size zero.
Vector (int)
Vector (int, const Type &)
Vector (int, const Type *)
Vector (const Vector &)
Vector & operator= (const Vector &)
Type & operator[] (const int)
Reference operator.
const Type & operator[] (const int) const
Reference operator.
int getSize (void)
This method returns the number of elements in the vector.
void setSize (int)
void resize (int)
void fillAtRandom (void)
This method assigns a random value comprised between -1 and 1 to each element in the vector.
void fillAtRandom (double, double)
Type calculateMean (void)
This method returns the mean of the elements in the vector.
Type calculateStandardDeviation (void)
This method returns the standard deviation of the elements in the vector.
Type calculateMinimum (void)
This method returns the smallest element in the vector.
Type calculateMaximum (void)
This method returns the largest element in the vector.
int calculateMinimalIndex (void)
This method returns the index of the smallest element in the vector.
int calculateMaximalIndex (void)
This method returns the index of the largest element in the vector.
double calculateNorm (void)
This element returns the vector norm.
Vector< Type > operator+ (Type)
Sum vector+scalar arithmetic operator.
Vector< Type > operator+ (Vector< Type >)
Sum vector+vector arithmetic operator.
Vector< Type > operator- (Type)
Difference vector-scalar arithmetic operator.
Vector< Type > operator- (Vector< Type >)
Difference vector-vector arithmetic operator.
Vector< Type > operator* (Type)
Product vector*scalar arithmetic operator.
Type dot (Vector< Type >)
Dot product vector*vector arithmetic operator.
Vector< Type > operator* (Vector< Type >)
Element by element product vector*vector arithmetic operator.
Vector< Type > operator* (Matrix< Type >)
Product vector*matrix arithmetic operator.
Matrix< Type > outer (Vector< Type >)
Outer product vector*vector arithmetic operator.
Vector< Type > operator/ (Type)
Cocient vector/scalar arithmetic operator.
Vector< Type > operator/ (Vector< Type >)
Cocient vector/vector arithmetic operator.
Type * begin ()
This method returns a pointer to the first element in the container.
Type * end ()
This method returns a pointer to the last element in the container.
void insert (int, Vector< Type >)
Insert another vector starting from a given position.
Vector< Type > extract (int, int)
Extract a vector of a given size from a given position.
Vector< Type > assemble (Vector< Type >)
Assemble two vectors.
void load (char *)
void save (char *)
~Vector ()
Destructor.
Private Attributes
int size
Size of vector.
Type * vector
Pointer to a Type.
Detailed Description
template<class Type>
class Flood::Vector< Type >
This template class defines a vector for general purpose use.
See also:
Matrix.
Definition at line 38 of file Vector.h.
Constructor & Destructor Documentation
template<typename Type> Flood::Vector< Type >::Vector (void) [inline]
Default constructor. It creates a vector of size zero.
Definition at line 136 of file Vector.h.
template<typename Type> Flood::Vector< Type >::Vector (int newSize) [inline]
Constructor. It creates a vector of size n, containing n copies of the default value for Type.
Parameters:
newSize Size of Vector.
Definition at line 147 of file Vector.h.
template<typename Type> Flood::Vector< Type >::Vector (int newSize, const Type & type) [inline]
Constructor. It creates a vector of size n, containing n copies of the type value of Type.
Parameters:
newSize Size of Vector.
type Value of Type.
Definition at line 158 of file Vector.h.
References Flood::Vector< Type >::vector.
template<typename Type> Flood::Vector< Type >::Vector (int newSize, const Type * type) [inline]
Constructor. It creates a vector of size n, containing n copies of the type value of Type.
Parameters:
newSize Size of Vector.
type Value of Type.
Definition at line 173 of file Vector.h.
References Flood::Vector< Type >::vector.
template<typename Type> Flood::Vector< Type >::Vector (const Vector< Type > & oldVector) [inline]
Copy constructor. It creates a copy of an existing Vector.
Parameters:
oldVector Vector to be copied.
Definition at line 187 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Flood::Vector< Type >::~Vector () [inline]
Destructor.
Definition at line 970 of file Vector.h.
References Flood::Vector< Type >::vector.
Member Function Documentation
template<typename Type> Vector< Type > & Flood::Vector< Type >::operator= (const Vector< Type > & oldVector) [inline]
Assignment operator. It assigns to self a copy of an existing Vector.
Parameters:
oldVector Vector to be assigned.
Definition at line 204 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Type & Flood::Vector< Type >::operator[] (const int) [inline]
Reference operator.
Definition at line 235 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> const Type & Flood::Vector< Type >::operator[] (const int) const [inline]
Reference operator.
Definition at line 263 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> int Flood::Vector< Type >::getSize (void) [inline]
This method returns the number of elements in the vector.
Definition at line 293 of file Vector.h.
References Flood::Vector< Type >::size.
Referenced by Flood::InputTargetDataSet::addSample(), Flood::MultilayerPerceptron::applyLowerAndUpperBounds(), Flood::Vector< Type >::assemble(), Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation(), Flood::MinimumDragProblem::calculateHomogeneousSolution(), Flood::IsoperimetricProblem::calculateHomogeneousSolution(), Flood::GeodesicProblem::calculateHomogeneousSolution(), Flood::CatenaryProblem::calculateHomogeneousSolution(), Flood::BrachistochroneProblem::calculateHomogeneousSolution(), Flood::MinimumDragProblem::calculateHomogeneousSolutionDerivative(), Flood::IsoperimetricProblem::calculateHomogeneousSolutionDerivative(), Flood::GeodesicProblem::calculateHomogeneousSolutionDerivative(), Flood::CatenaryProblem::calculateHomogeneousSolutionDerivative(), Flood::BrachistochroneProblem::calculateHomogeneousSolutionDerivative(), Flood::Perceptron::calculateNetInputSignal(), Flood::MultilayerPerceptron::calculateOutput(), Flood::Perceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::Perceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::Perceptron::calculateOutputSignalSecondDerivative(), Flood::MinimumDragProblem::calculateParticularSolution(), Flood::IsoperimetricProblem::calculateParticularSolution(), Flood::GeodesicProblem::calculateParticularSolution(), Flood::CatenaryProblem::calculateParticularSolution(), Flood::BrachistochroneProblem::calculateParticularSolution(), Flood::MinimumDragProblem::calculateParticularSolutionDerivative(), Flood::IsoperimetricProblem::calculateParticularSolutionDerivative(), Flood::GeodesicProblem::calculateParticularSolutionDerivative(), Flood::CatenaryProblem::calculateParticularSolutionDerivative(), Flood::BrachistochroneProblem::calculateParticularSolutionDerivative(), Flood::ObjectiveFunctional::calculatePotentialEvaluation(), Flood::ObjectiveFunctional::calculatePotentialGradient(), Flood::ObjectiveFunctional::calculatePotentialHessian(), Flood::IntegrationOfFunctions::calculateSimpsonIntegral(), Flood::IntegrationOfFunctions::calculateTrapezoidIntegral(), Flood::ObjectiveFunctional::calculateVectorHessianProduct(), Flood::MultilayerPerceptron::checkInput(), Flood::Vector< Type >::dot(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::initFreeParametersNormal(), Flood::MultilayerPerceptron::initFreeParametersUniform(), Flood::MultilayerPerceptron::initIndependentParametersNormal(), Flood::MultilayerPerceptron::initIndependentParametersUniform(), Flood::MultilayerPerceptron::initNeuralParametersNormal(), Flood::MultilayerPerceptron::initNeuralParametersUniform(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::Vector< Type >::insert(), Flood::Vector< Type >::operator*(), Flood::Matrix< Type >::operator*(), Flood::Vector< Type >::operator+(), Flood::Vector< Type >::operator-(), Flood::Vector< Type >::operator/(), Flood::operator>>(), Flood::Vector< Type >::outer(), Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), Flood::Matrix< Type >::setColumn(), Flood::MultilayerPerceptron::setDescriptionOfIndependentParameters(), Flood::InputTargetDataSet::setDescriptionOfInputVariables(), Flood::MultilayerPerceptron::setDescriptionOfInputVariables(), Flood::MultilayerPerceptron::setDescriptionOfOutputVariables(), Flood::InputTargetDataSet::setDescriptionOfTargetVariables(), Flood::EvolutionaryAlgorithm::setEvaluation(), Flood::EvolutionaryAlgorithm::setFitness(), Flood::MultilayerPerceptron::setFreeParameters(), Flood::MultilayerPerceptron::setHiddenLayersActivationFunction(), Flood::MultilayerPerceptron::setIndependentParameters(), Flood::EvolutionaryAlgorithm::setIndividual(), Flood::MultilayerPerceptron::setLowerBoundOfIndependentParameters(), Flood::MultilayerPerceptron::setLowerBoundOfOutputVariables(), Flood::MultilayerPerceptron::setMaximumOfIndependentParameters(), Flood::MultilayerPerceptron::setMaximumOfInputVariables(), Flood::MultilayerPerceptron::setMaximumOfOutputVariables(), Flood::RandomSearch::setMaximumValueOfFreeParameters(), Flood::MultilayerPerceptron::setMeanOfIndependentParameters(), Flood::MultilayerPerceptron::setMeanOfInputVariables(), Flood::MultilayerPerceptron::setMeanOfOutputVariables(), Flood::MultilayerPerceptron::setMinimumOfIndependentParameters(), Flood::MultilayerPerceptron::setMinimumOfInputVariables(), Flood::MultilayerPerceptron::setMinimumOfOutputVariables(), Flood::RandomSearch::setMinimumValueOfFreeParameters(), Flood::MultilayerPerceptron::setNameOfIndependentParameters(), Flood::InputTargetDataSet::setNameOfInputVariables(), Flood::MultilayerPerceptron::setNameOfInputVariables(), Flood::MultilayerPerceptron::setNameOfOutputVariables(), Flood::InputTargetDataSet::setNameOfTargetVariables(), Flood::MultilayerPerceptron::setNeuralParameters(), Flood::MultilayerPerceptron::setNumbersOfHiddenNeurons(), Flood::Matrix< Type >::setRow(), Flood::InputTargetDataSet::setSample(), Flood::EvolutionaryAlgorithm::setSelection(), Flood::MultilayerPerceptron::setStandardDeviationOfIndependentParameters(), Flood::MultilayerPerceptron::setStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::setStandardDeviationOfOutputVariables(), Flood::Perceptron::setSynapticWeights(), Flood::MultilayerPerceptron::setUnitsOfIndependentParameters(), Flood::InputTargetDataSet::setUnitsOfInputVariables(), Flood::MultilayerPerceptron::setUnitsOfInputVariables(), Flood::MultilayerPerceptron::setUnitsOfOutputVariables(), Flood::InputTargetDataSet::setUnitsOfTargetVariables(), Flood::MultilayerPerceptron::setUpperBoundOfIndependentParameters(), and Flood::MultilayerPerceptron::setUpperBoundOfOutputVariables().
template<typename Type> void Flood::Vector< Type >::setSize (int newSize) [inline]
This method sets a new size in the vector. It also initializes the new vector with the previous values.
Parameters:
newSize New number of elements.
Definition at line 307 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::Perceptron::Perceptron(), Flood::MultilayerPerceptron::setNetworkArchitecture(), Flood::MultilayerPerceptron::setNumberOfIndependentParameters(), and Flood::Perceptron::setNumberOfInputs().
template<typename Type> void Flood::Vector< Type >::resize (int newSize) [inline]
This method sets a new size in the vector. It also initializes the new vector with the previous values.
Parameters:
newSize New number of elements.
Definition at line 323 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm(), Flood::Vector< Type >::load(), Flood::RandomSearch::resizeTrainingHistory(), Flood::QuasiNewtonMethod::resizeTrainingHistory(), Flood::NewtonMethod::resizeTrainingHistory(), Flood::GradientDescent::resizeTrainingHistory(), Flood::EvolutionaryAlgorithm::resizeTrainingHistory(), Flood::ConjugateGradient::resizeTrainingHistory(), Flood::InputTargetDataSet::setInputTargetDataSet(), and Flood::EvolutionaryAlgorithm::setPopulationSize().
template<class Type> void Flood::Vector< Type >::fillAtRandom (void) [inline]
This method assigns a random value comprised between -1 and 1 to each element in the vector.
Definition at line 373 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<class Type> void Flood::Vector< Type >::fillAtRandom (double minimum, double maximum) [inline]
This method assigns a random value comprised between a minimum and a maximum values to each element in the vector.
Parameters:
minimum Minimum filling value.
maximum Maximum filling value.
Definition at line 395 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Type Flood::Vector< Type >::calculateMean (void) [inline]
This method returns the mean of the elements in the vector.
Definition at line 518 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::Vector< Type >::calculateStandardDeviation(), and Flood::EvolutionaryAlgorithm::train().
template<typename Type> Type Flood::Vector< Type >::calculateStandardDeviation (void) [inline]
This method returns the standard deviation of the elements in the vector.
Definition at line 540 of file Vector.h.
References Flood::Vector< Type >::calculateMean(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::EvolutionaryAlgorithm::train().
template<typename Type> Type Flood::Vector< Type >::calculateMinimum (void) [inline]
This method returns the smallest element in the vector.
Definition at line 430 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::QuasiNewtonMethod::calculateGoldenSectionTrainRate(), Flood::GradientDescent::calculateGoldenSectionTrainRate(), and Flood::ConjugateGradient::calculateGoldenSectionTrainRate().
template<typename Type> Type Flood::Vector< Type >::calculateMaximum (void) [inline]
This method returns the largest element in the vector.
Definition at line 451 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> int Flood::Vector< Type >::calculateMinimalIndex (void) [inline]
This method returns the index of the smallest element in the vector.
Definition at line 472 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> int Flood::Vector< Type >::calculateMaximalIndex (void) [inline]
This method returns the index of the largest element in the vector.
Definition at line 495 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> double Flood::Vector< Type >::calculateNorm (void) [inline]
This element returns the vector norm.
Definition at line 564 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::PrecipitateDissolutionModeling::calculateEvaluation(), Flood::EvolutionaryAlgorithm::calculatePopulationNorm(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), Flood::EvolutionaryAlgorithm::train(), and Flood::ConjugateGradient::train().
template<typename Type> Vector< Type > Flood::Vector< Type >::operator+ (Type scalar) [inline]
Sum vector+scalar arithmetic operator.
Definition at line 601 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator+ (Vector< Type > otherVector) [inline]
Sum vector+vector arithmetic operator.
Definition at line 619 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator- (Type scalar) [inline]
Difference vector-scalar arithmetic operator.
Definition at line 658 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator- (Vector< Type > otherVector) [inline]
Difference vector-vector arithmetic operator.
Definition at line 676 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator* (Type scalar) [inline]
Product vector*scalar arithmetic operator.
Definition at line 714 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Type Flood::Vector< Type >::dot (Vector< Type > otherVector) [inline]
Dot product vector*vector arithmetic operator.
Definition at line 813 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::DeJongFunction::calculateEvaluation(), Flood::ConjugateGradient::calculateFletcherReevesParameter(), Flood::Perceptron::calculateNetInputSignal(), Flood::ConjugateGradient::calculatePolakRibiereParameter(), and Flood::ConjugateGradient::train().
template<typename Type> Vector< Type > Flood::Vector< Type >::operator* (Vector< Type > otherVector) [inline]
Element by element product vector*vector arithmetic operator.
Definition at line 732 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator* (Matrix< Type > matrix) [inline]
Product vector*matrix arithmetic operator.
Definition at line 769 of file Vector.h.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Matrix< Type > Flood::Vector< Type >::outer (Vector< Type > otherVector) [inline]
Outer product vector*vector arithmetic operator.
Definition at line 850 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), and Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation().
template<typename Type> Vector< Type > Flood::Vector< Type >::operator/ (Type scalar) [inline]
Cocient vector/scalar arithmetic operator.
Definition at line 893 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Vector< Type > Flood::Vector< Type >::operator/ (Vector< Type > otherVector) [inline]
Cocient vector/vector arithmetic operator.
Definition at line 911 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<typename Type> Type * Flood::Vector< Type >::begin () [inline]
This method returns a pointer to the first element in the container.
Definition at line 948 of file Vector.h.
References Flood::Vector< Type >::vector.
Referenced by Flood::QuasiNewtonMethod::calculateBrentMethodTrainRate(), Flood::GradientDescent::calculateBrentMethodTrainRate(), Flood::ConjugateGradient::calculateBrentMethodTrainRate(), Flood::EvolutionaryAlgorithm::performLinearRankingFitnessAssignment(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
template<typename Type> Type * Flood::Vector< Type >::end () [inline]
This method returns a pointer to the last element in the container.
Definition at line 959 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::QuasiNewtonMethod::calculateBrentMethodTrainRate(), Flood::GradientDescent::calculateBrentMethodTrainRate(), Flood::ConjugateGradient::calculateBrentMethodTrainRate(), Flood::EvolutionaryAlgorithm::performLinearRankingFitnessAssignment(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
template<typename Type> void Flood::Vector< Type >::insert (int position, Vector< Type > otherVector) [inline]
Insert another vector starting from a given position.
Definition at line 1125 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::MultilayerPerceptron::getNeuralParameters().
template<typename Type> Vector< Type > Flood::Vector< Type >::extract (int position, int otherSize) [inline]
Extract a vector of a given size from a given position.
Definition at line 1158 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::MultilayerPerceptron::setNeuralParameters().
template<typename Type> Vector< Type > Flood::Vector< Type >::assemble (Vector< Type > otherVector) [inline]
Assemble two vectors.
Definition at line 1193 of file Vector.h.
References Flood::Vector< Type >::getSize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Referenced by Flood::MultilayerPerceptron::getFreeParameters().
template<class Type> void Flood::Vector< Type >::load (char * filename) [inline]
This method loads the elements of a vector from a data file. The file format is as follows:
NumberOfElements Element_0 Element_1 ... Element_N-1
Parameters:
filename Filename.
See also:
save(char*).
Definition at line 1028 of file Vector.h.
References Flood::Vector< Type >::resize(), Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
template<class Type> void Flood::Vector< Type >::save (char * filename) [inline]
This method saves to a data file the elements of the vector.
Parameters:
filename Filename.
See also:
load(char*).
Definition at line 1078 of file Vector.h.
References Flood::Vector< Type >::size, and Flood::Vector< Type >::vector.
Member Data Documentation
template<class Type> int Flood::Vector< Type >::size [private]
Size of vector.
Definition at line 45 of file Vector.h.
Referenced by Flood::Vector< Type >::assemble(), Flood::Vector< Type >::calculateMaximalIndex(), Flood::Vector< Type >::calculateMaximum(), Flood::Vector< Type >::calculateMean(), Flood::Vector< Type >::calculateMinimalIndex(), Flood::Vector< Type >::calculateMinimum(), Flood::Vector< Type >::calculateNorm(), Flood::Vector< Type >::calculateStandardDeviation(), Flood::Vector< Type >::dot(), Flood::Vector< Type >::end(), Flood::Vector< Type >::extract(), Flood::Vector< Type >::fillAtRandom(), Flood::Vector< Type >::getSize(), Flood::Vector< Type >::insert(), Flood::Vector< Type >::load(), Flood::Vector< Type >::operator*(), Flood::Vector< Type >::operator+(), Flood::Vector< Type >::operator-(), Flood::Vector< Type >::operator/(), Flood::operator<<(), Flood::Vector< Type >::operator=(), Flood::operator>>(), Flood::Vector< Type >::operator[](), Flood::Vector< Type >::outer(), Flood::Vector< Type >::resize(), Flood::Vector< Type >::save(), Flood::Vector< Type >::setSize(), and Flood::Vector< Type >::Vector().
template<class Type> Type* Flood::Vector< Type >::vector [private]
Pointer to a Type.
Definition at line 49 of file Vector.h.
Referenced by Flood::Vector< Type >::assemble(), Flood::Vector< Type >::begin(), Flood::Vector< Type >::calculateMaximalIndex(), Flood::Vector< Type >::calculateMaximum(), Flood::Vector< Type >::calculateMean(), Flood::Vector< Type >::calculateMinimalIndex(), Flood::Vector< Type >::calculateMinimum(), Flood::Vector< Type >::calculateNorm(), Flood::Vector< Type >::calculateStandardDeviation(), Flood::Vector< Type >::dot(), Flood::Vector< Type >::end(), Flood::Vector< Type >::extract(), Flood::Vector< Type >::fillAtRandom(), Flood::Vector< Type >::insert(), Flood::Vector< Type >::load(), Flood::Vector< Type >::operator*(), Flood::Vector< Type >::operator+(), Flood::Vector< Type >::operator-(), Flood::Vector< Type >::operator/(), Flood::Vector< Type >::operator=(), Flood::Vector< Type >::operator[](), Flood::Vector< Type >::outer(), Flood::Vector< Type >::resize(), Flood::Vector< Type >::save(), Flood::Vector< Type >::setSize(), Flood::Vector< Type >::Vector(), and Flood::Vector< Type >::~Vector().
The documentation for this class was generated from the following file:
G:/Documents/Flood/Flood/Utilities/Vector.h