Flood: Flood::EasomFunction Class Reference
Flood::EasomFunction Class Reference
#include <EasomFunction.h>
Public Member Functions
EasomFunction (MultilayerPerceptron *)
EasomFunction (void)
virtual ~EasomFunction (void)
Destructor.
double calculateEvaluation (void)
This method returns the Easom's function evaluation for a given vector of independent parameters.
Vector< double > calculateGradient (void)
This method returns the Easom's analytical gradient vector.
Matrix< double > calculateHessian (void)
This method returns the Easom's analytical Hessian matrix.
Matrix< double > calculateInverseHessian (void)
This method returns the Easom's analytical inverse Hessian matrix.
Detailed Description
This class represents the Easom's objective function. The Easom function is an unimodal test function, where the global minimum has a small area relative to the search space. The function was inverted for minimization. For more information please visit GEATbx - The Genetic and Evolutionary Algorithm Toolbox for Matlab, www.geatbx.com
See also:
ObjectiveFunctional.
Definition at line 36 of file EasomFunction.h.
Constructor & Destructor Documentation
Flood::EasomFunction::EasomFunction (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates an Easom's objective function object. It also initializes all the rest of class members to their default values:
Number of variables = 2.
Lower bound = 1,...,1.
Upper bound = 10,...,10.
Definition at line 38 of file EasomFunction.cpp.
References Flood::MultilayerPerceptron::getNumberOfIndependentParameters(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Flood::EasomFunction::EasomFunction (void)
Flood::EasomFunction::~EasomFunction (void) [virtual]
Destructor.
Definition at line 77 of file EasomFunction.cpp.
Member Function Documentation
double Flood::EasomFunction::calculateEvaluation (void) [virtual]
This method returns the Easom's function evaluation for a given vector of independent parameters.
Implements Flood::ObjectiveFunctional.
Definition at line 89 of file EasomFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Vector< double > Flood::EasomFunction::calculateGradient (void) [virtual]
This method returns the Easom's analytical gradient vector.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 124 of file EasomFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Matrix< double > Flood::EasomFunction::calculateHessian (void) [virtual]
This method returns the Easom's analytical Hessian matrix.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 147 of file EasomFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateInverseHessian().
Matrix< double > Flood::EasomFunction::calculateInverseHessian (void) [virtual]
This method returns the Easom's analytical inverse Hessian matrix.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 176 of file EasomFunction.cpp.
References calculateHessian(), Flood::MultilayerPerceptron::getIndependentParameters(), and Flood::ObjectiveFunctional::multilayerPerceptron.
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/EasomFunction.h
G:/Documents/Flood/Flood/ObjectiveFunctional/EasomFunction.cpp