Flood: Flood::IntegrationOfFunctions Class Reference
Flood::IntegrationOfFunctions Class Reference
#include <IntegrationOfFunctions.h>
Public Member Functions
IntegrationOfFunctions (void)
General constructor.
~IntegrationOfFunctions (void)
Destructor.
double calculateTrapezoidIntegral (double(*f)(double), double, double, int)
double calculateSimpsonIntegral (double(*f)(double), double, double, int)
double calculateTrapezoidIntegral (Vector< double >, Vector< double >)
double calculateSimpsonIntegral (Vector< double >, Vector< double >)
template<class T>
double calculateTrapezoidIntegral (T t, double(T::*f)(double), double a, double b, int n)
template<class T>
double calculateSimpsonIntegral (T t, double(T::*f)(double), double a, double b, int n)
Detailed Description
This class contains methods for numerical integration of functions. In particular it implements the trapezoid method and the Simpson's method.
Definition at line 27 of file IntegrationOfFunctions.h.
Constructor & Destructor Documentation
Flood::IntegrationOfFunctions::IntegrationOfFunctions (void)
General constructor.
Definition at line 28 of file IntegrationOfFunctions.cpp.
Flood::IntegrationOfFunctions::~IntegrationOfFunctions (void)
Destructor.
Definition at line 38 of file IntegrationOfFunctions.cpp.
Member Function Documentation
double Flood::IntegrationOfFunctions::calculateTrapezoidIntegral (double(*)(double) f, double a, double b, int n)
This method evaluates the integral of a function given as a pointer to a C-style function using the composite trapezoid rule with n intervals.
Parameters:
f Pointer to the C-style function to integrate.
a Lower integration limit.
b Upper integration limit.
n Number of intervals.
Definition at line 57 of file IntegrationOfFunctions.cpp.
double Flood::IntegrationOfFunctions::calculateSimpsonIntegral (double(*)(double) f, double a, double b, int n)
This method evaluates the integral of a function given as a pointer to a C-style function using the composite Simpson rule with n intervals.
Parameters:
f Pointer to the C-style function to integrate.
a Lower integration limit.
b Upper integration limit.
n Number of intervals.
Definition at line 93 of file IntegrationOfFunctions.cpp.
Referenced by Flood::AircraftLandingProblem::calculateEvaluation().
double Flood::IntegrationOfFunctions::calculateTrapezoidIntegral (Vector< double > x, Vector< double > y)
This method evaluates the integral of a function given as a set of n pairs of data (x,y) using the composite trapezoid rule.
Parameters:
x Vector of x data.
y Vector of y data.
Definition at line 134 of file IntegrationOfFunctions.cpp.
References Flood::Vector< Type >::getSize().
double Flood::IntegrationOfFunctions::calculateSimpsonIntegral (Vector< double > x, Vector< double > y)
This method evaluates the integral of a function given as a set of n pairs of data (x,y) using the composite Simpson's rule.
Parameters:
x Vector of x data.
y Vector of y data.
Definition at line 163 of file IntegrationOfFunctions.cpp.
References Flood::Vector< Type >::getSize().
template<class T> double Flood::IntegrationOfFunctions::calculateTrapezoidIntegral (T t, double(T::*)(double) f, double a, double b, int n) [inline]
This method evaluates the integral of a function given as a class member method using the composite trapezoid rule with n intervals.
Parameters:
t : Object constructor containing the member method to integrate.
f,: Pointer to the member method.
a,: Lower integration limit.
b,: Upper integration limit.
n,: Number of intervals.
Definition at line 70 of file IntegrationOfFunctions.h.
template<class T> double Flood::IntegrationOfFunctions::calculateSimpsonIntegral (T t, double(T::*)(double) f, double a, double b, int n) [inline]
This method evaluates the integral of a function given as a class member method using the composite Simpsons rule with n intervals.
Parameters:
t : Object constructor containing the member method to integrate.
f,: Pointer to the member method.
a,: Lower integration limit.
b,: Upper integration limit.
n,: Number of intervals.
Definition at line 110 of file IntegrationOfFunctions.h.
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Utilities/IntegrationOfFunctions.h
G:/Documents/Flood/Flood/Utilities/IntegrationOfFunctions.cpp