Flood: Flood::CorrectPredictionsAnalysis Class Reference
Flood::CorrectPredictionsAnalysis Class Reference
#include <CorrectPredictionsAnalysis.h>
Public Member Functions
CorrectPredictionsAnalysis (MultilayerPerceptron *, InputTargetDataSet *)
CorrectPredictionsAnalysis (void)
virtual ~CorrectPredictionsAnalysis ()
Destructor.
MultilayerPerceptron * getMultilayerPerceptron (void)
InputTargetDataSet * getInputTargetDataSet (void)
bool getDisplay (void)
void setMultilayerPerceptron (MultilayerPerceptron *)
void setInputTargetDataSet (InputTargetDataSet *)
void setDisplay (bool)
Matrix< double > getOutputData (void)
double calculateCorrectPredictionsRatio (void)
void printResults (void)
void saveResults (char *)
Private Attributes
MultilayerPerceptron * multilayerPerceptron
Pointer to a multilayer perceptron object.
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
bool display
Display messages to screen.
Detailed Description
This class contains methods for performing correct predictions analysis, which is a validation technique for pattern recognition problems. It consists on calculating the ratio of correct predictions made by a multilayer perceptron on an independent testing set.
See also:
MultilayerPerceptron
InputTargetDataSet
Definition at line 37 of file CorrectPredictionsAnalysis.h.
Constructor & Destructor Documentation
Flood::CorrectPredictionsAnalysis::CorrectPredictionsAnalysis (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a correct predictions analysis object associated to a multilayer perceptron and an input-target data set objects. That multilayer perceptron is going to be validated on that input-target data set. This constructor also initializes the rest of class members to their default values:
Display: True.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 43 of file CorrectPredictionsAnalysis.cpp.
Flood::CorrectPredictionsAnalysis::CorrectPredictionsAnalysis (void)
Default constructor. It creates a correct predictions analysis object not associated to any multilayer perceptron neither any input-target data set objects. This constructor also initializes the rest of class members to their default values:
Display: True.
Definition at line 63 of file CorrectPredictionsAnalysis.cpp.
References display, inputTargetDataSet, and multilayerPerceptron.
Flood::CorrectPredictionsAnalysis::~CorrectPredictionsAnalysis () [virtual]
Destructor.
Definition at line 77 of file CorrectPredictionsAnalysis.cpp.
Member Function Documentation
MultilayerPerceptron * Flood::CorrectPredictionsAnalysis::getMultilayerPerceptron (void)
This method returns a pointer to the multilayer perceptron object which is to be validated.
Definition at line 90 of file CorrectPredictionsAnalysis.cpp.
References multilayerPerceptron.
InputTargetDataSet * Flood::CorrectPredictionsAnalysis::getInputTargetDataSet (void)
This method returns a pointer to the input-target data set object used for validating the performance of a trained multilayer perceptron.
Definition at line 101 of file CorrectPredictionsAnalysis.cpp.
References inputTargetDataSet.
bool Flood::CorrectPredictionsAnalysis::getDisplay (void)
This method returns true if messages from this class can be displayed on the screen, or false if messages from this class can't be displayed on the screen.
Definition at line 112 of file CorrectPredictionsAnalysis.cpp.
References display.
void Flood::CorrectPredictionsAnalysis::setMultilayerPerceptron (MultilayerPerceptron * newMultilayerPerceptron)
This method sets a new multilayer perceptron which is to be validated.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 125 of file CorrectPredictionsAnalysis.cpp.
References multilayerPerceptron.
void Flood::CorrectPredictionsAnalysis::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a new input-target data set to be used for validating the quality of a trained multilayer perceptron.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 139 of file CorrectPredictionsAnalysis.cpp.
References inputTargetDataSet.
void Flood::CorrectPredictionsAnalysis::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 153 of file CorrectPredictionsAnalysis.cpp.
References display.
Matrix< double > Flood::CorrectPredictionsAnalysis::getOutputData (void)
This method retuns a Matrix containing the neural network outputs for the input data set.
Definition at line 164 of file CorrectPredictionsAnalysis.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), inputTargetDataSet, multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Referenced by calculateCorrectPredictionsRatio(), printResults(), and saveResults().
double Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio (void)
This method performs a correct predictions analysis between the neural network outputs and the corresponding data set targets and returns all the provided parameters in a single vector.
Definition at line 247 of file CorrectPredictionsAnalysis.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), getOutputData(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
Referenced by printResults(), and saveResults().
void Flood::CorrectPredictionsAnalysis::printResults (void)
This method performs a correct predictions analysis between the neural network outputs and the corresponding data set targets and then prints all results in the screen:
Correct predictions ratio.
Target and output data for each output variable.
See also:
getSaveResults(char*).
Definition at line 367 of file CorrectPredictionsAnalysis.cpp.
References calculateCorrectPredictionsRatio(), Flood::MultilayerPerceptron::getNameOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), getOutputData(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
void Flood::CorrectPredictionsAnalysis::saveResults (char * filename)
This method performs a correct predictions analysis between the neural network outputs and the corresponding data set targets and then saves all results to a data file:
Correct predictions value.
Parameters:
filename Filename.
See also:
printResults(char*).
Definition at line 427 of file CorrectPredictionsAnalysis.cpp.
References calculateCorrectPredictionsRatio(), display, Flood::MultilayerPerceptron::getNameOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), getOutputData(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
Member Data Documentation
MultilayerPerceptron* Flood::CorrectPredictionsAnalysis::multilayerPerceptron [private]
Pointer to a multilayer perceptron object.
Definition at line 46 of file CorrectPredictionsAnalysis.h.
Referenced by calculateCorrectPredictionsRatio(), CorrectPredictionsAnalysis(), getMultilayerPerceptron(), getOutputData(), printResults(), saveResults(), and setMultilayerPerceptron().
InputTargetDataSet* Flood::CorrectPredictionsAnalysis::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 50 of file CorrectPredictionsAnalysis.h.
Referenced by calculateCorrectPredictionsRatio(), CorrectPredictionsAnalysis(), getInputTargetDataSet(), getOutputData(), printResults(), saveResults(), and setInputTargetDataSet().
bool Flood::CorrectPredictionsAnalysis::display [private]
Display messages to screen.
Definition at line 54 of file CorrectPredictionsAnalysis.h.
Referenced by CorrectPredictionsAnalysis(), getDisplay(), saveResults(), and setDisplay().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Utilities/CorrectPredictionsAnalysis.h
G:/Documents/Flood/Flood/Utilities/CorrectPredictionsAnalysis.cpp