Flood: Flood::RootMeanSquaredError Class Reference
Flood::RootMeanSquaredError Class Reference
#include <RootMeanSquaredError.h>
Public Member Functions
RootMeanSquaredError (MultilayerPerceptron *, InputTargetDataSet *)
RootMeanSquaredError (void)
virtual ~RootMeanSquaredError (void)
Destructor.
InputTargetDataSet * getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objective functional is measured.
void setInputTargetDataSet (InputTargetDataSet *)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
void saveInputTargetAndOutput (char *)
Private Attributes
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
Detailed Description
This class represents the root mean squared error objective functional of a multilayer perceptron. This objective functional is used in data modeling problems.
See also:
MultilayerPerceptron.
InputTargetDataSet.
Definition at line 32 of file RootMeanSquaredError.h.
Constructor & Destructor Documentation
Flood::RootMeanSquaredError::RootMeanSquaredError (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a root mean squared error objective functional object associated to a multilayer perceptron and measured on an input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 41 of file RootMeanSquaredError.cpp.
References inputTargetDataSet.
Flood::RootMeanSquaredError::RootMeanSquaredError (void)
Default constructor. It creates a root mean squared error objective functional object not associated to any multilayer perceptron and not measured on any input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Definition at line 61 of file RootMeanSquaredError.cpp.
References inputTargetDataSet.
Flood::RootMeanSquaredError::~RootMeanSquaredError (void) [virtual]
Destructor.
Definition at line 71 of file RootMeanSquaredError.cpp.
Member Function Documentation
InputTargetDataSet * Flood::RootMeanSquaredError::getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objective functional is measured.
Definition at line 83 of file RootMeanSquaredError.cpp.
References inputTargetDataSet.
void Flood::RootMeanSquaredError::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a pointer to an input-data set object on which the objective functional is to be measured.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 96 of file RootMeanSquaredError.cpp.
References inputTargetDataSet.
double Flood::RootMeanSquaredError::calculateEvaluation (void) [virtual]
This method returns the evaluation value of a multilayer perceptron according to the root mean squared error on an input-target data set.
See also:
calculateGradient(void).
Implements Flood::ObjectiveFunctional.
Definition at line 109 of file RootMeanSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Referenced by calculateGradient().
Vector< double > Flood::RootMeanSquaredError::calculateGradient (void) [virtual]
This method returns the the root mean squared error function gradient of a multilayer perceptron on an input-target data set. It uses the error back-propagation method.
See also:
calculateEvaluation(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 212 of file RootMeanSquaredError.cpp.
References calculateEvaluation(), Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer(), Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::Matrix< Type >::getRow(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::MultilayerPerceptron::MeanAndStandardDeviation, Flood::MultilayerPerceptron::MinimumAndMaximum, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::MultilayerPerceptron::None, Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), and Flood::Vector< Type >::setSize().
void Flood::RootMeanSquaredError::saveInputTargetAndOutput (char * filename)
This method saves to a file the inputs and the targets in the input-target data set, together with the outputs from the multilayer perceptron for that inputs:
Inputs.
Targets.
Outputs.
Parameters:
filename Filename.
Definition at line 480 of file RootMeanSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, Flood::InputTargetDataSet::getInputData(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Member Data Documentation
InputTargetDataSet* Flood::RootMeanSquaredError::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 39 of file RootMeanSquaredError.h.
Referenced by calculateEvaluation(), calculateGradient(), getInputTargetDataSet(), RootMeanSquaredError(), saveInputTargetAndOutput(), and setInputTargetDataSet().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/RootMeanSquaredError.h
G:/Documents/Flood/Flood/ObjectiveFunctional/RootMeanSquaredError.cpp