Flood: Flood::RegularizedMinkowskiError Class Reference
Flood::RegularizedMinkowskiError Class Reference
#include <RegularizedMinkowskiError.h>
Public Member Functions
RegularizedMinkowskiError (MultilayerPerceptron *, InputTargetDataSet *)
RegularizedMinkowskiError (void)
virtual ~RegularizedMinkowskiError (void)
Destructor.
InputTargetDataSet * getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objectiveal is measured.
double getMeanSquaredErrorWeight (void)
This method returns the weight of the error term in the objective functional expression.
double getRegularizationWeight (void)
This method returns the weight of the regularization term in the objective functional expression.
void setInputTargetDataSet (InputTargetDataSet *)
void setMeanSquaredErrorWeight (double)
void setRegularizationWeight (double)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
void saveInputTargetAndOutput (char *)
Private Attributes
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
double meanSquaredErrorWeight
Mean squared error term weight.
double regularizationWeight
Regularization term weight.
Detailed Description
This class represents the mean squared error with regularization objective functional of a multilayer perceptron. The regularizer form used here is free parameter decay. This objective functional is used in data modeling problems.
See also:
MultilayerPerceptron.
InputTargetDataSet.
Todo:
This class is actually implementing a regularized mean squared error. Changing the mean squared error by a Minkowski one is required.
Definition at line 36 of file RegularizedMinkowskiError.h.
Constructor & Destructor Documentation
Flood::RegularizedMinkowskiError::RegularizedMinkowskiError (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a regularized mean squared error objective functional object associated to a multilayer perceptron and measured on an input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Mean squared error weight = 1.0.
Regularization weight = 0.1.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 43 of file RegularizedMinkowskiError.cpp.
References inputTargetDataSet, meanSquaredErrorWeight, and regularizationWeight.
Flood::RegularizedMinkowskiError::RegularizedMinkowskiError (void)
Default constructor. It creates a regularized mean squared error objective functional object not associated to any multilayer perceptron and not measured on any input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Mean squared error weight = 1.0.
Regularization weight = 0.1.
Definition at line 68 of file RegularizedMinkowskiError.cpp.
References inputTargetDataSet, meanSquaredErrorWeight, and regularizationWeight.
Flood::RegularizedMinkowskiError::~RegularizedMinkowskiError (void) [virtual]
Destructor.
Definition at line 81 of file RegularizedMinkowskiError.cpp.
Member Function Documentation
InputTargetDataSet * Flood::RegularizedMinkowskiError::getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objectiveal is measured.
Definition at line 93 of file RegularizedMinkowskiError.cpp.
References inputTargetDataSet.
double Flood::RegularizedMinkowskiError::getMeanSquaredErrorWeight (void)
This method returns the weight of the error term in the objective functional expression.
Definition at line 103 of file RegularizedMinkowskiError.cpp.
References meanSquaredErrorWeight.
double Flood::RegularizedMinkowskiError::getRegularizationWeight (void)
This method returns the weight of the regularization term in the objective functional expression.
Definition at line 113 of file RegularizedMinkowskiError.cpp.
References regularizationWeight.
void Flood::RegularizedMinkowskiError::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a pointer to an input-data set object on which the objective functional is to be measured.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 125 of file RegularizedMinkowskiError.cpp.
References inputTargetDataSet.
void Flood::RegularizedMinkowskiError::setMeanSquaredErrorWeight (double newMeanSquaredErrorWeight)
This method sets a new weight for the error term in the objective functional expression. This value must be greater than zero.
Parameters:
newMeanSquaredErrorWeight Weight value for the error term.
Definition at line 138 of file RegularizedMinkowskiError.cpp.
References meanSquaredErrorWeight.
void Flood::RegularizedMinkowskiError::setRegularizationWeight (double newRegularizationWeight)
This method sets a new weight for the regularization term in the objective functional expression. This value must be equal or greater than zero.
Parameters:
newRegularizationWeight Weight value for the regularization term.
Definition at line 166 of file RegularizedMinkowskiError.cpp.
References regularizationWeight.
double Flood::RegularizedMinkowskiError::calculateEvaluation (void) [virtual]
This method returns the evaluation value of a multilayer perceptron according to the mean squared error on an input-target data set.
See also:
calculateGradient(void).
Implements Flood::ObjectiveFunctional.
Definition at line 194 of file RegularizedMinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::Vector< Type >::dot(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, meanSquaredErrorWeight, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and regularizationWeight.
Vector< double > Flood::RegularizedMinkowskiError::calculateGradient (void) [virtual]
This method returns the the mean squared error function gradient of a multilayer perceptron on an input-target data set. It uses the error back-propagation method.
See also:
calculateEvaluation(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 304 of file RegularizedMinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer(), Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::Matrix< Type >::getRow(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::MultilayerPerceptron::MeanAndStandardDeviation, meanSquaredErrorWeight, Flood::MultilayerPerceptron::MinimumAndMaximum, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::MultilayerPerceptron::None, Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), regularizationWeight, and Flood::Vector< Type >::setSize().
void Flood::RegularizedMinkowskiError::saveInputTargetAndOutput (char * filename)
This method saves to a file the inputs and the targets in the input-target data set, together with the outputs from the multilayer perceptron for that inputs:
Inputs.
Targets.
Outputs.
Parameters:
filename Filename.
Definition at line 575 of file RegularizedMinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, Flood::InputTargetDataSet::getInputData(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Member Data Documentation
InputTargetDataSet* Flood::RegularizedMinkowskiError::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 43 of file RegularizedMinkowskiError.h.
Referenced by calculateEvaluation(), calculateGradient(), getInputTargetDataSet(), RegularizedMinkowskiError(), saveInputTargetAndOutput(), and setInputTargetDataSet().
double Flood::RegularizedMinkowskiError::meanSquaredErrorWeight [private]
Mean squared error term weight.
Definition at line 47 of file RegularizedMinkowskiError.h.
Referenced by calculateEvaluation(), calculateGradient(), getMeanSquaredErrorWeight(), RegularizedMinkowskiError(), and setMeanSquaredErrorWeight().
double Flood::RegularizedMinkowskiError::regularizationWeight [private]
Regularization term weight.
Definition at line 51 of file RegularizedMinkowskiError.h.
Referenced by calculateEvaluation(), calculateGradient(), getRegularizationWeight(), RegularizedMinkowskiError(), and setRegularizationWeight().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/RegularizedMinkowskiError.h
G:/Documents/Flood/Flood/ObjectiveFunctional/RegularizedMinkowskiError.cpp