Flood: Flood::CarProblem Class Reference
Flood::CarProblem Class Reference
#include <CarProblem.h>
Public Member Functions
CarProblem (MultilayerPerceptron *)
CarProblem (void)
virtual ~CarProblem (void)
Destructor.
double getInitialPosition (void)
This method returns the position of the car at the initial time.
double getInitialVelocity (void)
This method returns the velocity of the car at the initial time.
double getFinalPositionGoal (void)
This method returns the desired position of the car at the final time.
double getFinalVelocityGoal (void)
This method returns the desired velocity of the car at the final time.
double getMaximumAcceleration (void)
This method returns the maximum acceleration of the car, which is limited by the capability of the engine.
double getMaximumDeceleration (void)
This method returns the maximum deceleration of the car, which is limited by the braking system parameters.
double getFinalPositionErrorWeight (void)
This method returns the weight of the final position error term in the objective functional.
double getFinalVelocityErrorWeight (void)
This method returns the weight of the final velocity error term in the objective functional.
double getFinalTimeWeight (void)
This method returns the weight of the final time term in the objective functional.
double getTolerance (void)
int getInitialSize (void)
void setInitialPosition (double)
void setInitialVelocity (double)
void setFinalPositionGoal (double)
void setFinalVelocityGoal (double)
void setMaximumAcceleration (double)
void setMaximumDeceleration (double)
void setFinalPositionErrorWeight (double)
void setFinalVelocityErrorWeight (double)
void setFinalTimeWeight (double)
void setTolerance (double)
void setInitialSize (int)
double calculatePositionDot (double, double, double)
double calculateVelocityDot (double, double, double)
double calculateEvaluation (void)
This method returns the evaluation value of a multilayer perceptron for the car problem.
void saveResults (char *)
void print (void)
Private Attributes
double initialPosition
Initial car position.
double initialVelocity
Initial car velocity.
double finalPositionGoal
Desired final position of the car.
double finalVelocityGoal
Desired final velocity of the car.
double maximumAcceleration
Car maximum acceleration (bound).
double maximumDeceleration
Car maximum deceleration (bound).
double finalPositionErrorWeight
Weight for the final position error term in the objective functional.
double finalVelocityErrorWeight
Weight for the final velocity error term in the objective functional.
double finalTimeWeight
Weight for the final time term in the objective functional.
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
double tolerance
Tolerance of integration in Runge-Kutta-Fehlberg method.
int initialSize
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the car problem. The car problem for the multilayer perceptron is an optimal control problem with two controls and two state variables. It is defined by an objective functional with two constraints and requiring the integration of a system of ordinary differential equations.
See also:
ObjectiveFunctional.
Definition at line 34 of file CarProblem.h.
Constructor & Destructor Documentation
Flood::CarProblem::CarProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a car problem objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Initial position: 0.
Initial velocity: 0.
Final position goal: 1.
Final velocity goal: 0.
Maximum acceleration: 1.
Maximum decceleration: -1.
Final position error weight: 1.
Final velocity error weight: 1.
Final time weight: 1.0e-3.
Tolerance: 1.0e-12.
Initial size: 1000.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 48 of file CarProblem.cpp.
References finalPositionErrorWeight, finalPositionGoal, finalTimeWeight, finalVelocityErrorWeight, finalVelocityGoal, Flood::MultilayerPerceptron::getNumberOfIndependentParameters(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), initialPosition, initialSize, initialVelocity, maximumAcceleration, maximumDeceleration, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
Flood::CarProblem::CarProblem (void)
Default constructor. It creates a car problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Initial position: 0.
Initial velocity: 0.
Final position goal: 1.
Final velocity goal: 0.
Maximum acceleration: 1.
Maximum decceleration: -1.
Final position error weight: 1.
Final velocity error weight: 1.
Final time weight: 1.0e-3.
Tolerance: 1.0e-12.
Initial size: 1000.
Definition at line 122 of file CarProblem.cpp.
References finalPositionErrorWeight, finalPositionGoal, finalTimeWeight, finalVelocityErrorWeight, finalVelocityGoal, initialPosition, initialSize, initialVelocity, maximumAcceleration, maximumDeceleration, and tolerance.
Flood::CarProblem::~CarProblem (void) [virtual]
Destructor.
Definition at line 147 of file CarProblem.cpp.
Member Function Documentation
double Flood::CarProblem::getInitialPosition (void)
This method returns the position of the car at the initial time.
Definition at line 159 of file CarProblem.cpp.
References initialPosition.
double Flood::CarProblem::getInitialVelocity (void)
This method returns the velocity of the car at the initial time.
Definition at line 169 of file CarProblem.cpp.
References initialVelocity.
double Flood::CarProblem::getFinalPositionGoal (void)
This method returns the desired position of the car at the final time.
Definition at line 179 of file CarProblem.cpp.
References finalPositionGoal.
double Flood::CarProblem::getFinalVelocityGoal (void)
This method returns the desired velocity of the car at the final time.
Definition at line 189 of file CarProblem.cpp.
References finalVelocityGoal.
double Flood::CarProblem::getMaximumAcceleration (void)
This method returns the maximum acceleration of the car, which is limited by the capability of the engine.
Definition at line 199 of file CarProblem.cpp.
References maximumAcceleration.
double Flood::CarProblem::getMaximumDeceleration (void)
This method returns the maximum deceleration of the car, which is limited by the braking system parameters.
Definition at line 209 of file CarProblem.cpp.
References maximumDeceleration.
double Flood::CarProblem::getFinalPositionErrorWeight (void)
This method returns the weight of the final position error term in the objective functional.
Definition at line 219 of file CarProblem.cpp.
References finalPositionErrorWeight.
double Flood::CarProblem::getFinalVelocityErrorWeight (void)
This method returns the weight of the final velocity error term in the objective functional.
Definition at line 229 of file CarProblem.cpp.
References finalVelocityErrorWeight.
double Flood::CarProblem::getFinalTimeWeight (void)
This method returns the weight of the final time term in the objective functional.
Definition at line 239 of file CarProblem.cpp.
References finalTimeWeight.
double Flood::CarProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the final position and velocity errors.
Definition at line 250 of file CarProblem.cpp.
References tolerance.
int Flood::CarProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the final position and velocity errors.
Definition at line 261 of file CarProblem.cpp.
References initialSize.
void Flood::CarProblem::setInitialPosition (double newInitialPosition)
This method sets a new position of the car at the initial time.
Parameters:
newInitialPosition Initial position value.
Definition at line 273 of file CarProblem.cpp.
References initialPosition.
void Flood::CarProblem::setInitialVelocity (double newInitialVelocity)
This method sets a new velocity of the car at the initial time.
Parameters:
newInitialVelocity Initial velocity value.
Definition at line 285 of file CarProblem.cpp.
References initialVelocity.
void Flood::CarProblem::setFinalPositionGoal (double newFinalPositionGoal)
This method sets a new desired position of the car at the final time.
Parameters:
newFinalPositionGoal Desired final position.
Definition at line 297 of file CarProblem.cpp.
References finalPositionGoal.
void Flood::CarProblem::setFinalVelocityGoal (double newFinalVelocityGoal)
This method sets a new desired velocity of the car at the final time.
Parameters:
newFinalVelocityGoal Desired final velocity.
Definition at line 309 of file CarProblem.cpp.
References finalVelocityGoal.
void Flood::CarProblem::setMaximumAcceleration (double newMaximumAcceleration)
This method sets a new value for the maximum acceleration of the car. The maximum acceleration must be a positive number.
Parameters:
newMaximumAcceleration Maximum acceleration.
Definition at line 322 of file CarProblem.cpp.
References maximumAcceleration.
void Flood::CarProblem::setMaximumDeceleration (double newMaximumDeceleration)
This method sets a new value for the maximum deceleration of the car. The maximum deceleration must be a negative number.
Parameters:
newMaximumDeceleration Maximum deceleration.
Definition at line 350 of file CarProblem.cpp.
References maximumDeceleration.
void Flood::CarProblem::setFinalPositionErrorWeight (double newFinalPositionErrorWeight)
This method sets a new weight value for the final position error term in the objective functional expression. The weighs of all terms in the objective functional must be positive.
Parameters:
newFinalPositionErrorWeight Weight of final position error term.
Definition at line 378 of file CarProblem.cpp.
References finalPositionErrorWeight.
void Flood::CarProblem::setFinalVelocityErrorWeight (double newFinalVelocityErrorWeight)
This method sets a new weight value for the final velocity error term in the objective functional expression. The weighs of all terms in the objective functional must be positive.
Parameters:
newFinalVelocityErrorWeight Weight of final velocity error term.
Definition at line 406 of file CarProblem.cpp.
References finalVelocityErrorWeight.
void Flood::CarProblem::setFinalTimeWeight (double newFinalTimeWeight)
This method sets a new weight value for the final time term in the objective functional, which is to be minimized. The weighs of all terms in the objective functional must be positive.
Parameters:
newFinalTimeWeight Weight of final time term.
Definition at line 435 of file CarProblem.cpp.
References finalTimeWeight.
void Flood::CarProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the final position and velocity errors. The tolerance of integration must be a small value greater than zero.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 464 of file CarProblem.cpp.
References ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
void Flood::CarProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the final position and velocity errors. The initial size must be a big value greater than zero, otherwise resizing will be necessary.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 495 of file CarProblem.cpp.
References initialSize, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setInitialSize().
double Flood::CarProblem::calculatePositionDot (double time, double position, double velocity)
This method depicts the state equation for the position in the car problem. It returns the derivative of the position with respect to the time as a function of time, position and velocity.
Parameters:
time Actual time.
position Actual position.
velocity Actual velocity.
Definition at line 527 of file CarProblem.cpp.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::CarProblem::calculateVelocityDot (double time, double position, double velocity)
This method depicts the state equation for the velocity in the car problem. It returns the derivative of the velocity with respect to the time as a function of time, position and velocity.
Parameters:
time Actual time.
position Actual position.
velocity Actual velocity.
Definition at line 544 of file CarProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), maximumAcceleration, maximumDeceleration, and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::CarProblem::calculateEvaluation (void) [virtual]
This method returns the evaluation value of a multilayer perceptron for the car problem.
Implements Flood::ObjectiveFunctional.
Definition at line 583 of file CarProblem.cpp.
References calculatePositionDot(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), calculateVelocityDot(), finalPositionErrorWeight, finalPositionGoal, finalTimeWeight, finalVelocityErrorWeight, finalVelocityGoal, Flood::MultilayerPerceptron::getIndependentParameters(), Flood::MultilayerPerceptron::getNumberOfIndependentParameters(), initialPosition, initialVelocity, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and ordinaryDifferentialEquations.
void Flood::CarProblem::saveResults (char * filename)
This method saves the trajectory and the control signal for the car problem to a data file. The column format is as follows:
Time.
Position.
Velocity.
Acceleration.
Deceleration.
Parameters:
filename Filename.
Definition at line 672 of file CarProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), calculatePositionDot(), calculateVelocityDot(), Flood::ObjectiveFunctional::display, finalPositionGoal, finalVelocityGoal, Flood::MultilayerPerceptron::getIndependentParameters(), Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral(), initialPosition, initialVelocity, maximumAcceleration, maximumDeceleration, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setNumberOfPoints().
void Flood::CarProblem::print (void) [virtual]
This method prints to the screen useful information about the car problem objective functional of a multilayer perceptron.
Final position error.
Final velocity error.
Final time.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 803 of file CarProblem.cpp.
References calculatePositionDot(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), calculateVelocityDot(), finalPositionGoal, finalVelocityGoal, Flood::MultilayerPerceptron::getIndependentParameters(), initialPosition, initialVelocity, Flood::ObjectiveFunctional::multilayerPerceptron, and ordinaryDifferentialEquations.
Member Data Documentation
double Flood::CarProblem::initialPosition [private]
Initial car position.
Definition at line 41 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getInitialPosition(), print(), saveResults(), and setInitialPosition().
double Flood::CarProblem::initialVelocity [private]
Initial car velocity.
Definition at line 45 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getInitialVelocity(), print(), saveResults(), and setInitialVelocity().
double Flood::CarProblem::finalPositionGoal [private]
Desired final position of the car.
Definition at line 49 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getFinalPositionGoal(), print(), saveResults(), and setFinalPositionGoal().
double Flood::CarProblem::finalVelocityGoal [private]
Desired final velocity of the car.
Definition at line 53 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getFinalVelocityGoal(), print(), saveResults(), and setFinalVelocityGoal().
double Flood::CarProblem::maximumAcceleration [private]
Car maximum acceleration (bound).
Definition at line 57 of file CarProblem.h.
Referenced by calculateVelocityDot(), CarProblem(), getMaximumAcceleration(), saveResults(), and setMaximumAcceleration().
double Flood::CarProblem::maximumDeceleration [private]
Car maximum deceleration (bound).
Definition at line 61 of file CarProblem.h.
Referenced by calculateVelocityDot(), CarProblem(), getMaximumDeceleration(), saveResults(), and setMaximumDeceleration().
double Flood::CarProblem::finalPositionErrorWeight [private]
Weight for the final position error term in the objective functional.
Definition at line 65 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getFinalPositionErrorWeight(), and setFinalPositionErrorWeight().
double Flood::CarProblem::finalVelocityErrorWeight [private]
Weight for the final velocity error term in the objective functional.
Definition at line 69 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getFinalVelocityErrorWeight(), and setFinalVelocityErrorWeight().
double Flood::CarProblem::finalTimeWeight [private]
Weight for the final time term in the objective functional.
Definition at line 73 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), getFinalTimeWeight(), and setFinalTimeWeight().
OrdinaryDifferentialEquations Flood::CarProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 77 of file CarProblem.h.
Referenced by calculateEvaluation(), CarProblem(), print(), saveResults(), setInitialSize(), and setTolerance().
double Flood::CarProblem::tolerance [private]
Tolerance of integration in Runge-Kutta-Fehlberg method.
Definition at line 81 of file CarProblem.h.
Referenced by CarProblem(), getTolerance(), and setTolerance().
int Flood::CarProblem::initialSize [private]
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Definition at line 85 of file CarProblem.h.
Referenced by CarProblem(), getInitialSize(), and setInitialSize().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/CarProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/CarProblem.cpp