Flood: Flood::NewtonMethod Class Reference
Flood::NewtonMethod Class Reference
#include <NewtonMethod.h>
Public Member Functions
NewtonMethod (ObjectiveFunctional *)
NewtonMethod (void)
virtual ~NewtonMethod (void)
Destructor.
void train (void)
void print (void)
void load (char *)
void save (char *)
void resizeTrainingHistory (int)
void setReserveAllTrainingHistory (bool)
This method makes the training history of all variables to be reseved or not in memory.
void saveTrainingHistory (char *)
This method saves the training history to a data file.
Detailed Description
This concrete class represents the Newton method training algorithm for an objective functional of a multilayer perceptron.
See also:
TrainingAlgorithm.
Definition at line 32 of file NewtonMethod.h.
Constructor & Destructor Documentation
Flood::NewtonMethod::NewtonMethod (ObjectiveFunctional * newObjectiveFunctional)
General constructor. It creates a Newton method training algorithm object associated to an objective functional object. It also initializes the class members to their default values:
Stopping criteria:
Evaluation goal: -1.0e99.
Gradient norm goal: 0.0.
Maximum training time: 1.0e6.
Maximum number of epochs: 100.
User stuff:
Display: true.
Display period: 25.
Parameters:
newObjectiveFunctional Pointer to an objective functional object.
See also:
TrainingAlgorithm.
Definition at line 51 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
Flood::NewtonMethod::NewtonMethod (void)
Default constructor. It creates a Newton method training algorithm object not associated to any objective functional object. It also initializes the class members to their default values:
Stopping criteria:
Evaluation goal: -1.0e99.
Gradient norm goal: 0.0.
Maximum training time: 1.0e6.
Maximum number of epochs: 100.
User stuff:
Display: true.
Display period: 25.
See also:
TrainingAlgorithm.
Definition at line 89 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
Flood::NewtonMethod::~NewtonMethod (void) [virtual]
Destructor.
Definition at line 108 of file NewtonMethod.cpp.
Member Function Documentation
void Flood::NewtonMethod::train (void) [virtual]
This method trains a multilayer perceptron with an associated objective functional according to the Newton method algorithm. Training occurs according to the training parameters.
Implements Flood::TrainingAlgorithm.
Definition at line 122 of file NewtonMethod.cpp.
References Flood::ObjectiveFunctional::calculateEvaluation(), Flood::ObjectiveFunctional::calculateGradient(), Flood::ObjectiveFunctional::calculateInverseHessian(), Flood::Vector< Type >::calculateNorm(), Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::evaluationHistory, Flood::MultilayerPerceptron::getFreeParameters(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::gradientNormHistory, Flood::TrainingAlgorithm::maximumNumberOfEpochs, Flood::TrainingAlgorithm::maximumTime, Flood::TrainingAlgorithm::objectiveFunctional, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveGradientNormHistory, and Flood::MultilayerPerceptron::setFreeParameters().
void Flood::NewtonMethod::print (void) [virtual]
This method prints to the screen the training parameters, the stopping criteria and other user stuff concerning the Newton's method object:
Stopping criteria:
Evaluation goal.
Gradient norm goal.
Maximum training time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Implements Flood::TrainingAlgorithm.
Definition at line 391 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
void Flood::NewtonMethod::load (char * filename) [virtual]
This method loads a Newton's method object from a data file. Please mind about the file format, wich is specified in the User's Guide.
Stopping criteria:
Evaluation goal.
Gradient norm goal.
Maximum time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Parameters:
filename Filename.
See also:
save(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 520 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
void Flood::NewtonMethod::save (char * filename) [virtual]
This method saves the Newton's method object to a data file.
Stopping criteria:
Evaluation goal.
Gradient norm goal.
Maximum time.
Maximum number of epochs.
User stuff:
Display.
Display period.
Parameters:
filename Filename.
See also:
load(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 439 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, Flood::TrainingAlgorithm::gradientNormGoal, Flood::TrainingAlgorithm::maximumNumberOfEpochs, and Flood::TrainingAlgorithm::maximumTime.
void Flood::NewtonMethod::resizeTrainingHistory (int newSize)
This method resizes the vectors or matrices containing training history information to a new size:
Elapsed time history vector.
Free parameters history matrix.
Free parameters norm history vector.
Evaluation history vector.
Gradient history matrix.
Gradient norm history vector.
Training direction history matrix.
Training direction norm history vector
Training rate history vector.
Parameters:
newSize Size of training history.
Definition at line 612 of file NewtonMethod.cpp.
References Flood::TrainingAlgorithm::elapsedTimeHistory, Flood::TrainingAlgorithm::evaluationHistory, Flood::TrainingAlgorithm::freeParametersHistory, Flood::TrainingAlgorithm::freeParametersNormHistory, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::gradientHistory, Flood::TrainingAlgorithm::gradientNormHistory, Flood::TrainingAlgorithm::objectiveFunctional, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, Flood::TrainingAlgorithm::reserveFreeParametersNormHistory, Flood::TrainingAlgorithm::reserveGradientHistory, Flood::TrainingAlgorithm::reserveGradientNormHistory, Flood::Vector< Type >::resize(), and Flood::Matrix< Type >::resize().
void Flood::NewtonMethod::setReserveAllTrainingHistory (bool) [virtual]
This method makes the training history of all variables to be reseved or not in memory.
Implements Flood::TrainingAlgorithm.
void Flood::NewtonMethod::saveTrainingHistory (char *) [virtual]
This method saves the training history to a data file.
Implements Flood::TrainingAlgorithm.
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/TrainingAlgorithm/NewtonMethod.h
G:/Documents/Flood/Flood/TrainingAlgorithm/NewtonMethod.cpp