Flood: Flood::EvolutionaryAlgorithm Class Reference
Flood::EvolutionaryAlgorithm Class Reference
#include <EvolutionaryAlgorithm.h>
Public Types
enum FitnessAssignmentMethod { LinearRanking }
Enumeration of the available training operators for fitness assignment.
enum SelectionMethod { RouletteWheel, StochasticUniversalSampling }
Enumeration of the available training operators for selection.
enum RecombinationMethod { Line, Intermediate }
Enumeration of the available training operators for recombination.
enum MutationMethod { Normal, Uniform }
Enumeration of the available training operators for mutation.
Public Member Functions
EvolutionaryAlgorithm (ObjectiveFunctional *)
EvolutionaryAlgorithm (void)
virtual ~EvolutionaryAlgorithm (void)
Destructor.
int getPopulationSize (void)
This method returns the number of individuals in the population.
Matrix< double > getPopulation (void)
This method returns the population Matrix.
Vector< double > getEvaluation (void)
Vector< double > getFitness (void)
Vector< bool > getSelection (void)
double getSelectivePressure (void)
double getRecombinationSize (void)
double getMutationRate (void)
double getMutationRange (void)
double getMaximumNumberOfGenerations (void)
This method returns the maximum number of generations to train.
bool getReservePopulationHistory (void)
This method returns true if the population history vector of matrices is to be reserved, and false otherwise.
bool getReserveMeanNormHistory (void)
This method returns true if the mean population norm history vector is to be reserved, and false otherwise.
bool getReserveStandardDeviationNormHistory (void)
bool getReserveBestNormHistory (void)
bool getReserveMeanEvaluationHistory (void)
This method returns true if the mean evaluation history vector is to be reserved, and false otherwise.
bool getReserveStandardDeviationEvaluationHistory (void)
bool getReserveBestEvaluationHistory (void)
This method returns true if the best evaluation history vector is to be reserved, and false otherwise.
Vector< Matrix< double > > getPopulationHistory (void)
This method returns the population history over the training epochs, which is a vector of matrices.
Vector< double > getMeanNormHistory (void)
This method returns the mean norm history.
Vector< double > getStandardDeviationNormHistory (void)
This method returns the standard deviation norm history.
Vector< double > getBestNormHistory (void)
This method returns the best norm history.
Vector< double > getMeanEvaluationHistory (void)
Vector< double > getStandardDeviationEvaluationHistory (void)
Vector< double > getBestEvaluationHistory (void)
FitnessAssignmentMethod getFitnessAssignmentMethod (void)
SelectionMethod getSelectionMethod (void)
RecombinationMethod getRecombinationMethod (void)
MutationMethod getMutationMethod (void)
void setPopulationSize (int)
void setPopulation (Matrix< double >)
void setEvaluation (Vector< double >)
void setFitness (Vector< double >)
void setSelection (Vector< bool >)
void setSelectivePressure (double)
void setRecombinationSize (double)
void setMutationRate (double)
void setMutationRange (double)
void setMaximumNumberOfGenerations (int)
void setFitnessAssignmentMethod (FitnessAssignmentMethod)
void setSelectionMethod (SelectionMethod)
void setRecombinationMethod (RecombinationMethod)
void setMutationMethod (MutationMethod)
void setReservePopulationHistory (bool)
void setReserveMeanNormHistory (bool)
void setReserveStandardDeviationNormHistory (bool)
void setReserveBestNormHistory (bool)
void setReserveMeanEvaluationHistory (bool)
void setReserveStandardDeviationEvaluationHistory (bool)
void setReserveBestEvaluationHistory (bool)
void setPopulationHistory (Vector< Matrix< double > >)
void setMeanNormHistory (Vector< double >)
void setStandardDeviationNormHistory (Vector< double >)
void setBestNormHistory (Vector< double >)
void setMeanEvaluationHistory (Vector< double >)
void setStandardDeviationEvaluationHistory (Vector< double >)
void setBestEvaluationHistory (Vector< double >)
Vector< double > getIndividual (int)
void setIndividual (int, Vector< double >)
void initPopulationUniform (void)
void initPopulationUniform (double, double)
void initPopulationUniform (Vector< double >, Vector< double >)
void initPopulationUniform (Matrix< double >)
void initPopulationNormal (void)
void initPopulationNormal (double, double)
void initPopulationNormal (Vector< double >, Vector< double >)
void initPopulationNormal (Matrix< double >)
Vector< double > calculatePopulationNorm (void)
This method returns a vector containing the norm of each individual in the population.
void evaluatePopulation (void)
void performLinearRankingFitnessAssignment (void)
void performRouletteWheelSelection (void)
void performStochasticUniversalSamplingSelection (void)
void performIntermediateRecombination (void)
void performLineRecombination (void)
void performNormalMutation (void)
void performUniformMutation (void)
void train (void)
void resizeTrainingHistory (int)
void print (void)
void load (char *)
void save (char *)
void setReserveAllTrainingHistory (bool)
void saveTrainingHistory (char *)
Private Attributes
int populationSize
Number of individuals in the population.
Matrix< double > population
Population matrix.
Vector< double > evaluation
Evaluation of population.
Vector< double > fitness
Fitness of population.
Vector< bool > selection
Selected individuals in population.
double selectivePressure
double recombinationSize
double mutationRate
double mutationRange
int maximumNumberOfGenerations
Maximum number of generations to train.
bool reservePopulationHistory
bool reserveMeanNormHistory
True if the mean norm history vector is to be reserved, false otherwise.
bool reserveStandardDeviationNormHistory
True if the standard deviation of norm history vector is to be reserved, false otherwise.
bool reserveBestNormHistory
True if the best norm history vector is to be reserved, false otherwise.
bool reserveMeanEvaluationHistory
True if the mean evaluation history vector is to be reserved, false otherwise.
bool reserveStandardDeviationEvaluationHistory
True if the standard deviation of evaluation history vector is to be reserved, false otherwise.
bool reserveBestEvaluationHistory
True if the best evaluation history vector is to be reserved, false otherwise.
Vector< Matrix< double > > populationHistory
Vector< double > meanNormHistory
Vector< double > standardDeviationNormHistory
Vector< double > bestNormHistory
Best individual ever norm history.
Vector< double > meanEvaluationHistory
Mean evaluation training history.
Vector< double > standardDeviationEvaluationHistory
Standard deviation of evaluation training history.
Vector< double > bestEvaluationHistory
Best evaluation ever training history.
FitnessAssignmentMethod fitnessAssignmentMethod
Fitness assignment training operators enumeration.
SelectionMethod selectionMethod
Selection training operators enumeration.
RecombinationMethod recombinationMethod
Recombination training operators enumeration.
MutationMethod mutationMethod
Mutation training operators enumeration.
Detailed Description
This concrete class represents an evolutionary training algorithm for an objective functional of a multilayer perceptron.
See also:
TrainingAlgorithm.
Definition at line 32 of file EvolutionaryAlgorithm.h.
Member Enumeration Documentation
enum Flood::EvolutionaryAlgorithm::FitnessAssignmentMethod
Enumeration of the available training operators for fitness assignment.
Enumerator:
LinearRanking
Definition at line 41 of file EvolutionaryAlgorithm.h.
enum Flood::EvolutionaryAlgorithm::SelectionMethod
Enumeration of the available training operators for selection.
Enumerator:
RouletteWheel
StochasticUniversalSampling
Definition at line 45 of file EvolutionaryAlgorithm.h.
enum Flood::EvolutionaryAlgorithm::RecombinationMethod
Enumeration of the available training operators for recombination.
Enumerator:
Line
Intermediate
Definition at line 49 of file EvolutionaryAlgorithm.h.
enum Flood::EvolutionaryAlgorithm::MutationMethod
Enumeration of the available training operators for mutation.
Enumerator:
Normal
Uniform
Definition at line 53 of file EvolutionaryAlgorithm.h.
Constructor & Destructor Documentation
Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm (ObjectiveFunctional * newObjectiveFunctional)
General constructor. It creates a evolutionary training algorithm object associated to an objective functional object. It also initializes the class members to their default values:
Training operators:
Fitness assignment method: Linear ranking.
Selection method: Stochastic universal sampling.
Recombination method: Intermediate.
Mutation method: Normal.
Training parameters:
Population size: 10 * [number of free parameters].
Selective pressure: 1.5.
Recombination size: 0.25.
Mutation rate: = 1.0 / [number of free parameters].
Mutation range: = 0.1
Stopping criteria:
Evaluation goal: -1.0e99.
Maximum training time: 1.0e6.
Maximum number of generations: 100.
User stuff:
Display: 1.
Display period: 1.
Parameters:
newObjectiveFunctional Pointer to an objective functional object.
Definition at line 66 of file EvolutionaryAlgorithm.cpp.
References Flood::TrainingAlgorithm::displayPeriod, evaluation, Flood::TrainingAlgorithm::evaluationGoal, fitness, fitnessAssignmentMethod, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), initPopulationNormal(), Intermediate, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, mutationMethod, mutationRange, mutationRate, Normal, Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, recombinationMethod, recombinationSize, reserveBestEvaluationHistory, reserveBestNormHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, Flood::Vector< Type >::resize(), Flood::Matrix< Type >::resize(), selection, selectionMethod, selectivePressure, and StochasticUniversalSampling.
Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm (void)
Default constructor. It creates a evolutionary training algorithm object not associated to any objective functional object. It also initializes the class members to their default values:
Training operators:
Fitness assignment method: Linear ranking.
Selection method: Stochastic universal sampling.
Recombination method: Intermediate.
Mutation method: Normal.
Training parameters:
Population size: 0.
Selective pressure: 1.5.
Recombination size: 0.25.
Mutation rate: = 0.1.
Mutation range: = 0.1
Stopping criteria:
Evaluation goal: -1.0e99.
Maximum training time: 1.0e6.
Maximum number of generations: 100.
User stuff:
Display: 1.
Display period: 1.
Definition at line 175 of file EvolutionaryAlgorithm.cpp.
References Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, fitnessAssignmentMethod, Intermediate, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, mutationMethod, mutationRange, mutationRate, Normal, populationSize, recombinationMethod, recombinationSize, reserveBestEvaluationHistory, reserveBestNormHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, selectionMethod, selectivePressure, and StochasticUniversalSampling.
Flood::EvolutionaryAlgorithm::~EvolutionaryAlgorithm (void) [virtual]
Destructor.
Definition at line 227 of file EvolutionaryAlgorithm.cpp.
Member Function Documentation
int Flood::EvolutionaryAlgorithm::getPopulationSize (void)
This method returns the number of individuals in the population.
Definition at line 239 of file EvolutionaryAlgorithm.cpp.
References populationSize.
Matrix< double > Flood::EvolutionaryAlgorithm::getPopulation (void)
This method returns the population Matrix.
Definition at line 350 of file EvolutionaryAlgorithm.cpp.
References population.
Vector< double > Flood::EvolutionaryAlgorithm::getEvaluation (void)
This method returns the actual evaluation value of all individuals in the population.
See also:
getFitness(void).
getSelection(void).
Definition at line 363 of file EvolutionaryAlgorithm.cpp.
References evaluation.
Vector< double > Flood::EvolutionaryAlgorithm::getFitness (void)
This method returns the actual fitness value of all individuals in the population.
See also:
calculateEvaluation(void).
getSelection(void).
Definition at line 376 of file EvolutionaryAlgorithm.cpp.
References fitness.
Vector< bool > Flood::EvolutionaryAlgorithm::getSelection (void)
This method returns the actual selection value of all individuals in the population.
See also:
calculateEvaluation(void).
getFitness(void).
Definition at line 389 of file EvolutionaryAlgorithm.cpp.
References selection.
double Flood::EvolutionaryAlgorithm::getSelectivePressure (void)
This method returns the selective pressure value.
See also:
performLinearRankingFitnessAssignment(void).
Definition at line 958 of file EvolutionaryAlgorithm.cpp.
References selectivePressure.
double Flood::EvolutionaryAlgorithm::getRecombinationSize (void)
This method returns the recombination size value.
See also:
performIntermediateRecombination(void)
performLineRecombination(void).
Definition at line 971 of file EvolutionaryAlgorithm.cpp.
References recombinationSize.
double Flood::EvolutionaryAlgorithm::getMutationRate (void)
This method returns the mutation rate value.
See also:
performNormalMutation(void).
performUniformMutation(void).
Definition at line 984 of file EvolutionaryAlgorithm.cpp.
References mutationRate.
double Flood::EvolutionaryAlgorithm::getMutationRange (void)
This method returns the mutation range value.
See also:
performNormalMutation(void).
performUniformMutation(void).
Definition at line 997 of file EvolutionaryAlgorithm.cpp.
References mutationRange.
double Flood::EvolutionaryAlgorithm::getMaximumNumberOfGenerations (void)
This method returns the maximum number of generations to train.
Definition at line 1007 of file EvolutionaryAlgorithm.cpp.
References maximumNumberOfGenerations.
bool Flood::EvolutionaryAlgorithm::getReservePopulationHistory (void)
This method returns true if the population history vector of matrices is to be reserved, and false otherwise.
Definition at line 399 of file EvolutionaryAlgorithm.cpp.
References reservePopulationHistory.
bool Flood::EvolutionaryAlgorithm::getReserveMeanNormHistory (void)
This method returns true if the mean population norm history vector is to be reserved, and false otherwise.
Definition at line 409 of file EvolutionaryAlgorithm.cpp.
References reserveMeanNormHistory.
bool Flood::EvolutionaryAlgorithm::getReserveStandardDeviationNormHistory (void)
This method returns true if the standard deviation of the population norm history vector is to be reserved, and false otherwise.
Definition at line 420 of file EvolutionaryAlgorithm.cpp.
References reserveStandardDeviationNormHistory.
bool Flood::EvolutionaryAlgorithm::getReserveBestNormHistory (void)
This method returns true if the norm of the best individual in the population history vector is to be reserved, and false otherwise.
Definition at line 431 of file EvolutionaryAlgorithm.cpp.
References reserveBestNormHistory.
bool Flood::EvolutionaryAlgorithm::getReserveMeanEvaluationHistory (void)
This method returns true if the mean evaluation history vector is to be reserved, and false otherwise.
Definition at line 441 of file EvolutionaryAlgorithm.cpp.
References reserveMeanEvaluationHistory.
bool Flood::EvolutionaryAlgorithm::getReserveStandardDeviationEvaluationHistory (void)
This method returns true if the standard deviation of the evaluation history vector is to be reserved, and false otherwise.
Definition at line 452 of file EvolutionaryAlgorithm.cpp.
References reserveStandardDeviationEvaluationHistory.
bool Flood::EvolutionaryAlgorithm::getReserveBestEvaluationHistory (void)
This method returns true if the best evaluation history vector is to be reserved, and false otherwise.
Definition at line 462 of file EvolutionaryAlgorithm.cpp.
References reserveBestEvaluationHistory.
Vector< Matrix< double > > Flood::EvolutionaryAlgorithm::getPopulationHistory (void)
This method returns the population history over the training epochs, which is a vector of matrices.
Definition at line 472 of file EvolutionaryAlgorithm.cpp.
References populationHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getMeanNormHistory (void)
This method returns the mean norm history.
Definition at line 482 of file EvolutionaryAlgorithm.cpp.
References meanNormHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getStandardDeviationNormHistory (void)
This method returns the standard deviation norm history.
Definition at line 491 of file EvolutionaryAlgorithm.cpp.
References standardDeviationNormHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getBestNormHistory (void)
This method returns the best norm history.
Definition at line 501 of file EvolutionaryAlgorithm.cpp.
References bestNormHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getMeanEvaluationHistory (void)
This method returns a history with the mean evaluation of the population during training.
See also:
getBestEvaluationHistory(void).
getStandardDeviationEvaluationHistory(void).
Definition at line 252 of file EvolutionaryAlgorithm.cpp.
References meanEvaluationHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getStandardDeviationEvaluationHistory (void)
This method returns a history with the standard deviation of the population evaluation during training.
See also:
getBestEvaluationHistory(void).
getMeanEvaluationHistory(void).
Definition at line 265 of file EvolutionaryAlgorithm.cpp.
References standardDeviationEvaluationHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getBestEvaluationHistory (void)
This method returns a history with the evaluation value of the best individual ever during training.
See also:
getMeanEvaluationHistory(void).
getStandardDeviationEvaluationHistory(void).
Definition at line 278 of file EvolutionaryAlgorithm.cpp.
References bestEvaluationHistory.
EvolutionaryAlgorithm::FitnessAssignmentMethod Flood::EvolutionaryAlgorithm::getFitnessAssignmentMethod (void)
This method returns the fitness assignment method used for training.
See also:
performLinearRankingFitnessAssignment(void).
train(void).
Definition at line 1019 of file EvolutionaryAlgorithm.cpp.
References fitnessAssignmentMethod.
EvolutionaryAlgorithm::SelectionMethod Flood::EvolutionaryAlgorithm::getSelectionMethod (void)
This method returns the selection method used for training.
See also:
performRouletteWheelSelection(void).
performStochasticUniversalSamplingSelection(void).
train(void).
Definition at line 1033 of file EvolutionaryAlgorithm.cpp.
References selectionMethod.
EvolutionaryAlgorithm::RecombinationMethod Flood::EvolutionaryAlgorithm::getRecombinationMethod (void)
This method returns the recombination method used for training.
See also:
performIntermediateRecombination(void).
performLineRecombination(void).
train(void).
Definition at line 1047 of file EvolutionaryAlgorithm.cpp.
References recombinationMethod.
EvolutionaryAlgorithm::MutationMethod Flood::EvolutionaryAlgorithm::getMutationMethod (void)
This method returns the mutation method used for training.
See also:
performNormalMutation(void).
performUniformMutation(void).
train(void).
Definition at line 1061 of file EvolutionaryAlgorithm.cpp.
References mutationMethod.
void Flood::EvolutionaryAlgorithm::setPopulationSize (int newPopulationSize)
This method sets a new population with a new number of individuals. The new population size must be an even number equal or greater than four.
Parameters:
newPopulationSize Number of individuals in the population. This must be an even number equal or greater than four.
Definition at line 292 of file EvolutionaryAlgorithm.cpp.
References evaluation, fitness, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), initPopulationNormal(), Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, Flood::Vector< Type >::resize(), Flood::Matrix< Type >::resize(), and selection.
void Flood::EvolutionaryAlgorithm::setPopulation (Matrix< double > newPopulation)
This method sets a new population.
Parameters:
newPopulation Population Matrix.
Definition at line 513 of file EvolutionaryAlgorithm.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::TrainingAlgorithm::objectiveFunctional, population, and populationSize.
void Flood::EvolutionaryAlgorithm::setEvaluation (Vector< double > newEvaluation)
This method sets a new population evaluation vector.
Parameters:
newEvaluation Population evaluation values.
Definition at line 558 of file EvolutionaryAlgorithm.cpp.
References evaluation, Flood::Vector< Type >::getSize(), and populationSize.
void Flood::EvolutionaryAlgorithm::setFitness (Vector< double > newFitness)
This method sets a new population fitness vector.
Parameters:
newFitness Population fitness values.
Definition at line 588 of file EvolutionaryAlgorithm.cpp.
References fitness, Flood::Vector< Type >::getSize(), and populationSize.
void Flood::EvolutionaryAlgorithm::setSelection (Vector< bool > newSelection)
This method sets a new population selection vector.
Parameters:
newSelection Population selection values.
Definition at line 619 of file EvolutionaryAlgorithm.cpp.
References Flood::Vector< Type >::getSize(), populationSize, and selection.
void Flood::EvolutionaryAlgorithm::setSelectivePressure (double newSelectivePressure)
This method sets a new value for the selective pressure parameter. Linear ranking allows values for the selective pressure between 1 and 2.
Parameters:
newSelectivePressure Selective pressure value. This must be between 1 and 2 for linear ranking fitness assignment.
See also:
performLinearRankingFitnessAssignment(void).
Definition at line 1077 of file EvolutionaryAlgorithm.cpp.
References fitnessAssignmentMethod, LinearRanking, and selectivePressure.
void Flood::EvolutionaryAlgorithm::setRecombinationSize (double newRecombinationSize)
This method sets a new value for the recombination size parameter. The recombination size value must be equal or greater than 0.
Parameters:
newRecombinationSize Recombination size value. This must be equal or greater than 0.
See also:
performIntermediateRecombination(void)
performLineRecombination(void).
Definition at line 1114 of file EvolutionaryAlgorithm.cpp.
References recombinationSize.
void Flood::EvolutionaryAlgorithm::setMutationRate (double newMutationRate)
This method sets a new value for the mutation rate parameter. The mutation rate value must be between 0 and 1.
Parameters:
newMutationRate Mutation rate value. This value must lie in the interval [0,1].
See also:
performNormalMutation(void).
performUniformMutation(void).
Definition at line 1143 of file EvolutionaryAlgorithm.cpp.
References mutationRate.
void Flood::EvolutionaryAlgorithm::setMutationRange (double newMutationRange)
This method sets a new value for the mutation range parameter. The mutation range value must be 0 or a positive number.
Parameters:
newMutationRange Mutation range value. This must be equal or greater than 0.
See also:
performNormalMutation(void).
performUniformMutation(void).
Definition at line 1174 of file EvolutionaryAlgorithm.cpp.
References mutationRange.
void Flood::EvolutionaryAlgorithm::setMaximumNumberOfGenerations (int newMaximumNumberOfGenerations)
This method sets a new value for the maximum number of generations to train. The maximum number of generations value must be a positive number.
Parameters:
newMaximumNumberOfGenerations Maximum number of generations value.
Definition at line 1202 of file EvolutionaryAlgorithm.cpp.
References maximumNumberOfGenerations.
void Flood::EvolutionaryAlgorithm::setFitnessAssignmentMethod (EvolutionaryAlgorithm::FitnessAssignmentMethod newFitnessAssignmentMethod)
This method sets a new fitness assignment method to be used for training.
Parameters:
newFitnessAssignmentMethod Fitness assignment method chosen for training.
See also:
performLinearRankingFitnessAssignment(void).
Definition at line 1236 of file EvolutionaryAlgorithm.cpp.
References fitnessAssignmentMethod.
void Flood::EvolutionaryAlgorithm::setSelectionMethod (EvolutionaryAlgorithm::SelectionMethod newSelectionMethod)
This method sets a new selection method to be used for training.
Parameters:
newSelectionMethod Selection method chosen for training.
See also:
performRouletteWheelSelection(void).
performStochasticUniversalSamplingSelection(void).
Definition at line 1251 of file EvolutionaryAlgorithm.cpp.
References selectionMethod.
void Flood::EvolutionaryAlgorithm::setRecombinationMethod (EvolutionaryAlgorithm::RecombinationMethod newRecombinationMethod)
This method sets a new recombination method to be used for training.
Parameters:
newRecombinationMethod Recombination method chosen for training.
See also:
performIntermediateRecombination(void).
performLineRecombination(void).
Definition at line 1267 of file EvolutionaryAlgorithm.cpp.
References recombinationMethod.
void Flood::EvolutionaryAlgorithm::setMutationMethod (EvolutionaryAlgorithm::MutationMethod newMutationMethod)
This method sets a new mutation method to be used for training.
Parameters:
newMutationMethod Mutation method chosen for training.
See also:
performNormalMutation(void).
performUniformMutation(void).
Definition at line 1283 of file EvolutionaryAlgorithm.cpp.
References mutationMethod.
void Flood::EvolutionaryAlgorithm::setReservePopulationHistory (bool newReservePopulationHistory)
This method makes the population history vector of matrices to be reseved or not in memory.
Parameters:
newReservePopulationHistory True if the population history vector of matrices is to be reserved, false otherwise.
Definition at line 651 of file EvolutionaryAlgorithm.cpp.
References reservePopulationHistory.
void Flood::EvolutionaryAlgorithm::setReserveMeanNormHistory (bool newReserveMeanNormHistory)
This method makes the mean norm history vector to be reseved or not in memory.
Parameters:
newReserveMeanNormHistory True if the mean norm history vector is to be reserved, false otherwise.
Definition at line 663 of file EvolutionaryAlgorithm.cpp.
References reserveMeanNormHistory.
void Flood::EvolutionaryAlgorithm::setReserveStandardDeviationNormHistory (bool newReserveStandardDeviationNormHistory)
This method makes the standard deviation norm history vector to be reseved or not in memory.
Parameters:
newReserveStandardDeviationNormHistory True if the standard deviation norm history vector is to be reserved, false otherwise.
Definition at line 676 of file EvolutionaryAlgorithm.cpp.
References reserveStandardDeviationNormHistory.
void Flood::EvolutionaryAlgorithm::setReserveBestNormHistory (bool newReserveBestNormHistory)
This method makes the best norm history vector to be reseved or not in memory.
Parameters:
newReserveBestNormHistory True if the best norm history vector is to be reserved, false otherwise.
Definition at line 688 of file EvolutionaryAlgorithm.cpp.
References reserveBestNormHistory.
void Flood::EvolutionaryAlgorithm::setReserveMeanEvaluationHistory (bool newReserveMeanEvaluationHistory)
This method makes the mean evaluation history vector to be reseved or not in memory.
Parameters:
newReserveMeanEvaluationHistory True if the mean evaluation history vector is to be reserved, false otherwise.
Definition at line 701 of file EvolutionaryAlgorithm.cpp.
References reserveMeanEvaluationHistory.
void Flood::EvolutionaryAlgorithm::setReserveStandardDeviationEvaluationHistory (bool newReserveStandardDeviationEvaluationHistory)
This method makes the standard deviation evaluation history vector to be reseved or not in memory.
Parameters:
newReserveStandardDeviationEvaluationHistory True if the standard deviation evaluation history vector is to be reserved, false otherwise.
Definition at line 715 of file EvolutionaryAlgorithm.cpp.
References reserveStandardDeviationEvaluationHistory.
void Flood::EvolutionaryAlgorithm::setReserveBestEvaluationHistory (bool newReserveBestEvaluationHistory)
This method makes the best evaluation history vector to be reseved or not in memory.
Parameters:
newReserveBestEvaluationHistory True if the best evaluation history vector is to be reserved, false otherwise.
Definition at line 728 of file EvolutionaryAlgorithm.cpp.
References reserveBestEvaluationHistory.
void Flood::EvolutionaryAlgorithm::setPopulationHistory (Vector< Matrix< double > > newPopulationHistory)
This method sets a new matrix containing the training direction history over the training epochs. Each element in the vector must contain the population matrix of one single epoch.
Parameters:
newPopulationHistory Population history vector of matrices.
Definition at line 765 of file EvolutionaryAlgorithm.cpp.
References populationHistory.
void Flood::EvolutionaryAlgorithm::setMeanNormHistory (Vector< double > newMeanNormHistory)
This method sets a new vector containing the mean norm history over the training epochs. Each element in the vector must contain the mean norm of one single epoch.
Parameters:
newMeanNormHistory Mean norm history vector.
Definition at line 778 of file EvolutionaryAlgorithm.cpp.
References meanNormHistory.
void Flood::EvolutionaryAlgorithm::setStandardDeviationNormHistory (Vector< double > newStandardDeviationNormHistory)
This method sets a new vector containing the standard deviation norm history over the training epochs. Each element in the vector must contain the standard deviation norm of one single epoch.
Parameters:
newStandardDeviationNormHistory Standard deviation norm history vector.
Definition at line 791 of file EvolutionaryAlgorithm.cpp.
References standardDeviationNormHistory.
void Flood::EvolutionaryAlgorithm::setBestNormHistory (Vector< double > newBestNormHistory)
This method sets a new vector containing the best norm history over the training epochs. Each element in the vector must contain the best norm of one single epoch.
Parameters:
newBestNormHistory Best norm history vector.
Definition at line 804 of file EvolutionaryAlgorithm.cpp.
References bestNormHistory.
void Flood::EvolutionaryAlgorithm::setMeanEvaluationHistory (Vector< double > newMeanEvaluationHistory)
This method sets a new vector containing the mean evaluation history over the training epochs. Each element in the vector must contain the mean evaluation of one single epoch.
Parameters:
newMeanEvaluationHistory Mean evaluation history vector.
Definition at line 817 of file EvolutionaryAlgorithm.cpp.
References meanEvaluationHistory.
void Flood::EvolutionaryAlgorithm::setStandardDeviationEvaluationHistory (Vector< double > newStandardDeviationEvaluationHistory)
This method sets a new vector containing the standard deviation evaluation history over the training epochs. Each element in the vector must contain the standard deviation evaluation of one single epoch.
Parameters:
newStandardDeviationEvaluationHistory Standard deviation evaluation history vector.
Definition at line 831 of file EvolutionaryAlgorithm.cpp.
References standardDeviationEvaluationHistory.
void Flood::EvolutionaryAlgorithm::setBestEvaluationHistory (Vector< double > newBestEvaluationHistory)
This method sets a new vector containing the best evaluation history over the training epochs. Each element in the vector must contain the best evaluation of one single epoch.
Parameters:
newBestEvaluationHistory Best evaluation history vector.
Definition at line 844 of file EvolutionaryAlgorithm.cpp.
References bestEvaluationHistory.
Vector< double > Flood::EvolutionaryAlgorithm::getIndividual (int i)
This method returns the Vector of free parameters corresponding to the individual i in the population.
Parameters:
i Index of individual in the population.
Definition at line 856 of file EvolutionaryAlgorithm.cpp.
References Flood::Matrix< Type >::getRow(), population, and populationSize.
Referenced by calculatePopulationNorm(), evaluatePopulation(), initPopulationNormal(), initPopulationUniform(), performIntermediateRecombination(), performLineRecombination(), performNormalMutation(), performUniformMutation(), print(), save(), and train().
void Flood::EvolutionaryAlgorithm::setIndividual (int i, Vector< double > individual)
This method sets a new Vector of free parameters to the individual i in the population.
Parameters:
i Index of individual in the population.
individual Vector of free parameters to be assigned to individual i.
Definition at line 890 of file EvolutionaryAlgorithm.cpp.
References Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, and Flood::Matrix< Type >::setRow().
Referenced by initPopulationNormal(), initPopulationUniform(), performNormalMutation(), and performUniformMutation().
void Flood::EvolutionaryAlgorithm::initPopulationUniform (void)
This method initializes the free parameters of all the individuals in the population at random, with values comprised between -1 and 1.
Definition at line 1294 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationUniform (double minimum, double maximum)
This method initializes the free parameters of all the individuals in the population at random, with values comprised between a minimum and a maximum value.
Parameters:
minimum Minimum initialization value.
maximum Maximum initialization value.
Definition at line 1326 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationUniform (Vector< double > minimum, Vector< double > maximum)
This method initializes the free parameters of all the individuals in the population at random, with values comprised between different minimum and maximum values for each variable.
Parameters:
minimum Vector of minimum initialization values.
maximum Vector of maximum initialization values.
Definition at line 1375 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationUniform (Matrix< double > minimumAndMaximum)
This method initializes the free parameters of all the individuals in the population at random, with values comprised between different minimum and maximum values for each variable. All minimum and maximum values are given from a single matrix. The first row must contain the minimum value for each free parameter. The second row must contain the maximum value for each free parameter.
Parameters:
minimumAndMaximum Matrix of minimum and maximum initialization values.
Definition at line 1429 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationNormal (void)
This method initializes the free parameters of all the individuals in the population with random values chosen from a normal distribution with mean 0 and standard deviation 1.
Definition at line 1482 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
Referenced by EvolutionaryAlgorithm(), and setPopulationSize().
void Flood::EvolutionaryAlgorithm::initPopulationNormal (double mean, double standardDeviation)
This method initializes the free parameters of all the individuals in the population with random values chosen from a normal distribution with a given mean and a given standard deviation.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
Definition at line 1534 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationNormal (Vector< double > mean, Vector< double > standardDeviation)
This method initializes the free parameters of all the individuals in the population with random values chosen from normal distributions with different mean and standard deviation for each free parameter.
Parameters:
mean Vector of mean values.
standardDeviation Vector of standard deviation values.
Definition at line 1582 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
void Flood::EvolutionaryAlgorithm::initPopulationNormal (Matrix< double > meanAndStandardDeviation)
This method initializes the free parameters of all the individuals in the population with random values chosen from normal distributions with different mean and standard deviation for each parameter. All mean and standard deviation values are given from a single matrix. The first row must contain the mean value for each free parameter. The second row must contain the standard deviation value for each free parameter.
Parameters:
meanAndStandardDeviation Matrix of mean and standard deviation values.
Definition at line 1652 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
Vector< double > Flood::EvolutionaryAlgorithm::calculatePopulationNorm (void)
This method returns a vector containing the norm of each individual in the population.
Definition at line 935 of file EvolutionaryAlgorithm.cpp.
References Flood::Vector< Type >::calculateNorm(), getIndividual(), and populationSize.
Referenced by train().
void Flood::EvolutionaryAlgorithm::evaluatePopulation (void)
This method evaluates the objective functional of all individuals in the population. Results are stored in the evaluation vector.
See also:
train(void).
Definition at line 1723 of file EvolutionaryAlgorithm.cpp.
References Flood::ObjectiveFunctional::calculatePotentialEvaluation(), evaluation, getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, and populationSize.
Referenced by train().
void Flood::EvolutionaryAlgorithm::performLinearRankingFitnessAssignment (void)
This method ranks all individuals in the population by their objective evaluation, so that the least fit individual has rank 1 and the fittest individual has rank [population size]. It then assigns them a fitness value linearly proportional to their rank. Results are stored in the fitness vector.
See also:
train(void).
Definition at line 1764 of file EvolutionaryAlgorithm.cpp.
References Flood::Vector< Type >::begin(), Flood::Vector< Type >::end(), evaluation, fitness, populationSize, and selectivePressure.
Referenced by train().
void Flood::EvolutionaryAlgorithm::performRouletteWheelSelection (void)
This metod performs selection with roulette wheel selection. It selects half of the individuals from the population. Results are stored in the selection vector.
See also:
performStochasticUniversalSamplingSelection(void) method
train(void).
Definition at line 1818 of file EvolutionaryAlgorithm.cpp.
References fitness, populationSize, and selection.
Referenced by train().
void Flood::EvolutionaryAlgorithm::performStochasticUniversalSamplingSelection (void)
This metod performs selection with stochastic universal sampling. It selects half of the individuals from the population. Results are stored in the selection vector.
See also:
performRouletteWheelSelection(void) method.
train(void).
Definition at line 1901 of file EvolutionaryAlgorithm.cpp.
References fitness, populationSize, and selection.
Referenced by train().
void Flood::EvolutionaryAlgorithm::performIntermediateRecombination (void)
This method performs inediate recombination between pairs of selected individuals to generate a new population. Each selected individual is to be recombined with two other selected individuals chosen at random. Results are stored in the population matrix.
See also:
recombinationSize.
performLineRecombination(void).
train(void).
Definition at line 1990 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, recombinationSize, selection, and Flood::Matrix< Type >::setRow().
Referenced by train().
void Flood::EvolutionaryAlgorithm::performLineRecombination (void)
This method performs line recombination between pairs of selected individuals to generate a new population. Each selected individual is to be recombined with two other selected individuals chosen at random. Results are stored in the population matrix.
See also:
recombinationSize.
performIntermediateRecombination(void).
train(void).
Definition at line 2108 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, recombinationSize, selection, and Flood::Matrix< Type >::setRow().
Referenced by train().
void Flood::EvolutionaryAlgorithm::performNormalMutation (void)
This method performs normal mutation to all individuals in order to generate a new population. It uses the Box-Muller transformation to generate random numbers with normal distribution. Results are stored in the population matrix.
See also:
mutationRate.
mutationRange.
performUniformMutation(void).
train(void).
Definition at line 2219 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), mutationRange, mutationRate, Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
Referenced by train().
void Flood::EvolutionaryAlgorithm::performUniformMutation (void)
This method performs uniform mutation to all individuals in order to generate a new population. Results are stored in the population matrix.
See also:
mutationRate.
mutationRange.
performNormalMutation(void).
train(void).
Definition at line 2281 of file EvolutionaryAlgorithm.cpp.
References getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), mutationRange, mutationRate, Flood::TrainingAlgorithm::objectiveFunctional, populationSize, and setIndividual().
Referenced by train().
void Flood::EvolutionaryAlgorithm::train (void) [virtual]
This method trains a multilayer perceptron with an associated objective function according to the evolutionary algorithm. Training occurs according to the training operators and their related parameters.
See also:
FitnessAssignmentMethod.
SelectionMethod.
RecombinationMethod.
MutationMethod.
Implements Flood::TrainingAlgorithm.
Definition at line 2329 of file EvolutionaryAlgorithm.cpp.
References bestEvaluationHistory, bestNormHistory, Flood::Vector< Type >::calculateMean(), Flood::Vector< Type >::calculateNorm(), calculatePopulationNorm(), Flood::Vector< Type >::calculateStandardDeviation(), Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::elapsedTimeHistory, evaluatePopulation(), evaluation, Flood::TrainingAlgorithm::evaluationGoal, fitnessAssignmentMethod, getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Intermediate, Line, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, meanEvaluationHistory, meanNormHistory, mutationMethod, Normal, Flood::TrainingAlgorithm::objectiveFunctional, performIntermediateRecombination(), performLinearRankingFitnessAssignment(), performLineRecombination(), performNormalMutation(), performRouletteWheelSelection(), performStochasticUniversalSamplingSelection(), performUniformMutation(), population, populationHistory, populationSize, Flood::ObjectiveFunctional::print(), recombinationMethod, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, resizeTrainingHistory(), RouletteWheel, selection, selectionMethod, Flood::MultilayerPerceptron::setFreeParameters(), standardDeviationEvaluationHistory, standardDeviationNormHistory, StochasticUniversalSampling, and Uniform.
void Flood::EvolutionaryAlgorithm::resizeTrainingHistory (int newSize)
This method resizes the vectors or matrices containing training history information to a new size:
Elapsed time history.
Population history.
Mean norm history.
Standard deviation norm history.
Best norm history.
Mean evaluation history.
Standard deviation evaluation history.
Best evaluation history.
Parameters:
newSize Size of training history.
Definition at line 3760 of file EvolutionaryAlgorithm.cpp.
References bestEvaluationHistory, bestNormHistory, Flood::TrainingAlgorithm::elapsedTimeHistory, meanEvaluationHistory, meanNormHistory, populationHistory, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, Flood::Vector< Type >::resize(), standardDeviationEvaluationHistory, and standardDeviationNormHistory.
Referenced by train().
void Flood::EvolutionaryAlgorithm::print (void) [virtual]
This method prints to the screen the members of the evolutionary algorithm object.
Training operators:
Fitness assignment method.
Selection method.
Recombination method.
Mutation method.
Training parameters:
Population size.
Selective pressure.
Recombination size.
Mutation rate.
Mutation range.
Stopping criteria:
Evaluation goal.
Maximum time.
Maximum number of generations.
User stuff:
Display.
Display period.
Reserve elapsed time.
Reserve mean norm history.
Reserve standard deviation of norm history.
Reserve best norm history.
Reserve mean evaluation history.
Reserve standard deviation of evaluation history.
Reserve best evaluation history.
Population matrix.
Implements Flood::TrainingAlgorithm.
Definition at line 2854 of file EvolutionaryAlgorithm.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, fitnessAssignmentMethod, getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Intermediate, Line, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, mutationMethod, mutationRange, mutationRate, Normal, Flood::TrainingAlgorithm::objectiveFunctional, populationSize, recombinationMethod, recombinationSize, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, RouletteWheel, selectionMethod, selectivePressure, StochasticUniversalSampling, and Uniform.
void Flood::EvolutionaryAlgorithm::load (char * filename) [virtual]
This method loads a evolutionary algorithm object from a data file. Please mind about the file format, wich is specified in the User's Guide.
Training operators:
Fitness assignment method.
Selection method.
Recombination method.
Mutation method.
Training parameters:
Population size.
Selective pressure.
Recombination size.
Mutation rate.
Mutation range.
Stopping criteria:
Evaluation goal.
Maximum time.
Maximum number of generations.
User stuff:
Display.
Display period.
Reserve elapsed time history.
Reserve mean norm history.
Reserve standard deviation of norm history.
Reserve best norm history.
Reserve mean evaluation history.
Reserve standard deviation of evaluation history.
Reserve best evaluation history.
Parameters:
filename Filename.
See also:
save(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 3229 of file EvolutionaryAlgorithm.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, fitnessAssignmentMethod, Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Intermediate, Line, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, mutationMethod, mutationRange, mutationRate, Normal, Flood::TrainingAlgorithm::objectiveFunctional, population, populationSize, recombinationMethod, recombinationSize, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, RouletteWheel, selectionMethod, selectivePressure, StochasticUniversalSampling, and Uniform.
void Flood::EvolutionaryAlgorithm::save (char * filename) [virtual]
This method saves the evolutionary algorithm object to a data file.
Training operators:
Fitness assignment method.
Selection method.
Recombination method.
Mutation method.
Training parameters:
Population size.
Selective pressure.
Recombination size.
Mutation rate.
Mutation range.
Stopping criteria:
Evaluation goal.
Maximum time.
Maximum number of generations.
User stuff:
Display.
Display period.
Reserve elapsed time history.
Reserve mean norm history.
Reserve standard deviation of norm history.
Reserve best norm history.
Reserve mean evaluation history.
Reserve standard deviation of evaluation history.
Reserve best evaluation history.
Parameters:
filename Filename.
See also:
load(char*).
Implements Flood::TrainingAlgorithm.
Definition at line 3025 of file EvolutionaryAlgorithm.cpp.
References Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::displayPeriod, Flood::TrainingAlgorithm::evaluationGoal, fitnessAssignmentMethod, getIndividual(), Flood::ObjectiveFunctional::getMultilayerPerceptron(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Intermediate, Line, LinearRanking, maximumNumberOfGenerations, Flood::TrainingAlgorithm::maximumTime, mutationMethod, mutationRange, mutationRate, Normal, Flood::TrainingAlgorithm::objectiveFunctional, populationSize, recombinationMethod, recombinationSize, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, RouletteWheel, selectionMethod, selectivePressure, StochasticUniversalSampling, and Uniform.
void Flood::EvolutionaryAlgorithm::setReserveAllTrainingHistory (bool newReserveAllTrainingHistory) [virtual]
This method makes the training history of all variables to reseved or not in memory.
Parameters:
newReserveAllTrainingHistory True if the training history of all variables is to be reserved, false otherwise.
Implements Flood::TrainingAlgorithm.
Definition at line 741 of file EvolutionaryAlgorithm.cpp.
References reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, Flood::TrainingAlgorithm::reserveEvaluationHistory, Flood::TrainingAlgorithm::reserveFreeParametersHistory, Flood::TrainingAlgorithm::reserveFreeParametersNormHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, and reserveStandardDeviationNormHistory.
void Flood::EvolutionaryAlgorithm::saveTrainingHistory (char * filename) [virtual]
This method saves the training history to a data file.
Parameters:
filename Training history filename.
Implements Flood::TrainingAlgorithm.
Definition at line 3826 of file EvolutionaryAlgorithm.cpp.
References bestEvaluationHistory, bestNormHistory, Flood::TrainingAlgorithm::display, Flood::TrainingAlgorithm::elapsedTimeHistory, meanEvaluationHistory, meanNormHistory, populationHistory, reserveBestEvaluationHistory, reserveBestNormHistory, Flood::TrainingAlgorithm::reserveElapsedTimeHistory, reserveMeanEvaluationHistory, reserveMeanNormHistory, reservePopulationHistory, reserveStandardDeviationEvaluationHistory, reserveStandardDeviationNormHistory, standardDeviationEvaluationHistory, and standardDeviationNormHistory.
Member Data Documentation
int Flood::EvolutionaryAlgorithm::populationSize [private]
Number of individuals in the population.
Definition at line 63 of file EvolutionaryAlgorithm.h.
Referenced by calculatePopulationNorm(), evaluatePopulation(), EvolutionaryAlgorithm(), getIndividual(), getPopulationSize(), initPopulationNormal(), initPopulationUniform(), load(), performIntermediateRecombination(), performLinearRankingFitnessAssignment(), performLineRecombination(), performNormalMutation(), performRouletteWheelSelection(), performStochasticUniversalSamplingSelection(), performUniformMutation(), print(), save(), setEvaluation(), setFitness(), setIndividual(), setPopulation(), setPopulationSize(), setSelection(), and train().
Matrix<double> Flood::EvolutionaryAlgorithm::population [private]
Population matrix.
Definition at line 67 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getIndividual(), getPopulation(), load(), performIntermediateRecombination(), performLineRecombination(), setIndividual(), setPopulation(), setPopulationSize(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::evaluation [private]
Evaluation of population.
Definition at line 71 of file EvolutionaryAlgorithm.h.
Referenced by evaluatePopulation(), EvolutionaryAlgorithm(), getEvaluation(), performLinearRankingFitnessAssignment(), setEvaluation(), setPopulationSize(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::fitness [private]
Fitness of population.
Definition at line 75 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getFitness(), performLinearRankingFitnessAssignment(), performRouletteWheelSelection(), performStochasticUniversalSamplingSelection(), setFitness(), and setPopulationSize().
Vector<bool> Flood::EvolutionaryAlgorithm::selection [private]
Selected individuals in population.
Definition at line 79 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getSelection(), performIntermediateRecombination(), performLineRecombination(), performRouletteWheelSelection(), performStochasticUniversalSamplingSelection(), setPopulationSize(), setSelection(), and train().
double Flood::EvolutionaryAlgorithm::selectivePressure [private]
Selective pressure. Linear ranking allows values for the selective pressure between 1 and 2.
Definition at line 86 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getSelectivePressure(), load(), performLinearRankingFitnessAssignment(), print(), save(), and setSelectivePressure().
double Flood::EvolutionaryAlgorithm::recombinationSize [private]
Recombination size. The recombination size value must be equal or greater than 0.
Definition at line 91 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getRecombinationSize(), load(), performIntermediateRecombination(), performLineRecombination(), print(), save(), and setRecombinationSize().
double Flood::EvolutionaryAlgorithm::mutationRate [private]
Mutation rate. The mutation rate value must be between 0 and 1.
Definition at line 96 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getMutationRate(), load(), performNormalMutation(), performUniformMutation(), print(), save(), and setMutationRate().
double Flood::EvolutionaryAlgorithm::mutationRange [private]
Mutation range. The mutation range value must be 0 or a positive number.
Definition at line 101 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getMutationRange(), load(), performNormalMutation(), performUniformMutation(), print(), save(), and setMutationRange().
int Flood::EvolutionaryAlgorithm::maximumNumberOfGenerations [private]
Maximum number of generations to train.
Definition at line 105 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getMaximumNumberOfGenerations(), load(), print(), save(), setMaximumNumberOfGenerations(), and train().
bool Flood::EvolutionaryAlgorithm::reservePopulationHistory [private]
True if the population history, which is a vector of matrices, is to be reserved, false otherwise. Reserving the population history can be compuationally expensive if the number of free parameters, the population size and the number of generations are big numbers.
Definition at line 111 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReservePopulationHistory(), resizeTrainingHistory(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReservePopulationHistory(), and train().
bool Flood::EvolutionaryAlgorithm::reserveMeanNormHistory [private]
True if the mean norm history vector is to be reserved, false otherwise.
Definition at line 115 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveMeanNormHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReserveMeanNormHistory(), and train().
bool Flood::EvolutionaryAlgorithm::reserveStandardDeviationNormHistory [private]
True if the standard deviation of norm history vector is to be reserved, false otherwise.
Definition at line 119 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveStandardDeviationNormHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), and setReserveStandardDeviationNormHistory().
bool Flood::EvolutionaryAlgorithm::reserveBestNormHistory [private]
True if the best norm history vector is to be reserved, false otherwise.
Definition at line 123 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveBestNormHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReserveBestNormHistory(), and train().
bool Flood::EvolutionaryAlgorithm::reserveMeanEvaluationHistory [private]
True if the mean evaluation history vector is to be reserved, false otherwise.
Definition at line 127 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveMeanEvaluationHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReserveMeanEvaluationHistory(), and train().
bool Flood::EvolutionaryAlgorithm::reserveStandardDeviationEvaluationHistory [private]
True if the standard deviation of evaluation history vector is to be reserved, false otherwise.
Definition at line 131 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveStandardDeviationEvaluationHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReserveStandardDeviationEvaluationHistory(), and train().
bool Flood::EvolutionaryAlgorithm::reserveBestEvaluationHistory [private]
True if the best evaluation history vector is to be reserved, false otherwise.
Definition at line 135 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getReserveBestEvaluationHistory(), load(), print(), resizeTrainingHistory(), save(), saveTrainingHistory(), setReserveAllTrainingHistory(), setReserveBestEvaluationHistory(), and train().
Vector< Matrix<double> > Flood::EvolutionaryAlgorithm::populationHistory [private]
Population history over the epochs, which is a vector of matrices. The element 0 of the vector is the initial population, and so on.
Definition at line 140 of file EvolutionaryAlgorithm.h.
Referenced by getPopulationHistory(), resizeTrainingHistory(), saveTrainingHistory(), setPopulationHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::meanNormHistory [private]
Mean population norm training history. This vector is of the form (MeanOfPopulationNormAtEpoch0,...,MeanOfPopulationNormAtEpochN)
Definition at line 145 of file EvolutionaryAlgorithm.h.
Referenced by getMeanNormHistory(), resizeTrainingHistory(), saveTrainingHistory(), setMeanNormHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::standardDeviationNormHistory [private]
Standard deviation of population norm training history. This vector is of the form (StandardDeviationOfPopulationNormAtEpoch0,...,StandardDeviationOfPopulationNormAtEpochN)
Definition at line 151 of file EvolutionaryAlgorithm.h.
Referenced by getStandardDeviationNormHistory(), resizeTrainingHistory(), saveTrainingHistory(), setStandardDeviationNormHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::bestNormHistory [private]
Best individual ever norm history.
Definition at line 155 of file EvolutionaryAlgorithm.h.
Referenced by getBestNormHistory(), resizeTrainingHistory(), saveTrainingHistory(), setBestNormHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::meanEvaluationHistory [private]
Mean evaluation training history.
Definition at line 159 of file EvolutionaryAlgorithm.h.
Referenced by getMeanEvaluationHistory(), resizeTrainingHistory(), saveTrainingHistory(), setMeanEvaluationHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::standardDeviationEvaluationHistory [private]
Standard deviation of evaluation training history.
Definition at line 163 of file EvolutionaryAlgorithm.h.
Referenced by getStandardDeviationEvaluationHistory(), resizeTrainingHistory(), saveTrainingHistory(), setStandardDeviationEvaluationHistory(), and train().
Vector<double> Flood::EvolutionaryAlgorithm::bestEvaluationHistory [private]
Best evaluation ever training history.
Definition at line 167 of file EvolutionaryAlgorithm.h.
Referenced by getBestEvaluationHistory(), resizeTrainingHistory(), saveTrainingHistory(), setBestEvaluationHistory(), and train().
FitnessAssignmentMethod Flood::EvolutionaryAlgorithm::fitnessAssignmentMethod [private]
Fitness assignment training operators enumeration.
Definition at line 171 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getFitnessAssignmentMethod(), load(), print(), save(), setFitnessAssignmentMethod(), setSelectivePressure(), and train().
SelectionMethod Flood::EvolutionaryAlgorithm::selectionMethod [private]
Selection training operators enumeration.
Definition at line 175 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getSelectionMethod(), load(), print(), save(), setSelectionMethod(), and train().
RecombinationMethod Flood::EvolutionaryAlgorithm::recombinationMethod [private]
Recombination training operators enumeration.
Definition at line 179 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getRecombinationMethod(), load(), print(), save(), setRecombinationMethod(), and train().
MutationMethod Flood::EvolutionaryAlgorithm::mutationMethod [private]
Mutation training operators enumeration.
Definition at line 183 of file EvolutionaryAlgorithm.h.
Referenced by EvolutionaryAlgorithm(), getMutationMethod(), load(), print(), save(), setMutationMethod(), and train().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/TrainingAlgorithm/EvolutionaryAlgorithm.h
G:/Documents/Flood/Flood/TrainingAlgorithm/EvolutionaryAlgorithm.cpp