Flood: Flood::MinkowskiError Class Reference
Flood::MinkowskiError Class Reference
#include <MinkowskiError.h>
Public Member Functions
MinkowskiError (MultilayerPerceptron *, InputTargetDataSet *)
MinkowskiError (void)
virtual ~MinkowskiError (void)
Destructor.
InputTargetDataSet * getInputTargetDataSet (void)
double getMinkowskiParameter (void)
This method returns the Minkowski exponent value used to calculate the error.
void setInputTargetDataSet (InputTargetDataSet *)
void setMinkowskiParameter (double)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
void saveInputTargetAndOutput (char *)
Private Attributes
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
double minkowskiParameter
Minkowski exponent value.
Detailed Description
This class represents the Minkowski error objective functional of a multilayer perceptron. This objective functional is used in data modeling problems.
See also:
MultilayerPerceptron.
InputTargetDataSet.
Definition at line 32 of file MinkowskiError.h.
Constructor & Destructor Documentation
Flood::MinkowskiError::MinkowskiError (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a Minkowski error objective functional object associated to a multilayer perceptron and measured on an input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
MinkowskiParameter = 1.5.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 43 of file MinkowskiError.cpp.
References inputTargetDataSet, and minkowskiParameter.
Flood::MinkowskiError::MinkowskiError (void)
Default constructor. It creates Minkowski error objective functional object not associated to any multilayer perceptron and not measured on any input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
MinkowskiParameter = 1.5.
Definition at line 65 of file MinkowskiError.cpp.
References inputTargetDataSet, and minkowskiParameter.
Flood::MinkowskiError::~MinkowskiError (void) [virtual]
Destructor.
Definition at line 77 of file MinkowskiError.cpp.
Member Function Documentation
InputTargetDataSet * Flood::MinkowskiError::getInputTargetDataSet (void)
This method returns a pointer to the input-target data set object on which the objective functional is measured.
Definition at line 90 of file MinkowskiError.cpp.
References inputTargetDataSet.
double Flood::MinkowskiError::getMinkowskiParameter (void)
This method returns the Minkowski exponent value used to calculate the error.
Definition at line 100 of file MinkowskiError.cpp.
References minkowskiParameter.
void Flood::MinkowskiError::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a pointer to an input-data set object on which the objective functional is to be measured.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 112 of file MinkowskiError.cpp.
References inputTargetDataSet.
void Flood::MinkowskiError::setMinkowskiParameter (double newMinkowskiParameter)
This method sets a new Minkowski exponent value to be used in order to calculate the error. The Minkowski R-value must be comprised between 1 and 2.
Parameters:
newMinkowskiParameter Minkowski exponent value.
Definition at line 125 of file MinkowskiError.cpp.
References minkowskiParameter.
double Flood::MinkowskiError::calculateEvaluation (void) [virtual]
This method returns the objective functional value of a multilayer perceptron according to the Minkowski error on an input-target data set.
See also:
calculateGradient(void).
Implements Flood::ObjectiveFunctional.
Definition at line 153 of file MinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, minkowskiParameter, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Vector< double > Flood::MinkowskiError::calculateGradient (void) [virtual]
This method returns the the Minkowski error function gradient of a multilayer perceptron on an input-target data set. It uses the error back-propagation method.
See also:
calculateEvaluation(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 250 of file MinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer(), Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::Matrix< Type >::getRow(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::MultilayerPerceptron::MeanAndStandardDeviation, Flood::MultilayerPerceptron::MinimumAndMaximum, minkowskiParameter, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::MultilayerPerceptron::None, Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), and Flood::Vector< Type >::setSize().
void Flood::MinkowskiError::saveInputTargetAndOutput (char * filename)
This method saves to a data file the inputs and the targets in the input-target data set, together with the outputs from the multilayer perceptron for that inputs.
Parameters:
filename Filename.
Definition at line 546 of file MinkowskiError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Member Data Documentation
InputTargetDataSet* Flood::MinkowskiError::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 39 of file MinkowskiError.h.
Referenced by calculateEvaluation(), calculateGradient(), getInputTargetDataSet(), MinkowskiError(), saveInputTargetAndOutput(), and setInputTargetDataSet().
double Flood::MinkowskiError::minkowskiParameter [private]
Minkowski exponent value.
Definition at line 43 of file MinkowskiError.h.
Referenced by calculateEvaluation(), calculateGradient(), getMinkowskiParameter(), MinkowskiError(), and setMinkowskiParameter().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/MinkowskiError.h
G:/Documents/Flood/Flood/ObjectiveFunctional/MinkowskiError.cpp