Flood: Flood::RastriginFunction Class Reference
Flood::RastriginFunction Class Reference
#include <RastriginFunction.h>
Public Member Functions
RastriginFunction (MultilayerPerceptron *)
RastriginFunction (void)
virtual ~RastriginFunction (void)
Destructor.
int getNumberOfVariables (void)
void setNumberOfVariables (int)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
Matrix< double > calculateHessian (void)
Matrix< double > calculateInverseHessian (void)
Private Attributes
int numberOfVariables
Number of variables in the Rastrigin's function.
Detailed Description
This class represents the Rastrigin's objective function. Rastrigin's function is based on De Jong's function with the addition of cosine modulation to produce many local minima. Thus, the test function is highly multimodal. However, the location of the minima are regularly distributed. Analytical expressions for the gradient vector and the Hessian matrix are provided. For more information please visit GEATbx - The Genetic and Evolutionary Algorithm Toolbox for Matlab, www.geatbx.com
See also:
ObjectiveFunctional.
Definition at line 35 of file RastriginFunction.h.
Constructor & Destructor Documentation
Flood::RastriginFunction::RastriginFunction (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a Rastrigin's objective function object. It also initializes all the rest of class members to their default values:
Number of variables (independent parameters): 2.
Minimum of independent parameters: -5.12,...,-5.12.
Maximum of independent parameters: 5.12,...,5.12.
Definition at line 39 of file RastriginFunction.cpp.
References numberOfVariables.
Flood::RastriginFunction::RastriginFunction (void)
Flood::RastriginFunction::~RastriginFunction (void) [virtual]
Destructor.
Definition at line 50 of file RastriginFunction.cpp.
Member Function Documentation
int Flood::RastriginFunction::getNumberOfVariables (void)
This method returns the number of variables in the Rastrigin's function. This is the number of independent parameters in the multilayer perceptron.
Definition at line 64 of file RastriginFunction.cpp.
References numberOfVariables.
void Flood::RastriginFunction::setNumberOfVariables (int newNumberOfVariables)
This method sets a new number of variables in the Rastrigin's function. This also sets a new number of independent parameters in the multilayer perceptron. It also initializes all the rest of class members to their default values:
Name of independent parameters: x0,...,xn
Minimum of independent parameters: -5.12,...,-5.12.
Maximum of independent parameters: 5.12,...,5.12.
Parameters:
newNumberOfVariables Number of variables in the Rastrigin's function.
Definition at line 84 of file RastriginFunction.cpp.
References numberOfVariables.
double Flood::RastriginFunction::calculateEvaluation (void) [virtual]
This method returns the Rastrigin's function evaluation.
See also:
calculateGradient(void).
calculateHessian(void).
calculateInverseHessian(void).
Implements Flood::ObjectiveFunctional.
Definition at line 98 of file RastriginFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and numberOfVariables.
Vector< double > Flood::RastriginFunction::calculateGradient (void) [virtual]
This method returns the Rastrigin's analytical gradient vector.
See also:
calculateEvaluation(void).
calculateHessian(void).
calculateInverseHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 144 of file RastriginFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfVariables.
Matrix< double > Flood::RastriginFunction::calculateHessian (void) [virtual]
This method returns the Rastrigin's analytical Hessian matrix.
See also:
calculateEvaluation(void).
calculateGradient(void).
calculateInverseHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 169 of file RastriginFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfVariables.
Matrix< double > Flood::RastriginFunction::calculateInverseHessian (void) [virtual]
This method returns the Rastrigin's analytical inverse Hessian matrix.
See also:
calculateEvaluation(void).
calculateGradient(void).
calculateHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 204 of file RastriginFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfVariables.
Member Data Documentation
int Flood::RastriginFunction::numberOfVariables [private]
Number of variables in the Rastrigin's function.
Definition at line 42 of file RastriginFunction.h.
Referenced by calculateEvaluation(), calculateGradient(), calculateHessian(), calculateInverseHessian(), getNumberOfVariables(), RastriginFunction(), and setNumberOfVariables().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/RastriginFunction.h
G:/Documents/Flood/Flood/ObjectiveFunctional/RastriginFunction.cpp