Flood: Flood::InputTargetDataSet Class Reference
Flood::InputTargetDataSet Class Reference
#include <InputTargetDataSet.h>
Public Member Functions
InputTargetDataSet (int, int, int)
InputTargetDataSet (void)
virtual ~InputTargetDataSet ()
Destructor.
int getNumberOfSamples (void)
This method returns the number of samples in the input-target data set.
int getNumberOfInputVariables (void)
This method returns the number of input variables of the input-target data set.
int getNumberOfTargetVariables (void)
This method returns the number of target variables of the input-target data set.
Vector< std::string > getNameOfInputVariables (void)
Vector< std::string > getNameOfTargetVariables (void)
std::string getNameOfSingleInputVariable (int)
std::string getNameOfSingleTargetVariable (int)
Vector< std::string > getUnitsOfInputVariables (void)
Vector< std::string > getUnitsOfTargetVariables (void)
std::string getUnitsOfSingleInputVariable (int)
std::string getUnitsOfSingleTargetVariable (int)
Vector< std::string > getDescriptionOfInputVariables (void)
Vector< std::string > getDescriptionOfTargetVariables (void)
std::string getDescriptionOfSingleInputVariable (int)
std::string getDescriptionOfSingleTargetVariable (int)
Vector< Vector< std::string > > getAllInformation (void)
Matrix< double > & getInputData (void)
This method returns a Matrix containing the input data of the data set.
Matrix< double > & getTargetData (void)
This method returns a Matrix containing the target data of the data set.
Matrix< double > getInputAndTargetData (void)
Vector< double > getSample (int)
void setSample (int, Vector< double >)
void addSample (Vector< double >)
void subtractSample (int)
bool getDisplay (void)
void setInputTargetDataSet (int, int, int)
void setNameOfInputVariables (Vector< std::string >)
void setNameOfTargetVariables (Vector< std::string >)
void setNameOfSingleInputVariable (int, std::string)
void setNameOfSingleTargetVariable (int, std::string)
void setUnitsOfInputVariables (Vector< std::string >)
void setUnitsOfTargetVariables (Vector< std::string >)
void setUnitsOfSingleInputVariable (int, std::string)
void setUnitsOfSingleTargetVariable (int, std::string)
void setDescriptionOfInputVariables (Vector< std::string >)
void setDescriptionOfTargetVariables (Vector< std::string >)
void setDescriptionOfSingleInputVariable (int, std::string)
void setDescriptionOfSingleTargetVariable (int, std::string)
void setAllInformation (Vector< Vector< std::string > >)
void setInputData (Matrix< double >)
void setTargetData (Matrix< double >)
void setInputAndTargetData (Matrix< double >)
void setDisplay (bool)
Matrix< double > calculateMeanAndStandardDeviationOfInputData (void)
Matrix< double > calculateMeanAndStandardDeviationOfTargetData (void)
Matrix< double > calculateMinimumAndMaximumOfInputData (void)
Matrix< double > calculateMinimumAndMaximumOfTargetData (void)
Vector< Vector< double > > calculateAllStatistics (void)
void preprocessMeanAndStandardDeviation (void)
void preprocessMeanAndStandardDeviation (Matrix< double >, Matrix< double >)
void preprocessMinimumAndMaximum (void)
void preprocessMinimumAndMaximum (Matrix< double >, Matrix< double >)
void postprocessMeanAndStandardDeviation (Matrix< double >, Matrix< double >)
void postprocessMinimumAndMaximum (Matrix< double >, Matrix< double >)
void save (char *)
void load (char *)
void print (void)
void saveAllStatistics (char *)
void printAllStatistics (void)
Vector< InputTargetDataSet > splitTrainingValidationAndTesting (double, double, double)
Vector< InputTargetDataSet > split (double, double)
Private Attributes
int numberOfSamples
Number of samples in the data set.
int numberOfInputVariables
Number of input variables.
int numberOfTargetVariables
Number of target variables.
Vector< std::string > nameOfInputVariables
Name of input variables.
Vector< std::string > nameOfTargetVariables
Name of target variables.
Vector< std::string > unitsOfInputVariables
Units of input variables.
Vector< std::string > unitsOfTargetVariables
Units of target variables.
Vector< std::string > descriptionOfInputVariables
Description of input variables.
Vector< std::string > descriptionOfTargetVariables
Description of target variables.
Matrix< double > inputData
Input data Matrix.
Matrix< double > targetData
Target data Matrix.
bool display
Display messages to screen.
Detailed Description
This class represents the concept of input-target data set for data modelling problems, such as function regression, pattern recognition and time series prediction.
See also:
SumSquaredError
MeanSquaredError
RootMeanSquaredError
NormalizedSquaredError
MinkowskiError
RegularizedMeanSquaredError
Definition at line 38 of file InputTargetDataSet.h.
Constructor & Destructor Documentation
Flood::InputTargetDataSet::InputTargetDataSet (int newNumberOfSamples, int newNumberOfInputVariables, int newNumberOfTargetVariables)
General constructor. It creates an input-target data set object involving an input Matrix and an Target matrix. All input-target data is initialized to zero. It also initializes the rest of class members to their default values:
Name of input vaviables: InputVariable0,...
Name of target variables: TargetVariable0,...
Units of input vaviables: None.
Units of target variables: None.
Description of input vaviables: None.
Descritpion of target variables: None.
Display messages to screen: True.
Parameters:
newNumberOfSamples Number of samples in the data set.
newNumberOfInputVariables Number of input variables.
newNumberOfTargetVariables Number of target variables.
Definition at line 48 of file InputTargetDataSet.cpp.
Flood::InputTargetDataSet::InputTargetDataSet (void)
Default constructor. It creates an input-target data set object with zero samples and zero input and target variables. It also initializes the rest of class members to their default values:
Display messages to screen: True.
Definition at line 145 of file InputTargetDataSet.cpp.
References display, numberOfInputVariables, numberOfSamples, and numberOfTargetVariables.
Flood::InputTargetDataSet::~InputTargetDataSet () [virtual]
Destructor.
Definition at line 159 of file InputTargetDataSet.cpp.
Member Function Documentation
int Flood::InputTargetDataSet::getNumberOfSamples (void)
This method returns the number of samples in the input-target data set.
Definition at line 172 of file InputTargetDataSet.cpp.
References numberOfSamples.
Referenced by Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateJacobianTest(), Flood::LinearRegressionAnalysis::calculateRegressionParameters(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::LinearRegressionAnalysis::printResults(), Flood::CorrectPredictionsAnalysis::printResults(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::LinearRegressionAnalysis::saveResults(), and Flood::CorrectPredictionsAnalysis::saveResults().
int Flood::InputTargetDataSet::getNumberOfInputVariables (void)
This method returns the number of input variables of the input-target data set.
Definition at line 182 of file InputTargetDataSet.cpp.
References numberOfInputVariables.
Referenced by Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), and Flood::MeanSquaredError::saveInputTargetAndOutput().
int Flood::InputTargetDataSet::getNumberOfTargetVariables (void)
This method returns the number of target variables of the input-target data set.
Definition at line 192 of file InputTargetDataSet.cpp.
References numberOfTargetVariables.
Referenced by Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), and Flood::MeanSquaredError::saveInputTargetAndOutput().
Vector< std::string > Flood::InputTargetDataSet::getNameOfInputVariables (void)
This method returns the name of the input variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getNameOfTargetVariables(void).
getNameOfSingleInputVariable(void).
getNameOfSingleTargetVariable(void).
Definition at line 511 of file InputTargetDataSet.cpp.
References nameOfInputVariables.
Vector< std::string > Flood::InputTargetDataSet::getNameOfTargetVariables (void)
This method returns the name of the target variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getNameOfInputVariables(void).
getNameOfSingleInputVariable(void).
getNameOfSingleTargetVariable(void).
Definition at line 526 of file InputTargetDataSet.cpp.
References nameOfTargetVariables.
std::string Flood::InputTargetDataSet::getNameOfSingleInputVariable (int i)
This method returns the name of a single input variable in the input-target data set. Such a name is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getNameOfInputVariables(void).
getNameOfTargetVariables(void).
getNameOfSingleTargetVariable(void).
Definition at line 543 of file InputTargetDataSet.cpp.
References nameOfInputVariables, and numberOfInputVariables.
std::string Flood::InputTargetDataSet::getNameOfSingleTargetVariable (int i)
This method returns the name of a single target variable in the input-target data set. Such a name is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getNameOfInputVariables(void).
getNameOfTargetVariables(void).
getNameOfSingleInputVariable(void).
Definition at line 579 of file InputTargetDataSet.cpp.
References nameOfTargetVariables, and numberOfTargetVariables.
Vector< std::string > Flood::InputTargetDataSet::getUnitsOfInputVariables (void)
This method returns the units of the input variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getUnitsOfTargetVariables(void).
getUnitsOfSingleInputVariable(void).
getUnitsOfSingleTargetVariable(void).
Definition at line 613 of file InputTargetDataSet.cpp.
References unitsOfInputVariables.
Vector< std::string > Flood::InputTargetDataSet::getUnitsOfTargetVariables (void)
This method returns the units of the target variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getUnitsOfInputVariables(void).
getUnitsOfSingleInputVariable(void).
getUnitsOfSingleTargetVariable(void).
Definition at line 628 of file InputTargetDataSet.cpp.
References unitsOfTargetVariables.
std::string Flood::InputTargetDataSet::getUnitsOfSingleInputVariable (int i)
This method returns the units of a single input variable in the input-target data set. Such units are only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getUnitsOfInputVariables(void).
getUnitsOfTargetVariables(void).
getUnitsOfSingleTargetVariable(void).
Definition at line 645 of file InputTargetDataSet.cpp.
References numberOfInputVariables, and unitsOfInputVariables.
std::string Flood::InputTargetDataSet::getUnitsOfSingleTargetVariable (int i)
This method returns the units of a single target variable in the input-target data set. Such units are only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getUnitsOfInputVariables(void).
getUnitsOfTargetVariables(void).
getUnitsOfSingleInputVariable(void).
Definition at line 681 of file InputTargetDataSet.cpp.
References numberOfTargetVariables, and unitsOfTargetVariables.
Vector< std::string > Flood::InputTargetDataSet::getDescriptionOfInputVariables (void)
This method returns the current description of the input variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getDescriptionOfTargetVariables(void).
getDescriptionOfSingleInputVariable(void).
getDescriptionOfSingleTargetVariable(void).
Definition at line 716 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables.
Vector< std::string > Flood::InputTargetDataSet::getDescriptionOfTargetVariables (void)
This method returns the current description of the target variables in the input-target data set. Such names are only used to give the user basic information about the problem at hand.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfSingleInputVariable(void).
getDescriptionOfSingleTargetVariable(void).
Definition at line 731 of file InputTargetDataSet.cpp.
References descriptionOfTargetVariables.
std::string Flood::InputTargetDataSet::getDescriptionOfSingleInputVariable (int i)
This method returns the description of a single input variable in the input-target data set. Such a description is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfTargetVariables(void).
getDescriptionOfSingleTargetVariable(void).
Definition at line 748 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, and numberOfInputVariables.
std::string Flood::InputTargetDataSet::getDescriptionOfSingleTargetVariable (int i)
This method returns the description of a single target variable in the input-target data set. Such a description is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfTargetVariables(void).
getDescriptionOfSingleInputVariable(void).
Definition at line 784 of file InputTargetDataSet.cpp.
References descriptionOfTargetVariables, and numberOfTargetVariables.
Vector< Vector< std::string > > Flood::InputTargetDataSet::getAllInformation (void)
Definition at line 811 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, descriptionOfTargetVariables, nameOfInputVariables, nameOfTargetVariables, unitsOfInputVariables, and unitsOfTargetVariables.
Matrix< double > & Flood::InputTargetDataSet::getInputData (void)
This method returns a Matrix containing the input data of the data set.
Definition at line 202 of file InputTargetDataSet.cpp.
References inputData.
Referenced by Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), and Flood::MeanSquaredError::saveInputTargetAndOutput().
Matrix< double > & Flood::InputTargetDataSet::getTargetData (void)
This method returns a Matrix containing the target data of the data set.
Definition at line 212 of file InputTargetDataSet.cpp.
References targetData.
Referenced by Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::LinearRegressionAnalysis::calculateRegressionParameters(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::LinearRegressionAnalysis::printResults(), Flood::CorrectPredictionsAnalysis::printResults(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::LinearRegressionAnalysis::saveResults(), and Flood::CorrectPredictionsAnalysis::saveResults().
Matrix< double > Flood::InputTargetDataSet::getInputAndTargetData (void)
This method returns a Matrix containing both the input and the target data in the data set.
Definition at line 223 of file InputTargetDataSet.cpp.
References inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
Referenced by print(), and save().
Vector< double > Flood::InputTargetDataSet::getSample (int i)
This method returns the input and target values of a single sample in the input-target data set.
Parameters:
i Index of the sample.
Definition at line 253 of file InputTargetDataSet.cpp.
References inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
Referenced by split(), and splitTrainingValidationAndTesting().
void Flood::InputTargetDataSet::setSample (int i, Vector< double > sample)
This method sets new input and target values of a single sample in the input-target data set.
Parameters:
i Index of the sample.
sample New input and target values of the sample.
Definition at line 301 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
Referenced by splitTrainingValidationAndTesting().
void Flood::InputTargetDataSet::addSample (Vector< double > sample)
This method adds a new input-target sample to the input-target data set. Note that resizing is here necessary and therefore computationally expensive.
Parameters:
sample Input and target values of the sample to be added.
See also:
subtractSample(int).
Definition at line 358 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::subtractSample (int sampleIndex)
This method substract the input-target sample with a given index from the input-target data set. Note that resizing is here necessary and therefore computationally expensive.
Parameters:
sampleIndex Index of sample to be removed.
See also:
addSample(Vector<double>).
Definition at line 433 of file InputTargetDataSet.cpp.
References inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
bool Flood::InputTargetDataSet::getDisplay (void)
This method returns true if messages from this class can be displayed on the screen, or false if messages from this class can't be displayed on the screen.
Definition at line 833 of file InputTargetDataSet.cpp.
References display.
void Flood::InputTargetDataSet::setInputTargetDataSet (int newNumberOfSamples, int newNumberOfInputVariables, int newNumberOfTargetVariables)
This method sets new numbers of samples and input and target variables in the input-target data set. It also initializes the rest of class members to their default values:
Name of input vaviables: InputVariable0,...
Name of target variables: TargetVariable0,...
Units of input vaviables: None.
Units of target variables: None.
Description of input vaviables: None.
Description of target variables: None.
Parameters:
newNumberOfSamples Number of samples.
newNumberOfInputVariables Number of input variables.
newNumberOfTargetVariables Number of target variables.
Definition at line 858 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, descriptionOfTargetVariables, inputData, nameOfInputVariables, nameOfTargetVariables, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, Flood::Matrix< Type >::resize(), Flood::Vector< Type >::resize(), targetData, unitsOfInputVariables, and unitsOfTargetVariables.
Referenced by load().
void Flood::InputTargetDataSet::setNameOfInputVariables (Vector< std::string > newNameOfInputVariables)
This method sets a new name for the input variables in the input-target data set.
Parameters:
newNameOfInputVariables Names for the input variables.
Definition at line 1090 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), nameOfInputVariables, and numberOfInputVariables.
void Flood::InputTargetDataSet::setNameOfTargetVariables (Vector< std::string > newNameOfTargetVariables)
This method sets a new name for the target variables in the input-target data set.
Parameters:
newNameOfTargetVariables Names for the target variables.
Definition at line 1121 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), nameOfTargetVariables, and numberOfTargetVariables.
void Flood::InputTargetDataSet::setNameOfSingleInputVariable (int i, std::string newNameOfSingleInputVariable)
This method sets the name of a single input variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newNameOfSingleInputVariable New name for the input variable with index i.
See also:
setNameOfInputVariables(Vector<std::string>).
setNameOfTargetVariables(Vector<std::string>).
setNameOfSingleTargetVariable(int, std::string).
Definition at line 1158 of file InputTargetDataSet.cpp.
References nameOfInputVariables, and numberOfInputVariables.
void Flood::InputTargetDataSet::setNameOfSingleTargetVariable (int i, std::string newNameOfSingleTargetVariable)
This method sets the name of a single target variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of target variable.
newNameOfSingleTargetVariable New name for the target variable with index i.
See also:
setNameOfInputVariables(Vector<std::string>).
setNameOfTargetVariables(Vector<std::string>).
setNameOfSingleInputVariable(int, std::string).
Definition at line 1195 of file InputTargetDataSet.cpp.
References nameOfTargetVariables, and numberOfTargetVariables.
void Flood::InputTargetDataSet::setUnitsOfInputVariables (Vector< std::string > newUnitsOfInputVariables)
This method sets new units for the input variables in the input-target data set.
Parameters:
newUnitsOfInputVariables Units for the input variables.
Definition at line 1226 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), numberOfInputVariables, and unitsOfInputVariables.
void Flood::InputTargetDataSet::setUnitsOfTargetVariables (Vector< std::string > newUnitsOfTargetVariables)
This method sets new units for the target variables in the input-target data set.
Parameters:
newUnitsOfTargetVariables Units for the target variables.
Definition at line 1257 of file InputTargetDataSet.cpp.
References Flood::Vector< Type >::getSize(), numberOfTargetVariables, and unitsOfTargetVariables.
void Flood::InputTargetDataSet::setUnitsOfSingleInputVariable (int i, std::string newUnitsOfSingleInputVariable)
This method sets new units for a single input variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newUnitsOfSingleInputVariable New units for the input variable with index i.
See also:
setUnitsOfInputVariables(Vector<std::string>).
setUnitsOfTargetVariables(Vector<std::string>).
setUnitsOfSingleTargetVariable(int, std::string).
Definition at line 1294 of file InputTargetDataSet.cpp.
References numberOfInputVariables, and unitsOfInputVariables.
void Flood::InputTargetDataSet::setUnitsOfSingleTargetVariable (int i, std::string newUnitsOfSingleTargetVariable)
This method sets new units for a single target variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of target variable.
newUnitsOfSingleTargetVariable New units for the target variable with index i.
See also:
setUnitsOfInputVariables(Vector<std::string>).
setUnitsOfTargetVariables(Vector<std::string>).
setUnitsOfSingleInputVariable(int, std::string).
Definition at line 1331 of file InputTargetDataSet.cpp.
References numberOfTargetVariables, and unitsOfTargetVariables.
void Flood::InputTargetDataSet::setDescriptionOfInputVariables (Vector< std::string > newDescriptionOfInputVariables)
This method sets a new description for the input variables in the input-target data set.
Parameters:
newDescriptionOfInputVariables Description for the input variables.
Definition at line 1362 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, Flood::Vector< Type >::getSize(), and numberOfInputVariables.
void Flood::InputTargetDataSet::setDescriptionOfTargetVariables (Vector< std::string > newDescriptionOfTargetVariables)
This method sets a new description for the target variables in the input-target data set.
Parameters:
newDescriptionOfTargetVariables Description for the target variables.
Definition at line 1393 of file InputTargetDataSet.cpp.
References descriptionOfTargetVariables, Flood::Vector< Type >::getSize(), and numberOfTargetVariables.
void Flood::InputTargetDataSet::setDescriptionOfSingleInputVariable (int i, std::string newDescriptionOfSingleInputVariable)
This method sets a new description for a single input variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newDescriptionOfSingleInputVariable New description for the input variable with index i.
See also:
setDescriptionOfInputVariables(Vector<std::string>).
setDescriptionOfTargetVariables(Vector<std::string>).
setDescriptionOfSingleTargetVariable(int, std::string).
Definition at line 1430 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, and numberOfInputVariables.
void Flood::InputTargetDataSet::setDescriptionOfSingleTargetVariable (int i, std::string newDescriptionOfSingleTargetVariable)
This method sets a new description for a single target variable in the data set. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of target variable.
newDescriptionOfSingleTargetVariable New description for the target variable with index i.
See also:
setDescriptionOfInputVariables(Vector<std::string>).
setDescriptionOfTargetVariables(Vector<std::string>).
setDescriptionOfSingleInputVariable(int, std::string).
Definition at line 1467 of file InputTargetDataSet.cpp.
References descriptionOfTargetVariables, and numberOfTargetVariables.
void Flood::InputTargetDataSet::setAllInformation (Vector< Vector< std::string > >)
void Flood::InputTargetDataSet::setInputData (Matrix< double > newInputData)
This method sets a new input data matrix. The number of rows must be equal to the number of samples. The number of columns must be equal to the number of input variables.
Parameters:
newInputData Input data matrix.
Definition at line 949 of file InputTargetDataSet.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), inputData, numberOfInputVariables, and numberOfSamples.
void Flood::InputTargetDataSet::setTargetData (Matrix< double > newTargetData)
This method sets a new target data matrix. The number of rows must be equal to the number of samples. The number of columns must be equal to the number of target variables.
Parameters:
newTargetData Target data matrix.
Definition at line 992 of file InputTargetDataSet.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::setInputAndTargetData (Matrix< double > newInputAndTargetData)
This method sets both a new input set and a new target set from a single matrix. The number of rows must be equal to the number of samples. The number of columns must be equal to the total number of input and target variables.
Parameters:
newInputAndTargetData Input and target data matrix.
Definition at line 1036 of file InputTargetDataSet.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 1500 of file InputTargetDataSet.cpp.
References display.
Matrix< double > Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfInputData (void)
This method returns a matrix containing both the mean and the standard deviation of all the input variables. The first row contains the mean of the input variables. The second row contains the standard deviation of the input variables.
Definition at line 1513 of file InputTargetDataSet.cpp.
References inputData, numberOfInputVariables, numberOfSamples, and Flood::Matrix< Type >::setRow().
Referenced by calculateAllStatistics(), and preprocessMeanAndStandardDeviation().
Matrix< double > Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfTargetData (void)
This method returns a matrix containing both the mean and the standard deviation of all the target variables. The first row contains the mean of the target variables. The second row contains the standard deviation of the target variables.
Definition at line 1584 of file InputTargetDataSet.cpp.
References numberOfSamples, numberOfTargetVariables, Flood::Matrix< Type >::setRow(), and targetData.
Referenced by calculateAllStatistics(), Flood::NormalizedSquaredError::NormalizedSquaredError(), preprocessMeanAndStandardDeviation(), and Flood::NormalizedSquaredError::setInputTargetDataSet().
Matrix< double > Flood::InputTargetDataSet::calculateMinimumAndMaximumOfInputData (void)
This method returns a matrix containing both the minimum and the maximum of all the input variables. The first row contains the minimum of the input variables. The second row contains the maximum of the input variables.
Definition at line 1637 of file InputTargetDataSet.cpp.
References inputData, numberOfInputVariables, numberOfSamples, and Flood::Matrix< Type >::setRow().
Referenced by calculateAllStatistics(), and preprocessMinimumAndMaximum().
Matrix< double > Flood::InputTargetDataSet::calculateMinimumAndMaximumOfTargetData (void)
This method returns a matrix containing both the minimum and the maximum of all the target variables. The first row contains the minimum of the target variables. The second row contains the maximum of the target variables.
Definition at line 1680 of file InputTargetDataSet.cpp.
References numberOfSamples, numberOfTargetVariables, Flood::Matrix< Type >::setRow(), and targetData.
Referenced by calculateAllStatistics(), and preprocessMinimumAndMaximum().
Vector< Vector< double > > Flood::InputTargetDataSet::calculateAllStatistics (void)
Definition at line 1718 of file InputTargetDataSet.cpp.
References calculateMeanAndStandardDeviationOfInputData(), calculateMeanAndStandardDeviationOfTargetData(), calculateMinimumAndMaximumOfInputData(), calculateMinimumAndMaximumOfTargetData(), and Flood::Matrix< Type >::getRow().
Referenced by printAllStatistics(), and saveAllStatistics().
void Flood::InputTargetDataSet::preprocessMeanAndStandardDeviation (void)
This method preprocesses all input and target data so that the mean of all input and target variables is zero and their standard deviation is one. It then updates:
Input data matrix.
Target data matrix.
See also:
preprocessMeanAndStandardDeviation(Matrix<double>, Matrix<double>)
Definition at line 1777 of file InputTargetDataSet.cpp.
References calculateMeanAndStandardDeviationOfInputData(), calculateMeanAndStandardDeviationOfTargetData(), display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::preprocessMeanAndStandardDeviation (Matrix< double > meanAndStandardDeviationOfInputData, Matrix< double > meanAndStandardDeviationOfTargetData)
This method preprocesses all input and target data with given mean and standardard deviations for the input and target variables. It then updates:
Input data matrix.
Target data matrix.
Parameters:
meanAndStandardDeviationOfInputData Mean and standard deviation values for the input variables to be used for preprocessing.
meanAndStandardDeviationOfTargetData Mean and standard deviation values for the target variables to be used for preprocessing.
See also:
preprocessMeanAndStandardDeviation(void)
Definition at line 1881 of file InputTargetDataSet.cpp.
References display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::preprocessMinimumAndMaximum (void)
This method preprocesses all input and target data so that the minimum of all input and target variables is -1 and their maximum is 1. It then updates:
Input data matrix.
Target data matrix.
See also:
preprocessMinimumAndMaximum(Matrix<double>, Matrix<double>).
Definition at line 1978 of file InputTargetDataSet.cpp.
References calculateMinimumAndMaximumOfInputData(), calculateMinimumAndMaximumOfTargetData(), display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::preprocessMinimumAndMaximum (Matrix< double > minimumAndMaximumOfInputData, Matrix< double > minimumAndMaximumOfTargetData)
This method preprocesses all input and target data with given minimums and maximums for the input and target variables. It then updates:
Input data matrix.
Target data matrix.
Parameters:
minimumAndMaximumOfInputData Minimum and maximum values for the input variables to be used for preprocessing.
minimumAndMaximumOfTargetData Minimum and maximum values for the target variables to be used for preprocessing.
See also:
preprocessMinimumAndMaximum(void)
Definition at line 2084 of file InputTargetDataSet.cpp.
References display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::postprocessMeanAndStandardDeviation (Matrix< double > meanAndStandardDeviationOfInputData, Matrix< double > meanAndStandardDeviationOfTargetData)
This method postprocesses all input and target data with given mean and standardard deviations for the input and target variables. It then updates:
Input data matrix.
Target data matrix.
Parameters:
meanAndStandardDeviationOfInputData Mean and standard deviation values for the input variables to be used for postprocessing.
meanAndStandardDeviationOfTargetData Mean and standard deviation values for the target variables to be used for postprocessing.
Definition at line 2184 of file InputTargetDataSet.cpp.
References display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::postprocessMinimumAndMaximum (Matrix< double > minimumAndMaximumOfInputData, Matrix< double > minimumAndMaximumOfTargetData)
This method postprocesses all input and target data with given minimum and maximums for the input and target variables. It then updates:
Input data matrix.
Target data matrix.
Parameters:
minimumAndMaximumOfInputData Minimum and maximum values for the input variables to be used for postprocessing.
minimumAndMaximumOfTargetData Minimum and maximum values for the target variables to be used for postprocessing.
Definition at line 2289 of file InputTargetDataSet.cpp.
References display, Flood::Matrix< Type >::getRow(), inputData, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and targetData.
void Flood::InputTargetDataSet::save (char * filename)
This method saves the members of an input-target data set object to a data file:
Number of samples.
Number of input variables.
Number of target variables
Units of input variables.
Units of target variables
Description of input variables.
Description of target variables.
Input data.
Target data.
Parameters:
filename Filename.
See also:
load(char*).
Definition at line 2396 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, descriptionOfTargetVariables, display, getInputAndTargetData(), nameOfInputVariables, nameOfTargetVariables, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, unitsOfInputVariables, and unitsOfTargetVariables.
void Flood::InputTargetDataSet::load (char * filename)
This method loads the members of an input-target data set object from a data file:
Number of samples.
Number of input variables.
Number of target variables
Name of input variables.
Name of target variables.
Units of input variables.
Units of target variables.
Description of input variables.
Description of target variables.
Input data.
Target data.
Please mind about the file format. This is specified in the User's Guide.
Parameters:
filename Filename.
See also:
save(char*).
Definition at line 2499 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, descriptionOfTargetVariables, display, inputData, nameOfInputVariables, nameOfTargetVariables, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, setInputTargetDataSet(), targetData, unitsOfInputVariables, and unitsOfTargetVariables.
void Flood::InputTargetDataSet::print (void)
This method prints to the screen the members of an input-target data set object:
Number of samples.
Number of input variables.
Number of target variables
Name of input variables.
Name of target variables.
Description of input variables.
Description of target variables.
Input data.
Target data.
Definition at line 2710 of file InputTargetDataSet.cpp.
References descriptionOfInputVariables, descriptionOfTargetVariables, getInputAndTargetData(), nameOfInputVariables, nameOfTargetVariables, numberOfInputVariables, numberOfSamples, numberOfTargetVariables, unitsOfInputVariables, and unitsOfTargetVariables.
void Flood::InputTargetDataSet::saveAllStatistics (char * filename)
This saves some basic statistics of the input-target data set to a data file. This includes:
Mean and standard deviation of input data.
Mean and standard deviation of target data.
Minimum and maximum of input data.
Minimum and maximum of target data.
Definition at line 2775 of file InputTargetDataSet.cpp.
References calculateAllStatistics(), descriptionOfInputVariables, display, nameOfInputVariables, and unitsOfInputVariables.
void Flood::InputTargetDataSet::printAllStatistics (void)
Definition at line 2840 of file InputTargetDataSet.cpp.
References calculateAllStatistics().
Vector< InputTargetDataSet > Flood::InputTargetDataSet::splitTrainingValidationAndTesting (double percentageOfTrainingSamples, double percentageOfValidationSamples, double percentageOfTestingSamples)
This method returns tree InputTargetDataSet objects, a training set with 50% of the data, a validation set with 25% of the data and a testing set with 25% of the data.
Definition at line 2872 of file InputTargetDataSet.cpp.
References getSample(), numberOfInputVariables, numberOfSamples, numberOfTargetVariables, and setSample().
Vector< InputTargetDataSet > Flood::InputTargetDataSet::split (double percentage0, double percentage1)
Definition at line 3009 of file InputTargetDataSet.cpp.
References getSample(), numberOfInputVariables, numberOfSamples, and numberOfTargetVariables.
Member Data Documentation
int Flood::InputTargetDataSet::numberOfSamples [private]
Number of samples in the data set.
Definition at line 47 of file InputTargetDataSet.h.
Referenced by addSample(), calculateMeanAndStandardDeviationOfInputData(), calculateMeanAndStandardDeviationOfTargetData(), calculateMinimumAndMaximumOfInputData(), calculateMinimumAndMaximumOfTargetData(), getInputAndTargetData(), getNumberOfSamples(), getSample(), InputTargetDataSet(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), print(), save(), setInputAndTargetData(), setInputData(), setInputTargetDataSet(), setSample(), setTargetData(), split(), splitTrainingValidationAndTesting(), and subtractSample().
int Flood::InputTargetDataSet::numberOfInputVariables [private]
Number of input variables.
Definition at line 51 of file InputTargetDataSet.h.
Referenced by addSample(), calculateMeanAndStandardDeviationOfInputData(), calculateMinimumAndMaximumOfInputData(), getDescriptionOfSingleInputVariable(), getInputAndTargetData(), getNameOfSingleInputVariable(), getNumberOfInputVariables(), getSample(), getUnitsOfSingleInputVariable(), InputTargetDataSet(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), print(), save(), setDescriptionOfInputVariables(), setDescriptionOfSingleInputVariable(), setInputAndTargetData(), setInputData(), setInputTargetDataSet(), setNameOfInputVariables(), setNameOfSingleInputVariable(), setSample(), setUnitsOfInputVariables(), setUnitsOfSingleInputVariable(), split(), splitTrainingValidationAndTesting(), and subtractSample().
int Flood::InputTargetDataSet::numberOfTargetVariables [private]
Number of target variables.
Definition at line 55 of file InputTargetDataSet.h.
Referenced by addSample(), calculateMeanAndStandardDeviationOfTargetData(), calculateMinimumAndMaximumOfTargetData(), getDescriptionOfSingleTargetVariable(), getInputAndTargetData(), getNameOfSingleTargetVariable(), getNumberOfTargetVariables(), getSample(), getUnitsOfSingleTargetVariable(), InputTargetDataSet(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), print(), save(), setDescriptionOfSingleTargetVariable(), setDescriptionOfTargetVariables(), setInputAndTargetData(), setInputTargetDataSet(), setNameOfSingleTargetVariable(), setNameOfTargetVariables(), setSample(), setTargetData(), setUnitsOfSingleTargetVariable(), setUnitsOfTargetVariables(), split(), splitTrainingValidationAndTesting(), and subtractSample().
Vector<std::string> Flood::InputTargetDataSet::nameOfInputVariables [private]
Name of input variables.
Definition at line 59 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getNameOfInputVariables(), getNameOfSingleInputVariable(), load(), print(), save(), saveAllStatistics(), setInputTargetDataSet(), setNameOfInputVariables(), and setNameOfSingleInputVariable().
Vector<std::string> Flood::InputTargetDataSet::nameOfTargetVariables [private]
Name of target variables.
Definition at line 63 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getNameOfSingleTargetVariable(), getNameOfTargetVariables(), load(), print(), save(), setInputTargetDataSet(), setNameOfSingleTargetVariable(), and setNameOfTargetVariables().
Vector<std::string> Flood::InputTargetDataSet::unitsOfInputVariables [private]
Units of input variables.
Definition at line 67 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getUnitsOfInputVariables(), getUnitsOfSingleInputVariable(), load(), print(), save(), saveAllStatistics(), setInputTargetDataSet(), setUnitsOfInputVariables(), and setUnitsOfSingleInputVariable().
Vector<std::string> Flood::InputTargetDataSet::unitsOfTargetVariables [private]
Units of target variables.
Definition at line 71 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getUnitsOfSingleTargetVariable(), getUnitsOfTargetVariables(), load(), print(), save(), setInputTargetDataSet(), setUnitsOfSingleTargetVariable(), and setUnitsOfTargetVariables().
Vector<std::string> Flood::InputTargetDataSet::descriptionOfInputVariables [private]
Description of input variables.
Definition at line 75 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getDescriptionOfInputVariables(), getDescriptionOfSingleInputVariable(), load(), print(), save(), saveAllStatistics(), setDescriptionOfInputVariables(), setDescriptionOfSingleInputVariable(), and setInputTargetDataSet().
Vector<std::string> Flood::InputTargetDataSet::descriptionOfTargetVariables [private]
Description of target variables.
Definition at line 79 of file InputTargetDataSet.h.
Referenced by getAllInformation(), getDescriptionOfSingleTargetVariable(), getDescriptionOfTargetVariables(), load(), print(), save(), setDescriptionOfSingleTargetVariable(), setDescriptionOfTargetVariables(), and setInputTargetDataSet().
Matrix<double> Flood::InputTargetDataSet::inputData [private]
Input data Matrix.
Definition at line 83 of file InputTargetDataSet.h.
Referenced by addSample(), calculateMeanAndStandardDeviationOfInputData(), calculateMinimumAndMaximumOfInputData(), getInputAndTargetData(), getInputData(), getSample(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), setInputAndTargetData(), setInputData(), setInputTargetDataSet(), setSample(), and subtractSample().
Matrix<double> Flood::InputTargetDataSet::targetData [private]
Target data Matrix.
Definition at line 87 of file InputTargetDataSet.h.
Referenced by addSample(), calculateMeanAndStandardDeviationOfTargetData(), calculateMinimumAndMaximumOfTargetData(), getInputAndTargetData(), getSample(), getTargetData(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), setInputAndTargetData(), setInputTargetDataSet(), setSample(), setTargetData(), and subtractSample().
bool Flood::InputTargetDataSet::display [private]
Display messages to screen.
Definition at line 91 of file InputTargetDataSet.h.
Referenced by getDisplay(), InputTargetDataSet(), load(), postprocessMeanAndStandardDeviation(), postprocessMinimumAndMaximum(), preprocessMeanAndStandardDeviation(), preprocessMinimumAndMaximum(), save(), saveAllStatistics(), and setDisplay().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Utilities/InputTargetDataSet.h
G:/Documents/Flood/Flood/Utilities/InputTargetDataSet.cpp