Flood: Flood::DeJongFunction Class Reference
Flood::DeJongFunction Class Reference
#include <DeJongFunction.h>
Public Member Functions
DeJongFunction (MultilayerPerceptron *)
DeJongFunction (void)
virtual ~DeJongFunction (void)
Destructor.
int getNumberOfVariables (void)
void setNumberOfVariables (int)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
Matrix< double > calculateHessian (void)
Matrix< double > calculateInverseHessian (void)
Private Attributes
int numberOfVariables
Number of variables in the De Jong's Function.
Detailed Description
This class represents the De Jong's objective function. The simplest function for optimization is De Jong's function. It is continuos, convex and unimodal. Explicit expressions for the gradient and the Hessian are provided here, and numerical differentiation is not needed. For more information please visit GEATbx - The Genetic and Evolutionary Algorithm Toolbox for Matlab, www.geatbx.com
See also:
ObjectiveFunctional.
Definition at line 34 of file DeJongFunction.h.
Constructor & Destructor Documentation
Flood::DeJongFunction::DeJongFunction (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a De Jong's objective function object. It also initializes all the rest of class members to their default values:
Number of variables (independent parameters): 2.
Name of independent parameters: x0,...,xn
Minimum of independent parameters: -5.12,...,-5.12.
Maximum of independent parameters: 5.12,...,5.12.
Pre and postprocessing method: Minimum and maximum.
Definition at line 41 of file DeJongFunction.cpp.
References Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfVariables.
Flood::DeJongFunction::DeJongFunction (void)
Flood::DeJongFunction::~DeJongFunction (void) [virtual]
Destructor.
Definition at line 69 of file DeJongFunction.cpp.
Member Function Documentation
int Flood::DeJongFunction::getNumberOfVariables (void)
This method returns the number of variables in the De Jong's function. This is the number of independent parameters in the multilayer perceptron.
Definition at line 82 of file DeJongFunction.cpp.
References numberOfVariables.
void Flood::DeJongFunction::setNumberOfVariables (int newNumberOfVariables)
This method sets a new number of variables in the De Jong's function. This also sets a new number of independent parameters in the multilayer perceptron. It also initializes all the rest of class members to their default values:
Name of independent parameters: x0,...,xn
Minimum of independent parameters: -5.12,...,-5.12.
Maximum of independent parameters: 5.12,...,5.12.
Parameters:
newNumberOfVariables Number of variables in the De Jong's function.
Definition at line 102 of file DeJongFunction.cpp.
References Flood::MultilayerPerceptron::initIndependentParametersUniform(), Flood::ObjectiveFunctional::multilayerPerceptron, numberOfVariables, Flood::MultilayerPerceptron::setMaximumOfSingleIndependentParameter(), Flood::MultilayerPerceptron::setMinimumOfSingleIndependentParameter(), Flood::MultilayerPerceptron::setNameOfSingleIndependentParameter(), and Flood::MultilayerPerceptron::setNumberOfIndependentParameters().
double Flood::DeJongFunction::calculateEvaluation (void) [virtual]
This method returns the De Jong's function evaluation for the actual independent parameters in the multilayer perceptron.
See also:
calculateGradient(void).
calculateHessian(void).
calculateInverseHessian(void).
Implements Flood::ObjectiveFunctional.
Definition at line 133 of file DeJongFunction.cpp.
References Flood::Vector< Type >::dot(), Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Vector< double > Flood::DeJongFunction::calculateGradient (void) [virtual]
This method returns the De Jong's analytical gradient vector for the actual independent parameter values in the multilayer perceptron.
See also:
calculateEvaluation(void).
calculateHessian(void).
calculateInverseHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 167 of file DeJongFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Matrix< double > Flood::DeJongFunction::calculateHessian (void) [virtual]
This method returns the De Jong's analytical Hessian matrix for the actual independent parameter values in the multilayer perceptron.
See also:
calculateEvaluation(void).
calculateGradient(void).
calculateInverseHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 186 of file DeJongFunction.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfVariables.
Matrix< double > Flood::DeJongFunction::calculateInverseHessian (void) [virtual]
This method returns the De Jong's analytical inverse Hessian matrix for the actual independent parameter values in the multilayer perceptron.
See also:
calculateEvaluation(void).
calculateGradient(void).
calculateHessian(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 220 of file DeJongFunction.cpp.
References numberOfVariables.
Member Data Documentation
int Flood::DeJongFunction::numberOfVariables [private]
Number of variables in the De Jong's Function.
Definition at line 41 of file DeJongFunction.h.
Referenced by calculateHessian(), calculateInverseHessian(), DeJongFunction(), getNumberOfVariables(), and setNumberOfVariables().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/DeJongFunction.h
G:/Documents/Flood/Flood/ObjectiveFunctional/DeJongFunction.cpp