Flood: Flood::PlaneCylinder Class Reference
Flood::PlaneCylinder Class Reference
#include <PlaneCylinder.h>
Public Member Functions
PlaneCylinder (MultilayerPerceptron *)
PlaneCylinder (void)
virtual ~PlaneCylinder (void)
Destructor.
double getPenalty (void)
void setPenalty (double)
double calculateError (void)
double calculateEvaluation (void)
This method returns the plane-cylinder function evaluation for a given argument.
void print (void)
Private Attributes
double penalty
Penalty term ratio.
Detailed Description
This class represents the objective function for the plane-cylinder problem.
See also:
ObjectiveFunctional.
Definition at line 29 of file PlaneCylinder.h.
Constructor & Destructor Documentation
Flood::PlaneCylinder::PlaneCylinder (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a plane-cylinder objective function object. It also initializes all the rest of class members to their default values:
Minimum: -5.12,...,-5.12.
Maximum: 5.12,...,5.12.
Penalty: 100.
Definition at line 36 of file PlaneCylinder.cpp.
References Flood::MultilayerPerceptron::getNumberOfIndependentParameters(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::ObjectiveFunctional::multilayerPerceptron, and penalty.
Flood::PlaneCylinder::PlaneCylinder (void)
Flood::PlaneCylinder::~PlaneCylinder (void) [virtual]
Destructor.
Definition at line 76 of file PlaneCylinder.cpp.
Member Function Documentation
double Flood::PlaneCylinder::getPenalty (void)
This method returns the penalty term ratio to be used in the plane-cylinder problem.
See also:
calculateError(void)
calculateEvaluation(void)
Definition at line 91 of file PlaneCylinder.cpp.
References penalty.
void Flood::PlaneCylinder::setPenalty (double newPenalty)
This method sets a new penalty term ratio to be used in the plane-cylinder problem.
Parameters:
newPenalty New penalty term ratio.
See also:
calculateError(void)
calculateEvaluation(void)
Definition at line 106 of file PlaneCylinder.cpp.
References penalty.
double Flood::PlaneCylinder::calculateError (void)
This method returns the error made in the constraint by a given argument.
See also:
calculateEvaluation(void)
Definition at line 133 of file PlaneCylinder.cpp.
References Flood::MultilayerPerceptron::getIndependentParameters(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateEvaluation(), and print().
double Flood::PlaneCylinder::calculateEvaluation (void) [virtual]
This method returns the plane-cylinder function evaluation for a given argument.
Implements Flood::ObjectiveFunctional.
Definition at line 159 of file PlaneCylinder.cpp.
References calculateError(), Flood::MultilayerPerceptron::getIndependentParameters(), Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and penalty.
void Flood::PlaneCylinder::print (void) [virtual]
This method prints to the screen the error made in the constraint by a given argument during the optimization process.
See also:
calculateError(Vector<double>)
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 200 of file PlaneCylinder.cpp.
References calculateError().
Member Data Documentation
double Flood::PlaneCylinder::penalty [private]
Penalty term ratio.
Definition at line 36 of file PlaneCylinder.h.
Referenced by calculateEvaluation(), getPenalty(), PlaneCylinder(), and setPenalty().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/PlaneCylinder.h
G:/Documents/Flood/Flood/ObjectiveFunctional/PlaneCylinder.cpp