Flood: Flood::ObjectiveFunctional Class Reference
Flood::ObjectiveFunctional Class Reference
#include <ObjectiveFunctional.h>
Public Types
enum NumericalEpsilonMethod { Absolute, Relative }
enum NumericalDifferentiationMethod { ForwardDifferences, CentralDifferences }
Enumeration of available methods for calculating any derivative of the objective function numerically.
Public Member Functions
ObjectiveFunctional (MultilayerPerceptron *)
ObjectiveFunctional (void)
virtual ~ObjectiveFunctional (void)
Destructor.
MultilayerPerceptron * getMultilayerPerceptron (void)
This method returns a pointer to the multilayer perceptron object associated to the objective functional.
double getNumericalEpsilon (void)
int getNumberOfEvaluations (void)
bool getDisplay (void)
NumericalEpsilonMethod getNumericalEpsilonMethod (void)
This method returns the method used for numerical epsilon.
NumericalDifferentiationMethod getNumericalDifferentiationMethod (void)
This method returns the method used for numerical differentiation.
void setMultilayerPerceptron (MultilayerPerceptron *)
void setNumericalEpsilon (double)
void setNumberOfEvaluations (int)
void setDisplay (bool)
void setNumericalEpsilonMethod (NumericalEpsilonMethod)
void setNumericalDifferentiationMethod (NumericalDifferentiationMethod)
virtual double calculateEvaluation (void)=0
double calculatePotentialEvaluation (Vector< double >)
virtual Vector< double > calculateGradient (void)
Vector< double > calculatePotentialGradient (Vector< double >)
virtual Matrix< double > calculateHessian (void)
Matrix< double > calculatePotentialHessian (Vector< double >)
virtual Matrix< double > calculateInverseHessian (void)
Matrix< double > calculateDFPInverseHessianApproximation (Vector< double >, Vector< double >, Matrix< double >, Vector< double >, Vector< double >)
Matrix< double > calculateBFGSInverseHessianApproximation (Vector< double >, Vector< double >, Matrix< double >, Vector< double >, Vector< double >)
virtual Vector< double > calculateVectorHessianProduct (Vector< double >)
virtual void print (void)
Protected Attributes
MultilayerPerceptron * multilayerPerceptron
Pointer to a multilayer perceptron object.
int numberOfEvaluations
double numericalEpsilon
Epsilon value for the calculation of the objective function gradient with numerical differentiation.
bool display
Display messages to screen.
NumericalEpsilonMethod numericalEpsilonMethod
Numerical epsilon methods enumeration.
NumericalDifferentiationMethod numericalDifferentiationMethod
Numerical differentiation methods enumeration.
Detailed Description
This abstract class represents the concept of objective functional for the multilayer perceptron. Any derived class must implement the calculateEvaluation(void) method.
See also:
MultilayerPerceptron.
Definition at line 30 of file ObjectiveFunctional.h.
Member Enumeration Documentation
enum Flood::ObjectiveFunctional::NumericalEpsilonMethod
Enumeration of available methods for obtaining a numerical value of epsilon to be used in numerical differentiation.
Enumerator:
Absolute
Relative
Definition at line 40 of file ObjectiveFunctional.h.
enum Flood::ObjectiveFunctional::NumericalDifferentiationMethod
Enumeration of available methods for calculating any derivative of the objective function numerically.
Enumerator:
ForwardDifferences
CentralDifferences
Definition at line 44 of file ObjectiveFunctional.h.
Constructor & Destructor Documentation
Flood::ObjectiveFunctional::ObjectiveFunctional (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates an objective functional object associated to a multilayer perceptron object. It also initializes all the rest of class members to their default values:
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Number of evaluations = 0.
Numerical epsilon: 1.0e-6.
Display: true.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 40 of file ObjectiveFunctional.cpp.
References CentralDifferences, display, multilayerPerceptron, numberOfEvaluations, numericalDifferentiationMethod, numericalEpsilon, numericalEpsilonMethod, and Relative.
Flood::ObjectiveFunctional::ObjectiveFunctional (void)
General constructor. It creates an objective functional object not associated to any multilayer perceptron object. It also initializes all the rest of class members to their default values:
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Number of evaluations = 0.
Numerical epsilon: 1.0e-6.
Display: true.
Definition at line 71 of file ObjectiveFunctional.cpp.
References CentralDifferences, display, multilayerPerceptron, numberOfEvaluations, numericalDifferentiationMethod, numericalEpsilon, numericalEpsilonMethod, and Relative.
Flood::ObjectiveFunctional::~ObjectiveFunctional (void) [virtual]
Destructor.
Definition at line 91 of file ObjectiveFunctional.cpp.
Member Function Documentation
MultilayerPerceptron * Flood::ObjectiveFunctional::getMultilayerPerceptron (void)
This method returns a pointer to the multilayer perceptron object associated to the objective functional.
Definition at line 104 of file ObjectiveFunctional.cpp.
References multilayerPerceptron.
Referenced by Flood::QuasiNewtonMethod::calculateBrentMethodTrainRate(), Flood::GradientDescent::calculateBrentMethodTrainRate(), Flood::ConjugateGradient::calculateBrentMethodTrainRate(), Flood::QuasiNewtonMethod::calculateGoldenSectionTrainRate(), Flood::GradientDescent::calculateGoldenSectionTrainRate(), Flood::ConjugateGradient::calculateGoldenSectionTrainRate(), Flood::EvolutionaryAlgorithm::evaluatePopulation(), Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm(), Flood::RandomSearch::getMinimumAndMaximumValuesOfFreeParameters(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::EvolutionaryAlgorithm::load(), Flood::EvolutionaryAlgorithm::performIntermediateRecombination(), Flood::EvolutionaryAlgorithm::performLineRecombination(), Flood::EvolutionaryAlgorithm::performNormalMutation(), Flood::EvolutionaryAlgorithm::performUniformMutation(), Flood::EvolutionaryAlgorithm::print(), Flood::RandomSearch::RandomSearch(), Flood::RandomSearch::resizeTrainingHistory(), Flood::QuasiNewtonMethod::resizeTrainingHistory(), Flood::NewtonMethod::resizeTrainingHistory(), Flood::GradientDescent::resizeTrainingHistory(), Flood::ConjugateGradient::resizeTrainingHistory(), Flood::EvolutionaryAlgorithm::save(), Flood::EvolutionaryAlgorithm::setIndividual(), Flood::RandomSearch::setMaximumValueOfFreeParameters(), Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters(), Flood::RandomSearch::setMinimumValueOfFreeParameters(), Flood::EvolutionaryAlgorithm::setPopulation(), Flood::EvolutionaryAlgorithm::setPopulationSize(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), Flood::EvolutionaryAlgorithm::train(), and Flood::ConjugateGradient::train().
double Flood::ObjectiveFunctional::getNumericalEpsilon (void)
This method returns the epsilon value for the calculation of the objective function gradient by means of numerical differentiation.
See also:
calculateGradient(void)
calculateHessian(void)
calculateVectorHessianProduct(Vector<double>)
Definition at line 119 of file ObjectiveFunctional.cpp.
References numericalEpsilon.
int Flood::ObjectiveFunctional::getNumberOfEvaluations (void)
This method returns the number of calls to the calculateEvaluation(void) method.
See also:
calculateEvaluation(void).
Definition at line 131 of file ObjectiveFunctional.cpp.
References numberOfEvaluations.
bool Flood::ObjectiveFunctional::getDisplay (void)
This method returns true if messages from this class can be displayed on the screen, or false if messages from this class can't be displayed on the screen.
Definition at line 142 of file ObjectiveFunctional.cpp.
References display.
ObjectiveFunctional::NumericalEpsilonMethod Flood::ObjectiveFunctional::getNumericalEpsilonMethod (void)
This method returns the method used for numerical epsilon.
Definition at line 153 of file ObjectiveFunctional.cpp.
References numericalEpsilonMethod.
ObjectiveFunctional::NumericalDifferentiationMethod Flood::ObjectiveFunctional::getNumericalDifferentiationMethod (void)
This method returns the method used for numerical differentiation.
Definition at line 164 of file ObjectiveFunctional.cpp.
References numericalDifferentiationMethod.
void Flood::ObjectiveFunctional::setMultilayerPerceptron (MultilayerPerceptron * newMultilayerPerceptron)
This method sets a pointer to a multilayer perceptron object which is to be associated to the objective functional.
Parameters:
newMultilayerPerceptron Pointer to a multilayer percepron object to be associated to the objective functional.
Definition at line 178 of file ObjectiveFunctional.cpp.
References multilayerPerceptron.
void Flood::ObjectiveFunctional::setNumericalEpsilon (double newNumericalEpsilon)
This method sets a new epsilon value for the calculation of the objective function gradient by means of numerical differentiation.
Parameters:
newNumericalEpsilon New value for epsilon.
See also:
calculateGradient(void)
Definition at line 193 of file ObjectiveFunctional.cpp.
References numericalEpsilon.
void Flood::ObjectiveFunctional::setNumberOfEvaluations (int newNumberOfEvaluations)
This method sets the number of calls to the getObjective(void) method to a new value.
Parameters:
newNumberOfEvaluations New number of calls to the calculateEvaluation(void) method.
See also:
calculateEvaluation(void).
Definition at line 223 of file ObjectiveFunctional.cpp.
References numberOfEvaluations.
void Flood::ObjectiveFunctional::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 252 of file ObjectiveFunctional.cpp.
References display.
void Flood::ObjectiveFunctional::setNumericalEpsilonMethod (ObjectiveFunctional::NumericalEpsilonMethod newNumericalEpsilonMethod)
This method sets the method to be used for obtaining a numerical epsilon value to be used in numerical differentiation.
Parameters:
newNumericalEpsilonMethod New numerical epsilon method.
See also:
calculateGradient(void).
calculateHessian(void).
Definition at line 269 of file ObjectiveFunctional.cpp.
References numericalEpsilonMethod.
void Flood::ObjectiveFunctional::setNumericalDifferentiationMethod (ObjectiveFunctional::NumericalDifferentiationMethod newNumericalDifferentiationMethod)
This method sets the method to be used for the numerical differentiation of the Jacobian matrix for the multilayer perceptron.
Parameters:
newNumericalDifferentiationMethod New numerical differentiation method.
See also:
calculateGradient(void).
calculateHessian(void).
Definition at line 286 of file ObjectiveFunctional.cpp.
References numericalDifferentiationMethod.
virtual double Flood::ObjectiveFunctional::calculateEvaluation (void) [pure virtual]
This method returns the objective value of a multilayer perceptron.
See also:
calculateGradient(void).
Implemented in Flood::AircraftLandingProblem, Flood::BrachistochroneProblem, Flood::CarProblem, Flood::CatenaryProblem, Flood::DeJongFunction, Flood::EasomFunction, Flood::FedBatchFermenterProblem, Flood::GeodesicProblem, Flood::IsoperimetricProblem, Flood::MeanSquaredError, Flood::MinimumDragProblem, Flood::MinkowskiError, Flood::NormalizedSquaredError, Flood::PlaneCylinder, Flood::PrecipitateDissolutionModeling, Flood::RastriginFunction, Flood::RegularizedMinkowskiError, Flood::RootMeanSquaredError, Flood::RosenbrockFunction, and Flood::SumSquaredError.
Referenced by calculateGradient(), calculatePotentialEvaluation(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), and Flood::ConjugateGradient::train().
double Flood::ObjectiveFunctional::calculatePotentialEvaluation (Vector< double > potentialFreeParameters)
This method returns which would be the objective evaluation of a multilayer perceptron for an hypothetical vector of free parameters. It does not set that vector of free parameters to the multilayer perceptron.
Parameters:
potentialFreeParameters Vector of a potential free parameters for the multilayer perceptron associated to the objective functional.
See also:
calculateEvaluation(void).
Definition at line 302 of file ObjectiveFunctional.cpp.
References calculateEvaluation(), Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), multilayerPerceptron, and Flood::MultilayerPerceptron::setFreeParameters().
Referenced by Flood::QuasiNewtonMethod::calculateBrentMethodTrainRate(), Flood::GradientDescent::calculateBrentMethodTrainRate(), Flood::ConjugateGradient::calculateBrentMethodTrainRate(), Flood::QuasiNewtonMethod::calculateGoldenSectionTrainRate(), Flood::GradientDescent::calculateGoldenSectionTrainRate(), Flood::ConjugateGradient::calculateGoldenSectionTrainRate(), calculateGradient(), calculateHessian(), Flood::EvolutionaryAlgorithm::evaluatePopulation(), and Flood::RandomSearch::train().
Vector< double > Flood::ObjectiveFunctional::calculateGradient (void) [virtual]
This method returns the objective function gradient vector for a multilayer perceptron.
See also:
calculateEvaluation(void).
This method returns the default objective function gradient vector, which is computed using numerical differentiation.
See also:
NumericalEpsilonMethod.
NumericalDifferentiationMethod.
Reimplemented in Flood::DeJongFunction, Flood::EasomFunction, Flood::MeanSquaredError, Flood::MinkowskiError, Flood::NormalizedSquaredError, Flood::RastriginFunction, Flood::RegularizedMinkowskiError, Flood::RootMeanSquaredError, and Flood::SumSquaredError.
Definition at line 352 of file ObjectiveFunctional.cpp.
References Absolute, calculateEvaluation(), calculatePotentialEvaluation(), CentralDifferences, ForwardDifferences, Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), multilayerPerceptron, numericalDifferentiationMethod, numericalEpsilon, numericalEpsilonMethod, and Relative.
Referenced by calculatePotentialGradient(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), and Flood::ConjugateGradient::train().
Vector< double > Flood::ObjectiveFunctional::calculatePotentialGradient (Vector< double > potentialFreeParameters)
This method returns which would be the objective function gradient of a multilayer perceptron for an hypothetical vector of free parameters. It does not set that vector of free parameters to the multilayer perceptron.
Parameters:
potentialFreeParameters Vector of a potential free parameters for the multilayer perceptron associated to the objective functional.
See also:
calculateGradient(void).
Definition at line 525 of file ObjectiveFunctional.cpp.
References calculateGradient(), Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), multilayerPerceptron, and Flood::MultilayerPerceptron::setFreeParameters().
Referenced by calculateVectorHessianProduct().
Matrix< double > Flood::ObjectiveFunctional::calculateHessian (void) [virtual]
This method returns the objective function Hessian matrix for a multilayer perceptron. Please, do not use this method. It is not yet implemented!
This method returns the default objective function Hessian matrix, which is computed using numerical differentiation.
See also:
NumericalEpsilonMethod.
NumericalDifferentiationMethod.
Reimplemented in Flood::DeJongFunction, Flood::EasomFunction, and Flood::RastriginFunction.
Definition at line 574 of file ObjectiveFunctional.cpp.
References Absolute, calculatePotentialEvaluation(), CentralDifferences, ForwardDifferences, Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), multilayerPerceptron, numericalDifferentiationMethod, numericalEpsilon, numericalEpsilonMethod, and Relative.
Referenced by calculateInverseHessian(), and calculatePotentialHessian().
Matrix< double > Flood::ObjectiveFunctional::calculatePotentialHessian (Vector< double > potentialFreeParameters)
This method returns which would be the objective function Hessian of a multilayer perceptron for an hypothetical vector of free parameters. It does not set that vector of free parameters to the multilayer perceptron.
Parameters:
potentialFreeParameters Vector of a potential free parameters for the multilayer perceptron associated to the objective functional.
See also:
calculateHessian(void).
Definition at line 749 of file ObjectiveFunctional.cpp.
References calculateHessian(), Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), multilayerPerceptron, and Flood::MultilayerPerceptron::setFreeParameters().
Matrix< double > Flood::ObjectiveFunctional::calculateInverseHessian (void) [virtual]
This method returns inverse matrix of the Hessian. It first computes the Hessian matrix and then computes its inverse.
Reimplemented in Flood::DeJongFunction, Flood::EasomFunction, and Flood::RastriginFunction.
Definition at line 795 of file ObjectiveFunctional.cpp.
References calculateHessian(), and Flood::Matrix< Type >::calculateInverse().
Referenced by Flood::NewtonMethod::train().
Matrix< double > Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation (Vector< double > oldFreeParameters, Vector< double > oldGradient, Matrix< double > oldInverseHessian, Vector< double > freeParameters, Vector< double > gradient)
This method returns an approximation of the inverse Hessian matrix according to the Davidon-Fletcher-Powel (DFP) algorithm.
Parameters:
oldFreeParameters A previous set of free parameters.
oldGradient The gradient of the objective function for that previous set of free parameters.
oldInverseHessian The Hessian of the objective function for that previous set of free parameters.
freeParameters Actual set of free parameters.
gradient The gradient of the objective function for the actual set of free parameters.
Definition at line 818 of file ObjectiveFunctional.cpp.
References Flood::Vector< Type >::dot(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Vector< Type >::getSize(), multilayerPerceptron, and Flood::Vector< Type >::outer().
Referenced by Flood::QuasiNewtonMethod::train().
Matrix< double > Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation (Vector< double > oldFreeParameters, Vector< double > oldGradient, Matrix< double > oldInverseHessian, Vector< double > freeParameters, Vector< double > gradient)
This method returns an approximation of the inverse Hessian matrix according to the Broyden-Fletcher-Goldfarb-Shanno (BGFS) algorithm.
Parameters:
oldFreeParameters A previous set of free parameters.
oldGradient The gradient of the objective function for that previous set of free parameters.
oldInverseHessian The Hessian of the objective function for that previous set of free parameters.
freeParameters Actual set of free parameters.
gradient The gradient of the objective function for the actual set of free parameters.
Definition at line 931 of file ObjectiveFunctional.cpp.
References Flood::Vector< Type >::dot(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Vector< Type >::getSize(), multilayerPerceptron, and Flood::Vector< Type >::outer().
Referenced by Flood::QuasiNewtonMethod::train().
Vector< double > Flood::ObjectiveFunctional::calculateVectorHessianProduct (Vector< double > vector) [virtual]
This method returns the default product of some vector with the objective function Hessian matrix, which is computed using numerical differentiation.
See also:
NumericalEpsilonMethod.
NumericalDifferentiationMethod.
Definition at line 1045 of file ObjectiveFunctional.cpp.
References Absolute, calculatePotentialGradient(), CentralDifferences, ForwardDifferences, Flood::MultilayerPerceptron::getFreeParameters(), Flood::MultilayerPerceptron::getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), multilayerPerceptron, numericalDifferentiationMethod, numericalEpsilon, numericalEpsilonMethod, and Relative.
void Flood::ObjectiveFunctional::print (void) [virtual]
This method prints any useful information about the objective function during training. By default it prints nothing.
Reimplemented in Flood::CarProblem, Flood::CatenaryProblem, Flood::FedBatchFermenterProblem, Flood::IsoperimetricProblem, Flood::PlaneCylinder, and Flood::PrecipitateDissolutionModeling.
Definition at line 1163 of file ObjectiveFunctional.cpp.
Referenced by Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::GradientDescent::train(), Flood::EvolutionaryAlgorithm::train(), and Flood::ConjugateGradient::train().
Member Data Documentation
MultilayerPerceptron* Flood::ObjectiveFunctional::multilayerPerceptron [protected]
Pointer to a multilayer perceptron object.
Definition at line 50 of file ObjectiveFunctional.h.
Referenced by Flood::AircraftLandingProblem::AircraftLandingProblem(), Flood::BrachistochroneProblem::BrachistochroneProblem(), Flood::GeodesicProblem::calculateArcLengthIntegrand(), Flood::IsoperimetricProblem::calculateAreaIntegrand(), calculateBFGSInverseHessianApproximation(), Flood::BrachistochroneProblem::calculateDescentTimeIntegrand(), calculateDFPInverseHessianApproximation(), Flood::PlaneCylinder::calculateError(), Flood::SumSquaredError::calculateEvaluation(), Flood::RosenbrockFunction::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::RastriginFunction::calculateEvaluation(), Flood::PrecipitateDissolutionModeling::calculateEvaluation(), Flood::PlaneCylinder::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MinimumDragProblem::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::IsoperimetricProblem::calculateEvaluation(), Flood::GeodesicProblem::calculateEvaluation(), Flood::FedBatchFermenterProblem::calculateEvaluation(), Flood::EasomFunction::calculateEvaluation(), Flood::DeJongFunction::calculateEvaluation(), Flood::CatenaryProblem::calculateEvaluation(), Flood::CarProblem::calculateEvaluation(), Flood::BrachistochroneProblem::calculateEvaluation(), Flood::AircraftLandingProblem::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::RastriginFunction::calculateGradient(), calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::EasomFunction::calculateGradient(), Flood::DeJongFunction::calculateGradient(), Flood::RastriginFunction::calculateHessian(), calculateHessian(), Flood::EasomFunction::calculateHessian(), Flood::DeJongFunction::calculateHessian(), Flood::RastriginFunction::calculateInverseHessian(), Flood::EasomFunction::calculateInverseHessian(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateJacobianTest(), Flood::CatenaryProblem::calculateLengthIntegrand(), Flood::IsoperimetricProblem::calculatePerimeterIntegrand(), Flood::AircraftLandingProblem::calculatePitchAngleRateDot(), Flood::CatenaryProblem::calculatePotentialEnergyIntegrand(), calculatePotentialEvaluation(), calculatePotentialGradient(), calculatePotentialHessian(), Flood::SumSquaredError::calculateSquaredErrors(), calculateVectorHessianProduct(), Flood::CarProblem::calculateVelocityDot(), Flood::CarProblem::CarProblem(), Flood::CatenaryProblem::CatenaryProblem(), Flood::DeJongFunction::DeJongFunction(), Flood::EasomFunction::EasomFunction(), Flood::GeodesicProblem::GeodesicProblem(), Flood::FedBatchFermenterProblem::getBrothVolumeDot(), Flood::FedBatchFermenterProblem::getCellMassConcentrationDot(), Flood::MinimumDragProblem::getDragIntegrand(), Flood::PrecipitateDissolutionModeling::getFullDissolutionTime(), getMultilayerPerceptron(), Flood::FedBatchFermenterProblem::getProductConcentrationDot(), Flood::FedBatchFermenterProblem::getSubstrateConcentrationDot(), Flood::IsoperimetricProblem::IsoperimetricProblem(), Flood::MinimumDragProblem::MinimumDragProblem(), ObjectiveFunctional(), Flood::PlaneCylinder::PlaneCylinder(), Flood::PrecipitateDissolutionModeling::PrecipitateDissolutionModeling(), Flood::PrecipitateDissolutionModeling::print(), Flood::CarProblem::print(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::PrecipitateDissolutionModeling::saveInverseVickersHardnessTest(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), Flood::MinimumDragProblem::saveResults(), Flood::IsoperimetricProblem::saveResults(), Flood::GeodesicProblem::saveResults(), Flood::FedBatchFermenterProblem::saveResults(), Flood::CatenaryProblem::saveResults(), Flood::CarProblem::saveResults(), Flood::BrachistochroneProblem::saveResults(), Flood::AircraftLandingProblem::saveResults(), Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel(), setMultilayerPerceptron(), and Flood::DeJongFunction::setNumberOfVariables().
int Flood::ObjectiveFunctional::numberOfEvaluations [protected]
Number of calls to the calculateEvaluation(void) method.
See also:
calculateEvaluation(void).
Definition at line 56 of file ObjectiveFunctional.h.
Referenced by Flood::SumSquaredError::calculateEvaluation(), Flood::RosenbrockFunction::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::RastriginFunction::calculateEvaluation(), Flood::PrecipitateDissolutionModeling::calculateEvaluation(), Flood::PlaneCylinder::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MinimumDragProblem::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::IsoperimetricProblem::calculateEvaluation(), Flood::GeodesicProblem::calculateEvaluation(), Flood::FedBatchFermenterProblem::calculateEvaluation(), Flood::EasomFunction::calculateEvaluation(), Flood::DeJongFunction::calculateEvaluation(), Flood::CatenaryProblem::calculateEvaluation(), Flood::CarProblem::calculateEvaluation(), Flood::BrachistochroneProblem::calculateEvaluation(), Flood::AircraftLandingProblem::calculateEvaluation(), getNumberOfEvaluations(), ObjectiveFunctional(), and setNumberOfEvaluations().
double Flood::ObjectiveFunctional::numericalEpsilon [protected]
Epsilon value for the calculation of the objective function gradient with numerical differentiation.
Definition at line 60 of file ObjectiveFunctional.h.
Referenced by calculateGradient(), calculateHessian(), Flood::SumSquaredError::calculateJacobianTest(), calculateVectorHessianProduct(), getNumericalEpsilon(), ObjectiveFunctional(), and setNumericalEpsilon().
bool Flood::ObjectiveFunctional::display [protected]
Display messages to screen.
Definition at line 64 of file ObjectiveFunctional.h.
Referenced by getDisplay(), Flood::PrecipitateDissolutionModeling::loadVickersHardnessTest(), ObjectiveFunctional(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::MinimumDragProblem::saveResults(), Flood::IsoperimetricProblem::saveResults(), Flood::GeodesicProblem::saveResults(), Flood::CatenaryProblem::saveResults(), Flood::CarProblem::saveResults(), Flood::BrachistochroneProblem::saveResults(), Flood::AircraftLandingProblem::saveResults(), and setDisplay().
NumericalEpsilonMethod Flood::ObjectiveFunctional::numericalEpsilonMethod [protected]
Numerical epsilon methods enumeration.
Definition at line 68 of file ObjectiveFunctional.h.
Referenced by calculateGradient(), calculateHessian(), calculateVectorHessianProduct(), getNumericalEpsilonMethod(), ObjectiveFunctional(), and setNumericalEpsilonMethod().
NumericalDifferentiationMethod Flood::ObjectiveFunctional::numericalDifferentiationMethod [protected]
Numerical differentiation methods enumeration.
Definition at line 72 of file ObjectiveFunctional.h.
Referenced by calculateGradient(), calculateHessian(), Flood::SumSquaredError::calculateJacobianTest(), calculateVectorHessianProduct(), getNumericalDifferentiationMethod(), ObjectiveFunctional(), and setNumericalDifferentiationMethod().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/ObjectiveFunctional.h
G:/Documents/Flood/Flood/ObjectiveFunctional/ObjectiveFunctional.cpp