Flood: Flood::NormalizedSquaredError Class Reference
Flood::NormalizedSquaredError Class Reference
#include <NormalizedSquaredError.h>
Public Member Functions
NormalizedSquaredError (MultilayerPerceptron *, InputTargetDataSet *)
NormalizedSquaredError (void)
virtual ~NormalizedSquaredError (void)
Destructor.
InputTargetDataSet * getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objectiveal is measured.
void setInputTargetDataSet (InputTargetDataSet *)
double calculateEvaluation (void)
Vector< double > calculateGradient (void)
void saveInputTargetAndOutput (char *)
Private Attributes
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
Vector< double > meanOfTargetData
Mean values of all the target variables.
Detailed Description
This class represents the normalized squared error objective functional of a multilayer perceptron. This objective functional is used in data modeling problems. If it has a value of unity then the neural network predicting the data "in the mean" while a value of zero means perfect prediction of data.
See also:
MultilayerPerceptron.
InputTargetDataSet.
Definition at line 33 of file NormalizedSquaredError.h.
Constructor & Destructor Documentation
Flood::NormalizedSquaredError::NormalizedSquaredError (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a normalized squared error objective functional object associated to a multilayer perceptron and measured on an input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 41 of file NormalizedSquaredError.cpp.
References Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfTargetData(), Flood::Matrix< Type >::getRow(), inputTargetDataSet, and meanOfTargetData.
Flood::NormalizedSquaredError::NormalizedSquaredError (void)
Default constructor. It creates a normalized squared error objective functional object not associated to any multilayer perceptron and not measured on any input-target data set. It also initializes all the rest of class members to their default values:
Number of evaluations = 0.
Epsilon: 1.0e-6.
Display = true.
Definition at line 66 of file NormalizedSquaredError.cpp.
References inputTargetDataSet.
Flood::NormalizedSquaredError::~NormalizedSquaredError (void) [virtual]
Destructor.
Definition at line 76 of file NormalizedSquaredError.cpp.
Member Function Documentation
InputTargetDataSet * Flood::NormalizedSquaredError::getInputTargetDataSet (void)
This method returns a pointer to the input-target object on which the objectiveal is measured.
Definition at line 88 of file NormalizedSquaredError.cpp.
References inputTargetDataSet.
void Flood::NormalizedSquaredError::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a pointer to an input-data set object on which the objective functional is to be measured.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 100 of file NormalizedSquaredError.cpp.
References Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfTargetData(), Flood::Matrix< Type >::getRow(), inputTargetDataSet, and meanOfTargetData.
double Flood::NormalizedSquaredError::calculateEvaluation (void) [virtual]
This method returns the evaluation value of a multilayer perceptron according to the normalized squared error on an input-target data set.
See also:
calculateGradient(void).
Implements Flood::ObjectiveFunctional.
Definition at line 118 of file NormalizedSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, meanOfTargetData, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Vector< double > Flood::NormalizedSquaredError::calculateGradient (void) [virtual]
This method returns the the normalized squared error function gradient of a multilayer perceptron on an input-target data set. It uses the error back-propagation method.
See also:
calculateEvaluation(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 219 of file NormalizedSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer(), Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::Matrix< Type >::getRow(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::MultilayerPerceptron::MeanAndStandardDeviation, meanOfTargetData, Flood::MultilayerPerceptron::MinimumAndMaximum, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::MultilayerPerceptron::None, Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), and Flood::Vector< Type >::setSize().
void Flood::NormalizedSquaredError::saveInputTargetAndOutput (char * filename)
This method saves to a file the inputs and the targets in the input-target data set, together with the outputs from the multilayer perceptron for that inputs:
Inputs.
Targets.
Outputs.
Parameters:
filename Filename.
Definition at line 496 of file NormalizedSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, Flood::InputTargetDataSet::getInputData(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Member Data Documentation
InputTargetDataSet* Flood::NormalizedSquaredError::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 40 of file NormalizedSquaredError.h.
Referenced by calculateEvaluation(), calculateGradient(), getInputTargetDataSet(), NormalizedSquaredError(), saveInputTargetAndOutput(), and setInputTargetDataSet().
Vector<double> Flood::NormalizedSquaredError::meanOfTargetData [private]
Mean values of all the target variables.
Definition at line 44 of file NormalizedSquaredError.h.
Referenced by calculateEvaluation(), calculateGradient(), NormalizedSquaredError(), and setInputTargetDataSet().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/NormalizedSquaredError.h
G:/Documents/Flood/Flood/ObjectiveFunctional/NormalizedSquaredError.cpp