Flood: Flood::FedBatchFermenterProblem Class Reference
Flood::FedBatchFermenterProblem Class Reference
#include <FedBatchFermenterProblem.h>
Public Member Functions
FedBatchFermenterProblem (MultilayerPerceptron *)
FedBatchFermenterProblem (void)
virtual ~FedBatchFermenterProblem (void)
Destructor.
double getFinalTime (void)
This method returns the set time for the fermentation process (hour).
double getInitialCellMassConcentration (void)
This method returns the initial concentration of cell mass in the fermenter (gram/litre).
double getInitialSubstrateConcentration (void)
This method returns the initial concentration of substrate in the fermenter (gram/litre).
double getInitialProductConcentration (void)
This method returns the initial concentration of product in the fermenter (gram/litre).
double getInitialBrothVolume (void)
This method returns the initial volume of culture medium in the fermenter (litre).
double getFermenterVolume (void)
This method returns the volume of the fermenter (litre).
double getMinimumFeedRate (void)
This method returns the minimum feed rate (control action) to the fermenter (litre/hour).
double getMaximumFeedRate (void)
This method returns the maximum feed rate (control action) to the fermenter (litre/hour).
double getVolumeErrorWeight (void)
This method returns the weight for the final volume error term in the objective functional.
double getYieldWeight (void)
This method returns the weight for the final yield term in the objective functional.
double getTolerance (void)
int getInitialSize (void)
void setFinalTime (double)
void setInitialCellMassConcentration (double)
void setInitialSubstrateConcentration (double)
void setInitialProductConcentration (double)
void setInitialBrothVolume (double)
void setFermenterVolume (double)
void setMinimumFeedRate (double)
void setMaximumFeedRate (double)
void setVolumeErrorWeight (double)
void setYieldWeight (double)
void setTolerance (double)
void setInitialSize (int)
double getCellMassConcentrationDot (double, double, double, double, double)
double getSubstrateConcentrationDot (double, double, double, double, double)
double getProductConcentrationDot (double, double, double, double, double)
double getBrothVolumeDot (double, double, double, double, double)
double getSpecificGrowthRate (double, double)
double getSpecificProductivity (double, double)
double calculateEvaluation (void)
void print (void)
void saveResults (char *)
Private Attributes
double finalTime
Fermentation process time (hour).
double initialCellMassConcentration
Initial concentration of cell mass in the fermenter (gram/litre).
double initialSubstrateConcentration
Initial concentration of substrate in the fermenter (gram/litre).
double initialProductConcentration
Initial concentration of product in the fermenter (gram/litre).
double initialBrothVolume
Initial volume of culture medium in the fermenter (litre).
double fermenterVolume
Volume of fermenter (litre).
double minimumFeedRate
Minimum feed rate (control action) to the fermenter (litre/hour).
double maximumFeedRate
Maximum feed rate (control action) to the fermenter (litre/hour).
double volumeErrorWeight
Weight for the final volume error term in the objective functional.
double yieldWeight
Weight for the final yield term in the objective functional.
double yieldCoefficient
Yield coefficient in the fermentation process (no units).
double feedSubstrateConcentration
Concentration of substrate in the feed to the fermenter (gram/litre).
double kineticConstantMu0
Kinetic constant in the fementation process Mu0.
double kineticConstantEta0
Kinetic constant in the fementation process Eta0.
double kineticConstantKp
Kinetic constant in the fementation process Kp.
double kineticConstantKpDash
Kinetic constant in the fementation process JpDash.
double kineticConstantKs
Kinetic constant in the fementation process Ks.
double kineticConstantKsDash
Kinetic constant in the fementation process KsDash.
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
double tolerance
Tolerance of integration in Runge-Kutta-Fehlberg method.
int initialSize
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the fed batch fermenter problem. The fed batch fermenter problem for the multilayer perceptron is an optimal control problem with one control and four state variables. It is defined by an objective functional with one constraint and requiring the integration of a system of ordinary differential equations.
See also:
ObjectiveFunctional.
OrdinaryDifferentialEquations.
Definition at line 37 of file FedBatchFermenterProblem.h.
Constructor & Destructor Documentation
Flood::FedBatchFermenterProblem::FedBatchFermenterProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a fed batch fermenter problem objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Final time: 54.
Initial cell mass concentration: 1.
Initial substrate concentration: 150.
Initial product concentration: 0.
Initial broth volume: 10.
Maximum volume: 200.
Minimum feed rate: 0.
Maximum feed rate: 12.
Tolerance: 1.0e-6.
Initial size: 1000.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
See also:
ObjectiveFunctional.
Definition at line 52 of file FedBatchFermenterProblem.cpp.
Flood::FedBatchFermenterProblem::FedBatchFermenterProblem (void)
Default constructor. It creates a fed batch fermenter problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Final time: 54.
Initial cell mass concentration: 1.
Initial substrate concentration: 150.
Initial product concentration: 0.
Initial broth volume: 10.
Maximum volume: 200.
Minimum feed rate: 0.
Maximum feed rate: 12.
Tolerance: 1.0e-6.
Initial size: 1000.
See also:
ObjectiveFunctional.
Definition at line 126 of file FedBatchFermenterProblem.cpp.
References fermenterVolume, finalTime, initialBrothVolume, initialCellMassConcentration, initialProductConcentration, initialSize, initialSubstrateConcentration, maximumFeedRate, minimumFeedRate, tolerance, volumeErrorWeight, and yieldWeight.
Flood::FedBatchFermenterProblem::~FedBatchFermenterProblem (void) [virtual]
Destructor.
Definition at line 152 of file FedBatchFermenterProblem.cpp.
Member Function Documentation
double Flood::FedBatchFermenterProblem::getFinalTime (void)
This method returns the set time for the fermentation process (hour).
Definition at line 164 of file FedBatchFermenterProblem.cpp.
References finalTime.
double Flood::FedBatchFermenterProblem::getInitialCellMassConcentration (void)
This method returns the initial concentration of cell mass in the fermenter (gram/litre).
Definition at line 174 of file FedBatchFermenterProblem.cpp.
References initialCellMassConcentration.
double Flood::FedBatchFermenterProblem::getInitialSubstrateConcentration (void)
This method returns the initial concentration of substrate in the fermenter (gram/litre).
Definition at line 184 of file FedBatchFermenterProblem.cpp.
References initialSubstrateConcentration.
double Flood::FedBatchFermenterProblem::getInitialProductConcentration (void)
This method returns the initial concentration of product in the fermenter (gram/litre).
Definition at line 194 of file FedBatchFermenterProblem.cpp.
References initialProductConcentration.
double Flood::FedBatchFermenterProblem::getInitialBrothVolume (void)
This method returns the initial volume of culture medium in the fermenter (litre).
Definition at line 204 of file FedBatchFermenterProblem.cpp.
References initialBrothVolume.
double Flood::FedBatchFermenterProblem::getFermenterVolume (void)
This method returns the volume of the fermenter (litre).
Definition at line 214 of file FedBatchFermenterProblem.cpp.
References fermenterVolume.
double Flood::FedBatchFermenterProblem::getMinimumFeedRate (void)
This method returns the minimum feed rate (control action) to the fermenter (litre/hour).
Definition at line 224 of file FedBatchFermenterProblem.cpp.
References minimumFeedRate.
double Flood::FedBatchFermenterProblem::getMaximumFeedRate (void)
This method returns the maximum feed rate (control action) to the fermenter (litre/hour).
Definition at line 234 of file FedBatchFermenterProblem.cpp.
References maximumFeedRate.
double Flood::FedBatchFermenterProblem::getVolumeErrorWeight (void)
This method returns the weight for the final volume error term in the objective functional.
Definition at line 244 of file FedBatchFermenterProblem.cpp.
References volumeErrorWeight.
double Flood::FedBatchFermenterProblem::getYieldWeight (void)
This method returns the weight for the final yield term in the objective functional.
Definition at line 254 of file FedBatchFermenterProblem.cpp.
References yieldWeight.
double Flood::FedBatchFermenterProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the final volume error and yield.
Definition at line 265 of file FedBatchFermenterProblem.cpp.
References tolerance.
int Flood::FedBatchFermenterProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the final volume error and yield.
Definition at line 276 of file FedBatchFermenterProblem.cpp.
References initialSize.
void Flood::FedBatchFermenterProblem::setFinalTime (double newFinalTime)
This method sets a new final time for the fermentation process.
Parameters:
newFinalTime Final fermentation time.
Definition at line 288 of file FedBatchFermenterProblem.cpp.
References finalTime.
void Flood::FedBatchFermenterProblem::setInitialCellMassConcentration (double newInitialCellMassConcentration)
This method sets a new initial value for the cell mass concentration (state variable).
Parameters:
newInitialCellMassConcentration Initial cell mass concentration.
Definition at line 302 of file FedBatchFermenterProblem.cpp.
References initialCellMassConcentration.
void Flood::FedBatchFermenterProblem::setInitialSubstrateConcentration (double newInitialSubstrateConcentration)
This method sets a new initial value for the substrate concentration (state variable).
Parameters:
newInitialSubstrateConcentration Initial substrate concentration.
Definition at line 314 of file FedBatchFermenterProblem.cpp.
References initialSubstrateConcentration.
void Flood::FedBatchFermenterProblem::setInitialProductConcentration (double newInitialProductConcentration)
This method sets a new initial value for the ethanol concentration (state variable).
Parameters:
newInitialProductConcentration Initial product concentration.
Definition at line 326 of file FedBatchFermenterProblem.cpp.
References initialProductConcentration.
void Flood::FedBatchFermenterProblem::setInitialBrothVolume (double newInitialBrothVolume)
This method sets a new initial value for the broth volume (state variable).
Parameters:
newInitialBrothVolume Initial broth volume.
Definition at line 338 of file FedBatchFermenterProblem.cpp.
References initialBrothVolume.
void Flood::FedBatchFermenterProblem::setFermenterVolume (double newFermenterVolume)
This method sets a new value for the volume of the fermenter.
Parameters:
newFermenterVolume Fermenter volume.
Definition at line 350 of file FedBatchFermenterProblem.cpp.
References fermenterVolume.
void Flood::FedBatchFermenterProblem::setMinimumFeedRate (double newMinimumFeedRate)
This method sets a new minimum value for the feed rate to the fermenter. This is used as a lower bound for the control variable.
Parameters:
newMinimumFeedRate Minimum feed rate value.
Definition at line 363 of file FedBatchFermenterProblem.cpp.
References minimumFeedRate.
void Flood::FedBatchFermenterProblem::setMaximumFeedRate (double newMaximumFeedRate)
This method sets a new maximum value for the feed rate to the fermenter. This is used as an upper bound for the control variable.
Parameters:
newMaximumFeedRate Maximum feed rate value.
Definition at line 378 of file FedBatchFermenterProblem.cpp.
References maximumFeedRate.
void Flood::FedBatchFermenterProblem::setVolumeErrorWeight (double newVolumeErrorWeight)
This method sets a new value for the weight of the volume error term (constraint) in the objective functional expression.
Parameters:
newVolumeErrorWeight Volume error term weight value.
Definition at line 393 of file FedBatchFermenterProblem.cpp.
References volumeErrorWeight.
void Flood::FedBatchFermenterProblem::setYieldWeight (double newYieldWeight)
This method sets a new value for the weight of the yield term (objective) in the objective functional expression.
Parameters:
newYieldWeight Yield term weight value.
Definition at line 406 of file FedBatchFermenterProblem.cpp.
References yieldWeight.
void Flood::FedBatchFermenterProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the final volume error and yield. The tolerance of integration must be a small value greater than zero.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 420 of file FedBatchFermenterProblem.cpp.
References ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
void Flood::FedBatchFermenterProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the final volume error and yield. The initial size must be a big value greater than zero, otherwise resizing will be necessary.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 453 of file FedBatchFermenterProblem.cpp.
References initialSize, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setInitialSize().
double Flood::FedBatchFermenterProblem::getCellMassConcentrationDot (double time, double cellMassConcentration, double substrateConcentration, double productConcentration, double brothVolume)
This method depicts the state equation for the cell mass concentration in the fed batch fermenter problem. It returns the derivative of the cell mass concentration with respect to the time as a function of actual time, cell mass concentration, substrateConcentration, product concentration and broth volume.
Parameters:
time Actual time.
cellMassConcentration Actual cell mass concentration.
substrateConcentration Actual substrate concentraion.
productConcentration Actual product concentration.
brothVolume Actual broth volume.
Definition at line 519 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), getSpecificGrowthRate(), maximumFeedRate, minimumFeedRate, and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::FedBatchFermenterProblem::getSubstrateConcentrationDot (double time, double cellMassConcentration, double substrateConcentration, double productConcentration, double brothVolume)
This method depicts the state equation for the variable y2 in the fed batch fermenter problem. It returns the derivative of the variable y2 with respect to the time as a function of time, y1, y2, y3 and y4.
Parameters:
time Actual time.
cellMassConcentration Actual cell mass concentration.
substrateConcentration Actual substrate concentraion.
productConcentration Actual product concentration.
brothVolume Actual broth volume.
Definition at line 571 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), feedSubstrateConcentration, getSpecificGrowthRate(), maximumFeedRate, minimumFeedRate, Flood::ObjectiveFunctional::multilayerPerceptron, and yieldCoefficient.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::FedBatchFermenterProblem::getProductConcentrationDot (double time, double cellMassConcentration, double substrateConcentration, double productConcentration, double brothVolume)
This method depicts the state equation for the variable y3 in the fed batch fermenter problem. It returns the derivative of the variable y3 with respect to the time as a function of time, y1, y2, y3 and y4.
Parameters:
time Actual time.
cellMassConcentration Actual cell mass concentration.
substrateConcentration Actual substrate concentraion.
productConcentration Actual product concentration.
brothVolume Actual broth volume.
Definition at line 622 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), getSpecificProductivity(), maximumFeedRate, minimumFeedRate, and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::FedBatchFermenterProblem::getBrothVolumeDot (double time, double cellMassConcentration, double substrateConcentration, double productConcentration, double brothVolume)
This method depicts the state equation for the variable y4 in the fed batch fermenter problem. It returns the derivative of the variable y4 with respect to the time as a function of time, y1, y2, y3 and y4.
Parameters:
time Actual time.
cellMassConcentration Actual cell mass concentration.
substrateConcentration Actual substrate concentraion.
productConcentration Actual product concentration.
brothVolume Actual broth volume.
Definition at line 674 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), maximumFeedRate, minimumFeedRate, and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateEvaluation(), print(), and saveResults().
double Flood::FedBatchFermenterProblem::getSpecificGrowthRate (double productConcentration, double substrateConcentration)
This method returns the specific growth rate in the ferementer as a function of the product and substrate concentrations.
Parameters:
productConcentration Actual concentration of ethanol in the ferementer.
substrateConcentration Actual concentration of substrate in the ferementer.
Definition at line 472 of file FedBatchFermenterProblem.cpp.
References kineticConstantKp, kineticConstantKs, and kineticConstantMu0.
Referenced by getCellMassConcentrationDot(), getSubstrateConcentrationDot(), and saveResults().
double Flood::FedBatchFermenterProblem::getSpecificProductivity (double productConcentration, double substrateConcentration)
This method returns the specific productivity in the ferementer as a function of the product and substrate concentrations.
Parameters:
productConcentration Actual concentration of ethanol in the ferementer.
substrateConcentration Actual concentration of substrate in the ferementer.
Definition at line 493 of file FedBatchFermenterProblem.cpp.
References kineticConstantEta0, kineticConstantKpDash, and kineticConstantKsDash.
Referenced by getProductConcentrationDot(), and saveResults().
double Flood::FedBatchFermenterProblem::calculateEvaluation (void) [virtual]
This method returns the objective functional evaluation of a multilayer perceptron for the fed batch fermenter problem.
Implements Flood::ObjectiveFunctional.
Definition at line 715 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), fermenterVolume, finalTime, getBrothVolumeDot(), getCellMassConcentrationDot(), getProductConcentrationDot(), getSubstrateConcentrationDot(), initialBrothVolume, initialCellMassConcentration, initialProductConcentration, initialSubstrateConcentration, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, ordinaryDifferentialEquations, volumeErrorWeight, and yieldWeight.
void Flood::FedBatchFermenterProblem::print (void) [virtual]
This method prints to the screen useful information about the fed batch fermenter problem objective functional of a multilayer perceptron.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 935 of file FedBatchFermenterProblem.cpp.
References Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), fermenterVolume, finalTime, getBrothVolumeDot(), getCellMassConcentrationDot(), getProductConcentrationDot(), getSubstrateConcentrationDot(), initialBrothVolume, initialCellMassConcentration, initialProductConcentration, initialSubstrateConcentration, and ordinaryDifferentialEquations.
void Flood::FedBatchFermenterProblem::saveResults (char * filename)
This method saves the values of the independent and dependent variables for the brachistochrone problem to a data file.
Time.
Cell mass concentration value (state variable 1).
Substrate concentration value (state variable 2).
Product concentration value (state variable 3).
Broth volume value (state variabl 4).
Specific growth rate.
Specific productivity.
Feed rate (control variable).
Parameters:
filename Filename.
Definition at line 816 of file FedBatchFermenterProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), finalTime, getBrothVolumeDot(), getCellMassConcentrationDot(), getProductConcentrationDot(), getSpecificGrowthRate(), getSpecificProductivity(), getSubstrateConcentrationDot(), initialBrothVolume, initialCellMassConcentration, initialProductConcentration, initialSubstrateConcentration, maximumFeedRate, minimumFeedRate, Flood::ObjectiveFunctional::multilayerPerceptron, and ordinaryDifferentialEquations.
Member Data Documentation
double Flood::FedBatchFermenterProblem::finalTime [private]
Fermentation process time (hour).
Definition at line 44 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getFinalTime(), print(), saveResults(), and setFinalTime().
double Flood::FedBatchFermenterProblem::initialCellMassConcentration [private]
Initial concentration of cell mass in the fermenter (gram/litre).
Definition at line 48 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getInitialCellMassConcentration(), print(), saveResults(), and setInitialCellMassConcentration().
double Flood::FedBatchFermenterProblem::initialSubstrateConcentration [private]
Initial concentration of substrate in the fermenter (gram/litre).
Definition at line 52 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getInitialSubstrateConcentration(), print(), saveResults(), and setInitialSubstrateConcentration().
double Flood::FedBatchFermenterProblem::initialProductConcentration [private]
Initial concentration of product in the fermenter (gram/litre).
Definition at line 56 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getInitialProductConcentration(), print(), saveResults(), and setInitialProductConcentration().
double Flood::FedBatchFermenterProblem::initialBrothVolume [private]
Initial volume of culture medium in the fermenter (litre).
Definition at line 60 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getInitialBrothVolume(), print(), saveResults(), and setInitialBrothVolume().
double Flood::FedBatchFermenterProblem::fermenterVolume [private]
Volume of fermenter (litre).
Definition at line 64 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getFermenterVolume(), print(), and setFermenterVolume().
double Flood::FedBatchFermenterProblem::minimumFeedRate [private]
Minimum feed rate (control action) to the fermenter (litre/hour).
Definition at line 68 of file FedBatchFermenterProblem.h.
Referenced by FedBatchFermenterProblem(), getBrothVolumeDot(), getCellMassConcentrationDot(), getMinimumFeedRate(), getProductConcentrationDot(), getSubstrateConcentrationDot(), saveResults(), and setMinimumFeedRate().
double Flood::FedBatchFermenterProblem::maximumFeedRate [private]
Maximum feed rate (control action) to the fermenter (litre/hour).
Definition at line 72 of file FedBatchFermenterProblem.h.
Referenced by FedBatchFermenterProblem(), getBrothVolumeDot(), getCellMassConcentrationDot(), getMaximumFeedRate(), getProductConcentrationDot(), getSubstrateConcentrationDot(), saveResults(), and setMaximumFeedRate().
double Flood::FedBatchFermenterProblem::volumeErrorWeight [private]
Weight for the final volume error term in the objective functional.
Definition at line 76 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getVolumeErrorWeight(), and setVolumeErrorWeight().
double Flood::FedBatchFermenterProblem::yieldWeight [private]
Weight for the final yield term in the objective functional.
Definition at line 80 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), FedBatchFermenterProblem(), getYieldWeight(), and setYieldWeight().
double Flood::FedBatchFermenterProblem::yieldCoefficient [private]
Yield coefficient in the fermentation process (no units).
Definition at line 84 of file FedBatchFermenterProblem.h.
Referenced by getSubstrateConcentrationDot().
double Flood::FedBatchFermenterProblem::feedSubstrateConcentration [private]
Concentration of substrate in the feed to the fermenter (gram/litre).
Definition at line 88 of file FedBatchFermenterProblem.h.
Referenced by getSubstrateConcentrationDot().
double Flood::FedBatchFermenterProblem::kineticConstantMu0 [private]
Kinetic constant in the fementation process Mu0.
Definition at line 92 of file FedBatchFermenterProblem.h.
Referenced by getSpecificGrowthRate().
double Flood::FedBatchFermenterProblem::kineticConstantEta0 [private]
Kinetic constant in the fementation process Eta0.
Definition at line 96 of file FedBatchFermenterProblem.h.
Referenced by getSpecificProductivity().
double Flood::FedBatchFermenterProblem::kineticConstantKp [private]
Kinetic constant in the fementation process Kp.
Definition at line 100 of file FedBatchFermenterProblem.h.
Referenced by getSpecificGrowthRate().
double Flood::FedBatchFermenterProblem::kineticConstantKpDash [private]
Kinetic constant in the fementation process JpDash.
Definition at line 104 of file FedBatchFermenterProblem.h.
Referenced by getSpecificProductivity().
double Flood::FedBatchFermenterProblem::kineticConstantKs [private]
Kinetic constant in the fementation process Ks.
Definition at line 108 of file FedBatchFermenterProblem.h.
Referenced by getSpecificGrowthRate().
double Flood::FedBatchFermenterProblem::kineticConstantKsDash [private]
Kinetic constant in the fementation process KsDash.
Definition at line 112 of file FedBatchFermenterProblem.h.
Referenced by getSpecificProductivity().
OrdinaryDifferentialEquations Flood::FedBatchFermenterProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 116 of file FedBatchFermenterProblem.h.
Referenced by calculateEvaluation(), print(), saveResults(), setInitialSize(), and setTolerance().
double Flood::FedBatchFermenterProblem::tolerance [private]
Tolerance of integration in Runge-Kutta-Fehlberg method.
Definition at line 120 of file FedBatchFermenterProblem.h.
Referenced by FedBatchFermenterProblem(), getTolerance(), and setTolerance().
int Flood::FedBatchFermenterProblem::initialSize [private]
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Definition at line 124 of file FedBatchFermenterProblem.h.
Referenced by FedBatchFermenterProblem(), getInitialSize(), and setInitialSize().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/FedBatchFermenterProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/FedBatchFermenterProblem.cpp