Flood: Flood::SumSquaredError Class Reference
Flood::SumSquaredError Class Reference
#include <SumSquaredError.h>
Public Member Functions
SumSquaredError (MultilayerPerceptron *, InputTargetDataSet *)
SumSquaredError (void)
virtual ~SumSquaredError (void)
Destructor.
InputTargetDataSet * getInputTargetDataSet (void)
void setInputTargetDataSet (InputTargetDataSet *)
double calculateEvaluation (void)
Vector< double > calculateSquaredErrors (void)
Vector< double > calculateGradient (void)
Matrix< double > calculateJacobian (void)
Matrix< double > calculateJacobianTest (void)
void saveInputTargetAndOutput (char *)
Private Attributes
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
Detailed Description
This class represents the sum squared error objective functional of a multilayer perceptron. This objective functional is used in data modeling problems, such as function regression, pattern recognition or time series prediction.
See also:
MultilayerPerceptron.
InputTargetDataSet.
MeanSquaredError.
RootMeanSquaredError.
NormalizedSquaredError.
MinkowskiError.
RegularizedMeanSquaredError.
Definition at line 37 of file SumSquaredError.h.
Constructor & Destructor Documentation
Flood::SumSquaredError::SumSquaredError (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a sum squared error objective functional object associated to a multilayer perceptron and measured on an input-target data set. It also initializes all the rest of class members to their default values:
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Number of evaluations = 0.
Numerical epsilon: 1.0e-6.
Display = true.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 42 of file SumSquaredError.cpp.
References inputTargetDataSet.
Flood::SumSquaredError::SumSquaredError (void)
Default constructor. It creates a sum squared error objective functional object not associated to any multilayer perceptron and not measured on any input-target data set. It also initializes all the rest of class members to their default values:
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Number of evaluations = 0.
Numerical epsilon: 1.0e-6.
Display = true.
Definition at line 63 of file SumSquaredError.cpp.
References inputTargetDataSet.
Flood::SumSquaredError::~SumSquaredError (void) [virtual]
Destructor.
Definition at line 73 of file SumSquaredError.cpp.
Member Function Documentation
InputTargetDataSet * Flood::SumSquaredError::getInputTargetDataSet (void)
This method returns a pointer to the input-target data set object on which the objective functional is measured.
Definition at line 86 of file SumSquaredError.cpp.
References inputTargetDataSet.
void Flood::SumSquaredError::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a pointer to an input-data set object on which the objective functional is to be measured.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 98 of file SumSquaredError.cpp.
References inputTargetDataSet.
double Flood::SumSquaredError::calculateEvaluation (void) [virtual]
This method returns the objective functional value of a multilayer perceptron according to the sum squared error on an input-target data set.
See also:
calculateGradient(void).
Implements Flood::ObjectiveFunctional.
Definition at line 111 of file SumSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
Vector< double > Flood::SumSquaredError::calculateSquaredErrors (void)
This method returns a vector containing the squared error values between the outputs from the neural network and the targets in the data set. The size of this vector is the number of samples in the input-target data set.
Definition at line 794 of file SumSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateJacobianTest().
Vector< double > Flood::SumSquaredError::calculateGradient (void) [virtual]
This method returns the the sum squared error function gradient of a multilayer perceptron on an input-target data set. It uses the error back-propagation method.
See also:
calculateEvaluation(void).
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 207 of file SumSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer(), Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer(), Flood::MultilayerPerceptron::calculateOutputSignal(), Flood::MultilayerPerceptron::calculateOutputSignalDerivative(), Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer(), Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer(), Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::Matrix< Type >::getRow(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::MultilayerPerceptron::MeanAndStandardDeviation, Flood::MultilayerPerceptron::MinimumAndMaximum, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::MultilayerPerceptron::None, Flood::MultilayerPerceptron::postprocessOutputSignal(), Flood::MultilayerPerceptron::preprocessInput(), and Flood::Vector< Type >::setSize().
Matrix< double > Flood::SumSquaredError::calculateJacobian (void)
This method returns the Jacobian matrix of the sum squared error function, whose elements are given by the derivatives of the squared errors data set with respect to the neural parameters. The Jacobian matrix here is computed using numerical differentiation.
See also:
calculateJacobian(void).
Todo:
This method is not fully implemented, and it should be finished.
Definition at line 468 of file SumSquaredError.cpp.
References Flood::MultilayerPerceptron::getHiddenLayers(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getMaximumOfInputVariables(), Flood::MultilayerPerceptron::getMaximumOfOutputVariables(), Flood::MultilayerPerceptron::getMeanOfInputVariables(), Flood::MultilayerPerceptron::getMeanOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumOfInputVariables(), Flood::MultilayerPerceptron::getMinimumOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfHiddenLayers(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getOutputLayer(), Flood::MultilayerPerceptron::getPreAndPostProcessingMethod(), Flood::MultilayerPerceptron::getStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and Flood::ObjectiveFunctional::multilayerPerceptron.
Matrix< double > Flood::SumSquaredError::calculateJacobianTest (void)
This method returns the Jacobian matrix of the sum squared error function, whose elements are given by the derivatives of the squared errors data set with respect to the neural parameters. The Jacobian matrix here is computed using a back-propagation algorithm.
See also:
calculateJacobianTest(void).
Definition at line 689 of file SumSquaredError.cpp.
References calculateSquaredErrors(), Flood::ObjectiveFunctional::CentralDifferences, Flood::ObjectiveFunctional::ForwardDifferences, Flood::MultilayerPerceptron::getNeuralParameters(), Flood::MultilayerPerceptron::getNumberOfNeuralParameters(), Flood::InputTargetDataSet::getNumberOfSamples(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numericalDifferentiationMethod, Flood::ObjectiveFunctional::numericalEpsilon, and Flood::MultilayerPerceptron::setNeuralParameters().
void Flood::SumSquaredError::saveInputTargetAndOutput (char * filename)
This method saves to a data file the inputs and the targets in the input-target data set, together with the outputs from the multilayer perceptron for that inputs.
Parameters:
filename Filename.
Definition at line 856 of file SumSquaredError.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Member Data Documentation
InputTargetDataSet* Flood::SumSquaredError::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 44 of file SumSquaredError.h.
Referenced by calculateEvaluation(), calculateGradient(), calculateJacobian(), calculateJacobianTest(), calculateSquaredErrors(), getInputTargetDataSet(), saveInputTargetAndOutput(), setInputTargetDataSet(), and SumSquaredError().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/SumSquaredError.h
G:/Documents/Flood/Flood/ObjectiveFunctional/SumSquaredError.cpp