Flood: Flood::LinearRegressionAnalysis Class Reference
Flood::LinearRegressionAnalysis Class Reference
#include <LinearRegressionAnalysis.h>
Public Member Functions
LinearRegressionAnalysis (MultilayerPerceptron *, InputTargetDataSet *)
LinearRegressionAnalysis (void)
virtual ~LinearRegressionAnalysis ()
Destructor.
MultilayerPerceptron * getMultilayerPerceptron (void)
InputTargetDataSet * getInputTargetDataSet (void)
bool getDisplay (void)
void setMultilayerPerceptron (MultilayerPerceptron *)
void setInputTargetDataSet (InputTargetDataSet *)
void setDisplay (bool)
Matrix< double > getOutputData (void)
Matrix< double > calculateRegressionParameters (void)
void printResults (void)
void saveResults (char *)
Private Attributes
MultilayerPerceptron * multilayerPerceptron
Pointer to a multilayer perceptron object.
InputTargetDataSet * inputTargetDataSet
Pointer to an input-target data set object.
bool display
Display messages to screen.
Detailed Description
This class contains methods for performing linear regression analysis. This is a validation technique for data modeling problems which consists on performing a linear regression between the outputs from a multilayer perceptron and the corresponding targets from an input-target data set. Linear regression analysis leads to 3 parameters for each output variable. The first two, a and b, correspond to the y-intercept and the slope of the best linear regression relating network outputs to targets, that is, y = a + b*x. If we had a perfect fit (outputs exactly equal to targets), the y-intercept, a, would be 0 and the slope, b, would be 1. The third parameter is the correlation coefficient (R-value) between the outputs and the targets. If the correlation coefficient, R, is equal to 1, then there is perfect correlation.
See also:
MultilayerPerceptron
InputTargetDataSet
Definition at line 46 of file LinearRegressionAnalysis.h.
Constructor & Destructor Documentation
Flood::LinearRegressionAnalysis::LinearRegressionAnalysis (MultilayerPerceptron * newMultilayerPerceptron, InputTargetDataSet * newInputTargetDataSet)
General constructor. It creates a linear regression analysis object associated to a multilayer perceptron and an input-target data set objects. That multilayer perceptron is going to be validated on that input-target data set. This constructor also initializes the rest of class members to their default values:
Display: True.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 43 of file LinearRegressionAnalysis.cpp.
Flood::LinearRegressionAnalysis::LinearRegressionAnalysis (void)
Default constructor. It creates a linear regression analysis object not associated to any multilayer perceptron neither any input-target data set objects. This constructor also initializes the rest of class members to their default values:
Display: True.
Definition at line 64 of file LinearRegressionAnalysis.cpp.
References display, inputTargetDataSet, and multilayerPerceptron.
Flood::LinearRegressionAnalysis::~LinearRegressionAnalysis () [virtual]
Destructor.
Definition at line 78 of file LinearRegressionAnalysis.cpp.
Member Function Documentation
MultilayerPerceptron * Flood::LinearRegressionAnalysis::getMultilayerPerceptron (void)
This method returns a pointer to the multilayer perceptron object which is to be validated.
Definition at line 91 of file LinearRegressionAnalysis.cpp.
References multilayerPerceptron.
InputTargetDataSet * Flood::LinearRegressionAnalysis::getInputTargetDataSet (void)
This method returns a pointer to the input-target data set object used for validating the performance of a trained multilayer perceptron.
Definition at line 102 of file LinearRegressionAnalysis.cpp.
References inputTargetDataSet.
bool Flood::LinearRegressionAnalysis::getDisplay (void)
This method returns true if messages from this class can be displayed on the screen, or false if messages from this class can't be displayed on the screen.
Definition at line 113 of file LinearRegressionAnalysis.cpp.
References display.
void Flood::LinearRegressionAnalysis::setMultilayerPerceptron (MultilayerPerceptron * newMultilayerPerceptron)
This method sets a new multilayer perceptron which is to be validated.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 126 of file LinearRegressionAnalysis.cpp.
References multilayerPerceptron.
void Flood::LinearRegressionAnalysis::setInputTargetDataSet (InputTargetDataSet * newInputTargetDataSet)
This method sets a new input-target data set to be used for validating the quality of a trained multilayer perceptron.
Parameters:
newInputTargetDataSet Pointer to an input-target data set object.
Definition at line 140 of file LinearRegressionAnalysis.cpp.
References inputTargetDataSet.
void Flood::LinearRegressionAnalysis::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 154 of file LinearRegressionAnalysis.cpp.
References display.
Matrix< double > Flood::LinearRegressionAnalysis::getOutputData (void)
This method retuns a Matrix containing the neural network outputs for the input data set.
Definition at line 165 of file LinearRegressionAnalysis.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::InputTargetDataSet::getInputData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::InputTargetDataSet::getNumberOfInputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), Flood::InputTargetDataSet::getNumberOfTargetVariables(), Flood::Matrix< Type >::getRow(), inputTargetDataSet, multilayerPerceptron, and Flood::Matrix< Type >::setRow().
Referenced by calculateRegressionParameters(), printResults(), and saveResults().
Matrix< double > Flood::LinearRegressionAnalysis::calculateRegressionParameters (void)
This method performs a linear regression analysis between the neural network outputs and the corresponding data set targets and returns all the provided parameters in a single matrix. The number of rows in the matrix is equal to the number of output variables. The number of columns in the matrix is equal to the number of regression parameters (3). In this way, each row contains the regression parameters a, b and R of an output variable.
Definition at line 251 of file LinearRegressionAnalysis.cpp.
References Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), getOutputData(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
Referenced by printResults(), and saveResults().
void Flood::LinearRegressionAnalysis::printResults (void)
This method performs a linear regression analysis between the neural network outputs and the corresponding data set targets and then prints all results in the screen:
Regression parameters (a, b and R) for each output variable.
Target and output data for each output variable.
See also:
getSaveResults(char*).
Definition at line 382 of file LinearRegressionAnalysis.cpp.
References calculateRegressionParameters(), Flood::MultilayerPerceptron::getNameOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), getOutputData(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
void Flood::LinearRegressionAnalysis::saveResults (char * filename)
This method performs a linear regression analysis between the neural network outputs and the corresponding data set targets and then saves all results to a data file:
Regression parameters (a, b and R) for each output variable.
Target and output data for each output variable.
Parameters:
filename Filename.
See also:
printResults(char*).
Definition at line 450 of file LinearRegressionAnalysis.cpp.
References calculateRegressionParameters(), display, Flood::MultilayerPerceptron::getNameOfOutputVariables(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::InputTargetDataSet::getNumberOfSamples(), getOutputData(), Flood::InputTargetDataSet::getTargetData(), inputTargetDataSet, and multilayerPerceptron.
Member Data Documentation
MultilayerPerceptron* Flood::LinearRegressionAnalysis::multilayerPerceptron [private]
Pointer to a multilayer perceptron object.
Definition at line 55 of file LinearRegressionAnalysis.h.
Referenced by calculateRegressionParameters(), getMultilayerPerceptron(), getOutputData(), LinearRegressionAnalysis(), printResults(), saveResults(), and setMultilayerPerceptron().
InputTargetDataSet* Flood::LinearRegressionAnalysis::inputTargetDataSet [private]
Pointer to an input-target data set object.
Definition at line 59 of file LinearRegressionAnalysis.h.
Referenced by calculateRegressionParameters(), getInputTargetDataSet(), getOutputData(), LinearRegressionAnalysis(), printResults(), saveResults(), and setInputTargetDataSet().
bool Flood::LinearRegressionAnalysis::display [private]
Display messages to screen.
Definition at line 63 of file LinearRegressionAnalysis.h.
Referenced by getDisplay(), LinearRegressionAnalysis(), saveResults(), and setDisplay().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Utilities/LinearRegressionAnalysis.h
G:/Documents/Flood/Flood/Utilities/LinearRegressionAnalysis.cpp