Flood: Flood Namespace Reference
Flood Namespace Reference
Classes
class MultilayerPerceptron
class AircraftLandingProblem
class BrachistochroneProblem
class CarProblem
class CatenaryProblem
class DeJongFunction
class EasomFunction
class FedBatchFermenterProblem
class GeodesicProblem
class IsoperimetricProblem
class MeanSquaredError
class MinimumDragProblem
class MinkowskiError
class NormalizedSquaredError
class ObjectiveFunctional
class PlaneCylinder
class PrecipitateDissolutionModeling
class RastriginFunction
class RegularizedMinkowskiError
class RootMeanSquaredError
class RosenbrockFunction
class SumSquaredError
class Perceptron
This class represents the concept of perceptron neuron model.
class ConjugateGradient
class EvolutionaryAlgorithm
class GradientDescent
class NewtonMethod
class QuasiNewtonMethod
class RandomSearch
class TrainingAlgorithm
class CorrectPredictionsAnalysis
class InputTargetDataSet
class IntegrationOfFunctions
class LinearRegressionAnalysis
class Matrix
class OrdinaryDifferentialEquations
class Vector
Functions
template<typename Type>
std::istream & operator>> (std::istream &is, Matrix< Type > &m)
This method re-writes the input operator >> for the Vector template.
template<typename Type>
std::ostream & operator<< (std::ostream &os, Matrix< Type > &m)
This method re-writes the output operator << for the Vector template.
template<typename Type>
std::istream & operator>> (std::istream &is, Vector< Type > &v)
This method re-writes the input operator >> for the Vector template.
template<typename Type>
std::ostream & operator<< (std::ostream &os, Vector< Type > &v)
This method re-writes the output operator << for the Vector template.
Function Documentation
template<typename Type> std::ostream& Flood::operator<< (std::ostream & os, Vector< Type > & v) [inline]
This method re-writes the output operator << for the Vector template.
Definition at line 1002 of file Vector.h.
References Flood::Vector< Type >::size.
template<typename Type> std::ostream& Flood::operator<< (std::ostream & os, Matrix< Type > & m) [inline]
This method re-writes the output operator << for the Vector template.
Definition at line 1132 of file Matrix.h.
References Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> std::istream& Flood::operator>> (std::istream & is, Vector< Type > & v) [inline]
This method re-writes the input operator >> for the Vector template.
Definition at line 984 of file Vector.h.
References Flood::Vector< Type >::getSize(), and Flood::Vector< Type >::size.
template<typename Type> std::istream& Flood::operator>> (std::istream & is, Matrix< Type > & m) [inline]
This method re-writes the input operator >> for the Vector template.
Definition at line 1110 of file Matrix.h.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.