Flood: Flood::CatenaryProblem Class Reference
Flood::CatenaryProblem Class Reference
#include <CatenaryProblem.h>
Public Member Functions
CatenaryProblem (MultilayerPerceptron *)
CatenaryProblem (void)
virtual ~CatenaryProblem (void)
Destructor.
double getXA (void)
This method returns the x-value for the A point in the catenary problem.
double getYA (void)
This method returns the y-value for the A point in the catenary problem.
double getXB (void)
This method returns the x-value for the B point in the catenary problem.
double getYB (void)
This method returns the y-value for the B point in the catenary problem.
double getLengthGoal (void)
This method returns the chain length goal for the catenary problem.
double getPotentialEnergyWeight (void)
double getLengthErrorWeight (void)
double getTolerance (void)
int getInitialSize (void)
void setXA (double)
void setYA (double)
void setXB (double)
void setYB (double)
void setLengthGoal (double)
void setPotentialEnergyWeight (double)
void setLengthErrorWeight (double)
void setTolerance (double)
void setInitialSize (int)
Vector< double > calculateParticularSolution (Vector< double >)
Vector< double > calculateHomogeneousSolution (Vector< double >)
Vector< double > calculateParticularSolutionDerivative (Vector< double >)
Vector< double > calculateHomogeneousSolutionDerivative (Vector< double >)
double calculatePotentialEnergyIntegrand (double, double)
double calculatePotentialEnergy (void)
double calculateLengthIntegrand (double, double)
double calculateLength (void)
double calculateLengthError (void)
double calculateEvaluation (void)
This method returns the evaluation value of a multilayer perceptron for the catenary problem.
void print (void)
void saveResults (char *)
Private Attributes
double xA
Abscissa value for the A point.
double yA
Ordinate value for the A point.
double xB
Abscissa value for the B point.
double yB
Ordinate value for the B point.
double lengthGoal
Chain length goal.
double potentialEnergyWeight
Potential energy term weight in the objective functional.
double lengthErrorWeight
Chain length error term weight in the objective functional.
double tolerance
Tolerance in the Runge-Kutta-Fehlberg method.
int initialSize
Number of points to reserve for the Runge-Kutta-Fehlberg method.
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the catenary problem. This is a variational problem with one input and one output variables, two boundary conditions, and an objective functional with one constraint and requiring the integration of two functions.
See also:
ObjectiveFunctional.
Definition at line 31 of file CatenaryProblem.h.
Constructor & Destructor Documentation
Flood::CatenaryProblem::CatenaryProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a catenary problem objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
xA = 0.0.
yA = 1.0.
xB = 1.0.
yB = 1.0.
Length goal = 1.5.
Potential energy weight = 1.0.
Length error weight = 1.00.
Tolerance = 1.0e-15.
Initial size = 1e3.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 45 of file CatenaryProblem.cpp.
References Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), initialSize, lengthErrorWeight, lengthGoal, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, potentialEnergyWeight, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), tolerance, xA, xB, yA, and yB.
Flood::CatenaryProblem::CatenaryProblem (void)
Default constructor. It creates a catenary problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
xA = 0.0
yA = 1.0
xB = 1.0
yB = 1.0
Length goal = 1.5
Potential energy weight = 1.0
Length error weight = 1.00
Tolerance = 1.0e-15
Initial size = 1e3
Definition at line 99 of file CatenaryProblem.cpp.
References initialSize, lengthErrorWeight, lengthGoal, potentialEnergyWeight, tolerance, xA, xB, yA, and yB.
Flood::CatenaryProblem::~CatenaryProblem (void) [virtual]
Destructor.
Definition at line 120 of file CatenaryProblem.cpp.
Member Function Documentation
double Flood::CatenaryProblem::getXA (void)
This method returns the x-value for the A point in the catenary problem.
Definition at line 132 of file CatenaryProblem.cpp.
References xA.
double Flood::CatenaryProblem::getYA (void)
This method returns the y-value for the A point in the catenary problem.
Definition at line 142 of file CatenaryProblem.cpp.
References yA.
double Flood::CatenaryProblem::getXB (void)
This method returns the x-value for the B point in the catenary problem.
Definition at line 152 of file CatenaryProblem.cpp.
References xB.
double Flood::CatenaryProblem::getYB (void)
This method returns the y-value for the B point in the catenary problem.
Definition at line 162 of file CatenaryProblem.cpp.
References yB.
double Flood::CatenaryProblem::getLengthGoal (void)
This method returns the chain length goal for the catenary problem.
Definition at line 172 of file CatenaryProblem.cpp.
References lengthGoal.
double Flood::CatenaryProblem::getPotentialEnergyWeight (void)
This method returns the weight of the potential energy term in the objective functional expression.
Definition at line 194 of file CatenaryProblem.cpp.
References potentialEnergyWeight.
double Flood::CatenaryProblem::getLengthErrorWeight (void)
This method returns the weight of the chain length error term in the objective functional expression.
Definition at line 183 of file CatenaryProblem.cpp.
References lengthErrorWeight.
double Flood::CatenaryProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the chain lenght error and the potential energy.
Definition at line 205 of file CatenaryProblem.cpp.
References tolerance.
int Flood::CatenaryProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the chain lenght error and the potential energy.
Definition at line 216 of file CatenaryProblem.cpp.
References initialSize.
void Flood::CatenaryProblem::setXA (double newXA)
This method sets a new x-value for the A point in the catenary problem.
Parameters:
newXA xA value.
Definition at line 228 of file CatenaryProblem.cpp.
References xA.
void Flood::CatenaryProblem::setYA (double newYA)
This method sets a new y-value for the A point in the catenary problem.
Parameters:
newYA yA value.
Definition at line 242 of file CatenaryProblem.cpp.
References yA.
void Flood::CatenaryProblem::setXB (double newXB)
This method sets a new x-value for the B point in the catenary problem.
Parameters:
newXB xB value.
Definition at line 254 of file CatenaryProblem.cpp.
References xB.
void Flood::CatenaryProblem::setYB (double newYB)
This method sets a new y-value for the B point in the catenary problem.
Parameters:
newYB yB value.
Definition at line 268 of file CatenaryProblem.cpp.
References yB.
void Flood::CatenaryProblem::setLengthGoal (double newLengthGoal)
This method sets a new chain length goal for the catenary problem.
Parameters:
newLengthGoal Chain length goal.
Definition at line 280 of file CatenaryProblem.cpp.
References lengthGoal.
void Flood::CatenaryProblem::setPotentialEnergyWeight (double newPotentialEnergyWeight)
This method sets a new weight value for the chain length error term in the objective functional expression.
Parameters:
newPotentialEnergyWeight Potential energy weight value.
Definition at line 319 of file CatenaryProblem.cpp.
References potentialEnergyWeight.
void Flood::CatenaryProblem::setLengthErrorWeight (double newLengthErrorWeight)
This method sets a new weight value for the chain length error term in the objective functional expression.
Parameters:
newLengthErrorWeight Chain lenght error weight value.
Definition at line 292 of file CatenaryProblem.cpp.
References lengthErrorWeight.
void Flood::CatenaryProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the chain length and the potential energy.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 347 of file CatenaryProblem.cpp.
References ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
void Flood::CatenaryProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the chain length and the potential energy.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 377 of file CatenaryProblem.cpp.
References initialSize, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setInitialSize().
Vector< double > Flood::CatenaryProblem::calculateParticularSolution (Vector< double > input)
This method returns the particular solution term in order to satisfy the boundary conditions in the catenary problem. It holds phi0(a)=ya if there is a condition y(a)=ya.
Parameters:
input Value of independent variable x.
See also:
calculateHomogeneousSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 397 of file CatenaryProblem.cpp.
References Flood::Vector< Type >::getSize(), xA, xB, yA, and yB.
Vector< double > Flood::CatenaryProblem::calculateHomogeneousSolution (Vector< double > input)
This method returns the homogeneous solution term in order to satisfy the boundary conditions in the catenary problem. It must hold phi1(a)=0 if there is a condition y(a)=ya.
Parameters:
input Value of independent variable x.
See also:
calculateParticularSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 438 of file CatenaryProblem.cpp.
References Flood::Vector< Type >::getSize(), xA, and xB.
Vector< double > Flood::CatenaryProblem::calculateParticularSolutionDerivative (Vector< double > input)
This method returns the derivative of the particular solution term for the boundary conditions. It is used to calculate the derivative y'(x)=dy/dx.
Parameters:
input Value of independent variable x.
See also:
calculateParticularSolution.
calculateHomogeneousSolution.
calculateHomogeneousSolutionDerivative.
Definition at line 478 of file CatenaryProblem.cpp.
References Flood::Vector< Type >::getSize(), xA, xB, yA, and yB.
Vector< double > Flood::CatenaryProblem::calculateHomogeneousSolutionDerivative (Vector< double > input)
This method returns the derivative of the homogeneous solution term for the boundary conditions. It is used to calculate the derivative y'(x)=dy/dx.
Parameters:
input Value of independent variable x.
See also:
calculateParticularSolution.
calculateHomogeneousSolution.
calculateParticularSolutionDerivative.
Definition at line 516 of file CatenaryProblem.cpp.
References Flood::Vector< Type >::getSize(), xA, and xB.
double Flood::CatenaryProblem::calculatePotentialEnergyIntegrand (double x, double dummy)
This method returns the potential energy integrand for a value of x.
Parameters:
x Value of independent variable.
dummy Dummy variable to allow integration with Runge-Kutta-Fehlberg method.
See also:
calculatePotentialEnergy.
Definition at line 554 of file CatenaryProblem.cpp.
References Flood::MultilayerPerceptron::calculateJacobian(), Flood::MultilayerPerceptron::calculateOutput(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculatePotentialEnergy().
double Flood::CatenaryProblem::calculatePotentialEnergy (void)
This method integrates the potential energy integrand function to obtain the potential energy for the chain represented by the neural network. It uses the Runge-Kutta-Fehlberg method.
See also:
calculatePotentialEnergyIntegrand.
Definition at line 585 of file CatenaryProblem.cpp.
References calculatePotentialEnergyIntegrand(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), ordinaryDifferentialEquations, xA, and xB.
Referenced by calculateEvaluation(), and print().
double Flood::CatenaryProblem::calculateLengthIntegrand (double x, double dummy)
This method returns the chain length integrand for a value of x.
Parameters:
x Value of independent variable.
dummy Dummy variable to allow integration with Runge-Kutta-Fehlberg method.
See also:
calculateLength.
Definition at line 613 of file CatenaryProblem.cpp.
References Flood::MultilayerPerceptron::calculateJacobian(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateLength().
double Flood::CatenaryProblem::calculateLength (void)
This method integrates the length integrand function to obtain the chain length between xA and xB of the function represented by the neural network.
See also:
calculateLengthIntegrand.
Definition at line 636 of file CatenaryProblem.cpp.
References calculateLengthIntegrand(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), ordinaryDifferentialEquations, xA, and xB.
Referenced by calculateLengthError().
double Flood::CatenaryProblem::calculateLengthError (void)
This method returns the error between the length of the function addressed by the neural network and the length goal.
Definition at line 660 of file CatenaryProblem.cpp.
References calculateLength(), and lengthGoal.
Referenced by calculateEvaluation(), and print().
double Flood::CatenaryProblem::calculateEvaluation (void) [virtual]
This method returns the evaluation value of a multilayer perceptron for the catenary problem.
Implements Flood::ObjectiveFunctional.
Definition at line 676 of file CatenaryProblem.cpp.
References calculateLengthError(), calculatePotentialEnergy(), lengthErrorWeight, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and potentialEnergyWeight.
void Flood::CatenaryProblem::print (void) [virtual]
This method prints to the screen useful information about the catenary problem for the multilayer perceptron:
Length error.
Potential energy.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 717 of file CatenaryProblem.cpp.
References calculateLengthError(), and calculatePotentialEnergy().
void Flood::CatenaryProblem::saveResults (char * filename)
This method saves the values of the independent and dependent variables for the catenary problem to a data file.
Value of independent variariable (x).
Value of ependent variariable (y).
Parameters:
filename Filename.
Definition at line 739 of file CatenaryProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, and Flood::ObjectiveFunctional::multilayerPerceptron.
Member Data Documentation
double Flood::CatenaryProblem::xA [private]
Abscissa value for the A point.
Definition at line 38 of file CatenaryProblem.h.
Referenced by calculateHomogeneousSolution(), calculateHomogeneousSolutionDerivative(), calculateLength(), calculateParticularSolution(), calculateParticularSolutionDerivative(), calculatePotentialEnergy(), CatenaryProblem(), getXA(), and setXA().
double Flood::CatenaryProblem::yA [private]
Ordinate value for the A point.
Definition at line 42 of file CatenaryProblem.h.
Referenced by calculateParticularSolution(), calculateParticularSolutionDerivative(), CatenaryProblem(), getYA(), and setYA().
double Flood::CatenaryProblem::xB [private]
Abscissa value for the B point.
Definition at line 46 of file CatenaryProblem.h.
Referenced by calculateHomogeneousSolution(), calculateHomogeneousSolutionDerivative(), calculateLength(), calculateParticularSolution(), calculateParticularSolutionDerivative(), calculatePotentialEnergy(), CatenaryProblem(), getXB(), and setXB().
double Flood::CatenaryProblem::yB [private]
Ordinate value for the B point.
Definition at line 50 of file CatenaryProblem.h.
Referenced by calculateParticularSolution(), calculateParticularSolutionDerivative(), CatenaryProblem(), getYB(), and setYB().
double Flood::CatenaryProblem::lengthGoal [private]
Chain length goal.
Definition at line 54 of file CatenaryProblem.h.
Referenced by calculateLengthError(), CatenaryProblem(), getLengthGoal(), and setLengthGoal().
double Flood::CatenaryProblem::potentialEnergyWeight [private]
Potential energy term weight in the objective functional.
Definition at line 58 of file CatenaryProblem.h.
Referenced by calculateEvaluation(), CatenaryProblem(), getPotentialEnergyWeight(), and setPotentialEnergyWeight().
double Flood::CatenaryProblem::lengthErrorWeight [private]
Chain length error term weight in the objective functional.
Definition at line 62 of file CatenaryProblem.h.
Referenced by calculateEvaluation(), CatenaryProblem(), getLengthErrorWeight(), and setLengthErrorWeight().
double Flood::CatenaryProblem::tolerance [private]
Tolerance in the Runge-Kutta-Fehlberg method.
Definition at line 66 of file CatenaryProblem.h.
Referenced by CatenaryProblem(), getTolerance(), and setTolerance().
int Flood::CatenaryProblem::initialSize [private]
Number of points to reserve for the Runge-Kutta-Fehlberg method.
Definition at line 70 of file CatenaryProblem.h.
Referenced by CatenaryProblem(), getInitialSize(), and setInitialSize().
OrdinaryDifferentialEquations Flood::CatenaryProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 74 of file CatenaryProblem.h.
Referenced by calculateLength(), calculatePotentialEnergy(), CatenaryProblem(), setInitialSize(), and setTolerance().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/CatenaryProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/CatenaryProblem.cpp