Flood: Flood::MultilayerPerceptron Class Reference
Flood::MultilayerPerceptron Class Reference
#include <MultilayerPerceptron.h>
Public Types
enum PreAndPostProcessingMethod { None, MeanAndStandardDeviation, MinimumAndMaximum }
enum NumericalDifferentiationMethod { ForwardDifferences, CentralDifferences }
Public Member Functions
MultilayerPerceptron (int, int, int)
MultilayerPerceptron (int, Vector< int >, int)
MultilayerPerceptron (void)
~MultilayerPerceptron (void)
Destructor.
PreAndPostProcessingMethod getPreAndPostProcessingMethod (void)
NumericalDifferentiationMethod getNumericalDifferentiationMethod (void)
int getNumberOfInputs (void)
Vector< int > getNumbersOfHiddenNeurons (void)
int getNumberOfOutputs (void)
Vector
< Perceptron::ActivationFunction > getHiddenLayersActivationFunction (void)
Perceptron::ActivationFunction getOutputLayerActivationFunction (void)
Vector< Perceptron > & getHiddenLayer (void)
Vector< Vector< Perceptron > > & getHiddenLayers (void)
Vector< Perceptron > & getOutputLayer (void)
int getNumberOfHiddenLayers (void)
int getNumberOfNeuralParameters (void)
Vector< double > getNeuralParameters (void)
void setNeuralParameters (Vector< double >)
Vector< std::string > getNameOfInputVariables (void)
Vector< std::string > getNameOfOutputVariables (void)
std::string getNameOfSingleInputVariable (int)
std::string getNameOfSingleOutputVariable (int)
Vector< std::string > getUnitsOfInputVariables (void)
Vector< std::string > getUnitsOfOutputVariables (void)
std::string getUnitsOfSingleInputVariable (int)
std::string getUnitsOfSingleOutputVariable (int)
Vector< std::string > getDescriptionOfInputVariables (void)
Vector< std::string > getDescriptionOfOutputVariables (void)
std::string getDescriptionOfSingleInputVariable (int)
std::string getDescriptionOfSingleOutputVariable (int)
Vector< Vector< std::string > > getAllInformation (void)
Vector< double > getMeanOfInputVariables (void)
Vector< double > getStandardDeviationOfInputVariables (void)
Vector< double > getMeanOfOutputVariables (void)
Vector< double > getStandardDeviationOfOutputVariables (void)
Matrix< double > getMeanAndStandardDeviationOfInputVariables (void)
Matrix< double > getMeanAndStandardDeviationOfOutputVariables (void)
double getMeanOfSingleInputVariable (int)
double getStandardDeviationOfSingleInputVariable (int)
double getMeanOfSingleOutputVariable (int)
double getStandardDeviationOfSingleOutputVariable (int)
Vector< double > getMinimumOfInputVariables (void)
Vector< double > getMaximumOfInputVariables (void)
Vector< double > getMinimumOfOutputVariables (void)
Vector< double > getMaximumOfOutputVariables (void)
Matrix< double > getMinimumAndMaximumOfInputVariables (void)
Matrix< double > getMinimumAndMaximumOfOutputVariables (void)
double getMinimumOfSingleInputVariable (int)
double getMaximumOfSingleInputVariable (int)
double getMinimumOfSingleOutputVariable (int)
double getMaximumOfSingleOutputVariable (int)
Vector< Vector< double > > getAllStatistics (void)
Vector< double > getLowerBoundOfOutputVariables (void)
Vector< double > getUpperBoundOfOutputVariables (void)
Matrix< double > getLowerAndUpperBoundsOfOutputVariables (void)
double getLowerBoundOfSingleOutputVariable (int)
double getUpperBoundOfSingleOutputVariable (int)
int getNumberOfIndependentParameters (void)
Vector< double > scaleIndependentParameters (Vector< double >)
Vector< double > unscaleIndependentParameters (Vector< double >)
Vector< double > getIndependentParameters (void)
double getSingleIndependentParameter (int)
Vector< std::string > getNameOfIndependentParameters (void)
std::string getNameOfSingleIndependentParameter (int)
Vector< std::string > getUnitsOfIndependentParameters (void)
std::string getUnitsOfSingleIndependentParameter (int)
Vector< std::string > getDescriptionOfIndependentParameters (void)
std::string getDescriptionOfSingleIndependentParameter (int)
Vector< double > getMeanOfIndependentParameters (void)
Vector< double > getStandardDeviationOfIndependentParameters (void)
Matrix< double > getMeanAndStandardDeviationOfIndependentParameters (void)
double getMeanOfSingleIndependentParameter (int)
double getStandardDeviationOfSingleIndependentParameter (int)
Vector< double > getMinimumOfIndependentParameters (void)
Vector< double > getMaximumOfIndependentParameters (void)
Matrix< double > getMinimumAndMaximumOfIndependentParameters (void)
double getMinimumOfSingleIndependentParameter (int)
double getMaximumOfSingleIndependentParameter (int)
Vector< double > getLowerBoundOfIndependentParameters (void)
Vector< double > getUpperBoundOfIndependentParameters (void)
Matrix< double > getLowerAndUpperBoundsOfIndependentParameters (void)
double getLowerBoundOfSingleIndependentParameter (int)
double getUpperBoundOfSingleIndependentParameter (int)
double getNumericalEpsilon (void)
bool getDisplayOutOfRangeWarning (void)
bool getDisplay (void)
void setPreAndPostProcessingMethod (PreAndPostProcessingMethod)
void setNumericalDifferentiationMethod (NumericalDifferentiationMethod)
void setNetworkArchitecture (int, Vector< int >, int)
void setNumbersOfHiddenNeurons (Vector< int >)
void setHiddenLayersActivationFunction (Vector< Perceptron::ActivationFunction >)
void setOutputLayerActivationFunction (Perceptron::ActivationFunction)
void setNameOfInputVariables (Vector< std::string >)
void setNameOfOutputVariables (Vector< std::string >)
void setNameOfSingleInputVariable (int, std::string)
void setNameOfSingleOutputVariable (int, std::string)
void setUnitsOfInputVariables (Vector< std::string >)
void setUnitsOfOutputVariables (Vector< std::string >)
void setUnitsOfSingleInputVariable (int, std::string)
void setUnitsOfSingleOutputVariable (int, std::string)
void setDescriptionOfInputVariables (Vector< std::string >)
void setDescriptionOfOutputVariables (Vector< std::string >)
void setDescriptionOfSingleInputVariable (int, std::string)
void setDescriptionOfSingleOutputVariable (int, std::string)
void setAllInformation (Vector< Vector< std::string > >)
void setMeanOfInputVariables (Vector< double >)
void setStandardDeviationOfInputVariables (Vector< double >)
void setMeanOfOutputVariables (Vector< double >)
void setStandardDeviationOfOutputVariables (Vector< double >)
void setMeanAndStandardDeviationOfInputVariables (Matrix< double >)
void setMeanAndStandardDeviationOfOutputVariables (Matrix< double >)
void setMeanOfSingleInputVariable (int, double)
void setStandardDeviationOfSingleInputVariable (int, double)
void setMeanOfSingleOutputVariable (int, double)
void setStandardDeviationOfSingleOutputVariable (int, double)
void setMinimumOfInputVariables (Vector< double >)
void setMaximumOfInputVariables (Vector< double >)
void setMinimumOfOutputVariables (Vector< double >)
void setMaximumOfOutputVariables (Vector< double >)
void setMinimumAndMaximumOfInputVariables (Matrix< double >)
void setMinimumAndMaximumOfOutputVariables (Matrix< double >)
void setMinimumOfSingleInputVariable (int, double)
void setMaximumOfSingleInputVariable (int, double)
void setMinimumOfSingleOutputVariable (int, double)
void setMaximumOfSingleOutputVariable (int, double)
void setAllStatistics (Vector< Vector< double > >)
void setLowerBoundOfOutputVariables (Vector< double >)
void setUpperBoundOfOutputVariables (Vector< double >)
void setLowerAndUpperBoundsOfOutputVariables (Matrix< double >)
void setLowerBoundOfSingleOutputVariable (int, double)
void setUpperBoundOfSingleOutputVariable (int, double)
void setNumberOfIndependentParameters (int)
void setIndependentParameters (Vector< double >)
void setSingleIndependentParameter (int, double)
void setNameOfIndependentParameters (Vector< std::string >)
void setNameOfSingleIndependentParameter (int, std::string)
void setUnitsOfIndependentParameters (Vector< std::string >)
void setUnitsOfSingleIndependentParameter (int, std::string)
void setDescriptionOfIndependentParameters (Vector< std::string >)
void setDescriptionOfSingleIndependentParameter (int, std::string)
void setMeanOfIndependentParameters (Vector< double >)
void setStandardDeviationOfIndependentParameters (Vector< double >)
void setMeanAndStandardDeviationOfIndependentParameters (Matrix< double >)
void setMeanOfSingleIndependentParameter (int, double)
void setStandardDeviationOfSingleIndependentParameter (int, double)
void setMinimumOfIndependentParameters (Vector< double >)
void setMaximumOfIndependentParameters (Vector< double >)
void setMinimumAndMaximumOfIndependentParameters (Matrix< double >)
void setMinimumOfSingleIndependentParameter (int, double)
void setMaximumOfSingleIndependentParameter (int, double)
void setLowerBoundOfIndependentParameters (Vector< double >)
void setUpperBoundOfIndependentParameters (Vector< double >)
void setLowerAndUpperBoundsOfIndependentParameters (Matrix< double >)
void setLowerBoundOfSingleIndependentParameter (int, double)
void setUpperBoundOfSingleIndependentParameter (int, double)
void setDisplayOutOfRangeWarning (bool)
void setDisplay (bool)
void setNumericalEpsilon (double)
int getNumberOfFreeParameters (void)
Vector< double > getFreeParameters (void)
void setFreeParameters (Vector< double >)
void initNeuralParametersUniform (void)
void initNeuralParametersUniform (double, double)
void initNeuralParametersUniform (Vector< double >, Vector< double >)
void initNeuralParametersUniform (Matrix< double >)
void initNeuralParametersNormal (void)
void initNeuralParametersNormal (double, double)
void initNeuralParametersNormal (Vector< double >, Vector< double >)
void initNeuralParametersNormal (Matrix< double >)
void initIndependentParametersUniform (void)
void initIndependentParametersUniform (double, double)
void initIndependentParametersUniform (Vector< double >, Vector< double >)
void initIndependentParametersUniform (Matrix< double >)
void initIndependentParametersNormal (void)
void initIndependentParametersNormal (double, double)
void initIndependentParametersNormal (Vector< double >, Vector< double >)
void initIndependentParametersNormal (Matrix< double >)
void initFreeParametersUniform (void)
void initFreeParametersUniform (double, double)
void initFreeParametersUniform (Vector< double >, Vector< double >)
void initFreeParametersUniform (Matrix< double >)
void initFreeParametersNormal (void)
void initFreeParametersNormal (double, double)
void initFreeParametersNormal (Vector< double >, Vector< double >)
void initFreeParametersNormal (Matrix< double >)
void checkInput (Vector< double >)
Vector< double > preprocessInput (Vector< double >)
Vector< double > calculateNetInputSignalToHiddenLayer (int, Vector< double >)
Vector< double > calculateOutputSignalFromHiddenLayer (int, Vector< double >)
Vector< double > calculateOutputSignalDerivativeFromHiddenLayer (int, Vector< double >)
Vector< double > calculateNetInputSignalToOutputLayer (Vector< double >)
Vector< double > calculateOutputSignal (Vector< double >)
Vector< double > calculateOutputSignalDerivative (Vector< double >)
Vector< double > postprocessOutputSignal (Vector< double >)
Vector< double > applyLowerAndUpperBounds (Vector< double >)
Vector< double > calculateOutput (Vector< double >)
Matrix< double > calculateJacobian (Vector< double >)
Matrix< double > calculateJacobianTest (Vector< double >)
Matrix< double > calculateSensitivityTest (Vector< double >)
void print (void)
void save (char *)
void load (char *)
void saveExpression (char *)
template<class BoundaryConditionsType>
Vector< double > calculateOutput (Vector< double > input, BoundaryConditionsType &boundaryConditions)
template<class BoundaryConditionsType>
Matrix< double > calculateJacobian (Vector< double > input, BoundaryConditionsType &boundaryConditions)
Private Attributes
int numberOfInputs
Number of network inputs.
Vector< int > numbersOfHiddenNeurons
Number of neurons in the hidden layer of the neural network.
int numberOfOutputs
Number of output neurons in the neural network.
Vector
< Perceptron::ActivationFunction > hiddenLayersActivationFunction
Activation function of the hidden neurons.
Perceptron::ActivationFunction outputLayerActivationFunction
Activation function of the output neurons.
Vector< Vector< Perceptron > > hiddenLayers
Network's hidden layer. It is built as a Vector of perceptrons.
Vector< Perceptron > outputLayer
Network's output layer. It is built as a Vector of perceptrons.
Vector< std::string > nameOfInputVariables
Name of input variables.
Vector< std::string > nameOfOutputVariables
Name of output variables.
Vector< std::string > unitsOfInputVariables
Units of input variables.
Vector< std::string > unitsOfOutputVariables
Units of output variables.
Vector< std::string > descriptionOfInputVariables
Description of input variables.
Vector< std::string > descriptionOfOutputVariables
Description of output variables.
Vector< double > meanOfInputVariables
Mean of input variables.
Vector< double > standardDeviationOfInputVariables
Standard deviation of input variables.
Vector< double > meanOfOutputVariables
Mean of output variables.
Vector< double > standardDeviationOfOutputVariables
Standard deviation of output variables.
Vector< double > minimumOfInputVariables
Minimum of input variables.
Vector< double > maximumOfInputVariables
Maximum of input variables.
Vector< double > minimumOfOutputVariables
Minimum of output variables.
Vector< double > maximumOfOutputVariables
Maximum of output variables.
Vector< double > lowerBoundOfOutputVariables
Lower bound of output variables.
Vector< double > upperBoundOfOutputVariables
Upper bound of output variables.
int numberOfIndependentParameters
Number of independent parameters.
Vector< double > independentParameters
Independent parameters.
Vector< std::string > nameOfIndependentParameters
Name of independent parameters.
Vector< std::string > unitsOfIndependentParameters
Units of independent parameters.
Vector< std::string > descriptionOfIndependentParameters
Description of independent parameters.
Vector< double > meanOfIndependentParameters
Mean of independent parameters.
Vector< double > standardDeviationOfIndependentParameters
Standard deviation of independent parameters.
Vector< double > minimumOfIndependentParameters
Minimum of independent parameters.
Vector< double > maximumOfIndependentParameters
Maximum of independent parameters.
Vector< double > lowerBoundOfIndependentParameters
Lower bound of independent parameters.
Vector< double > upperBoundOfIndependentParameters
Upper bound of independent parameters.
double numericalEpsilon
bool displayOutOfRangeWarning
Display warning messages when inputs are out of the range defined by minimums and maximums.
bool display
Display messages to screen.
PreAndPostProcessingMethod preAndPostProcessingMethod
Pre and post-processing method variable.
NumericalDifferentiationMethod numericalDifferentiationMethod
Numerical differentiation method variable.
Detailed Description
This class represents the concept of multilayer perceptron with a hidden layer and an output layer of perceptron neuron models.
See also:
Perceptron.
Definition at line 34 of file MultilayerPerceptron.h.
Member Enumeration Documentation
enum Flood::MultilayerPerceptron::PreAndPostProcessingMethod
Enumeration of available methods for pre-processing network inputs and post-processing network outputs.
Enumerator:
None
MeanAndStandardDeviation
MinimumAndMaximum
Definition at line 43 of file MultilayerPerceptron.h.
enum Flood::MultilayerPerceptron::NumericalDifferentiationMethod
Enumeration of available methods for calculating the Jacobian matrix of the multilayer perceptron numerically.
Enumerator:
ForwardDifferences
CentralDifferences
Definition at line 48 of file MultilayerPerceptron.h.
Constructor & Destructor Documentation
Flood::MultilayerPerceptron::MultilayerPerceptron (int newNumberOfInputs, int newNumberOfHiddenNeurons, int newNumberOfOutputs)
General constructor. It creates a multilayer perceptron object with one hidden layer and an output layer of neurons. All the free parameters in the neural network are initialized with random values chosen from a normal distribution with mean zero and standard deviation. This constructor also initializes the rest of class members to their default values:
Hidden layer activation function: Hyperbolic tangent.
Output layer activation function: Linear.
Name of input vaviables: "InputVariable0",...
Name of output variables: "OutputVariable0",...
Units of input vaviables: "None".
Units of output variables: "None".
Description of input vaviables: "None".
Description of output variables: "None".
Mean of input variables: 0.
Standard deviation of input variables: 1.
Mean of output variables: 0.
Standard deviation of output variables: 1.
Minimum of input variables: -Inf.
Maximum of input variables: +Inf.
Minimum of output variables: -Inf.
Maximum of output variables: +Inf.
Lower bound of output variables: -Inf.
Upper bound of output variables: +Inf.
Number of independent parameters: 0.
Pre and post-processing method: None.
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Display out of range warning: False.
Display: True.
Numerical epsilon: 1.0e-6.
Parameters:
newNumberOfInputs Number of inputs in the neural network.
newNumberOfHiddenNeurons Number of neurons in the hidden layer.
newNumberOfOutputs Number of output neurons in the neural network.
Definition at line 68 of file MultilayerPerceptron.cpp.
Flood::MultilayerPerceptron::MultilayerPerceptron (int newNumberOfInputs, Vector< int > newNumbersOfHiddenNeurons, int newNumberOfOutputs)
Definition at line 103 of file MultilayerPerceptron.cpp.
Flood::MultilayerPerceptron::MultilayerPerceptron (void)
Default constructor. It creates a multilayer perceptron object with zero inputs, zero neurons in the hidden layer and zero output neurons. It also initializes the rest of class members to their default values:
Hidden layer activation function: Hyperbolic tangent.
Output layer activation function: Linear.
Number of independent parameters: 0.
Pre and post-processing method: None.
Numerical epsilon method: Relative.
Numerical differentiation method: Central differences.
Display out of range warning: False.
Display: True.
Numerical epsilon: 1.0e-6.
Definition at line 153 of file MultilayerPerceptron.cpp.
References CentralDifferences, display, displayOutOfRangeWarning, Flood::Perceptron::Linear, None, numberOfIndependentParameters, numberOfInputs, numberOfOutputs, numericalDifferentiationMethod, numericalEpsilon, outputLayerActivationFunction, and preAndPostProcessingMethod.
Flood::MultilayerPerceptron::~MultilayerPerceptron (void)
Destructor.
Definition at line 195 of file MultilayerPerceptron.cpp.
Member Function Documentation
MultilayerPerceptron::PreAndPostProcessingMethod Flood::MultilayerPerceptron::getPreAndPostProcessingMethod (void)
This method returns the method used for pre-processing network inputs and post-processing network outputs.
See also:
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
calculateOutput(Vector<double>).
calculateJacobian(Vector<double>).
Definition at line 212 of file MultilayerPerceptron.cpp.
References preAndPostProcessingMethod.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
MultilayerPerceptron::NumericalDifferentiationMethod Flood::MultilayerPerceptron::getNumericalDifferentiationMethod (void)
This method returns the method used for numerical differentiation in order to calculate the Jacobian matrix for the multilayer perceptron.
See also:
calculateJacobianTest(Vector<double>).
Definition at line 225 of file MultilayerPerceptron.cpp.
References numericalDifferentiationMethod.
int Flood::MultilayerPerceptron::getNumberOfInputs (void)
This method returns the number of inputs in the neural network.
See also:
getNumbersOfHiddenNeurons(void).
getNumberOfOutputs(void).
Definition at line 238 of file MultilayerPerceptron.cpp.
References numberOfInputs.
Referenced by Flood::AircraftLandingProblem::AircraftLandingProblem(), Flood::BrachistochroneProblem::BrachistochroneProblem(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::CarProblem::CarProblem(), Flood::CatenaryProblem::CatenaryProblem(), Flood::DeJongFunction::DeJongFunction(), Flood::EasomFunction::EasomFunction(), Flood::GeodesicProblem::GeodesicProblem(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::IsoperimetricProblem::IsoperimetricProblem(), Flood::MinimumDragProblem::MinimumDragProblem(), Flood::PlaneCylinder::PlaneCylinder(), Flood::PrecipitateDissolutionModeling::PrecipitateDissolutionModeling(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
Vector< int > Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons (void)
This method returns the number of neurons in the hidden layer of the neural network.
See also:
getNumberOfInputs(void).
getNumberOfOutputs(void).
Definition at line 251 of file MultilayerPerceptron.cpp.
References numbersOfHiddenNeurons.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
int Flood::MultilayerPerceptron::getNumberOfOutputs (void)
This method returns the number of neurons in the output layer of the neural network.
See also:
getNumberOfInputs(void).
getNumberOfHiddenNeurons(void).
Definition at line 264 of file MultilayerPerceptron.cpp.
References numberOfOutputs.
Referenced by Flood::AircraftLandingProblem::AircraftLandingProblem(), Flood::BrachistochroneProblem::BrachistochroneProblem(), Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::LinearRegressionAnalysis::calculateRegressionParameters(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::CarProblem::CarProblem(), Flood::CatenaryProblem::CatenaryProblem(), Flood::DeJongFunction::DeJongFunction(), Flood::EasomFunction::EasomFunction(), Flood::GeodesicProblem::GeodesicProblem(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::IsoperimetricProblem::IsoperimetricProblem(), Flood::MinimumDragProblem::MinimumDragProblem(), Flood::PlaneCylinder::PlaneCylinder(), Flood::PrecipitateDissolutionModeling::PrecipitateDissolutionModeling(), Flood::LinearRegressionAnalysis::printResults(), Flood::CorrectPredictionsAnalysis::printResults(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), Flood::LinearRegressionAnalysis::saveResults(), Flood::CorrectPredictionsAnalysis::saveResults(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
Vector< Perceptron::ActivationFunction > Flood::MultilayerPerceptron::getHiddenLayersActivationFunction (void)
This method returns the activation function of the perceptron neurons of the hidden layer.
See also:
getOutputLayerActivationFunction(void).
Definition at line 276 of file MultilayerPerceptron.cpp.
References hiddenLayersActivationFunction.
Perceptron::ActivationFunction Flood::MultilayerPerceptron::getOutputLayerActivationFunction (void)
This method returns the activation function of the perceptron neurons of the output layer.
See also:
getHiddenLayerActivationFunction(void).
Definition at line 288 of file MultilayerPerceptron.cpp.
References outputLayerActivationFunction.
Vector<Perceptron>& Flood::MultilayerPerceptron::getHiddenLayer (void)
Vector< Vector< Perceptron > > & Flood::MultilayerPerceptron::getHiddenLayers (void)
This method returns the Vector of neurons in the hidden layer.
See also:
getOutputLayer(void).
Definition at line 300 of file MultilayerPerceptron.cpp.
References hiddenLayers.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
Vector< Perceptron > & Flood::MultilayerPerceptron::getOutputLayer (void)
This method returns the Vector of output neurons.
See also:
getHiddenLayer(void).
Definition at line 312 of file MultilayerPerceptron.cpp.
References outputLayer.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
int Flood::MultilayerPerceptron::getNumberOfHiddenLayers (void)
Definition at line 5545 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), and numbersOfHiddenNeurons.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), calculateJacobian(), calculateJacobianTest(), calculateOutput(), calculateSensitivityTest(), getNeuralParameters(), getNumberOfNeuralParameters(), setNetworkArchitecture(), and setNeuralParameters().
int Flood::MultilayerPerceptron::getNumberOfNeuralParameters (void)
This method returns the number of biases and synaptic weights in the neural network.
See also:
getNumberOfIndependentParameters(void).
getNumberOfFreeParameters(void).
Definition at line 5560 of file MultilayerPerceptron.cpp.
References getNumberOfHiddenLayers(), hiddenLayers, numberOfOutputs, numbersOfHiddenNeurons, and outputLayer.
Referenced by Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateJacobian(), Flood::SumSquaredError::calculateJacobianTest(), calculateSensitivityTest(), getNeuralParameters(), getNumberOfFreeParameters(), initNeuralParametersNormal(), initNeuralParametersUniform(), setFreeParameters(), and setNeuralParameters().
Vector< double > Flood::MultilayerPerceptron::getNeuralParameters (void)
This method returns the values of all the biases and synaptic weights in the neural network as a single vector.
See also:
getIndependentParameters(void).
getFreeParameters(void).
Definition at line 5615 of file MultilayerPerceptron.cpp.
References getNumberOfHiddenLayers(), getNumberOfNeuralParameters(), hiddenLayers, Flood::Vector< Type >::insert(), numberOfOutputs, numbersOfHiddenNeurons, and outputLayer.
Referenced by Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::PrecipitateDissolutionModeling::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::SumSquaredError::calculateJacobianTest(), calculateSensitivityTest(), and getFreeParameters().
void Flood::MultilayerPerceptron::setNeuralParameters (Vector< double > newNeuralParameters)
This method sets all the biases and synaptic weights in the neural network from a single vector.
Parameters:
newNeuralParameters New set of biases and synaptic weights values.
Definition at line 5683 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::extract(), getNumberOfHiddenLayers(), getNumberOfNeuralParameters(), Flood::Vector< Type >::getSize(), hiddenLayers, numberOfOutputs, numbersOfHiddenNeurons, and outputLayer.
Referenced by Flood::SumSquaredError::calculateJacobianTest(), calculateSensitivityTest(), initNeuralParametersNormal(), initNeuralParametersUniform(), and setFreeParameters().
Vector< std::string > Flood::MultilayerPerceptron::getNameOfInputVariables (void)
This method returns the names of the input variables of the neural network. Such names are only used to give the user basic information about the problem at hand.
See also:
getNameOfOutputVariables(void).
getNameOfSingleInputVariable(int).
getNameOfSingleOutputVariable(int).
Definition at line 327 of file MultilayerPerceptron.cpp.
References nameOfInputVariables.
Vector< std::string > Flood::MultilayerPerceptron::getNameOfOutputVariables (void)
This method returns the names of the output variables of the neural network. Such names are only used to give the user basic information about the problem at hand.
See also:
getNameOfInputVariables(void).
getNameOfSingleInputVariable(int).
getNameOfSingleOutputVariable(int).
Definition at line 342 of file MultilayerPerceptron.cpp.
References nameOfOutputVariables.
Referenced by Flood::LinearRegressionAnalysis::printResults(), Flood::CorrectPredictionsAnalysis::printResults(), Flood::LinearRegressionAnalysis::saveResults(), and Flood::CorrectPredictionsAnalysis::saveResults().
std::string Flood::MultilayerPerceptron::getNameOfSingleInputVariable (int i)
This method returns the name of a single input variable of the neural network. Such a name is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getNameOfInputVariables(void).
getNameOfOutputVariables(void).
getNameOfSingleOutputVariable(int).
Definition at line 359 of file MultilayerPerceptron.cpp.
References nameOfInputVariables, and numberOfInputs.
std::string Flood::MultilayerPerceptron::getNameOfSingleOutputVariable (int i)
This method returns the name of a single output variable of the neural network. Such a name is only used to give the user basic information about the problem at hand.
Parameters:
i Index of output variable.
See also:
getNameOfInputVariables(void).
getNameOfOutputVariables(void).
getNameOfSingleInputVariable(int).
Definition at line 393 of file MultilayerPerceptron.cpp.
References nameOfOutputVariables, and numberOfOutputs.
Vector< std::string > Flood::MultilayerPerceptron::getUnitsOfInputVariables (void)
This method returns the units of the input variables of the neural network as strings. Such units are only used to give the user basic information about the problem at hand.
See also:
getUnitsOfOutputVariables(void).
getUnitsOfSingleInputVariable(int).
getUnitsOfSingleOutputVariable(int).
Definition at line 425 of file MultilayerPerceptron.cpp.
References unitsOfInputVariables.
Vector< std::string > Flood::MultilayerPerceptron::getUnitsOfOutputVariables (void)
This method returns the units of the output variables of the neural network as strings. Such units are only used to give the user basic information about the problem at hand.
See also:
getUnitsOfInputVariables(void).
getUnitsOfSingleInputVariable(int).
getUnitsOfSingleOutputVariable(int).
Definition at line 440 of file MultilayerPerceptron.cpp.
References unitsOfOutputVariables.
std::string Flood::MultilayerPerceptron::getUnitsOfSingleInputVariable (int i)
This method returns the units of a single input variable as a string. Such units are only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getUnitsOfInputVariables(void).
getUnitsOfOutputVariables(void).
getUnitsOfSingleOutputVariable(int).
Definition at line 457 of file MultilayerPerceptron.cpp.
References numberOfInputs, and unitsOfInputVariables.
std::string Flood::MultilayerPerceptron::getUnitsOfSingleOutputVariable (int i)
This method returns the units of a single output variable as a string. Such units are only used to give the user basic information about the problem at hand.
Parameters:
i Index of output variable.
See also:
getUnitsOfInputVariables(void).
getUnitsOfOutputVariables(void).
getUnitsOfSingleInputVariable(int).
Definition at line 491 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and unitsOfOutputVariables.
Vector< std::string > Flood::MultilayerPerceptron::getDescriptionOfInputVariables (void)
This method returns the description of the input variables of the neural network as strings. Such descriptions are only used to give the user basic information about the problem at hand.
See also:
getDescriptionOfOutputVariables(void).
getDescriptionOfSingleInputVariable(int).
getDescriptionOfSingleOutputVariable(int).
Definition at line 523 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables.
Vector< std::string > Flood::MultilayerPerceptron::getDescriptionOfOutputVariables (void)
This method returns the description of the output variables of the neural network as strings. Such descriptions are only used to give the user basic information about the problem at hand.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfSingleInputVariable(int).
getDescriptionOfSingleOutputVariable(int).
Definition at line 538 of file MultilayerPerceptron.cpp.
References descriptionOfOutputVariables.
std::string Flood::MultilayerPerceptron::getDescriptionOfSingleInputVariable (int i)
This method returns the description of a single input variable as a string. Such a description is only used to give the user basic information about the problem at hand.
Parameters:
i Index of input variable.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfOutputVariables(void).
getDescriptionOfSingleOutputVariable(int).
Definition at line 555 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables, and numberOfInputs.
std::string Flood::MultilayerPerceptron::getDescriptionOfSingleOutputVariable (int i)
This method returns the description of a single input variable as a string. Such a description is only used to give the user basic information about the problem at hand.
Parameters:
i Index of output variable.
See also:
getDescriptionOfInputVariables(void).
getDescriptionOfOutputVariables(void).
getDescriptionOfSingleInputVariable(int).
Definition at line 589 of file MultilayerPerceptron.cpp.
References descriptionOfOutputVariables, and numberOfOutputs.
Vector< Vector< std::string > > Flood::MultilayerPerceptron::getAllInformation (void)
Definition at line 614 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables, descriptionOfOutputVariables, nameOfInputVariables, nameOfOutputVariables, unitsOfInputVariables, and unitsOfOutputVariables.
Vector< double > Flood::MultilayerPerceptron::getMeanOfInputVariables (void)
This method returns the mean values of all the input variables of the neural network. Such values are to be used for preprocessing inputs with the mean and standard deviation method.
See also:
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 649 of file MultilayerPerceptron.cpp.
References meanOfInputVariables.
Referenced by Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getStandardDeviationOfInputVariables (void)
This method returns the standard deviation values of all the input variables of the neural network. Such values are to be used for preprocessing inputs with the mean and standard deviation method.
See also:
getMeanOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 673 of file MultilayerPerceptron.cpp.
References standardDeviationOfInputVariables.
Referenced by Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getMeanOfOutputVariables (void)
This method returns the mean values of all the output variables of the neural network. Such values are to be used for postprocessing output signals with the mean and standard deviation method.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 728 of file MultilayerPerceptron.cpp.
References meanOfOutputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getStandardDeviationOfOutputVariables (void)
This method returns the standard deviation values of all the output variables of the neural network. Such values are to be used for postprocessing output signals with the mean and standard deviation method.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 752 of file MultilayerPerceptron.cpp.
References standardDeviationOfOutputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
Matrix< double > Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfInputVariables (void)
This method returns the mean and the standard deviation values of all the input variables in a single matrix. The first row contains the mean values of the input variables. The second row contains the standard deviation values of the input variables. Such values are to be used for preprocessing inputs with the mean and standard deviation method.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 699 of file MultilayerPerceptron.cpp.
References meanOfInputVariables, numberOfInputs, Flood::Matrix< Type >::setRow(), and standardDeviationOfInputVariables.
Matrix< double > Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfOutputVariables (void)
This method returns the mean and the standard deviation values of all the output variables in a single matrix. The first row contains the mean values of the output variables. The second row contains the standard deviation values of the output variables. Such values are to be used for postprocessing output signals with the mean and standard deviation method.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 778 of file MultilayerPerceptron.cpp.
References meanOfOutputVariables, numberOfOutputs, Flood::Matrix< Type >::setRow(), and standardDeviationOfOutputVariables.
double Flood::MultilayerPerceptron::getMeanOfSingleInputVariable (int i)
This method returns the mean value of a single input variable of the neural network. Such a value is to be used for preprocessing that input with the mean and standard deviation method.
Parameters:
i Index of input variable.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 809 of file MultilayerPerceptron.cpp.
References meanOfInputVariables, and numberOfInputs.
double Flood::MultilayerPerceptron::getStandardDeviationOfSingleInputVariable (int i)
This method returns the standard deviation value of a single input variable of the neural network. Such a value is to be used for preprocessing that input with the mean and standard deviation method.
Parameters:
i Index of input variable.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 862 of file MultilayerPerceptron.cpp.
References numberOfInputs, and standardDeviationOfInputVariables.
double Flood::MultilayerPerceptron::getMeanOfSingleOutputVariable (int i)
This method returns the mean values of a single input variable of the neural network. Such a values is to be used for preprocessing inputs and postprocessing output signals with the mean and standard deviation method.
Parameters:
i Index of output variable.
See also:
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
getStandardDeviationOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 916 of file MultilayerPerceptron.cpp.
References meanOfOutputVariables, and numberOfOutputs.
double Flood::MultilayerPerceptron::getStandardDeviationOfSingleOutputVariable (int i)
This method returns the standard deviation value of a single output variable of the neural network. Such a value is to be used for postprocessing output signals with the mean and standard deviation method.
Parameters:
i Index of output variable.
See also:
getMeanOfInputVariables(void).
getStandardDeviationOfInputVariables(void).
getMeanOfOutputVariables(void).
getStandardDeviationOfOutputVariables(void).
getMeanAndStandardDeviationOfInputVariables(void).
getMeanAndStandardDeviationOfOutputVariables(void).
getMeanOfSingleInputVariable(int).
getStandardDeviationOfSingleInputVariable(int).
getMeanOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 969 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and standardDeviationOfOutputVariables.
Vector< double > Flood::MultilayerPerceptron::getMinimumOfInputVariables (void)
This method returns the minimum values of all the input variables in the neural network. Such values are to be used for preprocessing inputs with the minimum and maximum method.
See also:
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1020 of file MultilayerPerceptron.cpp.
References minimumOfInputVariables.
Referenced by Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getMaximumOfInputVariables (void)
This method returns the maximum values of all the input variables in the neural network. Such values are to be used for preprocessing inputs with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1044 of file MultilayerPerceptron.cpp.
References maximumOfInputVariables.
Referenced by Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getMinimumOfOutputVariables (void)
This method returns the minimum values of all the output variables in the neural network. Such values are to be used for postprocessing output signals with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1068 of file MultilayerPerceptron.cpp.
References minimumOfOutputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::getMaximumOfOutputVariables (void)
This method returns the maximum values of all the output variables in the neural network. Such values are to be used for postprocessing output signals with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1092 of file MultilayerPerceptron.cpp.
References maximumOfOutputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and Flood::SumSquaredError::calculateJacobian().
Matrix< double > Flood::MultilayerPerceptron::getMinimumAndMaximumOfInputVariables (void)
This method returns the minimum and the maximum values of all the input variables in a single matrix. The first row contains the minimum values of the input variables. The second row contains the maximum values of the input variables. Such values are to be used for preprocessing inputs with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1118 of file MultilayerPerceptron.cpp.
References maximumOfInputVariables, minimumOfInputVariables, numberOfInputs, and Flood::Matrix< Type >::setRow().
Matrix< double > Flood::MultilayerPerceptron::getMinimumAndMaximumOfOutputVariables (void)
This method returns the minimum and the maximum values of all the output variables in a single matrix. The first row contains the minimum values of the output variables. The second row contains the maximum values of the output variables. Such values are to be used for postprocessing output signals with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1149 of file MultilayerPerceptron.cpp.
References maximumOfOutputVariables, minimumOfOutputVariables, numberOfOutputs, and Flood::Matrix< Type >::setRow().
double Flood::MultilayerPerceptron::getMinimumOfSingleInputVariable (int i)
This method returns the minimum value of a single input variable in the neural network. Such value is to be used for preprocessing that input with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1178 of file MultilayerPerceptron.cpp.
References minimumOfInputVariables, and numberOfInputs.
double Flood::MultilayerPerceptron::getMaximumOfSingleInputVariable (int i)
This method returns the maximum value of a single input variable in the neural network. Such value is to be used for preprocessing that input with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1229 of file MultilayerPerceptron.cpp.
References maximumOfInputVariables, and numberOfInputs.
double Flood::MultilayerPerceptron::getMinimumOfSingleOutputVariable (int i)
This method returns the minimum value of a single output variable in the neural network. Such value is to be used for postprocessing that output signal with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMaximumOfSingleInputVariable(int).
getMaximumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1279 of file MultilayerPerceptron.cpp.
References minimumOfOutputVariables, and numberOfOutputs.
double Flood::MultilayerPerceptron::getMaximumOfSingleOutputVariable (int i)
This method returns the maximum value of a single input variable in the neural network. Such value is to be used for postprocessing that output signal with the minimum and maximum method.
See also:
getMinimumOfInputVariables(void).
getMaximumOfInputVariables(void).
getMinimumOfOutputVariables(void).
getMaximumOfOutputVariables(void).
getMinimumAndMaximumOfInputVariables(void).
getMinimumAndMaximumOfOutputVariables(void).
getMinimumOfSingleInputVariable(int).
getMaximumOfSingleInputVariable(int).
getMinimumOfSingleOutputVariable(int).
preprocessInput(Vector<double>).
postprocessOutputSignal(Vector<double>).
Definition at line 1330 of file MultilayerPerceptron.cpp.
References maximumOfOutputVariables, and numberOfOutputs.
Vector< Vector< double > > Flood::MultilayerPerceptron::getAllStatistics (void)
Definition at line 1365 of file MultilayerPerceptron.cpp.
References maximumOfInputVariables, maximumOfOutputVariables, meanOfInputVariables, meanOfOutputVariables, minimumOfInputVariables, minimumOfOutputVariables, standardDeviationOfInputVariables, and standardDeviationOfOutputVariables.
Vector< double > Flood::MultilayerPerceptron::getLowerBoundOfOutputVariables (void)
This method returns the lower bound of all the output variables in the neural network. These values are used to postprocess the outputs so that they are not less than the lower bounds.
See also:
getUpperBoundOfOutputVariables(void).
getLowerAndUpperBoundsOfOutputVariables(void).
getLowerBoundOfSingleOutputVariable(void).
getUpperBoundOfSingleOutputVariable(void).
applyLowerAndUpperBounds(Vector<double>).
Definition at line 1396 of file MultilayerPerceptron.cpp.
References lowerBoundOfOutputVariables.
Vector< double > Flood::MultilayerPerceptron::getUpperBoundOfOutputVariables (void)
This method returns the upper bound of all the output variables in the neural network. These values are used to postprocess the outputs so that they are not greater than the upper bounds.
See also:
getLowerBoundOfOutputVariables(void).
getLowerAndUpperBoundsOfOutputVariables(void).
getLowerBoundOfSingleOutputVariable(void).
getUpperBoundOfSingleOutputVariable(void).
applyLowerAndUpperBounds(Vector<double>).
Definition at line 1414 of file MultilayerPerceptron.cpp.
References upperBoundOfOutputVariables.
Matrix< double > Flood::MultilayerPerceptron::getLowerAndUpperBoundsOfOutputVariables (void)
This method returns the lower bounds and the upper bounds of all the output variables in a single matrix. The first row contains the lower bound values of the output variables. The second row contains the upper bound values of the output variables. These values are used to postprocess the outputs so that they are neither less than the lower bounds nor greater than the upper bounds.
See also:
getLowerBoundOfOutputVariables(void).
getUpperBoundOfOutputVariables(void).
getLowerBoundOfSingleOutputVariable(void).
getUpperBoundOfSingleOutputVariable(void).
applyLowerAndUpperBounds(Vector<double>).
Definition at line 1436 of file MultilayerPerceptron.cpp.
References lowerBoundOfOutputVariables, numberOfOutputs, Flood::Matrix< Type >::setRow(), and upperBoundOfOutputVariables.
double Flood::MultilayerPerceptron::getLowerBoundOfSingleOutputVariable (int i)
This method returns the lower bound of a single output variable in the neural network. This value is used to postprocess that output so that it is not less than the lower bound.
See also:
getLowerBoundOfOutputVariables(void).
getUpperBoundOfOutputVariables(void).
getLowerAndUpperBoundsOfOutputVariables(void).
getUpperBoundOfSingleOutputVariable(void).
applyLowerAndUpperBounds(Vector<double>).
Definition at line 1459 of file MultilayerPerceptron.cpp.
References lowerBoundOfOutputVariables, and numberOfOutputs.
double Flood::MultilayerPerceptron::getUpperBoundOfSingleOutputVariable (int i)
This method returns the upper bound of a single output variable in the neural network. This value is used to postprocess that output so that it is not greater than the upper bound.
See also:
getLowerBoundOfOutputVariables(void).
getUpperBoundOfOutputVariables(void).
getLowerAndUpperBoundsOfOutputVariables(void).
getLowerBoundOfSingleOutputVariable(void).
applyLowerAndUpperBounds(Vector<double>).
Definition at line 1504 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and upperBoundOfOutputVariables.
int Flood::MultilayerPerceptron::getNumberOfIndependentParameters (void)
This method returns the number of free parameters independent of the neural network. Independent parameters can be used in the context of neural netwotks for many purposes.
See also:
CarProblem.
CarProblemNeurocomputing.
Definition at line 1545 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters.
Referenced by Flood::CarProblem::calculateEvaluation(), Flood::CarProblem::CarProblem(), Flood::EasomFunction::EasomFunction(), and Flood::PlaneCylinder::PlaneCylinder().
Vector< double > Flood::MultilayerPerceptron::scaleIndependentParameters (Vector< double > unscaledIndependentParameters)
Definition at line 2176 of file MultilayerPerceptron.cpp.
References display, maximumOfIndependentParameters, MeanAndStandardDeviation, meanOfIndependentParameters, MinimumAndMaximum, minimumOfIndependentParameters, None, numberOfIndependentParameters, preAndPostProcessingMethod, and standardDeviationOfIndependentParameters.
Referenced by getFreeParameters().
Vector< double > Flood::MultilayerPerceptron::unscaleIndependentParameters (Vector< double > scaledIndependentParameters)
Definition at line 2248 of file MultilayerPerceptron.cpp.
References display, maximumOfIndependentParameters, MeanAndStandardDeviation, meanOfIndependentParameters, MinimumAndMaximum, minimumOfIndependentParameters, None, numberOfIndependentParameters, preAndPostProcessingMethod, and standardDeviationOfIndependentParameters.
Referenced by setFreeParameters().
Vector< double > Flood::MultilayerPerceptron::getIndependentParameters (void)
This method returns the values of the independent parameters. These values are postprocessed so that they are neither less than the lower bounds nor greater than the upper bounds.
See also:
getSingleIndependentParameter(int).
Definition at line 2327 of file MultilayerPerceptron.cpp.
References independentParameters, lowerBoundOfIndependentParameters, numberOfIndependentParameters, and upperBoundOfIndependentParameters.
Referenced by Flood::PlaneCylinder::calculateError(), Flood::RosenbrockFunction::calculateEvaluation(), Flood::RastriginFunction::calculateEvaluation(), Flood::PlaneCylinder::calculateEvaluation(), Flood::EasomFunction::calculateEvaluation(), Flood::DeJongFunction::calculateEvaluation(), Flood::CarProblem::calculateEvaluation(), Flood::RastriginFunction::calculateGradient(), Flood::EasomFunction::calculateGradient(), Flood::DeJongFunction::calculateGradient(), Flood::RastriginFunction::calculateHessian(), Flood::EasomFunction::calculateHessian(), Flood::DeJongFunction::calculateHessian(), Flood::RastriginFunction::calculateInverseHessian(), Flood::EasomFunction::calculateInverseHessian(), getFreeParameters(), Flood::CarProblem::print(), and Flood::CarProblem::saveResults().
double Flood::MultilayerPerceptron::getSingleIndependentParameter (int i)
This method returns the value of a single independent parameter. Such a value is postprocessed so that it is neither less than the lower bound nor greater than the upper bound.
Parameters:
i Index of independent parameter.
See also:
getIndependentParameters(void).
Definition at line 2357 of file MultilayerPerceptron.cpp.
References independentParameters, lowerBoundOfIndependentParameters, numberOfIndependentParameters, and upperBoundOfIndependentParameters.
Referenced by Flood::PrecipitateDissolutionModeling::getFullDissolutionTime(), Flood::PrecipitateDissolutionModeling::print(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
Vector< std::string > Flood::MultilayerPerceptron::getNameOfIndependentParameters (void)
This method returns the name of the independent parameters. Such names are only used to give the user basic information about the problem at hand.
See also:
getNameOfSingleIndependentParameter(int).
Definition at line 1558 of file MultilayerPerceptron.cpp.
References nameOfIndependentParameters.
std::string Flood::MultilayerPerceptron::getNameOfSingleIndependentParameter (int i)
This method returns the name of a single independent parameter. Such name is only used to give the user basic information about the problem at hand.
Parameters:
i Index of independent parameter.
See also:
getNameOfIndependentParameters(void).
Definition at line 1573 of file MultilayerPerceptron.cpp.
References nameOfIndependentParameters, and numberOfIndependentParameters.
Vector< std::string > Flood::MultilayerPerceptron::getUnitsOfIndependentParameters (void)
This method returns the units of the independent parameters. Such units are only used to give the user basic information about the problem at hand.
See also:
getUnitsOfSingleIndependentParameter(int).
Definition at line 1614 of file MultilayerPerceptron.cpp.
References unitsOfIndependentParameters.
std::string Flood::MultilayerPerceptron::getUnitsOfSingleIndependentParameter (int i)
This method returns the units of a single independent parameter. Such units are only used to give the user basic information about the problem at hand.
Parameters:
i Index of independent parameter.
See also:
getUnitsOfIndependentParameters(void).
Definition at line 1629 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and unitsOfIndependentParameters.
Vector< std::string > Flood::MultilayerPerceptron::getDescriptionOfIndependentParameters (void)
This method returns the description of the independent parameters. Such descriptions are only used to give the user basic information about the problem at hand.
See also:
getDescriptionOfSingleIndependentParameter(int).
Definition at line 1671 of file MultilayerPerceptron.cpp.
References descriptionOfIndependentParameters.
std::string Flood::MultilayerPerceptron::getDescriptionOfSingleIndependentParameter (int i)
This method returns the description of a single independent parameter. Such description is only used to give the user basic information about the problem at hand.
Parameters:
i Index of independent parameter.
See also:
getDescriptionOfIndependentParameters(void).
Definition at line 1686 of file MultilayerPerceptron.cpp.
References descriptionOfIndependentParameters, and numberOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getMeanOfIndependentParameters (void)
This method returns the mean values of all the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the mean and standard deviation method.
See also:
getStandardDeviationOfIndependentParameters(void).
getMeanAndStandardDeviationOfIndependentParameters(void).
getMeanOfSingleIndependentParameter(int).
getStandardDeviationOfSingleIndependentParameter(int).
Definition at line 1731 of file MultilayerPerceptron.cpp.
References meanOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getStandardDeviationOfIndependentParameters (void)
This method returns the standard deviation values of all the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the mean and standard deviation method.
See also:
getMeanOfIndependentParameters(void).
getMeanAndStandardDeviationOfIndependentParameters(void).
getMeanOfSingleIndependentParameter(int).
getStandardDeviationOfSingleIndependentParameter(int).
Definition at line 1748 of file MultilayerPerceptron.cpp.
References standardDeviationOfIndependentParameters.
Matrix< double > Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfIndependentParameters (void)
This method returns the mean and the standard deviation values of all the independent parameters in a single matrix. The first row contains the mean values of the independent parameters. The second row contains the standard deviation values of the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the mean and standard deviation method.
See also:
getMeanOfIndependentParameters(void).
getStandardDeviationOfIndependentParameters(void).
getMeanOfSingleIndependentParameter(int).
getStandardDeviationOfSingleIndependentParameter(int).
Definition at line 1768 of file MultilayerPerceptron.cpp.
References meanOfIndependentParameters, numberOfIndependentParameters, Flood::Matrix< Type >::setRow(), and standardDeviationOfIndependentParameters.
double Flood::MultilayerPerceptron::getMeanOfSingleIndependentParameter (int i)
This method returns the mean value of a single independent parameter. Such a value is to be used for pre and postprocessing that parameter with the mean and standard deviation method.
Parameters:
i Index of independent parameter.
See also:
getMeanOfIndependentParameters(void).
getStandardDeviationOfIndependentParameters(void).
getMeanAndStandardDeviationOfIndependentParameters(void).
getStandardDeviationOfSingleIndependentParameter(int).
Definition at line 1792 of file MultilayerPerceptron.cpp.
References meanOfIndependentParameters, and numberOfIndependentParameters.
double Flood::MultilayerPerceptron::getStandardDeviationOfSingleIndependentParameter (int i)
This method returns the standard deviation value of a single independent parameter. Such a value is to be used for pre and postprocessing that parameter with the mean and standard deviation method.
Parameters:
i Index of independent parameter.
See also:
getMeanOfIndependentParameters(void).
getStandardDeviationOfIndependentParameters(void).
getMeanAndStandardDeviationOfIndependentParameters(void).
getMeanOfSingleIndependentParameter(int).
Definition at line 1839 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and standardDeviationOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getMinimumOfIndependentParameters (void)
This method returns the minimum values of all the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the minimum and maximum method.
See also:
getMaximumOfIndependentParameters(void).
getMinimumAndMaximumOfIndependentParameters(void).
getMinimumOfSingleIndependentParameter(int).
getMaximumOfSingleIndependentParameter(int).
Definition at line 1884 of file MultilayerPerceptron.cpp.
References minimumOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getMaximumOfIndependentParameters (void)
This method returns the maximum values of all the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the minimum and maximum method.
See also:
getMinimumOfIndependentParameters(void).
getMinimumAndMaximumOfIndependentParameters(void).
getMinimumOfSingleIndependentParameter(int).
getMaximumOfSingleIndependentParameter(int).
Definition at line 1901 of file MultilayerPerceptron.cpp.
References maximumOfIndependentParameters.
Matrix< double > Flood::MultilayerPerceptron::getMinimumAndMaximumOfIndependentParameters (void)
This method returns the minimum and maximum values of all the independent parameters in a single matrix. The first row contains the minimum values of the independent parameters. The second row contains the maximum values of the independent parameters. Such values are to be used for pre and postprocessing independent parameters with the minimum and maximum method.
See also:
getMinimumOfIndependentParameters(void).
getMaximumOfIndependentParameters(void).
getMinimumOfSingleIndependentParameter(int).
getMaximumOfSingleIndependentParameter(int).
Definition at line 1920 of file MultilayerPerceptron.cpp.
References maximumOfIndependentParameters, minimumOfIndependentParameters, numberOfIndependentParameters, and Flood::Matrix< Type >::setRow().
double Flood::MultilayerPerceptron::getMinimumOfSingleIndependentParameter (int i)
This method returns the minimum value of a single independent parameter. Such value is to be used for pre and postprocessing that independent parameter with the minimum and maximum method.
Parameters:
i Index of independent parameter.
See also:
getMinimumOfIndependentParameters(void).
getMaximumOfIndependentParameters(void).
getMinimumAndMaximumOfIndependentParameters(void).
getMaximumOfSingleIndependentParameter(int).
Definition at line 1944 of file MultilayerPerceptron.cpp.
References minimumOfIndependentParameters, and numberOfIndependentParameters.
double Flood::MultilayerPerceptron::getMaximumOfSingleIndependentParameter (int i)
This method returns the maximum value of a single independent parameter. Such value is to be used for pre and postprocessing that independent parameter with the minimum and maximum method.
Parameters:
i Index of independent parameter.
See also:
getMinimumOfIndependentParameters(void).
getMaximumOfIndependentParameters(void).
getMinimumAndMaximumOfIndependentParameters(void).
getMinimumOfSingleIndependentParameter(int).
Definition at line 1991 of file MultilayerPerceptron.cpp.
References maximumOfIndependentParameters, and numberOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getLowerBoundOfIndependentParameters (void)
This method returns the lower bounds of all the independent parameters. These values are used to postprocess the independent parameters so that they are not less than the lower bounds.
See also:
getUpperBoundOfIndependentParameters(void).
getLowerAndUpperBoundsOfIndependentParameters(void).
getLowerBoundOfSingleIndependentParameter(int).
getUpperBoundOfSingleIndependentParameter(int).
Definition at line 2036 of file MultilayerPerceptron.cpp.
References lowerBoundOfIndependentParameters.
Vector< double > Flood::MultilayerPerceptron::getUpperBoundOfIndependentParameters (void)
This method returns the upper bounds of all the independent parameters. These values are used to postprocess the independent parameters so that they are not greater than the upper bounds.
See also:
getLowerBoundOfIndependentParameters(void).
getLowerAndUpperBoundsOfIndependentParameters(void).
getLowerBoundOfSingleIndependentParameter(int).
getUpperBoundOfSingleIndependentParameter(int).
Definition at line 2053 of file MultilayerPerceptron.cpp.
References upperBoundOfIndependentParameters.
Matrix< double > Flood::MultilayerPerceptron::getLowerAndUpperBoundsOfIndependentParameters (void)
This method returns the lower and upper bounds of all the independent parameters in a single matrix. The first row contains the lower bounds of the independent parameters. The second row contains the upper bounds of the independent parameters. These values are used to postprocess the independent parameters so that they are neither less than the lower bounds nor greater than the upper bounds.
See also:
getLowerBoundOfIndependentParameters(void).
getUpperBoundOfIndependentParameters(void).
getLowerBoundOfSingleIndependentParameter(int).
getUpperBoundOfSingleIndependentParameter(int).
Definition at line 2072 of file MultilayerPerceptron.cpp.
References lowerBoundOfIndependentParameters, numberOfIndependentParameters, Flood::Matrix< Type >::setRow(), and upperBoundOfIndependentParameters.
double Flood::MultilayerPerceptron::getLowerBoundOfSingleIndependentParameter (int i)
This method returns the lower bound of a single independent parameter. These values are used to postprocess that independent parameter so that it is not less than the lower bound.
Parameters:
i Index of independent parameter.
See also:
getLowerBoundOfIndependentParameters(void).
getUpperBoundOfIndependentParameters(void).
getLowerAndUpperBoundsOfIndependentParameters(void).
getUpperBoundOfSingleIndependentParameter(int).
Definition at line 2095 of file MultilayerPerceptron.cpp.
References lowerBoundOfIndependentParameters, and numberOfIndependentParameters.
double Flood::MultilayerPerceptron::getUpperBoundOfSingleIndependentParameter (int i)
This method returns the upper bound of a single independent parameter. These values are used to postprocess that independent parameter so that it is not greater than the upper bound.
Parameters:
i Index of independent parameter.
See also:
getLowerBoundOfIndependentParameters(void).
getUpperBoundOfIndependentParameters(void).
getLowerAndUpperBoundsOfIndependentParameters(void).
getLowerBoundOfSingleIndependentParameter(int).
Definition at line 2141 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and upperBoundOfIndependentParameters.
double Flood::MultilayerPerceptron::getNumericalEpsilon (void)
This method returns the epsilon value to be used for computing the Jacobian matrix of the neural network for a set of input signals and by means of numerical differentiation.
See also:
calculateJacobianTest(Vector<double>).
Definition at line 2428 of file MultilayerPerceptron.cpp.
References numericalEpsilon.
bool Flood::MultilayerPerceptron::getDisplayOutOfRangeWarning (void)
This method returns true if a warning message is to be displayed on the screen when some input variables fall outside the range defined by the minimum and maximum, or false otherwise.
Definition at line 2404 of file MultilayerPerceptron.cpp.
References displayOutOfRangeWarning.
bool Flood::MultilayerPerceptron::getDisplay (void)
This method returns true if messages from this class are to be displayed on the screen, or false if messages from this class are not to be displayed on the screen.
Definition at line 2415 of file MultilayerPerceptron.cpp.
References display.
void Flood::MultilayerPerceptron::setPreAndPostProcessingMethod (MultilayerPerceptron::PreAndPostProcessingMethod newPreAndPostProcessingMethod)
This method sets the method to be used for preprocessing network inputs and postprocessing network outputs.
Parameters:
newPreAndPostProcessingMethod New pre and post-processing method.
Definition at line 2441 of file MultilayerPerceptron.cpp.
References preAndPostProcessingMethod.
void Flood::MultilayerPerceptron::setNumericalDifferentiationMethod (MultilayerPerceptron::NumericalDifferentiationMethod newNumericalDifferentiationMethod)
This method sets the method to be used for the numerical differentiation of the Jacobian matrix for the multilayer perceptron.
Parameters:
newNumericalDifferentiationMethod New numerical differentiation method.
See also:
calculateJacobianTest(Vector<double>).
Definition at line 2457 of file MultilayerPerceptron.cpp.
References numericalDifferentiationMethod.
void Flood::MultilayerPerceptron::setNetworkArchitecture (int newNumberOfInputs, Vector< int > newNumbersOfHiddenNeurons, int newNumberOfOutputs)
This method sets the architecture of the neural network. All the free parameters of the neural network are initialized with random values chosen from a normal distribution with mean zero and standard deviation one. It also initializes the rest of class members to their default values:
Name of input vaviables: "InputVariable0",...
Name of output variables: "OutputVariable0",...
Units of input vaviables: "None",...
Units of output variables: "None",...
Description of input vaviables: "None",...
Description of output variables: "None",...
Mean of input variables: 0.
Standard deviation of input variables: 1.
Mean of output variables: 0.
Standard deviation of output variables: 1.
Minimum of input variables: -Inf.
Maximum of input variables: +Inf.
Minimum of output variables: -Inf.
Maximum of output variables: +Inf.
Lower bound of output variables: -Inf.
Lower bound of output variables: +Inf.
Parameters:
newNumberOfInputs New number of inputs in the neural network.
newNumbersOfHiddenNeurons New numbers of neurons for the hidden layers of the neural network. The size of this vector is the number of hidden layers.
newNumberOfOutputs New number of output neurons in the neural network.
Definition at line 2495 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables, descriptionOfOutputVariables, getNumberOfHiddenLayers(), hiddenLayers, hiddenLayersActivationFunction, Flood::Perceptron::HyperbolicTangent, Flood::Perceptron::Linear, lowerBoundOfOutputVariables, maximumOfInputVariables, maximumOfOutputVariables, meanOfInputVariables, meanOfOutputVariables, minimumOfInputVariables, minimumOfOutputVariables, nameOfInputVariables, nameOfOutputVariables, numberOfInputs, numberOfOutputs, numbersOfHiddenNeurons, outputLayer, outputLayerActivationFunction, Flood::Vector< Type >::setSize(), standardDeviationOfInputVariables, standardDeviationOfOutputVariables, unitsOfInputVariables, unitsOfOutputVariables, and upperBoundOfOutputVariables.
void Flood::MultilayerPerceptron::setNumbersOfHiddenNeurons (Vector< int > newNumbersOfHiddenNeurons)
Definition at line 2705 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), hiddenLayers, hiddenLayersActivationFunction, Flood::Perceptron::HyperbolicTangent, numberOfInputs, numberOfOutputs, numbersOfHiddenNeurons, outputLayer, and outputLayerActivationFunction.
void Flood::MultilayerPerceptron::setHiddenLayersActivationFunction (Vector< Perceptron::ActivationFunction > newHiddenLayersActivationFunction)
This class sets a new activation (or transfer) function in all the perceptrons composing the hidden layer.
Parameters:
newHiddenLayersActivationFunction Activation function for the hidden layers. The size of this Vector must be equal to the number of hidden layers, and each element corresponds to the activation function of one hidden layer.
See also:
Perceptron.
setOutputLayerActivationFunction(Perceptron::ActivationFunction).
Definition at line 2764 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), hiddenLayers, hiddenLayersActivationFunction, and numbersOfHiddenNeurons.
void Flood::MultilayerPerceptron::setOutputLayerActivationFunction (Perceptron::ActivationFunction newOutputLayerActivationFunction)
This class sets a new activation (or transfer) function in all the perceptrons composing the output layer.
Parameters:
newOutputLayerActivationFunction Activation function for the output units.
See also:
Perceptron.
setHiddenLayerActivationFunction(Perceptron::ActivationFunction).
Definition at line 2790 of file MultilayerPerceptron.cpp.
References numberOfOutputs, outputLayer, and outputLayerActivationFunction.
void Flood::MultilayerPerceptron::setNameOfInputVariables (Vector< std::string > newNameOfInputVariables)
This method sets the names of the input variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newNameOfInputVariables New names for the input variables of the neural network.
See also:
setNameOfOutputVariables(Vector<std::string>).
setNameOfSingleInputVariable(int, std::string).
setNameOfSingleOutputVariable(int, std::string).
Definition at line 2813 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), nameOfInputVariables, and numberOfInputs.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setNameOfOutputVariables (Vector< std::string > newNameOfOutputVariables)
This method sets the names of the output variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newNameOfOutputVariables New names for the output variables of the neural network.
See also:
setNameOfInputVariables(Vector<std::string>).
setNameOfSingleInputVariable(int, std::string).
setNameOfSingleOutputVariable(int, std::string).
Definition at line 2849 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), nameOfOutputVariables, and numberOfOutputs.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setNameOfSingleInputVariable (int i, std::string newNameOfSingleInputVariable)
This method sets the name of a single input variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newNameOfSingleInputVariable New name for the input variable with index i.
See also:
setNameOfInputVariables(Vector<std::string>).
setNameOfOutputVariables(Vector<std::string>).
setNameOfSingleOutputVariable(int, std::string).
Definition at line 2886 of file MultilayerPerceptron.cpp.
References nameOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setNameOfSingleOutputVariable (int i, std::string newNameOfSingleOutputVariable)
This method sets the name of a single output variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of output variable.
newNameOfSingleOutputVariable New name for the output variable with index i.
See also:
setNameOfInputVariables(Vector<std::string>).
setNameOfOutputVariables(Vector<std::string>).
setNameOfSingleInputVariable(int, std::string).
Definition at line 2923 of file MultilayerPerceptron.cpp.
References nameOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setUnitsOfInputVariables (Vector< std::string > newUnitsOfInputVariables)
This method sets new units for all the input variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newUnitsOfInputVariables New units for the input variables of the neural network.
See also:
setUnitsOfOutputVariables(Vector<std::string>).
setUnitsOfSingleInputVariable(int, std::string).
setUnitsOfSingleOutputVariable(int, std::string).
Definition at line 2959 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfInputs, and unitsOfInputVariables.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setUnitsOfOutputVariables (Vector< std::string > newUnitsOfOutputVariables)
This method sets new units for all the output variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newUnitsOfOutputVariables New units for the input variables of the neural network.
See also:
setUnitsOfInputVariables(Vector<std::string>).
setUnitsOfSingleInputVariable(int, std::string).
setUnitsOfSingleOutputVariable(int, std::string).
Definition at line 2995 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfOutputs, and unitsOfOutputVariables.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setUnitsOfSingleInputVariable (int i, std::string newUnitsOfSingleInputVariable)
This method sets new units for a single input variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newUnitsOfSingleInputVariable New units for the input variable with index i.
See also:
setUnitsOfInputVariables(Vector<std::string>).
setUnitsOfOutputVariables(Vector<std::string>).
setUnitsOfSingleOutputVariable(int, std::string).
Definition at line 3032 of file MultilayerPerceptron.cpp.
References numberOfInputs, and unitsOfInputVariables.
void Flood::MultilayerPerceptron::setUnitsOfSingleOutputVariable (int i, std::string newUnitsOfSingleOutputVariable)
This method sets new units for a single output variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of output variable.
newUnitsOfSingleOutputVariable New units for the output variable with index i.
See also:
setUnitsOfInputVariables(Vector<std::string>).
setUnitsOfOutputVariables(Vector<std::string>).
setUnitsOfSingleInputVariable(int, std::string).
Definition at line 3070 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and unitsOfOutputVariables.
void Flood::MultilayerPerceptron::setDescriptionOfInputVariables (Vector< std::string > newDescriptionOfInputVariables)
This method sets new descriptions for all the input variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newDescriptionOfInputVariables New description for the input variables of the neural network.
See also:
setDescriptionOfOutputVariables(Vector<std::string>).
setDescriptionOfSingleInputVariable(int, std::string).
setDescriptionOfSingleOutputVariable(int, std::string).
Definition at line 3107 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables, Flood::Vector< Type >::getSize(), and numberOfInputs.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setDescriptionOfOutputVariables (Vector< std::string > newDescriptionOfOutputVariables)
This method sets new descriptions for all the output variables. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newDescriptionOfOutputVariables New description for the output variables of the neural network.
See also:
setDescriptionOfInputVariables(Vector<std::string>).
setDescriptionOfSingleInputVariable(int, std::string).
setDescriptionOfSingleOutputVariable(int, std::string).
Definition at line 3143 of file MultilayerPerceptron.cpp.
References descriptionOfOutputVariables, Flood::Vector< Type >::getSize(), and numberOfOutputs.
Referenced by setAllInformation().
void Flood::MultilayerPerceptron::setDescriptionOfSingleInputVariable (int i, std::string newDescriptionOfSingleInputVariable)
This method sets a new description for a single input variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of input variable.
newDescriptionOfSingleInputVariable New description for the input variable with index i.
See also:
setDescriptionOfInputVariables(Vector<std::string>).
setDescriptionOfOutputVariables(Vector<std::string>).
setDescriptionOfSingleOutputVariable(int, std::string).
Definition at line 3180 of file MultilayerPerceptron.cpp.
References descriptionOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setDescriptionOfSingleOutputVariable (int i, std::string newDescriptionOfSingleOutputVariable)
This method sets a new description for a single output variable. Such value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of output variable.
newDescriptionOfSingleOutputVariable New description for the output variable with index i.
See also:
setDescriptionOfInputVariables(Vector<std::string>).
setDescriptionOfOutputVariables(Vector<std::string>).
setDescriptionOfSingleInputVariable(int, std::string).
Definition at line 3218 of file MultilayerPerceptron.cpp.
References descriptionOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setAllInformation (Vector< Vector< std::string > > newInformation)
Definition at line 3246 of file MultilayerPerceptron.cpp.
References setDescriptionOfInputVariables(), setDescriptionOfOutputVariables(), setNameOfInputVariables(), setNameOfOutputVariables(), setUnitsOfInputVariables(), and setUnitsOfOutputVariables().
void Flood::MultilayerPerceptron::setMeanOfInputVariables (Vector< double > newMeanOfInputVariables)
This method sets new mean values for all the input variables. These values are used for preprocessing the inputs to the neural network with the meand and standard deviation method.
Parameters:
newMeanOfInputVariables New set of mean values for the input variables of the neural network.
See also:
setStandardDeviationOfInputVariables(Vector<double>).
setMeanAndStandardDeviationOfInputVariables(Matrix<double>).
setMeanOfSingleInputVariable(int, double).
setStandardDeviationOfSingleInputVariable(int, double).
Definition at line 3294 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), meanOfInputVariables, and numberOfInputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setStandardDeviationOfInputVariables (Vector< double > newStandardDeviationOfInputVariables)
This method sets new standard deviation values for all the input variables. These values are used for preprocessing the inputs to the neural network with the meand and standard deviation method.
Parameters:
newStandardDeviationOfInputVariables New set of standard deviation values for the input variables of the neural network.
See also:
setMeanOfInputVariables(Vector<double>).
setMeanAndStandardDeviationOfInputVariables(Matrix<double>).
setMeanOfSingleInputVariable(int, double).
setStandardDeviationOfSingleInputVariable(int, double).
Definition at line 3333 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfInputs, and standardDeviationOfInputVariables.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMeanOfOutputVariables (Vector< double > newMeanOfOutputVariables)
This method sets new mean values for all the output variables. These values are used for postprocessing the output signals from the neural network with the meand and standard deviation method.
Parameters:
newMeanOfOutputVariables New set of mean values for the output variables of the neural network.
See also:
setStandardDeviationOfOutputVariables(Vector<double>).
setMeanAndStandardDeviationOfOutputVariables(Matrix<double>).
setMeanOfSingleOutputVariable(int, double).
setStandardDeviationOfSingleOutputVariable(int, double).
Definition at line 3442 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), meanOfOutputVariables, and numberOfOutputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setStandardDeviationOfOutputVariables (Vector< double > newStandardDeviationOfOutputVariables)
This method sets new standard deviation values for all the output variables. These values are used for postprocessing the output signals from the neural network with the meand and standard deviation method.
Parameters:
newStandardDeviationOfOutputVariables New set of standard deviation values for the output variables of the neural network.
See also:
setMeanOfOutputVariables(Vector<double>).
setMeanAndStandardDeviationOfOutputVariables(Matrix<double>).
setMeanOfSingleOutputVariable(int, double).
setStandardDeviationOfSingleOutputVariable(int, double).
Definition at line 3482 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfOutputs, and standardDeviationOfOutputVariables.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfInputVariables (Matrix< double > newMeanAndStandardDeviationOfInputVariables)
This method sets both the mean and the standard deviation values of all the input variables from a single matrix. The first row must contain the mean values for the input variables. The second row must contain the standard deviation values for the input variables. These values are used for preprocessing the inputs to the neural network with the meand and standard deviation method.
Parameters:
newMeanAndStandardDeviationOfInputVariables New set of mean and standard deviation values for the input variables of the neural network.
See also:
setMeanOfInputVariables(Vector<double>).
setStandardDeviationOfInputVariables(Vector<double>).
setMeanOfSingleInputVariable(int, double).
setStandardDeviationOfSingleInputVariable(int, double).
Definition at line 3376 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), meanOfInputVariables, numberOfInputs, and standardDeviationOfInputVariables.
void Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfOutputVariables (Matrix< double > newMeanAndStandardDeviationOfOutputVariables)
This method sets both the mean and the standard deviation values of all the output variables from a single matrix. The first row must contain the mean values for the output variables. The second row must contain the standard deviation values for the output variables.
Parameters:
newMeanAndStandardDeviationOfOutputVariables New set of mean and standard deviation values for the output variables of the neural network.
See also:
setMeanOfOutputVariables(Vector<double>).
setStandardDeviationOfOutputVariables(Vector<double>).
setMeanOfSingleOutputVariable(int, double).
setStandardDeviationOfSingleOutputVariable(int, double).
Definition at line 3523 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), meanOfOutputVariables, numberOfOutputs, and standardDeviationOfOutputVariables.
void Flood::MultilayerPerceptron::setMeanOfSingleInputVariable (int i, double newMeanOfSingleInputVariable)
This method sets a new mean value for a single input variable. These values are used for preprocessing the inputs to the neural network with the meand and standard deviation method.
Parameters:
i Index of input variable.
newMeanOfSingleInputVariable New mean values for the input variable with index i.
See also:
setMeanOfInputVariables(Vector<double>).
setStandardDeviationOfInputVariables(Vector<double>).
setMeanAndStandardDeviationOfInputVariables(Matrix<double>).
setStandardDeviationOfSingleInputVariable(int, double).
Definition at line 3574 of file MultilayerPerceptron.cpp.
References meanOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setStandardDeviationOfSingleInputVariable (int i, double newStandardDeviationOfSingleInputVariable)
This method sets a new standard deviation value for a single input variable. These values are used for preprocessing the inputs to the neural network with the meand and standard deviation method.
Parameters:
i Index of input variable.
newStandardDeviationOfSingleInputVariable New standard deviation value for the input variable with index i.
See also:
setMeanOfInputVariables(Vector<double>).
setStandardDeviationOfInputVariables(Vector<double>).
setMeanAndStandardDeviationOfInputVariables(Matrix<double>).
setMeanOfSingleInputVariable(int, double).
Definition at line 3614 of file MultilayerPerceptron.cpp.
References numberOfInputs, and standardDeviationOfInputVariables.
void Flood::MultilayerPerceptron::setMeanOfSingleOutputVariable (int i, double newMeanOfSingleOutputVariable)
This method sets a new mean value for a single output variable. These values are used for postprocessing the output signals form the neural network with the meand and standard deviation method.
Parameters:
i Index of output variable.
newMeanOfSingleOutputVariable New mean value for the output variable with index i.
See also:
setMeanOfOutputVariables(Vector<double>).
setStandardDeviationOfOutputVariables(Vector<double>).
setMeanAndStandardDeviationOfOutputVariables(Matrix<double>).
setStandardDeviationOfSingleOutputVariable(int, double).
Definition at line 3654 of file MultilayerPerceptron.cpp.
References meanOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setStandardDeviationOfSingleOutputVariable (int i, double newStandardDeviationOfSingleOutputVariable)
This method sets a new standard deviation value for a single output variable. These values are used for postprocessing the output signals form the neural network with the meand and standard deviation method.
Parameters:
i Index of output variable.
newStandardDeviationOfSingleOutputVariable New standard deviation value for the output variable with index i.
See also:
setMeanOfOutputVariables(Vector<double>).
setStandardDeviationOfOutputVariables(Vector<double>).
setMeanAndStandardDeviationOfOutputVariables(Matrix<double>).
setMeanOfSingleOutputVariable(int, double).
Definition at line 3694 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and standardDeviationOfOutputVariables.
void Flood::MultilayerPerceptron::setMinimumOfInputVariables (Vector< double > newMinimumOfInputVariables)
This method sets new minimum values for all the input variables. These values are used for preprocessing the inputs to the neural network with the minimum and maximum method.
Parameters:
newMinimumOfInputVariables New set of minimum values for the input variables of the neural network.
See also:
setMaximumOfInputVariables(Vector<double>).
setMinimumAndMaximumOfInputVariables(Matrix<double>).
setMinimumOfSingleInputVariable(int, double).
setMaximumOfSingleInputVariable(int, double).
Definition at line 3732 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), minimumOfInputVariables, and numberOfInputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMaximumOfInputVariables (Vector< double > newMaximumOfInputVariables)
This method sets new maximum values for all the input variables. These values are used for preprocessing the inputs to the neural network with the minimum and maximum method.
Parameters:
newMaximumOfInputVariables New set of maximum values for the input variables of the neural network.
See also:
setMinimumOfInputVariables(Vector<double>).
setMinimumAndMaximumOfInputVariables(Matrix<double>).
setMinimumOfSingleInputVariable(int, double).
setMaximumOfSingleInputVariable(int, double).
Definition at line 3769 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), maximumOfInputVariables, and numberOfInputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMinimumOfOutputVariables (Vector< double > newMinimumOfOutputVariables)
This method sets new minimum values for all the output variables. These values are used for postprocessing the output signals from the neural network with the minimum and maximum method.
Parameters:
newMinimumOfOutputVariables New set of minimum values for the output variables of the neural network.
See also:
setMaximumOfOutputVariables(Vector<double>).
setMinimumAndMaximumOfOutputVariables(Matrix<double>).
setMinimumOfSingleOutputVariable(int, double).
setMaximumOfSingleOutputVariable(int, double).
Definition at line 3807 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), minimumOfOutputVariables, and numberOfOutputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMaximumOfOutputVariables (Vector< double > newMaximumOfOutputVariables)
This method sets new maximum values for all the output variables. These values are used for postprocessing the output signals from the neural network with the minimum and maximum method.
Parameters:
newMaximumOfOutputVariables New set of maximum values for the output variables of the neural network.
See also:
setMinimumOfOutputVariables(Vector<double>).
setMinimumAndMaximumOfOutputVariables(Matrix<double>).
setMinimumOfSingleOutputVariable(int, double).
setMaximumOfSingleOutputVariable(int, double).
Definition at line 3845 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), maximumOfOutputVariables, and numberOfOutputs.
Referenced by setAllStatistics().
void Flood::MultilayerPerceptron::setMinimumAndMaximumOfInputVariables (Matrix< double > newMinimumAndMaximumOfInputVariables)
This method sets both the minimum and the maximum values of all the input variables from a single matrix. The first row must contain the minimum values for the input variables. The second row must contain the maximum values for the input variables. These values are used for preprocessing the inputs to the neural network with the minimum and maximum method.
Parameters:
newMinimumAndMaximumOfInputVariables New set of minimum and maximum values for the input variables of the neural network.
See also:
setMinimumOfInputVariables(Vector<double>).
setMaximumOfInputVariables(Matrix<double>).
setMinimumOfSingleInputVariable(int, double).
setMaximumOfSingleInputVariable(int, double).
Definition at line 3887 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), maximumOfInputVariables, minimumOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setMinimumAndMaximumOfOutputVariables (Matrix< double > newMinimumAndMaximumOfOutputVariables)
This method sets both the minimum and the maximum values of all the output variables from a single matrix. The first row must contain the minimum values for the output variables. The second row must contain the maximum values for the output variables. These values are used for postprocessing the output signals from network with the minimum and maximum method.
Parameters:
newMinimumAndMaximumOfOutputVariables New set of minimum and maximum values for the output variables of the neural network.
See also:
setMinimumOfOutputVariables(Vector<double>).
setMaximumOfOutputVariables(Matrix<double>).
setMinimumOfSingleOutputVariable(int, double).
setMaximumOfSingleOutputVariable(int, double).
Definition at line 3957 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), maximumOfOutputVariables, minimumOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setMinimumOfSingleInputVariable (int i, double newMinimumOfSingleInputVariable)
This method sets a new minimum value for a single input variable. This value is used for preprocessing that input to the neural network with the minimum and maximum method.
Parameters:
i Index of input variable.
newMinimumOfSingleInputVariable New minimum value for the input variable with index i.
See also:
setMinimumOfInputVariables(Vector<double>).
setMaximumOfInputVariables(Vector<double>).
setMinimumAndMaximumOfInputVariables(Matrix<double>).
setMaximumOfSingleInputVariable(int, double).
Definition at line 4023 of file MultilayerPerceptron.cpp.
References minimumOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setMaximumOfSingleInputVariable (int i, double newMaximumOfSingleInputVariable)
This method sets a new maximum value for a single input variable. This value is used for preprocessing that input to the neural network with the minimum and maximum method.
Parameters:
i Index of input variable.
newMaximumOfSingleInputVariable New maximum value for the input variable with index i.
See also:
setMinimumOfInputVariables(Vector<double>).
setMaximumOfInputVariables(Vector<double>).
setMinimumAndMaximumOfInputVariables(Matrix<double>).
setMinimumOfSingleInputVariable(int, double).
Definition at line 4061 of file MultilayerPerceptron.cpp.
References maximumOfInputVariables, and numberOfInputs.
void Flood::MultilayerPerceptron::setMinimumOfSingleOutputVariable (int i, double newMinimumOfSingleOutputVariable)
This method sets a new minimum value for a single output variable. This value is used for postprocessing that output signals from the neural network with the minimum and maximum method.
Parameters:
i Index of output variable.
newMinimumOfSingleOutputVariable New minimum value for the output variable with index i.
See also:
setMinimumOfOutputVariables(Vector<double>).
setMaximumOfOutputVariables(Vector<double>).
setMinimumAndMaximumOfOutputVariables(Matrix<double>).
setMaximumOfSingleOutputVariable(int, double).
Definition at line 4100 of file MultilayerPerceptron.cpp.
References minimumOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setMaximumOfSingleOutputVariable (int i, double newMaximumOfSingleOutputVariable)
This method sets a new maximum value for a single output variable. This value is used for postprocessing that output signals from the neural network with the minimum and maximum method.
Parameters:
i Index of output variable.
newMaximumOfSingleOutputVariable New maximum value for the output variable with index i.
See also:
setMinimumOfOutputVariables(Vector<double>).
setMaximumOfOutputVariables(Vector<double>).
setMinimumAndMaximumOfOutputVariables(Matrix<double>).
setMinimumOfSingleOutputVariable(int, double).
Definition at line 4140 of file MultilayerPerceptron.cpp.
References maximumOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setAllStatistics (Vector< Vector< double > > newStatistics)
Definition at line 4168 of file MultilayerPerceptron.cpp.
References setMaximumOfInputVariables(), setMaximumOfOutputVariables(), setMeanOfInputVariables(), setMeanOfOutputVariables(), setMinimumOfInputVariables(), setMinimumOfOutputVariables(), setStandardDeviationOfInputVariables(), and setStandardDeviationOfOutputVariables().
void Flood::MultilayerPerceptron::setLowerBoundOfOutputVariables (Vector< double > newLowerBoundOfOutputVariables)
This method sets new lower bounds for all the output variables. These values are used for postprocessing the outputs so that they are not less than the lower bounds.
Parameters:
newLowerBoundOfOutputVariables New set of lower bounds for the output variables of the neural network.
See also:
setUpperBoundOfOutputVariables(Vector<double>).
setLowerAndUpperBoundOfOutputVariables(Vector<double>).
setLowerBoundOfSingleOutputVariable(int, double).
setUpperBoundOfSingleOutputVariable(int, double).
Definition at line 4217 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), lowerBoundOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setUpperBoundOfOutputVariables (Vector< double > newUpperBoundOfOutputVariables)
This method sets new upper bounds for all the output variables. These values are used for postprocessing the outputs so that they are not greater than the upper bounds.
Parameters:
newUpperBoundOfOutputVariables New set of upper bounds for the output variables of the neural network.
See also:
setLowerBoundOfOutputVariables(Vector<double>).
setLowerAndUpperBoundOfOutputVariables(Vector<double>).
setLowerBoundOfSingleOutputVariable(int, double).
setUpperBoundOfSingleOutputVariable(int, double).
Definition at line 4254 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfOutputs, and upperBoundOfOutputVariables.
void Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfOutputVariables (Matrix< double > newLowerAndUpperBoundsOfOutputVariables)
This method sets both the lower bounds and the upper bounds of all the output variables from a single matrix. The first row must contain the lower bound values for the output variables. The second row must contain the upper bound values for the output variables. These values are used for postprocessing the outputs so that they are not greater than the upper bounds.
Parameters:
newLowerAndUpperBoundsOfOutputVariables New set of lower and upper bounds for the output variables of the neural network.
See also:
setLowerBoundOfOutputVariables(Vector<double>).
setUpperBoundOfOutputVariables(Vector<double>).
setLowerBoundOfSingleOutputVariable(int, double).
setUpperBoundOfSingleOutputVariable(int, double).
Definition at line 4296 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), lowerBoundOfOutputVariables, numberOfOutputs, and upperBoundOfOutputVariables.
void Flood::MultilayerPerceptron::setLowerBoundOfSingleOutputVariable (int i, double newLowerBoundOfSingleOutputVariable)
This method sets a new lower bound for a single output variable. This value is used for postprocessing that output so that it is not less than the lower bound.
Parameters:
i Index of output variable.
newLowerBoundOfSingleOutputVariable New lower bound for the output variable with index i.
See also:
setLowerBoundOfOutputVariables(Vector<double>).
setUpperBoundOfOutputVariables(Vector<double>).
setLowerAndUpperBoundOfOutputVariables(Vector<double>).
setUpperBoundOfSingleOutputVariable(int, double).
Definition at line 4348 of file MultilayerPerceptron.cpp.
References lowerBoundOfOutputVariables, and numberOfOutputs.
void Flood::MultilayerPerceptron::setUpperBoundOfSingleOutputVariable (int i, double newUpperBoundOfSingleOutputVariable)
This method sets a new upper bound for a single output variable. This value is used for postprocessing that output so that it is not greater than the upper bound.
Parameters:
i Index of output variable.
newUpperBoundOfSingleOutputVariable New upper bound for the output variable with index i.
See also:
setLowerBoundOfOutputVariables(Vector<double>).
setUpperBoundOfOutputVariables(Vector<double>).
setLowerAndUpperBoundOfOutputVariables(Vector<double>).
setLowerBoundOfSingleOutputVariable(int, double).
Definition at line 4387 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and upperBoundOfOutputVariables.
void Flood::MultilayerPerceptron::setNumberOfIndependentParameters (int newNumberOfIndependentParameters)
This method sets a new number of free parameters independent of the neural network. It initializes the independent parameters with random values chosen from a normal distribution with mean zero and standard deviation one. This method also initializes all the class members related to independent with their default value:
Name of independent parameters: "IndependentParameter0", ...
Units of independent parameters: "None".
Description of independent parameters: "None".
Mean of independent parameters: 0.
Standard deviation of independent parameters: 1.
Minimum of independent parameters: -Inf.
Maximum of independent parameters: +Inf.
Lower bound of independent parameters: -Inf.
Upper bound of independent parameters: +Inf.
Definition at line 4432 of file MultilayerPerceptron.cpp.
References descriptionOfIndependentParameters, independentParameters, initIndependentParametersNormal(), lowerBoundOfIndependentParameters, maximumOfIndependentParameters, meanOfIndependentParameters, minimumOfIndependentParameters, nameOfIndependentParameters, numberOfIndependentParameters, Flood::Vector< Type >::setSize(), standardDeviationOfIndependentParameters, unitsOfIndependentParameters, and upperBoundOfIndependentParameters.
Referenced by Flood::DeJongFunction::setNumberOfVariables().
void Flood::MultilayerPerceptron::setIndependentParameters (Vector< double > newIndependentParameters)
This method sets new values for all the independent parameters.
Parameters:
newIndependentParameters Independent parameters values.
See also:
setSingleIndependentParameter(int, double).
Definition at line 4752 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), independentParameters, and numberOfIndependentParameters.
Referenced by setFreeParameters().
void Flood::MultilayerPerceptron::setSingleIndependentParameter (int i, double newSingleIndependentParameter)
This method sets a new value for a single independent parameter.
Parameters:
i Independent parameter index.
newSingleIndependentParameter Independent parameter value.
See also:
setIndependentParameters(Vector<double>).
Definition at line 4786 of file MultilayerPerceptron.cpp.
References independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setNameOfIndependentParameters (Vector< std::string > newNameOfIndependentParameters)
This method sets new names for the independent parameters. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newNameOfIndependentParameters New names for the independent parameters of the neural network.
@ see setNameOfSingleIndependentParameter(int, std::string).
Definition at line 4540 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), nameOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setNameOfSingleIndependentParameter (int i, std::string newNameOfSingleIndependentParameter)
This method sets a new name for a single independent parameter. Such a value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of independent parameter.
newNameOfSingleIndependentParameter New name for the independent parameter of index i.
@ see setNameOfIndependentParameters(Vector<std::string>).
Definition at line 4575 of file MultilayerPerceptron.cpp.
References nameOfIndependentParameters, and numberOfIndependentParameters.
Referenced by Flood::DeJongFunction::setNumberOfVariables().
void Flood::MultilayerPerceptron::setUnitsOfIndependentParameters (Vector< std::string > newUnitsOfIndependentParameters)
This method sets new units for the independent parameters. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newUnitsOfIndependentParameters New units for the independent parameters of the neural network.
@ see setUnitsOfSingleIndependentParameter(int, std::string).
Definition at line 4610 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfIndependentParameters, and unitsOfIndependentParameters.
void Flood::MultilayerPerceptron::setUnitsOfSingleIndependentParameter (int i, std::string newUnitsOfSingleIndependentParameter)
This method sets new units for a single independent parameter. Such a value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of independent parameter.
newUnitsOfSingleIndependentParameter New units for the independent parameter of index i.
@ see setUnitsOfIndependentParameters(Vector<std::string>).
Definition at line 4645 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and unitsOfIndependentParameters.
void Flood::MultilayerPerceptron::setDescriptionOfIndependentParameters (Vector< std::string > newDescriptionOfIndependentParameters)
This method sets new descriptions for the independent parameters. Such values are only used to give the user basic information on the problem at hand.
Parameters:
newDescriptionOfIndependentParameters New description for the independent parameters of the neural network.
@ see setDescriptionOfSingleIndependentParameter(int, std::string).
Definition at line 4682 of file MultilayerPerceptron.cpp.
References descriptionOfIndependentParameters, Flood::Vector< Type >::getSize(), and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setDescriptionOfSingleIndependentParameter (int i, std::string newDescriptionOfSingleIndependentParameter)
This method sets a new description for a single independent parameter. Such a value is only used to give the user basic information on the problem at hand.
Parameters:
i Index of independent parameter.
newDescriptionOfSingleIndependentParameter New description for the independent parameter of index i.
@ see setDescriptionOfIndependentParameters(Vector<std::string>).
Definition at line 4717 of file MultilayerPerceptron.cpp.
References descriptionOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setMeanOfIndependentParameters (Vector< double > newMeanOfIndependentParameters)
This method sets the mean values of all the independent parameters. These values are used for pre and postprocessing the independent parameters with the mean and standard deviation method.
Parameters:
newMeanOfIndependentParameters New set of mean values for the independent parameters of the neural network.
See also:
setStandardDeviationOfIndependentParameters(Vector<double>).
setMeanOfSingleIndependentParameter(int, double).
setStandardDeviationOfSingleIndependentParameter(int, double).
Definition at line 4824 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), meanOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setStandardDeviationOfIndependentParameters (Vector< double > newStandardDeviationOfIndependentParameters)
This method sets the standard deviation values of all the independent parameters. These values are used for pre and postprocessing the independent parameters with the mean and standard deviation method.
Parameters:
newStandardDeviationOfIndependentParameters New set of standard deviation values for the independent parameters of the neural network.
See also:
setMeanOfIndependentParameters(Vector<double>).
setMeanOfSingleIndependentParameter(int, double).
setStandardDeviationOfSingleIndependentParameter(int, double).
Definition at line 4863 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfIndependentParameters, and standardDeviationOfIndependentParameters.
void Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfIndependentParameters (Matrix< double > newMeanAndStandardDeviationOfIndependentParameters)
This method sets both the mean and the standard deviation values of all the independent parameters from a single matrix. The first row must contain the mean values values for the independent parameters. The second row must contain the standard deviation values for the independent parameters. These values are used for pre and postprocessing the independent parameters with the mean and standard deviation method.
Parameters:
newMeanAndStandardDeviationOfIndependentParameters New set of mean and standard deviation values for the independent parameters of the neural network.
See also:
setMeanOfIndependentParameters(Vector<double>).
setStandardDeviationOfIndependentParameters(Vector<double>).
Definition at line 4904 of file MultilayerPerceptron.cpp.
References display, Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), meanOfIndependentParameters, numberOfIndependentParameters, numberOfInputs, and standardDeviationOfIndependentParameters.
void Flood::MultilayerPerceptron::setMeanOfSingleIndependentParameter (int i, double newMeanOfSingleIndependentParameter)
This method sets a new mean value for a single independent parameter. Such a value is used for pre and postprocessing the independent parameters with the mean and standard deviation method.
Parameters:
i Index of independent parameter.
newMeanOfSingleIndependentParameter New mean value for the independent parameter of index i.
See also:
setMeanOfIndependentParameters(Vector<double>).
setStandardDeviationOfIndependentParameters(Vector<double>).
setStandardDeviationOfSingleIndependentParameter(int, double).
Definition at line 4974 of file MultilayerPerceptron.cpp.
References meanOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setStandardDeviationOfSingleIndependentParameter (int i, double newStandardDeviationOfSingleIndependentParameter)
This method sets a new standard deviation value for a single independent parameter. Such a value is used for pre and postprocessing the independent parameters with the mean and standard deviation method.
Parameters:
i Index of independent parameter.
newStandardDeviationOfSingleIndependentParameter New standard deviation value for the independent parameter of index i.
See also:
setMeanOfIndependentParameters(Vector<double>).
setStandardDeviationOfIndependentParameters(Vector<double>).
setMeanOfSingleIndependentParameter(int, double).
Definition at line 5013 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and standardDeviationOfIndependentParameters.
void Flood::MultilayerPerceptron::setMinimumOfIndependentParameters (Vector< double > newMinimumOfIndependentParameters)
This method sets the minimum values of all the independent parameters. These values are used for pre and postprocessing the independent parameters with the minimum and maximum method.
Parameters:
newMinimumOfIndependentParameters New set of minimum values for the independent parameters of the neural network.
See also:
setMaximumOfIndependentParameters(Vector<double>).
setMinimumAndMaximumOfIndependentParameters(Matrix<double>).
setMinimumOfSingleIndependentParameter(int, double).
setMaximumOfSingleIndependentParameter(int, double).
Definition at line 5054 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), minimumOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setMaximumOfIndependentParameters (Vector< double > newMaximumOfIndependentParameters)
This method sets the maximum values of all the independent parameters. These values are used for pre and postprocessing the independent parameters with the minimum and maximum method.
Parameters:
newMaximumOfIndependentParameters New set of maximum values for the independent parameters of the neural network.
See also:
setMinimumOfIndependentParameters(Vector<double>).
setMinimumAndMaximumOfIndependentParameters(Matrix<double>).
setMinimumOfSingleIndependentParameter(int, double).
setMaximumOfSingleIndependentParameter(int, double).
Definition at line 5093 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), maximumOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setMinimumAndMaximumOfIndependentParameters (Matrix< double > newMinimumAndMaximumOfIndependentParameters)
This method sets both the minimum and the values of all the independent parameters from a single matrix. The first row must contain the minimum values values for the independent parameters. The second row must contain the maximum values for the independent parameters. These values are used for pre and postprocessing the independent parameters with the minimum and maximum method.
Parameters:
newMinimumAndMaximumOfIndependentParameters New set of minimum and maximum values for the independent parameters of the neural network.
See also:
setMinimumOfIndependentParameters(Vector<double>).
setMaximumOfIndependentParameters(Vector<double>).
setMinimumOfSingleIndependentParameter(int, double).
setMaximumOfSingleIndependentParameter(int, double).
Definition at line 5135 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), maximumOfIndependentParameters, minimumOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setMinimumOfSingleIndependentParameter (int i, double newMinimumOfSingleIndependentParameter)
This method sets a minimum value for a single independent parameter. Such a value is used for pre and postprocessing that independent parameter with the minimum and maximum method.
Parameters:
i Index of independent parameter.
newMinimumOfSingleIndependentParameter New minimum value for the independent parameter of index i.
See also:
setMinimumOfIndependentParameters(Vector<double>).
setMaximumOfIndependentParameters(Vector<double>).
setMinimumAndMaximumOfIndependentParameters(Matrix<double>).
setMaximumOfSingleIndependentParameter(int, double).
Definition at line 5202 of file MultilayerPerceptron.cpp.
References minimumOfIndependentParameters, and numberOfIndependentParameters.
Referenced by Flood::DeJongFunction::setNumberOfVariables().
void Flood::MultilayerPerceptron::setMaximumOfSingleIndependentParameter (int i, double newMaximumOfSingleIndependentParameter)
This method sets a maximum value for a single independent parameter. Such a value is used for pre and postprocessing that independent parameter with the minimum and maximum method.
Parameters:
i Index of independent parameter.
newMaximumOfSingleIndependentParameter New maximum value for the independent parameter of index i.
See also:
setMinimumOfIndependentParameters(Vector<double>).
setMaximumOfIndependentParameters(Vector<double>).
setMinimumAndMaximumOfIndependentParameters(Matrix<double>).
setMinimumOfSingleIndependentParameter(int, double).
Definition at line 5242 of file MultilayerPerceptron.cpp.
References maximumOfIndependentParameters, and numberOfIndependentParameters.
Referenced by Flood::DeJongFunction::setNumberOfVariables().
void Flood::MultilayerPerceptron::setLowerBoundOfIndependentParameters (Vector< double > newLowerBoundOfIndependentParameters)
This method sets the lower bound of all the independent parameters. These values are used for postprocessing the independent parameters so that they are not less than the lower bounds.
Parameters:
newLowerBoundOfIndependentParameters New set of lower bounds for the independent parameters of the neural network.
See also:
setUpperBoundOfIndependentParameters(Vector<double>).
setLowerAndUpperBoundsOfIndependentParameters(Matrix<double>).
setLowerBoundOfSingleIndependentParameters(int, double).
setUpperBoundOfSingleIndependentParameters(int, double).
Definition at line 5283 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), lowerBoundOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setUpperBoundOfIndependentParameters (Vector< double > newUpperBoundOfIndependentParameters)
This method sets the upper bound of all the independent parameters. These values are used for postprocessing the independent parameters so that they are not greater than the upper bounds.
Parameters:
newUpperBoundOfIndependentParameters New set of upper bounds for the independent parameters of the neural network.
See also:
setLowerBoundOfIndependentParameters(Vector<double>).
setLowerAndUpperBoundsOfIndependentParameters(Matrix<double>).
setLowerBoundOfSingleIndependentParameters(int, double).
setUpperBoundOfSingleIndependentParameters(int, double).
Definition at line 5322 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfIndependentParameters, and upperBoundOfIndependentParameters.
void Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfIndependentParameters (Matrix< double > newLowerAndUpperBoundsOfIndependentParameters)
This method sets both the lower and the upper bounds of all the independent parameters from a single matrix. The first row must contain the lower bound values values for the independent parameters. The second row must contain the upper bound values for the independent parameters. These values are used for postprocessing the independent parameters so that they are neither less than the lower bounds nor greater than the upper bounds.
Parameters:
newLowerAndUpperBoundsOfIndependentParameters New set of lower and upper bounds for the independent parameters of the neural network.
See also:
setLowerBoundOfIndependentParameters(Vector<double>).
setUpperBoundOfIndependentParameters(Matrix<double>).
setLowerBoundOfSingleIndependentParameters(int, double).
setUpperBoundOfSingleIndependentParameters(int, double).
Definition at line 5364 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), lowerBoundOfIndependentParameters, numberOfIndependentParameters, and upperBoundOfIndependentParameters.
void Flood::MultilayerPerceptron::setLowerBoundOfSingleIndependentParameter (int i, double newLowerBoundOfSingleIndependentParameter)
This method sets the lower bound of a single independent parameter. Such a value is used for postprocessing that independent parameter so that it is not less than its lower bound.
Parameters:
i Index of independent parameter.
newLowerBoundOfSingleIndependentParameter New lower bound for the independent parameter of index i.
See also:
setLowerBoundOfIndependentParameters(Vector<double>).
setUpperBoundOfIndependentParameters(Vector<double>).
setLowerAndUpperBoundsOfIndependentParameters(Matrix<double>).
setUpperBoundOfSingleIndependentParameters(int, double).
Definition at line 5417 of file MultilayerPerceptron.cpp.
References lowerBoundOfIndependentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::setUpperBoundOfSingleIndependentParameter (int i, double newUpperBoundOfSingleIndependentParameter)
This method sets the upper bound of a single independent parameter. Such a value is used for postprocessing that independent parameter so that it is not greater than its upper bound.
Parameters:
i Index of independent parameter.
newUpperBoundOfSingleIndependentParameter New upper bound for the independent parameter of index i.
See also:
setLowerBoundOfIndependentParameters(Vector<double>).
setUpperBoundOfIndependentParameters(Vector<double>).
setLowerAndUpperBoundsOfIndependentParameters(Matrix<double>).
setLowerBoundOfSingleIndependentParameters(int, double).
Definition at line 5457 of file MultilayerPerceptron.cpp.
References numberOfIndependentParameters, and upperBoundOfIndependentParameters.
void Flood::MultilayerPerceptron::setDisplayOutOfRangeWarning (bool newDisplayOutOfRangeWarning)
This method sets a new display out of range warning value. If it is set to true a warning message is to be displayed when inputs fall outside minimum and maximums. if it is set to false that warning message is not to be displayed
Parameters:
newDisplayOutOfRangeWarning Display value for the out of range warning.
Definition at line 5525 of file MultilayerPerceptron.cpp.
References displayOutOfRangeWarning.
void Flood::MultilayerPerceptron::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 5539 of file MultilayerPerceptron.cpp.
References display.
void Flood::MultilayerPerceptron::setNumericalEpsilon (double newNumericalEpsilon)
This method sets a new value of epsilon for the computation of the Jacobian matrix by means of numerical differentiation.
Parameters:
newNumericalEpsilon New value for epsilon.
See also:
calculateJacobianTest(Vector<double>).
Definition at line 5492 of file MultilayerPerceptron.cpp.
References numericalEpsilon.
int Flood::MultilayerPerceptron::getNumberOfFreeParameters (void)
This method returns the number of free parameters in the neural network. The number of free parameters is the sum of all the biases, synaptic weights and independent parameters.
See also:
getNumberOfNeuralParameters(void).
getNumberOfIndependentParameters(void).
Definition at line 5595 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), and numberOfIndependentParameters.
Referenced by Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), Flood::QuasiNewtonMethod::calculateBrentMethodTrainRate(), Flood::GradientDescent::calculateBrentMethodTrainRate(), Flood::ConjugateGradient::calculateBrentMethodTrainRate(), Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation(), Flood::QuasiNewtonMethod::calculateGoldenSectionTrainRate(), Flood::GradientDescent::calculateGoldenSectionTrainRate(), Flood::ConjugateGradient::calculateGoldenSectionTrainRate(), Flood::ObjectiveFunctional::calculateGradient(), Flood::ObjectiveFunctional::calculateHessian(), Flood::ObjectiveFunctional::calculatePotentialEvaluation(), Flood::ObjectiveFunctional::calculatePotentialGradient(), Flood::ObjectiveFunctional::calculatePotentialHessian(), Flood::ObjectiveFunctional::calculateVectorHessianProduct(), Flood::EvolutionaryAlgorithm::evaluatePopulation(), Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm(), Flood::RandomSearch::getMinimumAndMaximumValuesOfFreeParameters(), initFreeParametersNormal(), initFreeParametersUniform(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::EvolutionaryAlgorithm::load(), Flood::EvolutionaryAlgorithm::performIntermediateRecombination(), Flood::EvolutionaryAlgorithm::performLineRecombination(), Flood::EvolutionaryAlgorithm::performNormalMutation(), Flood::EvolutionaryAlgorithm::performUniformMutation(), Flood::EvolutionaryAlgorithm::print(), Flood::RandomSearch::RandomSearch(), Flood::RandomSearch::resizeTrainingHistory(), Flood::QuasiNewtonMethod::resizeTrainingHistory(), Flood::NewtonMethod::resizeTrainingHistory(), Flood::GradientDescent::resizeTrainingHistory(), Flood::ConjugateGradient::resizeTrainingHistory(), Flood::EvolutionaryAlgorithm::save(), setFreeParameters(), Flood::EvolutionaryAlgorithm::setIndividual(), Flood::RandomSearch::setMaximumValueOfFreeParameters(), Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters(), Flood::RandomSearch::setMinimumValueOfFreeParameters(), Flood::EvolutionaryAlgorithm::setPopulation(), Flood::EvolutionaryAlgorithm::setPopulationSize(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::GradientDescent::train(), Flood::EvolutionaryAlgorithm::train(), and Flood::ConjugateGradient::train().
Vector< double > Flood::MultilayerPerceptron::getFreeParameters (void)
This method returns the values of the free parameters in the neural network as a single vector. This contains all the biases, synaptic weights and scaled independent parameters.
Definition at line 5663 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::assemble(), getIndependentParameters(), getNeuralParameters(), independentParameters, and scaleIndependentParameters().
Referenced by Flood::ObjectiveFunctional::calculateGradient(), Flood::ObjectiveFunctional::calculateHessian(), Flood::ObjectiveFunctional::calculatePotentialEvaluation(), Flood::ObjectiveFunctional::calculatePotentialGradient(), Flood::ObjectiveFunctional::calculatePotentialHessian(), Flood::ObjectiveFunctional::calculateVectorHessianProduct(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), and Flood::ConjugateGradient::train().
void Flood::MultilayerPerceptron::setFreeParameters (Vector< double > newFreeParameters)
This method sets all the free parameters in the neural network from a single vector.
Parameters:
newFreeParameters New set of free parameter values.
Definition at line 5741 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), getNumberOfNeuralParameters(), Flood::Vector< Type >::getSize(), numberOfIndependentParameters, setIndependentParameters(), setNeuralParameters(), and unscaleIndependentParameters().
Referenced by Flood::ObjectiveFunctional::calculatePotentialEvaluation(), Flood::ObjectiveFunctional::calculatePotentialGradient(), Flood::ObjectiveFunctional::calculatePotentialHessian(), initFreeParametersNormal(), initFreeParametersUniform(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::NewtonMethod::train(), Flood::GradientDescent::train(), Flood::EvolutionaryAlgorithm::train(), and Flood::ConjugateGradient::train().
void Flood::MultilayerPerceptron::initNeuralParametersUniform (void)
This method initializes all the biases and synaptic weights in the newtork at random with values comprised between -1 and +1.
Definition at line 5797 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersUniform (double minimum, double maximum)
This method initializes all the biases and synaptic weights in the neural network at random with values comprised between a minimum and a maximum values.
Parameters:
minimum Minimum initialization value.
maximum Maximum initialization value.
Definition at line 5824 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersUniform (Vector< double > minimum, Vector< double > maximum)
This method initializes all the biases and synaptic weights in the neural network at random, with values comprised between different minimum and maximum numbers for each parameter.
Parameters:
minimum Vector of minimum initialization values.
maximum Vector of maximum initialization values.
Definition at line 5868 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), Flood::Vector< Type >::getSize(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersUniform (Matrix< double > minimumAndMaximum)
This method initializes all the biases and synaptic weights in the neural network at random, with values comprised between a different minimum and maximum numbers for each parameter. All minimum are maximum initialization values must be given from a single matrix. The first row must contain the minimum inizizalization value for each parameter. The second row must contain the maximum inizizalization value for each parameter.
Parameters:
minimumAndMaximum Matrix of minimum and maximum initialization values.
Definition at line 5932 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), getNumberOfNeuralParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersNormal (void)
This method initializes all the biases and synaptic weights in the newtork with random values chosen from a uniform distribution with mean 0 and standard deviation 1.
Definition at line 5999 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersNormal (double mean, double standardDeviation)
This method initializes all the biases and synaptic weights in the neural network with random random values chosen from a normal distribution with a given mean and a given standard deviation.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
Definition at line 6027 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersNormal (Vector< double > mean, Vector< double > standardDeviation)
This method initializes all the biases an synaptic weights in the neural network with random values chosen from normal distributions with different mean and standard deviation for each parameter.
Parameters:
mean Vector of mean values.
standardDeviation Vector of standard deviation values.
Definition at line 6082 of file MultilayerPerceptron.cpp.
References getNumberOfNeuralParameters(), Flood::Vector< Type >::getSize(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initNeuralParametersNormal (Matrix< double > meanAndStandardDeviation)
This method initializes all the biases and synaptic weights in the neural network with random values chosen from normal distributions with different mean and standard deviation for each parameter. All mean and standard deviation values are given from a single matrix. The first row must contain the mean value for each parameter. The second row must contain the standard deviation value for each parameter.
Parameters:
meanAndStandardDeviation Matrix of mean and standard deviation values.
Definition at line 6160 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), getNumberOfNeuralParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), and setNeuralParameters().
void Flood::MultilayerPerceptron::initIndependentParametersUniform (void)
This method initializes the independent parameters associated to the newtork at random with values comprised between -1 and +1.
Definition at line 6238 of file MultilayerPerceptron.cpp.
References independentParameters, and numberOfIndependentParameters.
Referenced by Flood::DeJongFunction::setNumberOfVariables().
void Flood::MultilayerPerceptron::initIndependentParametersUniform (double minimum, double maximum)
This method initializes the independent parameters associated to the neural network at random with values comprised between a minimum and a maximum values.
Parameters:
minimum Minimum initialization value.
maximum Maximum initialization value.
Definition at line 6259 of file MultilayerPerceptron.cpp.
References independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initIndependentParametersUniform (Vector< double > minimum, Vector< double > maximum)
This method initializes the independent parameters associated to the neural network at random with values comprised between different minimum and maximum numbers for each independent parameter.
Parameters:
minimum Vector of minimum initialization values.
maximum Vector of maximum initialization values.
Definition at line 6297 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initIndependentParametersUniform (Matrix< double > minimumAndMaximum)
This method initializes the independent parameters associated to the neural network at random values comprised between different minimum and maximum numbers for each independent parameter. All minimum and maximum values are given from a single matrix. The first row must contain the minimum inizizalization value for each independent parameter. The second row must contain the maximum inizizalization value for each independent parameter.
Parameters:
minimumAndMaximum Matrix of minimum and maximum initialization values.
Definition at line 6356 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initIndependentParametersNormal (void)
This method initializes the independent parameters associated to the newtork with random values chosen from a normal distribution with mean 0 and standard deviation 1.
Definition at line 6419 of file MultilayerPerceptron.cpp.
References independentParameters, and numberOfIndependentParameters.
Referenced by setNumberOfIndependentParameters().
void Flood::MultilayerPerceptron::initIndependentParametersNormal (double mean, double standardDeviation)
This method initializes the independent parameters associated to the neural network with random values chosen from a normal distribution with a given mean and a given standard deviation.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
Definition at line 6440 of file MultilayerPerceptron.cpp.
References independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initIndependentParametersNormal (Vector< double > mean, Vector< double > standardDeviation)
This method initializes the independent parameters associated to the neural network with random values chosen from normal distributions with different mean and standard deviation for each independent parameter.
Parameters:
mean Vector of mean values.
standardDeviation Vector of standard deviation values.
Definition at line 6491 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initIndependentParametersNormal (Matrix< double > meanAndStandardDeviation)
This method initializes the independent parameters associated to the neural network with random values chosen from normal distributions with different mean and standard deviation for each independent parameter. All mean and standard deviation values are given from a single matrix The first row must contain the mean value for each independent parameter. The second row must contain the standard deviation value for each independent parameter.
Parameters:
meanAndStandardDeviation Matrix of mean and standard deviation values.
Definition at line 6560 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), independentParameters, and numberOfIndependentParameters.
void Flood::MultilayerPerceptron::initFreeParametersUniform (void)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values comprised between -1 and +1.
Definition at line 6630 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersUniform (double minimum, double maximum)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values comprised between a given minimum and a given maximum values.
Parameters:
minimum Minimum initialization value.
maximum Maximum initialization value.
Definition at line 6657 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersUniform (Vector< double > minimum, Vector< double > maximum)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values comprised between a different minimum and maximum numbers for each free parameter.
Parameters:
minimum Vector of minimum initialization values.
maximum Vector of maximum initialization values.
Definition at line 6702 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersUniform (Matrix< double > minimumAndMaximum)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) values comprised between a different minimum and maximum numbers for each free parameter. Minimum and maximum initialization values are given from a single matrix. The first row must contain the minimum inizizalization value for each free parameter. The second row must contain the maximum inizizalization value for each free parameter.
Parameters:
minimumAndMaximum Matrix of minimum and maximum initialization values.
Definition at line 6765 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersNormal (void)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values chosen from a normal distribution with mean 0 and standard deviation 1.
Definition at line 6830 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersNormal (double mean, double standardDeviation)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values chosen from a normal distribution with a given mean and a given standard deviation.
Parameters:
mean Mean of normal distribution.
standardDeviation Standard deviation of normal distribution.
Definition at line 6858 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersNormal (Vector< double > mean, Vector< double > standardDeviation)
This method initializes all the free parameters in the neural newtork (biases and synaptic weiths + independent parameters) at random with values chosen from normal distributions with a given mean and a given standard deviation for each free parameter.
Parameters:
mean Vector of minimum initialization values.
standardDeviation Vector of maximum initialization values.
Definition at line 6914 of file MultilayerPerceptron.cpp.
References getNumberOfFreeParameters(), Flood::Vector< Type >::getSize(), and setFreeParameters().
void Flood::MultilayerPerceptron::initFreeParametersNormal (Matrix< double > meanAndStandardDeviation)
This method initializes all the free parameters in the newtork (biases and synaptic weiths + independent parameters) at random with values chosen from normal distributions with a given mean and a given standard deviation for each free parameter. All mean and standard deviation values are given from a single matrix. The first row must contain the mean value for each free parameter. The second row must contain the standard deviation value for each free parameter.
Parameters:
meanAndStandardDeviation Matrix of mean and standard deviation values.
Definition at line 6989 of file MultilayerPerceptron.cpp.
References Flood::Matrix< Type >::getNumberOfColumns(), getNumberOfFreeParameters(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getRow(), and setFreeParameters().
void Flood::MultilayerPerceptron::checkInput (Vector< double > input)
This method chechs whether the inputs to the neural network have the right size. If not, it displays an error message and exits the program. It also checks whether the input values are inside the range defined by the minimum and maximum values, and displays a warning message if they are outside.
Parameters:
input Set of inputs to the neural network.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7072 of file MultilayerPerceptron.cpp.
References displayOutOfRangeWarning, Flood::Vector< Type >::getSize(), maximumOfInputVariables, minimumOfInputVariables, and numberOfInputs.
Referenced by calculateJacobian(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::preprocessInput (Vector< double > input)
This method preprocesses the inputs to the neural network in order to obtain a set of scaled input signals.
Parameters:
input Set of inputs to the neural network.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7127 of file MultilayerPerceptron.cpp.
References display, Flood::Vector< Type >::getSize(), maximumOfInputVariables, MeanAndStandardDeviation, meanOfInputVariables, MinimumAndMaximum, minimumOfInputVariables, None, numberOfInputs, preAndPostProcessingMethod, and standardDeviationOfInputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), calculateJacobian(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::calculateNetInputSignalToHiddenLayer (int index, Vector< double > inputSignalToHiddenLayer)
This method returns the net input signal to every perceptron in the hidden layer as a function of the set of input signals to the neural network.
Parameters:
index Hidden layer index.
inputSignalToHiddenLayer Set of scaled input signals to the hidden layer with the previous index.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7238 of file MultilayerPerceptron.cpp.
References hiddenLayers, and numbersOfHiddenNeurons.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), calculateJacobian(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::calculateOutputSignalFromHiddenLayer (int index, Vector< double > netInputSignalToHiddenLayer)
This method returns the output signals from every perceptron in the hidden layer as a function of their net input signals.
Parameters:
index Hidden layer index.
netInputSignalToHiddenLayer Net input signal to every neuron in the hidden layer with the previous index.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7287 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), hiddenLayers, and numbersOfHiddenNeurons.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), calculateJacobian(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::calculateOutputSignalDerivativeFromHiddenLayer (int index, Vector< double > netInputSignalToHiddenLayer)
This method returns the activation derivative from every perceptron in the hidden layer as a function of their net input signals.
Parameters:
index Hidden layer index.
netInputSignalToHiddenLayer Net input signal to every neuron in the hidden layer with the previous index.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7336 of file MultilayerPerceptron.cpp.
References hiddenLayers, and numbersOfHiddenNeurons.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::calculateNetInputSignalToOutputLayer (Vector< double > outputSignalFromHiddenLayer)
This method returns the net input signal to every perceptron in the ouptut layer as a function of the output signals from the hidden neurons.
Parameters:
outputSignalFromHiddenLayer Output signal from every neuron in the hidden layer.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7386 of file MultilayerPerceptron.cpp.
References numberOfOutputs, and outputLayer.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), calculateJacobian(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::calculateOutputSignal (Vector< double > netInputSignalToOutputLayer)
This method returns the output signal from every perceptron in the ouptut layer as a function of their net input signals.
Parameters:
netInputSignalToOutputLayer Net input signal to every neuron in the output layer.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7432 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfOutputs, and outputLayer.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), calculateJacobianTest(), calculateOutput(), and calculateSensitivityTest().
Vector< double > Flood::MultilayerPerceptron::calculateOutputSignalDerivative (Vector< double > netInputSignalToOutputLayer)
This method returns the output signal derivative from every perceptron in the ouptut layer as a function of their net input signals.
Parameters:
netInputSignalToOutputLayer Net input signal to every neuron in the output layer.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7478 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), numberOfOutputs, and outputLayer.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and calculateJacobian().
Vector< double > Flood::MultilayerPerceptron::postprocessOutputSignal (Vector< double > outputSignal)
This method postprocesses the output signals from the neural network in order to obtain a set of unscaled outputs.
Parameters:
outputSignal Set of output signals from the neural network.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7524 of file MultilayerPerceptron.cpp.
References display, Flood::Vector< Type >::getSize(), maximumOfOutputVariables, MeanAndStandardDeviation, meanOfOutputVariables, MinimumAndMaximum, minimumOfOutputVariables, None, numberOfOutputs, preAndPostProcessingMethod, and standardDeviationOfOutputVariables.
Referenced by Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), and calculateOutput().
Vector< double > Flood::MultilayerPerceptron::applyLowerAndUpperBounds (Vector< double > output)
This method postprocesses the outputs from the neural network in order to obtain a new set of outputs falling in the range defined by the lower and the upper bounds.
Parameters:
output Set of outputs from the neural network.
See also:
calculateOutput.
calculateJacobian.
Definition at line 7635 of file MultilayerPerceptron.cpp.
References Flood::Vector< Type >::getSize(), lowerBoundOfOutputVariables, numberOfOutputs, and upperBoundOfOutputVariables.
Referenced by calculateOutput().
Vector< double > Flood::MultilayerPerceptron::calculateOutput (Vector< double > input)
This method calculates the set of outputs from the neural network in response to a set of inputs, when no boundary conditions ar imposed.
Parameters:
input Set of inputs to the neural network.
See also:
checkInput(Vector<double>).
preprocessInput(Vector<double>).
calculateNetInputSignalToHiddenLayer(Vector<double>).
calculateNetInputSignalToHiddenLayer(Vector<double>).
calculateOutputSignalDerivativeFromHiddenLayer(Vector<double>).
calculateNetInputSignalToOutputLayer(Vector<double>).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(Vector<double>).
postprocessOutputSignal(Vector<double>). applyLowerAndUpperBounds(Vector<double>).
calculateJacobian(Vector<double>).
calculateJacobianTest(Vector<double>).
Definition at line 7700 of file MultilayerPerceptron.cpp.
References applyLowerAndUpperBounds(), calculateNetInputSignalToHiddenLayer(), calculateNetInputSignalToOutputLayer(), calculateOutputSignal(), calculateOutputSignalFromHiddenLayer(), checkInput(), getNumberOfHiddenLayers(), Flood::Vector< Type >::getSize(), numberOfInputs, numberOfOutputs, postprocessOutputSignal(), and preprocessInput().
Referenced by Flood::IsoperimetricProblem::calculateAreaIntegrand(), Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::BrachistochroneProblem::calculateDescentTimeIntegrand(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::PrecipitateDissolutionModeling::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::FedBatchFermenterProblem::calculateEvaluation(), Flood::AircraftLandingProblem::calculateEvaluation(), calculateJacobian(), Flood::AircraftLandingProblem::calculatePitchAngleRateDot(), Flood::CatenaryProblem::calculatePotentialEnergyIntegrand(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::CarProblem::calculateVelocityDot(), Flood::FedBatchFermenterProblem::getBrothVolumeDot(), Flood::FedBatchFermenterProblem::getCellMassConcentrationDot(), Flood::MinimumDragProblem::getDragIntegrand(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::FedBatchFermenterProblem::getProductConcentrationDot(), Flood::FedBatchFermenterProblem::getSubstrateConcentrationDot(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::PrecipitateDissolutionModeling::saveInverseVickersHardnessTest(), Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel(), Flood::MinimumDragProblem::saveResults(), Flood::IsoperimetricProblem::saveResults(), Flood::GeodesicProblem::saveResults(), Flood::FedBatchFermenterProblem::saveResults(), Flood::CatenaryProblem::saveResults(), Flood::CarProblem::saveResults(), Flood::BrachistochroneProblem::saveResults(), Flood::AircraftLandingProblem::saveResults(), and Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel().
Matrix< double > Flood::MultilayerPerceptron::calculateJacobian (Vector< double > input)
This method returns the the Jacobian Matrix of the neural network for a set of inputs, corresponding to the point in input space at which the Jacobian Matrix is to be found. It uses the back-propagation method.
Parameters:
input Set of inputs to the neural network.
See also:
calculateOutput(Vector<double>).
calculateJacobianTest(Vector<double>).
Todo:
This method is only implemented for multilayer perceptrons with one hidden layer. An extension of this algorithm so as to consider any number of hidden layers must be implemented.
Definition at line 7783 of file MultilayerPerceptron.cpp.
References calculateNetInputSignalToHiddenLayer(), calculateNetInputSignalToOutputLayer(), calculateOutputSignalDerivative(), calculateOutputSignalDerivativeFromHiddenLayer(), calculateOutputSignalFromHiddenLayer(), checkInput(), getNumberOfHiddenLayers(), hiddenLayers, numberOfInputs, numberOfOutputs, numbersOfHiddenNeurons, outputLayer, and preprocessInput().
Referenced by Flood::GeodesicProblem::calculateArcLengthIntegrand(), Flood::IsoperimetricProblem::calculateAreaIntegrand(), Flood::BrachistochroneProblem::calculateDescentTimeIntegrand(), calculateJacobian(), Flood::CatenaryProblem::calculateLengthIntegrand(), Flood::IsoperimetricProblem::calculatePerimeterIntegrand(), Flood::CatenaryProblem::calculatePotentialEnergyIntegrand(), and Flood::MinimumDragProblem::getDragIntegrand().
Matrix< double > Flood::MultilayerPerceptron::calculateJacobianTest (Vector< double > input)
This method returns the the Jacobian matrix of the neural network for a set of inputs corresponding to the point in input space at which the Jacobian Matrix is to be found. It uses numerical differentiation.
Parameters:
input,: Set of inputs to the neural network.
See also:
numericalEpsilon.
calculateOutput(Vector<double>).
calculateJacobian(Vector<double>).
Definition at line 7885 of file MultilayerPerceptron.cpp.
References calculateNetInputSignalToHiddenLayer(), calculateNetInputSignalToOutputLayer(), calculateOutputSignal(), calculateOutputSignalFromHiddenLayer(), CentralDifferences, checkInput(), ForwardDifferences, getNumberOfHiddenLayers(), numberOfInputs, numberOfOutputs, numericalDifferentiationMethod, numericalEpsilon, and preprocessInput().
Matrix< double > Flood::MultilayerPerceptron::calculateSensitivityTest (Vector< double > input)
Todo:
The calculus of the sensitivity matrix is only implemented using numerical differentiation. A back-propagation algorithm for that derivatives should be developed.
Definition at line 8066 of file MultilayerPerceptron.cpp.
References calculateNetInputSignalToHiddenLayer(), calculateNetInputSignalToOutputLayer(), calculateOutputSignal(), calculateOutputSignalFromHiddenLayer(), CentralDifferences, checkInput(), ForwardDifferences, getNeuralParameters(), getNumberOfHiddenLayers(), getNumberOfNeuralParameters(), numberOfOutputs, numericalDifferentiationMethod, numericalEpsilon, preprocessInput(), and setNeuralParameters().
void Flood::MultilayerPerceptron::print (void)
This method prints to the screen the members of a multilayer perceptron object:
Number of inputs.
Number of hidden neurons.
Number of outputs.
Hidden layer activation function.
Output layer activation function.
Name of input vaviables.
Name of output variables.
Units of input vaviables.
Units of output variables.
Description of input vaviables.
Description of output variables.
Mean of input variables.
Standard deviation of input variables.
Mean of output variables.
Standard deviation of output variables.
Minimum of input variables.
Maximum of input variables.
Minimum of output variables.
Maximum of output variables.
Lower bound of output variables.
Upper bound of output variables.
Biases and synaptic weights.
Pre and postprocessing method.
Number of independent parameters.
Name of independent parameters.
Units of independent parameters.
Description of independent parameters.
Mean of independent parameters.
Standard deviation of independent parameters.
Minimum of independent parameters.
Maximum of independent parameters.
Lower bound of independent parameters.
Upper bound of independent parameters.
Independent parameters.
Pre and postprocessing method.
Numerical epsilon method.
Numerical differentiation method.
Display out of range warning.
Display.
Numerical epsilon.
Definition at line 8318 of file MultilayerPerceptron.cpp.
void Flood::MultilayerPerceptron::save (char * filename)
This method saves to a data file the members of a multilayer perceptron object:
Number of inputs.
Number of hidden neurons.
Number of outputs.
Hidden layer activation function.
Output layer activation function.
Name of input vaviables.
Name of output variables.
Mean of input variables.
Standard deviation of input variables.
Mean of output variables.
Standard deviation of output variables.
Minimum of input variables.
Maximum of input variables.
Minimum of output variables.
Maximum of output variables.
Biases and synaptic weights.
Pre and postprocessing method.
Number of independent parameters.
Name of independent parameters.
Units of independent parameters.
Description of independent parameters.
Mean of independent parameters.
Standard deviation of independent parameters.
Minimum of independent parameters.
Maximum of independent parameters.
Independent parameters.
Display out of range warning.
Display.
Numerical epsilon.
Parameters:
filename Filename.
See also:
load(char*).
Definition at line 8668 of file MultilayerPerceptron.cpp.
void Flood::MultilayerPerceptron::load (char * filename)
This method loads from a data file the members of a multilayer perceptron object:
Number of inputs.
Number of hidden neurons.
Number of outputs.
Hidden layer activation function.
Output layer activation function.
Name of input vaviables.
Name of output variables.
Units of input vaviables.
Units of output variables.
Description of input vaviables.
Description of output variables.
Mean of input variables.
Standard deviation of input variables.
Mean of output variables.
Standard deviation of output variables.
Minimum of input variables.
Maximum of input variables.
Minimum of output variables.
Maximum of output variables.
Lower bound of output variables.
Upper bound of output variables.
Biases and synaptic weights.
Number of independent parameters.
Name of independent parameters.
Mean of independent parameters.
Standard deviation of independent parameters.
Minimum of independent parameters.
Maximum of independent parameters.
Lower bound of independent parameters.
Upper bound of independent parameters.
Independent parameters.
Pre and postprocessing method.
Numerical epsilon method.
Numerical differentiation method.
Display out of range warning.
Display.
Numerical epsilon.
Please mind about the file format, which is specified in the User's Guide.
Parameters:
filename Filename.
See also:
save(char*).
Definition at line 9073 of file MultilayerPerceptron.cpp.
void Flood::MultilayerPerceptron::saveExpression (char * filename)
This method saves the explicit mathematical expression addressed by the multilayer perceptron to a file.
Parameters:
filename Filename.
Todo:
This method is not fully implemented.
Definition at line 9466 of file MultilayerPerceptron.cpp.
template<class BoundaryConditionsType> Vector<double> Flood::MultilayerPerceptron::calculateOutput (Vector< double > input, BoundaryConditionsType & boundaryConditions) [inline]
This method calculates the set of outputs from the neural network in response to a set of inputs, when boundary conditions are imposed.
Parameters:
input,: Set of inputs to the neural network.
boundaryConditions,: Boundary conditions given by a set of homogeneous and particular solution terms.
See also:
checkInput(Vector<double>).
preprocessInput(Vector<double>).
calculateNetInputSignalToHiddenLayer(Vector<double>).
calculateNetInputSignalToHiddenLayer(Vector<double>).
calculateOutputSignalDerivativeFromHiddenLayer(Vector<double>).
calculateNetInputSignalToOutputLayer(Vector<double>).
calculateOutputSignal(Vector<double>).
calculateOutputSignalDerivative(Vector<double>).
postprocessOutputSignal(Vector<double>).
calculateOutput(Vector<double>).
GeodesicProblem.
BrachistochroneProblem.
CatenaryProblem.
IsoperimetricProblem.
Definition at line 653 of file MultilayerPerceptron.h.
References applyLowerAndUpperBounds(), calculateNetInputSignalToHiddenLayer(), calculateNetInputSignalToOutputLayer(), calculateOutputSignal(), calculateOutputSignalFromHiddenLayer(), checkInput(), getNumberOfHiddenLayers(), numberOfOutputs, postprocessOutputSignal(), and preprocessInput().
template<class BoundaryConditionsType> Matrix<double> Flood::MultilayerPerceptron::calculateJacobian (Vector< double > input, BoundaryConditionsType & boundaryConditions) [inline]
This method returns the the Jacobian matrix of the neural network for a set of inputs, corresponding to the point in input space at which the Jacobian Matrix is to be found. This method applies when boundary conditions are imposed. It uses the back-propagation method.
Parameters:
input,: Set of inputs to the neural network.
boundaryConditions,: Boundary conditions type.
See also:
calculateOutput(Vector<double>).
calculateJacobianTest(Vector<double>).
Todo:
this method is implemented only for one input and one or two output variables. An extension of the algorithm to consider any number of inputs and outputs is required.
Definition at line 731 of file MultilayerPerceptron.h.
References calculateJacobian(), calculateOutput(), numberOfInputs, and numberOfOutputs.
Member Data Documentation
int Flood::MultilayerPerceptron::numberOfInputs [private]
Number of network inputs.
Definition at line 56 of file MultilayerPerceptron.h.
Referenced by calculateJacobian(), calculateJacobianTest(), calculateOutput(), checkInput(), getDescriptionOfSingleInputVariable(), getMaximumOfSingleInputVariable(), getMeanAndStandardDeviationOfInputVariables(), getMeanOfSingleInputVariable(), getMinimumAndMaximumOfInputVariables(), getMinimumOfSingleInputVariable(), getNameOfSingleInputVariable(), getNumberOfInputs(), getStandardDeviationOfSingleInputVariable(), getUnitsOfSingleInputVariable(), MultilayerPerceptron(), preprocessInput(), setDescriptionOfInputVariables(), setDescriptionOfSingleInputVariable(), setMaximumOfInputVariables(), setMaximumOfSingleInputVariable(), setMeanAndStandardDeviationOfIndependentParameters(), setMeanAndStandardDeviationOfInputVariables(), setMeanOfInputVariables(), setMeanOfSingleInputVariable(), setMinimumAndMaximumOfInputVariables(), setMinimumOfInputVariables(), setMinimumOfSingleInputVariable(), setNameOfInputVariables(), setNameOfSingleInputVariable(), setNetworkArchitecture(), setNumbersOfHiddenNeurons(), setStandardDeviationOfInputVariables(), setStandardDeviationOfSingleInputVariable(), setUnitsOfInputVariables(), and setUnitsOfSingleInputVariable().
Vector<int> Flood::MultilayerPerceptron::numbersOfHiddenNeurons [private]
Number of neurons in the hidden layer of the neural network.
Definition at line 60 of file MultilayerPerceptron.h.
Referenced by calculateJacobian(), calculateNetInputSignalToHiddenLayer(), calculateOutputSignalDerivativeFromHiddenLayer(), calculateOutputSignalFromHiddenLayer(), getNeuralParameters(), getNumberOfHiddenLayers(), getNumberOfNeuralParameters(), getNumbersOfHiddenNeurons(), setHiddenLayersActivationFunction(), setNetworkArchitecture(), setNeuralParameters(), and setNumbersOfHiddenNeurons().
int Flood::MultilayerPerceptron::numberOfOutputs [private]
Number of output neurons in the neural network.
Definition at line 64 of file MultilayerPerceptron.h.
Referenced by applyLowerAndUpperBounds(), calculateJacobian(), calculateJacobianTest(), calculateNetInputSignalToOutputLayer(), calculateOutput(), calculateOutputSignal(), calculateOutputSignalDerivative(), calculateSensitivityTest(), getDescriptionOfSingleOutputVariable(), getLowerAndUpperBoundsOfOutputVariables(), getLowerBoundOfSingleOutputVariable(), getMaximumOfSingleOutputVariable(), getMeanAndStandardDeviationOfOutputVariables(), getMeanOfSingleOutputVariable(), getMinimumAndMaximumOfOutputVariables(), getMinimumOfSingleOutputVariable(), getNameOfSingleOutputVariable(), getNeuralParameters(), getNumberOfNeuralParameters(), getNumberOfOutputs(), getStandardDeviationOfSingleOutputVariable(), getUnitsOfSingleOutputVariable(), getUpperBoundOfSingleOutputVariable(), MultilayerPerceptron(), postprocessOutputSignal(), setDescriptionOfOutputVariables(), setDescriptionOfSingleOutputVariable(), setLowerAndUpperBoundsOfOutputVariables(), setLowerBoundOfOutputVariables(), setLowerBoundOfSingleOutputVariable(), setMaximumOfOutputVariables(), setMaximumOfSingleOutputVariable(), setMeanAndStandardDeviationOfOutputVariables(), setMeanOfOutputVariables(), setMeanOfSingleOutputVariable(), setMinimumAndMaximumOfOutputVariables(), setMinimumOfOutputVariables(), setMinimumOfSingleOutputVariable(), setNameOfOutputVariables(), setNameOfSingleOutputVariable(), setNetworkArchitecture(), setNeuralParameters(), setNumbersOfHiddenNeurons(), setOutputLayerActivationFunction(), setStandardDeviationOfOutputVariables(), setStandardDeviationOfSingleOutputVariable(), setUnitsOfOutputVariables(), setUnitsOfSingleOutputVariable(), setUpperBoundOfOutputVariables(), and setUpperBoundOfSingleOutputVariable().
Vector<Perceptron::ActivationFunction> Flood::MultilayerPerceptron::hiddenLayersActivationFunction [private]
Activation function of the hidden neurons.
Definition at line 68 of file MultilayerPerceptron.h.
Referenced by getHiddenLayersActivationFunction(), setHiddenLayersActivationFunction(), setNetworkArchitecture(), and setNumbersOfHiddenNeurons().
Perceptron::ActivationFunction Flood::MultilayerPerceptron::outputLayerActivationFunction [private]
Activation function of the output neurons.
Definition at line 72 of file MultilayerPerceptron.h.
Referenced by getOutputLayerActivationFunction(), MultilayerPerceptron(), setNetworkArchitecture(), setNumbersOfHiddenNeurons(), and setOutputLayerActivationFunction().
Vector< Vector<Perceptron> > Flood::MultilayerPerceptron::hiddenLayers [private]
Network's hidden layer. It is built as a Vector of perceptrons.
Definition at line 76 of file MultilayerPerceptron.h.
Referenced by calculateJacobian(), calculateNetInputSignalToHiddenLayer(), calculateOutputSignalDerivativeFromHiddenLayer(), calculateOutputSignalFromHiddenLayer(), getHiddenLayers(), getNeuralParameters(), getNumberOfNeuralParameters(), setHiddenLayersActivationFunction(), setNetworkArchitecture(), setNeuralParameters(), and setNumbersOfHiddenNeurons().
Vector<Perceptron> Flood::MultilayerPerceptron::outputLayer [private]
Network's output layer. It is built as a Vector of perceptrons.
Definition at line 80 of file MultilayerPerceptron.h.
Referenced by calculateJacobian(), calculateNetInputSignalToOutputLayer(), calculateOutputSignal(), calculateOutputSignalDerivative(), getNeuralParameters(), getNumberOfNeuralParameters(), getOutputLayer(), setNetworkArchitecture(), setNeuralParameters(), setNumbersOfHiddenNeurons(), and setOutputLayerActivationFunction().
Vector<std::string> Flood::MultilayerPerceptron::nameOfInputVariables [private]
Name of input variables.
Definition at line 84 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getNameOfInputVariables(), getNameOfSingleInputVariable(), setNameOfInputVariables(), setNameOfSingleInputVariable(), and setNetworkArchitecture().
Vector<std::string> Flood::MultilayerPerceptron::nameOfOutputVariables [private]
Name of output variables.
Definition at line 88 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getNameOfOutputVariables(), getNameOfSingleOutputVariable(), setNameOfOutputVariables(), setNameOfSingleOutputVariable(), and setNetworkArchitecture().
Vector<std::string> Flood::MultilayerPerceptron::unitsOfInputVariables [private]
Units of input variables.
Definition at line 92 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getUnitsOfInputVariables(), getUnitsOfSingleInputVariable(), setNetworkArchitecture(), setUnitsOfInputVariables(), and setUnitsOfSingleInputVariable().
Vector<std::string> Flood::MultilayerPerceptron::unitsOfOutputVariables [private]
Units of output variables.
Definition at line 96 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getUnitsOfOutputVariables(), getUnitsOfSingleOutputVariable(), setNetworkArchitecture(), setUnitsOfOutputVariables(), and setUnitsOfSingleOutputVariable().
Vector<std::string> Flood::MultilayerPerceptron::descriptionOfInputVariables [private]
Description of input variables.
Definition at line 100 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getDescriptionOfInputVariables(), getDescriptionOfSingleInputVariable(), setDescriptionOfInputVariables(), setDescriptionOfSingleInputVariable(), and setNetworkArchitecture().
Vector<std::string> Flood::MultilayerPerceptron::descriptionOfOutputVariables [private]
Description of output variables.
Definition at line 104 of file MultilayerPerceptron.h.
Referenced by getAllInformation(), getDescriptionOfOutputVariables(), getDescriptionOfSingleOutputVariable(), setDescriptionOfOutputVariables(), setDescriptionOfSingleOutputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::meanOfInputVariables [private]
Mean of input variables.
Definition at line 108 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMeanAndStandardDeviationOfInputVariables(), getMeanOfInputVariables(), getMeanOfSingleInputVariable(), preprocessInput(), setMeanAndStandardDeviationOfInputVariables(), setMeanOfInputVariables(), setMeanOfSingleInputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::standardDeviationOfInputVariables [private]
Standard deviation of input variables.
Definition at line 112 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMeanAndStandardDeviationOfInputVariables(), getStandardDeviationOfInputVariables(), getStandardDeviationOfSingleInputVariable(), preprocessInput(), setMeanAndStandardDeviationOfInputVariables(), setNetworkArchitecture(), setStandardDeviationOfInputVariables(), and setStandardDeviationOfSingleInputVariable().
Vector<double> Flood::MultilayerPerceptron::meanOfOutputVariables [private]
Mean of output variables.
Definition at line 116 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMeanAndStandardDeviationOfOutputVariables(), getMeanOfOutputVariables(), getMeanOfSingleOutputVariable(), postprocessOutputSignal(), setMeanAndStandardDeviationOfOutputVariables(), setMeanOfOutputVariables(), setMeanOfSingleOutputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::standardDeviationOfOutputVariables [private]
Standard deviation of output variables.
Definition at line 120 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMeanAndStandardDeviationOfOutputVariables(), getStandardDeviationOfOutputVariables(), getStandardDeviationOfSingleOutputVariable(), postprocessOutputSignal(), setMeanAndStandardDeviationOfOutputVariables(), setNetworkArchitecture(), setStandardDeviationOfOutputVariables(), and setStandardDeviationOfSingleOutputVariable().
Vector<double> Flood::MultilayerPerceptron::minimumOfInputVariables [private]
Minimum of input variables.
Definition at line 124 of file MultilayerPerceptron.h.
Referenced by checkInput(), getAllStatistics(), getMinimumAndMaximumOfInputVariables(), getMinimumOfInputVariables(), getMinimumOfSingleInputVariable(), preprocessInput(), setMinimumAndMaximumOfInputVariables(), setMinimumOfInputVariables(), setMinimumOfSingleInputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::maximumOfInputVariables [private]
Maximum of input variables.
Definition at line 128 of file MultilayerPerceptron.h.
Referenced by checkInput(), getAllStatistics(), getMaximumOfInputVariables(), getMaximumOfSingleInputVariable(), getMinimumAndMaximumOfInputVariables(), preprocessInput(), setMaximumOfInputVariables(), setMaximumOfSingleInputVariable(), setMinimumAndMaximumOfInputVariables(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::minimumOfOutputVariables [private]
Minimum of output variables.
Definition at line 132 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMinimumAndMaximumOfOutputVariables(), getMinimumOfOutputVariables(), getMinimumOfSingleOutputVariable(), postprocessOutputSignal(), setMinimumAndMaximumOfOutputVariables(), setMinimumOfOutputVariables(), setMinimumOfSingleOutputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::maximumOfOutputVariables [private]
Maximum of output variables.
Definition at line 136 of file MultilayerPerceptron.h.
Referenced by getAllStatistics(), getMaximumOfOutputVariables(), getMaximumOfSingleOutputVariable(), getMinimumAndMaximumOfOutputVariables(), postprocessOutputSignal(), setMaximumOfOutputVariables(), setMaximumOfSingleOutputVariable(), setMinimumAndMaximumOfOutputVariables(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::lowerBoundOfOutputVariables [private]
Lower bound of output variables.
Definition at line 140 of file MultilayerPerceptron.h.
Referenced by applyLowerAndUpperBounds(), getLowerAndUpperBoundsOfOutputVariables(), getLowerBoundOfOutputVariables(), getLowerBoundOfSingleOutputVariable(), setLowerAndUpperBoundsOfOutputVariables(), setLowerBoundOfOutputVariables(), setLowerBoundOfSingleOutputVariable(), and setNetworkArchitecture().
Vector<double> Flood::MultilayerPerceptron::upperBoundOfOutputVariables [private]
Upper bound of output variables.
Definition at line 144 of file MultilayerPerceptron.h.
Referenced by applyLowerAndUpperBounds(), getLowerAndUpperBoundsOfOutputVariables(), getUpperBoundOfOutputVariables(), getUpperBoundOfSingleOutputVariable(), setLowerAndUpperBoundsOfOutputVariables(), setNetworkArchitecture(), setUpperBoundOfOutputVariables(), and setUpperBoundOfSingleOutputVariable().
int Flood::MultilayerPerceptron::numberOfIndependentParameters [private]
Number of independent parameters.
Definition at line 148 of file MultilayerPerceptron.h.
Referenced by getDescriptionOfSingleIndependentParameter(), getIndependentParameters(), getLowerAndUpperBoundsOfIndependentParameters(), getLowerBoundOfSingleIndependentParameter(), getMaximumOfSingleIndependentParameter(), getMeanAndStandardDeviationOfIndependentParameters(), getMeanOfSingleIndependentParameter(), getMinimumAndMaximumOfIndependentParameters(), getMinimumOfSingleIndependentParameter(), getNameOfSingleIndependentParameter(), getNumberOfFreeParameters(), getNumberOfIndependentParameters(), getSingleIndependentParameter(), getStandardDeviationOfSingleIndependentParameter(), getUnitsOfSingleIndependentParameter(), getUpperBoundOfSingleIndependentParameter(), initIndependentParametersNormal(), initIndependentParametersUniform(), MultilayerPerceptron(), scaleIndependentParameters(), setDescriptionOfIndependentParameters(), setDescriptionOfSingleIndependentParameter(), setFreeParameters(), setIndependentParameters(), setLowerAndUpperBoundsOfIndependentParameters(), setLowerBoundOfIndependentParameters(), setLowerBoundOfSingleIndependentParameter(), setMaximumOfIndependentParameters(), setMaximumOfSingleIndependentParameter(), setMeanAndStandardDeviationOfIndependentParameters(), setMeanOfIndependentParameters(), setMeanOfSingleIndependentParameter(), setMinimumAndMaximumOfIndependentParameters(), setMinimumOfIndependentParameters(), setMinimumOfSingleIndependentParameter(), setNameOfIndependentParameters(), setNameOfSingleIndependentParameter(), setNumberOfIndependentParameters(), setSingleIndependentParameter(), setStandardDeviationOfIndependentParameters(), setStandardDeviationOfSingleIndependentParameter(), setUnitsOfIndependentParameters(), setUnitsOfSingleIndependentParameter(), setUpperBoundOfIndependentParameters(), setUpperBoundOfSingleIndependentParameter(), and unscaleIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::independentParameters [private]
Independent parameters.
Definition at line 152 of file MultilayerPerceptron.h.
Referenced by getFreeParameters(), getIndependentParameters(), getSingleIndependentParameter(), initIndependentParametersNormal(), initIndependentParametersUniform(), setIndependentParameters(), setNumberOfIndependentParameters(), and setSingleIndependentParameter().
Vector<std::string> Flood::MultilayerPerceptron::nameOfIndependentParameters [private]
Name of independent parameters.
Definition at line 156 of file MultilayerPerceptron.h.
Referenced by getNameOfIndependentParameters(), getNameOfSingleIndependentParameter(), setNameOfIndependentParameters(), setNameOfSingleIndependentParameter(), and setNumberOfIndependentParameters().
Vector<std::string> Flood::MultilayerPerceptron::unitsOfIndependentParameters [private]
Units of independent parameters.
Definition at line 160 of file MultilayerPerceptron.h.
Referenced by getUnitsOfIndependentParameters(), getUnitsOfSingleIndependentParameter(), setNumberOfIndependentParameters(), setUnitsOfIndependentParameters(), and setUnitsOfSingleIndependentParameter().
Vector<std::string> Flood::MultilayerPerceptron::descriptionOfIndependentParameters [private]
Description of independent parameters.
Definition at line 164 of file MultilayerPerceptron.h.
Referenced by getDescriptionOfIndependentParameters(), getDescriptionOfSingleIndependentParameter(), setDescriptionOfIndependentParameters(), setDescriptionOfSingleIndependentParameter(), and setNumberOfIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::meanOfIndependentParameters [private]
Mean of independent parameters.
Definition at line 168 of file MultilayerPerceptron.h.
Referenced by getMeanAndStandardDeviationOfIndependentParameters(), getMeanOfIndependentParameters(), getMeanOfSingleIndependentParameter(), scaleIndependentParameters(), setMeanAndStandardDeviationOfIndependentParameters(), setMeanOfIndependentParameters(), setMeanOfSingleIndependentParameter(), setNumberOfIndependentParameters(), and unscaleIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::standardDeviationOfIndependentParameters [private]
Standard deviation of independent parameters.
Definition at line 172 of file MultilayerPerceptron.h.
Referenced by getMeanAndStandardDeviationOfIndependentParameters(), getStandardDeviationOfIndependentParameters(), getStandardDeviationOfSingleIndependentParameter(), scaleIndependentParameters(), setMeanAndStandardDeviationOfIndependentParameters(), setNumberOfIndependentParameters(), setStandardDeviationOfIndependentParameters(), setStandardDeviationOfSingleIndependentParameter(), and unscaleIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::minimumOfIndependentParameters [private]
Minimum of independent parameters.
Definition at line 176 of file MultilayerPerceptron.h.
Referenced by getMinimumAndMaximumOfIndependentParameters(), getMinimumOfIndependentParameters(), getMinimumOfSingleIndependentParameter(), scaleIndependentParameters(), setMinimumAndMaximumOfIndependentParameters(), setMinimumOfIndependentParameters(), setMinimumOfSingleIndependentParameter(), setNumberOfIndependentParameters(), and unscaleIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::maximumOfIndependentParameters [private]
Maximum of independent parameters.
Definition at line 180 of file MultilayerPerceptron.h.
Referenced by getMaximumOfIndependentParameters(), getMaximumOfSingleIndependentParameter(), getMinimumAndMaximumOfIndependentParameters(), scaleIndependentParameters(), setMaximumOfIndependentParameters(), setMaximumOfSingleIndependentParameter(), setMinimumAndMaximumOfIndependentParameters(), setNumberOfIndependentParameters(), and unscaleIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::lowerBoundOfIndependentParameters [private]
Lower bound of independent parameters.
Definition at line 184 of file MultilayerPerceptron.h.
Referenced by getIndependentParameters(), getLowerAndUpperBoundsOfIndependentParameters(), getLowerBoundOfIndependentParameters(), getLowerBoundOfSingleIndependentParameter(), getSingleIndependentParameter(), setLowerAndUpperBoundsOfIndependentParameters(), setLowerBoundOfIndependentParameters(), setLowerBoundOfSingleIndependentParameter(), and setNumberOfIndependentParameters().
Vector<double> Flood::MultilayerPerceptron::upperBoundOfIndependentParameters [private]
Upper bound of independent parameters.
Definition at line 188 of file MultilayerPerceptron.h.
Referenced by getIndependentParameters(), getLowerAndUpperBoundsOfIndependentParameters(), getSingleIndependentParameter(), getUpperBoundOfIndependentParameters(), getUpperBoundOfSingleIndependentParameter(), setLowerAndUpperBoundsOfIndependentParameters(), setNumberOfIndependentParameters(), setUpperBoundOfIndependentParameters(), and setUpperBoundOfSingleIndependentParameter().
double Flood::MultilayerPerceptron::numericalEpsilon [private]
Numerical epsilon. It is used for computing the Jacobian matrix of the neural network for a set of input signals by means of numerical differentiation.
Definition at line 193 of file MultilayerPerceptron.h.
Referenced by calculateJacobianTest(), calculateSensitivityTest(), getNumericalEpsilon(), MultilayerPerceptron(), and setNumericalEpsilon().
bool Flood::MultilayerPerceptron::displayOutOfRangeWarning [private]
Display warning messages when inputs are out of the range defined by minimums and maximums.
Definition at line 197 of file MultilayerPerceptron.h.
Referenced by checkInput(), getDisplayOutOfRangeWarning(), MultilayerPerceptron(), and setDisplayOutOfRangeWarning().
bool Flood::MultilayerPerceptron::display [private]
Display messages to screen.
Definition at line 201 of file MultilayerPerceptron.h.
Referenced by getDisplay(), MultilayerPerceptron(), postprocessOutputSignal(), preprocessInput(), scaleIndependentParameters(), setDisplay(), setMeanAndStandardDeviationOfIndependentParameters(), and unscaleIndependentParameters().
PreAndPostProcessingMethod Flood::MultilayerPerceptron::preAndPostProcessingMethod [private]
Pre and post-processing method variable.
Definition at line 205 of file MultilayerPerceptron.h.
Referenced by getPreAndPostProcessingMethod(), MultilayerPerceptron(), postprocessOutputSignal(), preprocessInput(), scaleIndependentParameters(), setPreAndPostProcessingMethod(), and unscaleIndependentParameters().
NumericalDifferentiationMethod Flood::MultilayerPerceptron::numericalDifferentiationMethod [private]
Numerical differentiation method variable.
Definition at line 209 of file MultilayerPerceptron.h.
Referenced by calculateJacobianTest(), calculateSensitivityTest(), getNumericalDifferentiationMethod(), MultilayerPerceptron(), and setNumericalDifferentiationMethod().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/MultilayerPerceptron/MultilayerPerceptron.h
G:/Documents/Flood/Flood/MultilayerPerceptron/MultilayerPerceptron.cpp