Flood: Flood::OrdinaryDifferentialEquations Class Reference
Flood::OrdinaryDifferentialEquations Class Reference
#include <OrdinaryDifferentialEquations.h>
Public Member Functions
OrdinaryDifferentialEquations (void)
General constructor.
~OrdinaryDifferentialEquations (void)
Destructor.
int getNumberOfPoints (void)
This method returns the number of integration points to be used in the Runge-Kutta method.
double getTolerance (void)
This method returns the tolerance to be used in the Runge-Kutta-Fehlberg method.
int getInitialSize (void)
int getWarningSize (void)
int getErrorSize (void)
bool getDisplay (void)
void setNumberOfPoints (int)
void setTolerance (double)
void setInitialSize (int)
void setWarningSize (int)
void setErrorSize (int)
void setDisplay (bool)
void getRungeKuttaIntegral (Vector< double > &, Vector< double > &, double(*f)(double, double), double, double, double)
void getRungeKuttaIntegral (Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double), double(*f2)(double, double, double), double, double, double, double)
void getRungeKuttaIntegral (Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double, double), double(*f2)(double, double, double, double), double(*f3)(double, double, double, double), double, double, double, double, double)
void getRungeKuttaIntegral (Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double, double, double), double(*f2)(double, double, double, double, double), double(*f3)(double, double, double, double, double), double(*f4)(double, double, double, double, double), double, double, double, double, double, double)
void getRungeKuttaIntegral (Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double, double, double, double), double(*f2)(double, double, double, double, double, double), double(*f3)(double, double, double, double, double, double), double(*f4)(double, double, double, double, double, double), double(*f5)(double, double, double, double, double, double), double, double, double, double, double, double, double)
int calculateRungeKuttaFehlbergIntegral (Vector< double > &, Vector< double > &, double(*f)(double, double), double, double, double)
int calculateRungeKuttaFehlbergIntegral (Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double), double(*f2)(double, double, double), double, double, double, double)
int calculateRungeKuttaFehlbergIntegral (Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double, double), double(*f2)(double, double, double, double), double(*f3)(double, double, double, double), double, double, double, double, double)
int calculateRungeKuttaFehlbergIntegral (Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, Vector< double > &, double(*f1)(double, double, double, double, double), double(*f2)(double, double, double, double, double), double(*f3)(double, double, double, double, double), double(*f4)(double, double, double, double, double), double, double, double, double, double, double)
template<class T>
void getRungeKuttaIntegral (T &t, Vector< double > &x, Vector< double > &y, double(T::*f)(double, double), double a, double b, double ya)
template<class T>
void getRungeKuttaIntegral (T &t, Vector< double > &x, Vector< double > &y1, Vector< double > &y2, double(T::*f1)(double, double, double), double(T::*f2)(double, double, double), double a, double b, double y1a, double y2a)
template<class T>
void getRungeKuttaIntegral (T &t, Vector< double > &x, Vector< double > &y1, Vector< double > &y2, Vector< double > &y3, double(T::*f1)(double, double, double, double), double(T::*f2)(double, double, double, double), double(T::*f3)(double, double, double, double), double a, double b, double y1a, double y2a, double y3a)
template<class T>
void getRungeKuttaIntegral (T &t, Vector< double > &x, Vector< double > &y1, Vector< double > &y2, Vector< double > &y3, Vector< double > &y4, double(T::*f1)(double, double, double, double, double), double(T::*f2)(double, double, double, double, double), double(T::*f3)(double, double, double, double, double), double(T::*f4)(double, double, double, double, double), double a, double b, double y1a, double y2a, double y3a, double y4a)
template<class T>
void getRungeKuttaIntegral (T &t, Vector< double > &x, Vector< double > &y1, Vector< double > &y2, Vector< double > &y3, Vector< double > &y4, Vector< double > &y5, double(T::*f1)(double, double, double, double, double, double), double(T::*f2)(double, double, double, double, double, double), double(T::*f3)(double, double, double, double, double, double), double(T::*f4)(double, double, double, double, double, double), double(T::*f5)(double, double, double, double, double, double), double a, double b, double y1a, double y2a, double y3a, double y4a, double y5a)
template<class T>
int calculateRungeKuttaFehlbergIntegral (T &t, Vector< double > &xOut, Vector< double > &yOut, double(T::*f)(double, double), double a, double b, double ya)
template<class T>
int calculateRungeKuttaFehlbergIntegral (T &t, Vector< double > &xOut, Vector< double > &y1Out, Vector< double > &y2Out, double(T::*f1)(double, double, double), double(T::*f2)(double, double, double), double a, double b, double y1a, double y2a)
template<class T>
int calculateRungeKuttaFehlbergIntegral (T &t, Vector< double > &xOut, Vector< double > &y1Out, Vector< double > &y2Out, Vector< double > &y3Out, double(T::*f1)(double, double, double, double), double(T::*f2)(double, double, double, double), double(T::*f3)(double, double, double, double), double a, double b, double y1a, double y2a, double y3a)
template<class T>
int calculateRungeKuttaFehlbergIntegral (T &t, Vector< double > &xOut, Vector< double > &y1Out, Vector< double > &y2Out, Vector< double > &y3Out, Vector< double > &y4Out, double(T::*f1)(double, double, double, double, double), double(T::*f2)(double, double, double, double, double), double(T::*f3)(double, double, double, double, double), double(T::*f4)(double, double, double, double, double), double a, double b, double y1a, double y2a, double y3a, double y4a)
template<class T>
int calculateRungeKuttaFehlbergIntegral (T &t, Vector< double > &xOut, Vector< double > &y1Out, Vector< double > &y2Out, Vector< double > &y3Out, Vector< double > &y4Out, Vector< double > &y5Out, double(T::*f1)(double, double, double, double, double, double), double(T::*f2)(double, double, double, double, double, double), double(T::*f3)(double, double, double, double, double, double), double(T::*f4)(double, double, double, double, double, double), double(T::*f5)(double, double, double, double, double, double), double a, double b, double y1a, double y2a, double y3a, double y4a, double y5a)
Private Attributes
int numberOfPoints
Number of integration points in the Runge-Kutta method.
double tolerance
int initialSize
Initial solution vectors size.
int warningSize
Size of solution vectors at with a warning message is displayed.
int errorSize
Size of solution vectors at with an error is thrown and the program is exited.
bool display
Display messages to screen variable.
Detailed Description
This class contains methods for numerical integration of ordinary differential equations. In particular it implements the Runge-Kutta and the Runge-Kutta-Fehlberg methods for systems consisting of up to five ODEs.
Definition at line 33 of file OrdinaryDifferentialEquations.h.
Constructor & Destructor Documentation
Flood::OrdinaryDifferentialEquations::OrdinaryDifferentialEquations (void)
General constructor.
Definition at line 30 of file OrdinaryDifferentialEquations.cpp.
References display, errorSize, initialSize, numberOfPoints, tolerance, and warningSize.
Flood::OrdinaryDifferentialEquations::~OrdinaryDifferentialEquations (void)
Destructor.
Definition at line 52 of file OrdinaryDifferentialEquations.cpp.
Member Function Documentation
int Flood::OrdinaryDifferentialEquations::getNumberOfPoints (void)
This method returns the number of integration points to be used in the Runge-Kutta method.
Definition at line 66 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
double Flood::OrdinaryDifferentialEquations::getTolerance (void)
This method returns the tolerance to be used in the Runge-Kutta-Fehlberg method.
Definition at line 76 of file OrdinaryDifferentialEquations.cpp.
References tolerance.
int Flood::OrdinaryDifferentialEquations::getInitialSize (void)
This method returns the initial size of the solution vectors for the Runge-Kutta-Fehlberg method. If during integration the number of points required is greater, the algorithm resizes that vectors.
Definition at line 87 of file OrdinaryDifferentialEquations.cpp.
References initialSize.
int Flood::OrdinaryDifferentialEquations::getWarningSize (void)
This method returns the size for the solution vectors at wich a warning message is written to the screen during Runge-Kutta-Fehlberg integration.
See also:
getErrorSize(void).
Definition at line 100 of file OrdinaryDifferentialEquations.cpp.
References warningSize.
int Flood::OrdinaryDifferentialEquations::getErrorSize (void)
This method returns the size of the solution vectors at wich the Runge-Kutta-Fehlberg method throws an error.
See also:
getWarningSize(void).
Definition at line 112 of file OrdinaryDifferentialEquations.cpp.
References errorSize.
bool Flood::OrdinaryDifferentialEquations::getDisplay (void)
This method returns true if messages from this class are to be displayed on the screen, or false if messages from this class are not to be displayed on the screen.
Definition at line 123 of file OrdinaryDifferentialEquations.cpp.
References display.
void Flood::OrdinaryDifferentialEquations::setNumberOfPoints (int newNumberOfPoints)
This method returns sets a new number of integration points to be used in the Runge-Kutta method.
Parameters:
newNumberOfPoints Number of integration points.
Definition at line 137 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
Referenced by Flood::CarProblem::saveResults().
void Flood::OrdinaryDifferentialEquations::setTolerance (double newTolerance)
This method sets a new tolerance to be used in the Runge-Kutta-Fehlberg method.
Parameters:
newTolerance Tolerance in the integration error.
Definition at line 149 of file OrdinaryDifferentialEquations.cpp.
References tolerance.
Referenced by Flood::AircraftLandingProblem::AircraftLandingProblem(), Flood::BrachistochroneProblem::BrachistochroneProblem(), Flood::CarProblem::CarProblem(), Flood::CatenaryProblem::CatenaryProblem(), Flood::GeodesicProblem::GeodesicProblem(), Flood::IsoperimetricProblem::IsoperimetricProblem(), Flood::MinimumDragProblem::MinimumDragProblem(), Flood::MinimumDragProblem::setTolerance(), Flood::IsoperimetricProblem::setTolerance(), Flood::GeodesicProblem::setTolerance(), Flood::FedBatchFermenterProblem::setTolerance(), Flood::CatenaryProblem::setTolerance(), Flood::CarProblem::setTolerance(), and Flood::BrachistochroneProblem::setTolerance().
void Flood::OrdinaryDifferentialEquations::setInitialSize (int newInitialSize)
This method returns sets a new initial size of the solution vectors for the Runge-Kutta-Fehlberg method. If during integration the number of points required is greater, the algorithm resizes that vectors.
Parameters:
newInitialSize Initial size for the solution vectors.
Definition at line 162 of file OrdinaryDifferentialEquations.cpp.
References initialSize.
Referenced by Flood::AircraftLandingProblem::AircraftLandingProblem(), Flood::BrachistochroneProblem::BrachistochroneProblem(), Flood::CarProblem::CarProblem(), Flood::CatenaryProblem::CatenaryProblem(), Flood::GeodesicProblem::GeodesicProblem(), Flood::IsoperimetricProblem::IsoperimetricProblem(), Flood::MinimumDragProblem::MinimumDragProblem(), Flood::MinimumDragProblem::setInitialSize(), Flood::IsoperimetricProblem::setInitialSize(), Flood::GeodesicProblem::setInitialSize(), Flood::FedBatchFermenterProblem::setInitialSize(), Flood::CatenaryProblem::setInitialSize(), Flood::CarProblem::setInitialSize(), and Flood::BrachistochroneProblem::setInitialSize().
void Flood::OrdinaryDifferentialEquations::setWarningSize (int newWarningSize)
This method a new size for the solution vectors at wich a warning message is written to the screen during Runge-Kutta-Fehlberg integration.
See also:
setErrorSize(int).
Definition at line 175 of file OrdinaryDifferentialEquations.cpp.
References warningSize.
void Flood::OrdinaryDifferentialEquations::setErrorSize (int newErrorSize)
This method returns sets a new size for the solution vectors at wich the Runge-Kutta-Fehlberg method throws an error.
See also:
setWarningSize(int).
Definition at line 188 of file OrdinaryDifferentialEquations.cpp.
References errorSize.
void Flood::OrdinaryDifferentialEquations::setDisplay (bool newDisplay)
This method sets a new display value. If it is set to true messages from this class are to be displayed on the screen; if it is set to false messages from this class are not to be displayed on the screen.
Parameters:
newDisplay Display value.
Definition at line 202 of file OrdinaryDifferentialEquations.cpp.
References display.
void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (Vector< double > & x, Vector< double > & y, double(*)(double, double) f, double a, double b, double ya)
This method integrates the differential equation
y' = f(x, y),
where y' is given as a C-style function, from x=a to x=b with initial condition y(a)=ya. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x Pointer to vector with x values.
y Pointer to vector with y values.
f Pointer to C-style function f (state equation for variable y).
a Lower integration limit.
b Upper integration limit.
ya Initial condition for variable y.
Definition at line 229 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
Referenced by Flood::CarProblem::saveResults().
void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (Vector< double > & x, Vector< double > & y1, Vector< double > & y2, double(*)(double, double, double) f1, double(*)(double, double, double) f2, double a, double b, double y1a, double y2a)
This method integrates the system of two differential equations
y1' = f1(x, y1, y2),
y2' = f2(x, y1, y2),
where y1' and y2' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a and y2(a)=y2a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x Pointer to vector with x values.
y1 Pointer to vector with y1 values.
y2 Pointer to vector with y2 values.
f1 Pointer to C-style function f1' (state equation for variable y1).
f2 Pointer to C-style function f2' (state equation for variable y2).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
Definition at line 301 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, double(*)(double, double, double, double) f1, double(*)(double, double, double, double) f2, double(*)(double, double, double, double) f3, double a, double b, double y1a, double y2a, double y3a)
This method integrates the system of three differential equations
y1' = f1(x, y1, y2, y3),
y2' = f2(x, y1, y2, y3),
y3' = f3(x, y1, y2, y3),
where y1', y2' and y3' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a and y3(a)=y3a.
The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x Pointer to vector with x values.
y1 Pointer to vector with y1 values.
y2 Pointer to vector with y2 values.
y3 Pointer to vector with y3 values.
f1 Pointer to C-style function f1 (state equation for variable y1).
f2 Pointer to C-style function f2 (state equation for variable y2).
f3 Pointer to C-style function f3 (state equation for variable y3).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
y3a Initial condition for variable y3.
Definition at line 393 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, Vector< double > & y4, double(*)(double, double, double, double, double) f1, double(*)(double, double, double, double, double) f2, double(*)(double, double, double, double, double) f3, double(*)(double, double, double, double, double) f4, double a, double b, double y1a, double y2a, double y3a, double y4a)
This method integrates the system of four differential equations
y1' = f1(x, y1, y2, y3, y4)
y2' = f2(x, y1, y2, y3, y4)
y3' = f3(x, y1, y2, y3, y4)
y4' = f4(x, y1, y2, y3, y4)
where y1', y2', y3' and y4' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a and y4(a)=y4a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x Pointer to vector with x values.
y1 Pointer to vector with y1 values.
y2 Pointer to vector with y2 values.
y3 Pointer to vector with y3 values.
y4 Pointer to vector with y4 values.
f1 Pointer to C-style function f1 (state equation for variable y1).
f2 Pointer to C-style function f2 (state equation for variable y2).
f3 Pointer to C-style function f3 (state equation for variable y3).
f4 Pointer to C-style function f4 (state equation for variable y4).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
y3a Initial condition for variable y3.
y4a Initial condition for variable y4.
Definition at line 499 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, Vector< double > & y4, Vector< double > & y5, double(*)(double, double, double, double, double, double) f1, double(*)(double, double, double, double, double, double) f2, double(*)(double, double, double, double, double, double) f3, double(*)(double, double, double, double, double, double) f4, double(*)(double, double, double, double, double, double) f5, double a, double b, double y1a, double y2a, double y3a, double y4a, double y5a)
This method integrates the system of five differential equations
y1' = f1(x, y1, y2, y3, y4, y5)
y2' = f2(x, y1, y2, y3, y4, y5)
y3' = f3(x, y1, y2, y3, y4, y5)
y4' = f4(x, y1, y2, y3, y4, y5)
y5' = f5(x, y1, y2, y3, y4, y5)
where y1', y2', y3', y4' and y5' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a, y4(a)=y4a and y5(a)=y5a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x Pointer to vector with x values.
y1 Pointer to vector with y1 values.
y2 Pointer to vector with y2 values.
y3 Pointer to vector with y3 values.
y4 Pointer to vector with y4 values.
y5 Pointer to vector with y5 values.
f1 Pointer to C-style function f1 (state equation for variable y1).
f2 Pointer to C-style function f2 (state equation for variable y2).
f3 Pointer to C-style function f3 (state equation for variable y3).
f4 Pointer to C-style function f4 (state equation for variable y4).
f5 Pointer to C-style function f5 (state equation for variable y5).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
y3a Initial condition for variable y3.
y4a Initial condition for variable y4.
y5a Initial condition for variable y5.
Definition at line 656 of file OrdinaryDifferentialEquations.cpp.
References numberOfPoints.
int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (Vector< double > & xOut, Vector< double > & yOut, double(*)(double, double) f, double a, double b, double ya)
This method integrates the differential equation
y' = f(x, y),
where y' is given as a C-style function, from x=a to x=b with initial condition y(a)=ya. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
xOut Pointer to vector with x values.
yOut Pointer to vector with y values.
f Pointer to C-style function f (state equation for variable y).
a Lower integration limit.
b Upper integration limit.
ya Initial condition for variable y.
Definition at line 763 of file OrdinaryDifferentialEquations.cpp.
References initialSize, and tolerance.
Referenced by Flood::GeodesicProblem::calculateArcLength(), Flood::IsoperimetricProblem::calculateArea(), Flood::BrachistochroneProblem::calculateDescentTime(), Flood::FedBatchFermenterProblem::calculateEvaluation(), Flood::CarProblem::calculateEvaluation(), Flood::AircraftLandingProblem::calculateEvaluation(), Flood::CatenaryProblem::calculateLength(), Flood::IsoperimetricProblem::calculatePerimeter(), Flood::CatenaryProblem::calculatePotentialEnergy(), Flood::MinimumDragProblem::getDrag(), Flood::FedBatchFermenterProblem::print(), Flood::CarProblem::print(), Flood::FedBatchFermenterProblem::saveResults(), and Flood::AircraftLandingProblem::saveResults().
int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, double(*)(double, double, double) f1, double(*)(double, double, double) f2, double a, double b, double y1a, double y2a)
This method integrates the system of two differential equations
y1' = f1(x, y1, y2),
y2' = f2(x, y1, y2),
where y1' and y2' are given as C-syle functions, from x=a to x=b with initial conditions y1(a)=y1a and y2(a)=y2a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
xOut Pointer to vector with x values.
y1Out Pointer to vector with y1 values.
y2Out Pointer to vector with y2 values.
f1 Member method to integrate (state equation for variable y1).
f2 Member method to integrate (state equation for variable y2).
a Lower integration limit.
b,: Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
Definition at line 949 of file OrdinaryDifferentialEquations.cpp.
References initialSize, and tolerance.
int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, Vector< double > & y3Out, double(*)(double, double, double, double) f1, double(*)(double, double, double, double) f2, double(*)(double, double, double, double) f3, double a, double b, double y1a, double y2a, double y3a)
This method integrates the system of three differential equations
y1' = f1(x, y1, y2, y3),
y2' = f2(x, y1, y2, y3),
y3' = f3(x, y1, y2, y3),
where y1', y2' and y3' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a and y3(a)=y3a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
xOut Pointer to vector with x values.
y1Out Pointer to vector with y1 values.
y2Out Pointer to vector with y2 values.
y3Out Pointer to vector with y3 values.
f1 Member method to integrate (state equation for variable y1).
f2 Member method to integrate (state equation for variable y2).
f3 Member method to integrate (state equation for variable y3).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
y3a Initial condition for variable y3.
Definition at line 1184 of file OrdinaryDifferentialEquations.cpp.
References initialSize, and tolerance.
int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, Vector< double > & y3Out, Vector< double > & y4Out, double(*)(double, double, double, double, double) f1, double(*)(double, double, double, double, double) f2, double(*)(double, double, double, double, double) f3, double(*)(double, double, double, double, double) f4, double a, double b, double y1a, double y2a, double y3a, double y4a)
This method integrates the system of four differential equations
y1' = f1(x, y1, y2, y3, y4),
y2' = f2(x, y1, y2, y3, y4),
y3' = f3(x, y1, y2, y3, y4),
y4' = f4(x, y1, y2, y3, y4),
where y1', y2', y3' and y4' are given as C-style functions, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a and y4(a)=y4a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
xOut Pointer to vector with x values.
y1Out Pointer to vector with y1 values.
y2Out Pointer to vector with y2 values.
y3Out Pointer to vector with y3 values.
y4Out Pointer to vector with y4 values.
f1 Member method to integrate (state equation for variable y1).
f2 Member method to integrate (state equation for variable y2).
f3 Member method to integrate (state equation for variable y3).
f4 Member method to integrate (state equation for variable y4).
a Lower integration limit.
b Upper integration limit.
y1a Initial condition for variable y1.
y2a Initial condition for variable y2.
y3a Initial condition for variable y3.
y4a Initial condition for variable y4.
Definition at line 1436 of file OrdinaryDifferentialEquations.cpp.
References initialSize, and tolerance.
template<class T> void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (T & t, Vector< double > & x, Vector< double > & y, double(T::*)(double, double) f, double a, double b, double ya) [inline]
This method integrates the differential equation
y' = f(x, y),
where y' is given as a class member method, from x=a to x=b with initial condition y(a)=ya. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x,: Pointer to vector with x values.
y,: Pointer to vector with y values.
t,: Object constructor containing the member method to integrate (state equation)
f,: Member method to integrate (state equation for variable y).
a,: Lower integration limit.
b,: Upper integration limit.
ya,: Initial condition for variable y.
Definition at line 182 of file OrdinaryDifferentialEquations.h.
References numberOfPoints.
template<class T> void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (T & t, Vector< double > & x, Vector< double > & y1, Vector< double > & y2, double(T::*)(double, double, double) f1, double(T::*)(double, double, double) f2, double a, double b, double y1a, double y2a) [inline]
This method integrates the system of two differential equations
y1' = f1(x, y1, y2),
y2' = f2(x, y1, y2),
where y1' and y2' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a and y2(a)=y2a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x,: Pointer to vector with x values.
y1,: Pointer to vector with y1 values.
y2,: Pointer to vector with y2 values.
t,: Object constructor containing the member methods to integrate (state equations).
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
Definition at line 254 of file OrdinaryDifferentialEquations.h.
References numberOfPoints.
template<class T> void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (T & t, Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, double(T::*)(double, double, double, double) f1, double(T::*)(double, double, double, double) f2, double(T::*)(double, double, double, double) f3, double a, double b, double y1a, double y2a, double y3a) [inline]
This method integrates the system of three differential equations
y1' = f1(x, y1, y2, y3),
y2' = f2(x, y1, y2, y3),
y3' = f3(x, y1, y2, y3),
where y1', y2' and y3' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a and y3(a)=y3a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
x,: Pointer to vector with x values.
y1,: Pointer to vector with y1 values.
y2,: Pointer to vector with y2 values.
y3,: Pointer to vector with y3 values.
t,: Object constructor containing the member methods to integrate (state equations).
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
Definition at line 343 of file OrdinaryDifferentialEquations.h.
References numberOfPoints.
template<class T> void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (T & t, Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, Vector< double > & y4, double(T::*)(double, double, double, double, double) f1, double(T::*)(double, double, double, double, double) f2, double(T::*)(double, double, double, double, double) f3, double(T::*)(double, double, double, double, double) f4, double a, double b, double y1a, double y2a, double y3a, double y4a) [inline]
This method integrates the system of four differential equations
y1' = f1(x, y1, y2, y3, y4),
y2' = f2(x, y1, y2, y3, y4),
y3' = f3(x, y1, y2, y3, y4),
y4' = f4(x, y1, y2, y3, y4),
where y1', y2', y3' and y4' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a and y4(a)=y4a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
x,: Pointer to vector with x values.
y1,: Pointer to vector with y1 values.
y2,: Pointer to vector with y2 values.
y3,: Pointer to vector with y3 values.
y4,: Pointer to vector with y4 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
f4,: Member method to integrate (state equation for variable y4).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
y4a,: Initial condition for variable y4.
Definition at line 447 of file OrdinaryDifferentialEquations.h.
References numberOfPoints.
template<class T> void Flood::OrdinaryDifferentialEquations::getRungeKuttaIntegral (T & t, Vector< double > & x, Vector< double > & y1, Vector< double > & y2, Vector< double > & y3, Vector< double > & y4, Vector< double > & y5, double(T::*)(double, double, double, double, double, double) f1, double(T::*)(double, double, double, double, double, double) f2, double(T::*)(double, double, double, double, double, double) f3, double(T::*)(double, double, double, double, double, double) f4, double(T::*)(double, double, double, double, double, double) f5, double a, double b, double y1a, double y2a, double y3a, double y4a, double y5a) [inline]
This method integrates the system of five differential equations
y1' = f1(x, y1, y2, y3, y4, y5),
y2' = f2(x, y1, y2, y3, y4, y5),
y3' = f3(x, y1, y2, y3, y4, y5),
y4' = f4(x, y1, y2, y3, y4, y5),
y5' = f5(x, y1, y2, y3, y4, y5),
where y1', y2', y3', y4' and y5' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a, y4(a)=y4a and y5(a)=y5a. The method is based on an explicit fourth order Runge-Kutta formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
x,: Pointer to vector with x values.
y1,: Pointer to vector with y1 values.
y2,: Pointer to vector with y2 values.
y3,: Pointer to vector with y3 values.
y4,: Pointer to vector with y4 values.
y5,: Pointer to vector with y5 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
f4,: Member method to integrate (state equation for variable y4).
f5,: Member method to integrate (state equation for variable y5).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
y4a,: Initial condition for variable y4.
y5a,: Initial condition for variable y5.
Definition at line 566 of file OrdinaryDifferentialEquations.h.
References numberOfPoints.
template<class T> int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (T & t, Vector< double > & xOut, Vector< double > & yOut, double(T::*)(double, double) f, double a, double b, double ya) [inline]
This method integrates differential equation
y' = f(x, y),
where y' is given as a class member method, from x=a to x=b and with initial condition y(a)=ya. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
xOut,: Pointer to vector with x values.
yOut,: Pointer to vector with y1 values.
f,: Member method to integrate (state equation for variable y).
a,: Lower integration limit.
b,: Upper integration limit.
ya,: Initial condition for variable y.
Definition at line 672 of file OrdinaryDifferentialEquations.h.
References display, errorSize, initialSize, Flood::Vector< Type >::resize(), tolerance, and warningSize.
template<class T> int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (T & t, Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, double(T::*)(double, double, double) f1, double(T::*)(double, double, double) f2, double a, double b, double y1a, double y2a) [inline]
This method integrates the system of two differential equations
y1' = f1(x, y1, y2),
y2' = f2(x, y1, y2),
where y1' and y2' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a and y2(a)=y2a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
xOut,: Pointer to vector with x values.
y1Out,: Pointer to vector with y1 values.
y2Out,: Pointer to vector with y2 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
Definition at line 895 of file OrdinaryDifferentialEquations.h.
References display, errorSize, initialSize, Flood::Vector< Type >::resize(), tolerance, and warningSize.
template<class T> int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (T & t, Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, Vector< double > & y3Out, double(T::*)(double, double, double, double) f1, double(T::*)(double, double, double, double) f2, double(T::*)(double, double, double, double) f3, double a, double b, double y1a, double y2a, double y3a) [inline]
This method integrates the system of three differential equations
y1' = f1(x, y1, y2, y3),
y2' = f2(x, y1, y2, y3),
y3' = f3(x, y1, y2, y3),
where y1', y2' and y3' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a and y3(a)=y3a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
xOut,: Pointer to vector with x values.
y1Out,: Pointer to vector with y1 values.
y2Out,: Pointer to vector with y2 values.
y3Out,: Pointer to vector with y3 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
Definition at line 1143 of file OrdinaryDifferentialEquations.h.
References display, errorSize, initialSize, Flood::Vector< Type >::resize(), tolerance, and warningSize.
template<class T> int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (T & t, Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, Vector< double > & y3Out, Vector< double > & y4Out, double(T::*)(double, double, double, double, double) f1, double(T::*)(double, double, double, double, double) f2, double(T::*)(double, double, double, double, double) f3, double(T::*)(double, double, double, double, double) f4, double a, double b, double y1a, double y2a, double y3a, double y4a) [inline]
This method integrates the system of four differential equations
y1' = f1(x, y1, y2, y3, y4),
y2' = f2(x, y1, y2, y3, y4),
y3' = f3(x, y1, y2, y3, y4),
y4' = f4(x, y1, y2, y3, y4),
where y1', y2', y3' and y4' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a and y4(a)=y4a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
xOut,: Pointer to vector with x values.
y1Out,: Pointer to vector with y1 values.
y2Out,: Pointer to vector with y2 values.
y3Out,: Pointer to vector with y3 values.
y4Out,: Pointer to vector with y4 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
f4,: Member method to integrate (state equation for variable y4).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
y4a,: Initial condition for variable y4.
Definition at line 1398 of file OrdinaryDifferentialEquations.h.
References display, errorSize, initialSize, Flood::Vector< Type >::resize(), tolerance, and warningSize.
template<class T> int Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral (T & t, Vector< double > & xOut, Vector< double > & y1Out, Vector< double > & y2Out, Vector< double > & y3Out, Vector< double > & y4Out, Vector< double > & y5Out, double(T::*)(double, double, double, double, double, double) f1, double(T::*)(double, double, double, double, double, double) f2, double(T::*)(double, double, double, double, double, double) f3, double(T::*)(double, double, double, double, double, double) f4, double(T::*)(double, double, double, double, double, double) f5, double a, double b, double y1a, double y2a, double y3a, double y4a, double y5a) [inline]
This method integrates the system of five differential equations
y1' = f1(x, y1, y2, y3, y4, y5),
y2' = f2(x, y1, y2, y3, y4, y5),
y3' = f3(x, y1, y2, y3, y4, y5),
y4' = f4(x, y1, y2, y3, y4, y5),
y5' = f5(x, y1, y2, y3, y4, y5),
where y1', y2', y3', y4' and y5' are given as class member methods, from x=a to x=b with initial conditions y1(a)=y1a, y2(a)=y2a, y3(a)=y3a, y4(a)=y4a and y5(a)=y5a. The method is based on an explicit fourth order Runge-Kutta-Fehlberg formula.
Parameters:
t,: Object constructor containing the member methods to integrate (state equations).
xOut,: Pointer to vector with x values.
y1Out,: Pointer to vector with y1 values.
y2Out,: Pointer to vector with y2 values.
y3Out,: Pointer to vector with y3 values.
y4Out,: Pointer to vector with y4 values.
y5Out,: Pointer to vector with y5 values.
f1,: Member method to integrate (state equation for variable y1).
f2,: Member method to integrate (state equation for variable y2).
f3,: Member method to integrate (state equation for variable y3).
f4,: Member method to integrate (state equation for variable y4).
f5,: Member method to integrate (state equation for variable y5).
a,: Lower integration limit.
b,: Upper integration limit.
y1a,: Initial condition for variable y1.
y2a,: Initial condition for variable y2.
y3a,: Initial condition for variable y3.
y4a,: Initial condition for variable y4.
y5a,: Initial condition for variable y4.
Definition at line 1710 of file OrdinaryDifferentialEquations.h.
References display, errorSize, initialSize, Flood::Vector< Type >::resize(), tolerance, and warningSize.
Member Data Documentation
int Flood::OrdinaryDifferentialEquations::numberOfPoints [private]
Number of integration points in the Runge-Kutta method.
Definition at line 41 of file OrdinaryDifferentialEquations.h.
Referenced by getNumberOfPoints(), getRungeKuttaIntegral(), OrdinaryDifferentialEquations(), and setNumberOfPoints().
double Flood::OrdinaryDifferentialEquations::tolerance [private]
Tolerance of error in the Runge-Kutta-Fehlberg method, defined as the difference between 4th and 5th orders of integration.
Definition at line 48 of file OrdinaryDifferentialEquations.h.
Referenced by calculateRungeKuttaFehlbergIntegral(), getTolerance(), OrdinaryDifferentialEquations(), and setTolerance().
int Flood::OrdinaryDifferentialEquations::initialSize [private]
Initial solution vectors size.
Definition at line 52 of file OrdinaryDifferentialEquations.h.
Referenced by calculateRungeKuttaFehlbergIntegral(), getInitialSize(), OrdinaryDifferentialEquations(), and setInitialSize().
int Flood::OrdinaryDifferentialEquations::warningSize [private]
Size of solution vectors at with a warning message is displayed.
Definition at line 56 of file OrdinaryDifferentialEquations.h.
Referenced by calculateRungeKuttaFehlbergIntegral(), getWarningSize(), OrdinaryDifferentialEquations(), and setWarningSize().
int Flood::OrdinaryDifferentialEquations::errorSize [private]
Size of solution vectors at with an error is thrown and the program is exited.
Definition at line 60 of file OrdinaryDifferentialEquations.h.
Referenced by calculateRungeKuttaFehlbergIntegral(), getErrorSize(), OrdinaryDifferentialEquations(), and setErrorSize().
bool Flood::OrdinaryDifferentialEquations::display [private]
Display messages to screen variable.
Definition at line 64 of file OrdinaryDifferentialEquations.h.
Referenced by calculateRungeKuttaFehlbergIntegral(), getDisplay(), OrdinaryDifferentialEquations(), and setDisplay().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/Utilities/OrdinaryDifferentialEquations.h
G:/Documents/Flood/Flood/Utilities/OrdinaryDifferentialEquations.cpp