Flood: Flood::MinimumDragProblem Class Reference
Flood::MinimumDragProblem Class Reference
#include <MinimumDragProblem.h>
Public Member Functions
MinimumDragProblem (MultilayerPerceptron *)
MinimumDragProblem (void)
virtual ~MinimumDragProblem (void)
Destructor.
double getTolerance (void)
int getInitialSize (void)
void setTolerance (double)
void setInitialSize (int)
Vector< double > calculateParticularSolution (Vector< double >)
Vector< double > calculateHomogeneousSolution (Vector< double >)
Vector< double > calculateParticularSolutionDerivative (Vector< double >)
Vector< double > calculateHomogeneousSolutionDerivative (Vector< double >)
double getDragIntegrand (double, double)
double getDrag (void)
double calculateEvaluation (void)
This method returns the evaluation of a multilayer perceptron for the minimum drag problem.
void saveResults (char *)
Private Attributes
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
double tolerance
Tolerance of integration in Runge-Kutta-Fehlberg method.
int initialSize
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the minimum drag problem. The minimum drag problem for the multilayer perceptron is an optimal shape design problem with one input and one output variables, besides two boundary conditions. It is defined by an unconstrained objective fucntional requiring the integration of a function.
See also:
ObjectiveFunctional.
Definition at line 33 of file MinimumDragProblem.h.
Constructor & Destructor Documentation
Flood::MinimumDragProblem::MinimumDragProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a minimum drag problem objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Tolerance = 1.0e-12
Reseve = 1000000
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 42 of file MinimumDragProblem.cpp.
References Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), initialSize, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
Flood::MinimumDragProblem::MinimumDragProblem (void)
Default constructor. It creates a minimum drag problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Tolerance = 1.0e-12
Reseve = 1000000
Definition at line 80 of file MinimumDragProblem.cpp.
References initialSize, ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
Flood::MinimumDragProblem::~MinimumDragProblem (void) [virtual]
Destructor.
Definition at line 94 of file MinimumDragProblem.cpp.
Member Function Documentation
double Flood::MinimumDragProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the drag of an axisymmetric body.
Definition at line 107 of file MinimumDragProblem.cpp.
References tolerance.
int Flood::MinimumDragProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the drag of an axisymmetric body.
Definition at line 118 of file MinimumDragProblem.cpp.
References initialSize.
void Flood::MinimumDragProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the drag of an axisymmetric body. The tolerance of integration must be a small value greater than zero.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 132 of file MinimumDragProblem.cpp.
References ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
void Flood::MinimumDragProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the drag of an axisymmetric body. The initial size must be a big value greater than zero, otherwise resizing will be necessary.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 163 of file MinimumDragProblem.cpp.
References initialSize, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setInitialSize().
Vector< double > Flood::MinimumDragProblem::calculateParticularSolution (Vector< double > input)
This method returns the particular solution term phi0(x) in order to satisfy the boundary conditions for the minimum drag problem. It must hold phi0(xa)=ya if there is a condition y(xa)=ya.
Parameters:
input Value of independent variable x.
See also:
calculateHomogeneousSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 185 of file MinimumDragProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::MinimumDragProblem::calculateHomogeneousSolution (Vector< double > input)
This method returns the homogeneous solution term phi1(x) in order to satisfy the boundary conditions for the minimum drag problem. It must hold phi1(xa)=0 if there is a condition y(xa)=ya.
Parameters:
input Value of independent variable x.
See also:
calculateParticularSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 232 of file MinimumDragProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::MinimumDragProblem::calculateParticularSolutionDerivative (Vector< double > input)
This method returns the derivative of the particular solution term, phi0'(x), which will be used to compute the derivative of the descent curve, y'(x), in the minimum drag problem.
Parameters:
input Value of independent variable x.
See also:
getParticularSolutionSolution.
calculateHomogeneousSolution.
calculateHomogeneousSolutionDerivative.
Definition at line 275 of file MinimumDragProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::MinimumDragProblem::calculateHomogeneousSolutionDerivative (Vector< double > input)
This method returns the derivative of the homogeneous solution term, phi1'(x), which will be used to compute the derivative of the descent curve, y'(x), in the minimum drag problem.
Parameters:
input Value of independent variable x.
See also:
getParticularSolutionSolution.
calculateHomogeneousSolution.
calculateHomogeneousSolutionDerivative.
Definition at line 319 of file MinimumDragProblem.cpp.
References Flood::Vector< Type >::getSize().
double Flood::MinimumDragProblem::getDragIntegrand (double x, double dummy)
This method returns the drag integrand for a value of x.
Parameters:
x Value of independent variable.
dummy Dummy variable used to make this method integrable as an ordinary differential equation.
See also:
getDrag.
Definition at line 360 of file MinimumDragProblem.cpp.
References Flood::MultilayerPerceptron::calculateJacobian(), Flood::MultilayerPerceptron::calculateOutput(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by getDrag().
double Flood::MinimumDragProblem::getDrag (void)
This method integrates the drag integrand function to obtain the drag of the axisymmetric body represented by the neural network. Note that the integral is performed with an ordinary differential equations approach.
See also:
getDragIntegrand.
Definition at line 403 of file MinimumDragProblem.cpp.
References Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), getDragIntegrand(), and ordinaryDifferentialEquations.
Referenced by calculateEvaluation().
double Flood::MinimumDragProblem::calculateEvaluation (void) [virtual]
This method returns the evaluation of a multilayer perceptron for the minimum drag problem.
Implements Flood::ObjectiveFunctional.
Definition at line 425 of file MinimumDragProblem.cpp.
References getDrag(), Flood::ObjectiveFunctional::multilayerPerceptron, and Flood::ObjectiveFunctional::numberOfEvaluations.
void Flood::MinimumDragProblem::saveResults (char * filename)
This method saves the values of the independent and dependent variables for the minimum drag problem to a data file.
Value of independent variariable (x).
Value of dependent variariable (y).
Parameters:
filename Filename.
Definition at line 466 of file MinimumDragProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, and Flood::ObjectiveFunctional::multilayerPerceptron.
Member Data Documentation
OrdinaryDifferentialEquations Flood::MinimumDragProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 40 of file MinimumDragProblem.h.
Referenced by getDrag(), MinimumDragProblem(), setInitialSize(), and setTolerance().
double Flood::MinimumDragProblem::tolerance [private]
Tolerance of integration in Runge-Kutta-Fehlberg method.
Definition at line 44 of file MinimumDragProblem.h.
Referenced by getTolerance(), MinimumDragProblem(), and setTolerance().
int Flood::MinimumDragProblem::initialSize [private]
Initial size of solution vectors for the Runge-Kutta-Fehlberg method.
Definition at line 48 of file MinimumDragProblem.h.
Referenced by getInitialSize(), MinimumDragProblem(), and setInitialSize().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/MinimumDragProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/MinimumDragProblem.cpp