Flood: Flood::AircraftLandingProblem Class Reference
Flood::AircraftLandingProblem Class Reference
#include <AircraftLandingProblem.h>
Public Member Functions
AircraftLandingProblem (MultilayerPerceptron *)
AircraftLandingProblem (void)
virtual ~AircraftLandingProblem (void)
Destructor.
double getShortPeriodGain (void)
This method returns the short period gain value, which is an aircraf property.
double getPathTimeConstant (void)
This method returns the path time constant value, which is an aircraf property.
double getShortPeriodResonantFrequency (void)
This method returns the short period resonant frequency, which is an aircraf property.
double getShortPeriodDampingFactor (void)
This method returns the short period damping factor, which is an aircraf property.
double getVelocity (void)
This method returns the velocity of the aircraft, which is assumed to be constant.
double getInitialPitchAngle (void)
This method returns the initial value for the pitch angle (state variable).
double getInitialPitchAngleRate (void)
This method returns the initial value for the pitch angle rate (state variable).
double getInitialAltitude (void)
This method returns the initial value for the altitude (state variable).
double getInitialAltitudeRate (void)
This method returns the initial value for the altitude rate (state variable).
double getLandingTime (void)
double getTolerance (void)
int getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method.
void setShortPeriodGain (double)
void setShortPeriodResonantFrequency (double)
void setShortPeriodDampingFactor (double)
void setPathTimeConstant (double)
void setVelocity (double)
void setInitialPitchAngle (double)
void setInitialPitchAngleRate (double)
void setInitialAltitude (double)
void setInitialAltitudeRate (double)
void setLandingTime (double)
void setTolerance (double)
void setInitialSize (int)
void setStateVariableWeights (double, double, double, double)
void setLandingVariablesWeights (double, double, double, double)
void setControlWeight (double)
double getPitchAngleRateWeight (double)
double getPitchAngleWeight (double)
double getAltitudeRateWeight (double)
double getAltitudeWeight (double)
double getLandingPitchAngleRateWeight (void)
This method returns the weight factor at landing for the pitch angle.
double getLandingPitchAngleWeight (void)
This method returns the weight factor at landing for the pitch angle.
double getLandingAltitudeRateWeight (void)
This method returns the weight factor at landing for the altitude variable.
double getLandingAltitudeWeight (void)
This method returns the weight factor at landing for the altitude variable.
double getElevatorWeight (void)
This method returns the weight factor for the elevator control.
void printWeights (void)
double calculatePitchAngleRateDot (double, double, double, double, double)
double calculatePitchAngleDot (double, double, double, double, double)
double calculateAltitudeRateDot (double, double, double, double, double)
double calculateAltitudeDot (double, double, double, double, double)
double getPitchAngleGoal (double)
double getPitchAngleRateGoal (double)
double getAltitudeGoal (double)
double getAltitudeRateGoal (double)
double calculateEvaluation (void)
This method returns the performance of a multilayer perceptron for the aircraft landing problem.
void saveResults (char *)
Private Attributes
double pi
Pi value.
double shortPeriodGain
Short period gain aircraf property value.
double shortPeriodResonantFrequency
Shor period resonant frequency aircraft property value.
double shortPeriodDampingFactor
Short period damping factor aircraft property value.
double pathTimeConstant
Path time constant aircraft property value.
double velocity
Velocity of the aircraft, assumed to be constant.
double initialPitchAngle
Initial value for the pitch angle.
double initialPitchAngleRate
Initial value for the pitch angle rate.
double initialAltitude
Initial value for the altitude.
double initialAltitudeRate
Initial value for the altitude rate.
double landingTime
Landing time.
double pitchAngleWeight
Weight factor for the pitch angle history term in the objective functional.
double pitchAngleRateWeight
Weight factor for the pitch angle rate history term in the objective functional.
double altitudeWeight
Weight factor for the altitude history term in the objective functional.
double altitudeRateWeight
Weight factor for the altitude rate history term in the objective functional.
double landingPitchAngleWeight
Weight factor for the pitch angle at the moment of landing term.
double landingPitchAngleRateWeight
Weight factor for the pitch angle rate at the moment of landing term.
double landingAltitudeWeight
Weight factor for the altitude at the moment of landing term.
double landingAltitudeRateWeight
Weight factor for the altitude rate at the moment of landing term.
double elevatorWeight
Weight factor for the elevator deflection angle term.
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
IntegrationOfFunctions integrationOfFunctions
Integration of functions object.
double tolerance
Tolerance in the Runge-Kutta-Fehlberg method.
int initialSize
Initial number of points to be reserved in the Runge-Kutta-Fehlberg method.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the aircraft landing problem. This is an optimal control problem of aeronautical engineering interest, with one control and four state variables, and where the objective functional is evaluated by integrating a system of four ordinary differential equations.
See also:
ObjectiveFunctional.
Definition at line 34 of file AircraftLandingProblem.h.
Constructor & Destructor Documentation
Flood::AircraftLandingProblem::AircraftLandingProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates an aircraft landing problem objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Short period gain = -0.95 (s-1)
Path time constant = 2.5 (s)
Short period resonant frequency = 1.0 (rad/s)
Short period damping factor = 0.5
Velocity = 256.0 (ft/s)
Landing time = 20.0 (s)
Initial pitch angle rate = 0.0 (rad/s)
Initial pitch angle = 0.0781 (rad)
Initial altitude = velocity*landingTime*tan(-flightPathAngle) // (m)
Initial altitude rate = -20.0/3.28084 (m/s)
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object. This neural network will represent the control variable for this system.
Definition at line 47 of file AircraftLandingProblem.cpp.
References altitudeRateWeight, altitudeWeight, elevatorWeight, Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), initialAltitude, initialAltitudeRate, initialPitchAngle, initialPitchAngleRate, initialSize, landingAltitudeRateWeight, landingAltitudeWeight, landingPitchAngleRateWeight, landingPitchAngleWeight, landingTime, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, pathTimeConstant, pi, pitchAngleRateWeight, pitchAngleWeight, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), shortPeriodDampingFactor, shortPeriodGain, shortPeriodResonantFrequency, tolerance, and velocity.
Flood::AircraftLandingProblem::AircraftLandingProblem (void)
Default constructor. It creates an aircraft landing problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Short period gain = -0.95 (s-1)
Path time constant = 2.5 (s)
Short period resonant frequency = 1.0 (rad/s)
Short period damping factor = 0.5
Velocity = 256.0 (ft/s)
Landing time = 20.0 (s)
Initial pitch angle rate = 0.0 (rad/s)
Initial pitch angle = 0.0781 (rad)
Initial altitude = velocity*landingTime*tan(-flightPathAngle) // (m)
Initial altitude rate = -20.0/3.28084 (m/s)
Definition at line 134 of file AircraftLandingProblem.cpp.
References altitudeRateWeight, altitudeWeight, elevatorWeight, initialAltitude, initialAltitudeRate, initialPitchAngle, initialPitchAngleRate, initialSize, landingAltitudeRateWeight, landingAltitudeWeight, landingPitchAngleRateWeight, landingPitchAngleWeight, landingTime, pathTimeConstant, pi, pitchAngleRateWeight, pitchAngleWeight, shortPeriodDampingFactor, shortPeriodGain, shortPeriodResonantFrequency, tolerance, and velocity.
Flood::AircraftLandingProblem::~AircraftLandingProblem (void) [virtual]
Destructor.
Definition at line 172 of file AircraftLandingProblem.cpp.
Member Function Documentation
double Flood::AircraftLandingProblem::getShortPeriodGain (void)
This method returns the short period gain value, which is an aircraf property.
Definition at line 184 of file AircraftLandingProblem.cpp.
References shortPeriodGain.
double Flood::AircraftLandingProblem::getPathTimeConstant (void)
This method returns the path time constant value, which is an aircraf property.
Definition at line 194 of file AircraftLandingProblem.cpp.
References pathTimeConstant.
double Flood::AircraftLandingProblem::getShortPeriodResonantFrequency (void)
This method returns the short period resonant frequency, which is an aircraf property.
Definition at line 204 of file AircraftLandingProblem.cpp.
References shortPeriodResonantFrequency.
double Flood::AircraftLandingProblem::getShortPeriodDampingFactor (void)
This method returns the short period damping factor, which is an aircraf property.
Definition at line 214 of file AircraftLandingProblem.cpp.
References shortPeriodDampingFactor.
double Flood::AircraftLandingProblem::getVelocity (void)
This method returns the velocity of the aircraft, which is assumed to be constant.
Definition at line 224 of file AircraftLandingProblem.cpp.
References velocity.
double Flood::AircraftLandingProblem::getInitialPitchAngle (void)
This method returns the initial value for the pitch angle (state variable).
Definition at line 234 of file AircraftLandingProblem.cpp.
References initialPitchAngle.
double Flood::AircraftLandingProblem::getInitialPitchAngleRate (void)
This method returns the initial value for the pitch angle rate (state variable).
Definition at line 244 of file AircraftLandingProblem.cpp.
References initialPitchAngleRate.
double Flood::AircraftLandingProblem::getInitialAltitude (void)
This method returns the initial value for the altitude (state variable).
Definition at line 254 of file AircraftLandingProblem.cpp.
References initialAltitude.
Referenced by printWeights().
double Flood::AircraftLandingProblem::getInitialAltitudeRate (void)
This method returns the initial value for the altitude rate (state variable).
Definition at line 264 of file AircraftLandingProblem.cpp.
References initialAltitudeRate.
double Flood::AircraftLandingProblem::getLandingTime (void)
This method returns the time duration of the landing process, which is set to a fixed value.
Definition at line 275 of file AircraftLandingProblem.cpp.
References landingTime.
double Flood::AircraftLandingProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating different terms in the objective functional.
Definition at line 286 of file AircraftLandingProblem.cpp.
References tolerance.
int Flood::AircraftLandingProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method.
Definition at line 296 of file AircraftLandingProblem.cpp.
References initialSize.
void Flood::AircraftLandingProblem::setShortPeriodGain (double newShortPeriodGain)
This method sets a new short period gain value. That is, it modifies the properties of the aircraft.
Parameters:
newShortPeriodGain Short period gain value.
Definition at line 308 of file AircraftLandingProblem.cpp.
References shortPeriodGain.
void Flood::AircraftLandingProblem::setShortPeriodResonantFrequency (double newShortPeriodResonantFrequency)
This method sets a new short period resonant frequency. That is, it modifies the properties of the aircraft.
Parameters:
newShortPeriodResonantFrequency Short period resonant frequency.
Definition at line 320 of file AircraftLandingProblem.cpp.
References shortPeriodResonantFrequency.
void Flood::AircraftLandingProblem::setShortPeriodDampingFactor (double newShortPeriodDampingFactor)
This method sets a new short period damping factor. That is, it modifies the properties of the aircraft.
Parameters:
newShortPeriodDampingFactor Short period damping factor.
Definition at line 344 of file AircraftLandingProblem.cpp.
References shortPeriodDampingFactor.
void Flood::AircraftLandingProblem::setPathTimeConstant (double newPathTimeConstant)
This method sets a new path time constant value. That is, it modifies the properties of the aircraft.
Parameters:
newPathTimeConstant Path time constant value.
Definition at line 332 of file AircraftLandingProblem.cpp.
References pathTimeConstant.
void Flood::AircraftLandingProblem::setVelocity (double newVelocity)
This method sets a new aircraft constant velocity during the landing process.
Parameters:
newVelocity Velocity value.
Definition at line 356 of file AircraftLandingProblem.cpp.
References velocity.
void Flood::AircraftLandingProblem::setInitialPitchAngle (double newInitialPitchAngle)
This method sets a new initial value for the pitch angle (state variable).
Parameters:
newInitialPitchAngle Initial pitch angle value.
Definition at line 380 of file AircraftLandingProblem.cpp.
References initialPitchAngle.
void Flood::AircraftLandingProblem::setInitialPitchAngleRate (double newInitialPitchAngleRate)
This method sets a new initial value for the pitch angle rate (state variable).
Parameters:
newInitialPitchAngleRate Initial pitch angle rate.
Definition at line 368 of file AircraftLandingProblem.cpp.
References initialPitchAngleRate.
void Flood::AircraftLandingProblem::setInitialAltitude (double newInitialAltitude)
This method sets a new initial value for the altitude (state variable).
Parameters:
newInitialAltitude Initial altitude value.
Definition at line 403 of file AircraftLandingProblem.cpp.
References initialAltitude.
void Flood::AircraftLandingProblem::setInitialAltitudeRate (double newInitialAltitudeRate)
This method sets a new initial value for the altitude rate (state variable).
Parameters:
newInitialAltitudeRate Initial altitude rate.
Definition at line 392 of file AircraftLandingProblem.cpp.
References initialAltitudeRate.
void Flood::AircraftLandingProblem::setLandingTime (double newLandingTime)
This method sets a new fixed time for the landing process.
Parameters:
newLandingTime Landing time value.
Definition at line 416 of file AircraftLandingProblem.cpp.
References landingTime.
void Flood::AircraftLandingProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the different terms in the objective functional.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 429 of file AircraftLandingProblem.cpp.
References tolerance.
void Flood::AircraftLandingProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 441 of file AircraftLandingProblem.cpp.
References initialSize.
void Flood::AircraftLandingProblem::setStateVariableWeights (double newPitchAngleRateWeight, double newPitchAngleWeight, double newAltitudeRateWeight, double newAltitudeWeight)
This sets the weight factors of the state variables
Parameters:
newPitchAngleRateWeight Pitch angle rate weight factor.
newPitchAngleWeight Pitch angle weight factor.
newAltitudeRateWeight Altitude rate weight factor.
newAltitudeWeight Altitude weight factor.
Definition at line 665 of file AircraftLandingProblem.cpp.
References altitudeRateWeight, altitudeWeight, pitchAngleRateWeight, and pitchAngleWeight.
void Flood::AircraftLandingProblem::setLandingVariablesWeights (double newLandingPitchAngleRateWeight, double newLandingPitchAngleWeight, double newLandingAltitudeRateWeight, double newLandingAltitudeWeight)
This sets the weight factors of the state variables at landing
Parameters:
newLandingPitchAngleRateWeight Landing Pitch Angle Rate Weight Factor.
newLandingPitchAngleWeight Landing Pitch Angle Weight Factor.
newLandingAltitudeRateWeight Landing Altitude Rate Weight Factor.
newLandingAltitudeWeight Landing Altitude Weight Factor.
Definition at line 687 of file AircraftLandingProblem.cpp.
References landingAltitudeRateWeight, landingAltitudeWeight, landingPitchAngleRateWeight, and landingPitchAngleWeight.
void Flood::AircraftLandingProblem::setControlWeight (double newElevatorWeight)
This method sets the weight factors of the state variables.
Parameters:
newElevatorWeight Elevator Control Weight Factor
Definition at line 706 of file AircraftLandingProblem.cpp.
References elevatorWeight.
double Flood::AircraftLandingProblem::getPitchAngleRateWeight (double time)
This method returns the weight factor for the pitch angle rate variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 719 of file AircraftLandingProblem.cpp.
References pitchAngleRateWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getPitchAngleWeight (double time)
This method returns the weight factor for the pitch angle variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 734 of file AircraftLandingProblem.cpp.
References pitchAngleWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getAltitudeRateWeight (double time)
This method returns the weight factor for the altitude rate variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 750 of file AircraftLandingProblem.cpp.
References altitudeRateWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getAltitudeWeight (double time)
This method returns the weight factor for the altitude variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 765 of file AircraftLandingProblem.cpp.
References altitudeWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getLandingPitchAngleRateWeight (void)
This method returns the weight factor at landing for the pitch angle.
Definition at line 777 of file AircraftLandingProblem.cpp.
References landingPitchAngleRateWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getLandingPitchAngleWeight (void)
This method returns the weight factor at landing for the pitch angle.
Definition at line 791 of file AircraftLandingProblem.cpp.
References landingPitchAngleWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getLandingAltitudeRateWeight (void)
This method returns the weight factor at landing for the altitude variable.
Definition at line 804 of file AircraftLandingProblem.cpp.
References landingAltitudeRateWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getLandingAltitudeWeight (void)
This method returns the weight factor at landing for the altitude variable.
Definition at line 816 of file AircraftLandingProblem.cpp.
References landingAltitudeWeight.
Referenced by printWeights(), and saveResults().
double Flood::AircraftLandingProblem::getElevatorWeight (void)
This method returns the weight factor for the elevator control.
Definition at line 829 of file AircraftLandingProblem.cpp.
References elevatorWeight.
Referenced by printWeights(), and saveResults().
void Flood::AircraftLandingProblem::printWeights (void)
This method prints to the screen all the weights used for the different terms in the objective functional expression.
Definition at line 844 of file AircraftLandingProblem.cpp.
References getAltitudeRateWeight(), getAltitudeWeight(), getElevatorWeight(), getInitialAltitude(), getLandingAltitudeRateWeight(), getLandingAltitudeWeight(), getLandingPitchAngleRateWeight(), getLandingPitchAngleWeight(), getPitchAngleRateWeight(), and getPitchAngleWeight().
double Flood::AircraftLandingProblem::calculatePitchAngleRateDot (double time, double pitchAngleRate, double pitchAngle, double altitudeRate, double altitude)
This method depicts the state equation for the pitch angle rate in the aircraft landing problem. It returns the derivative of the pitch angle rate with respect to the time as a function of time, pitch angle rate pitch angle, altitude rate and altitude.
Parameters:
time Actual time.
pitchAngleRate Actual pitch angle rate.
pitchAngle Actual pitch angle.
altitudeRate Actual altitude rate.
altitude Actual altitude.
Definition at line 459 of file AircraftLandingProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::multilayerPerceptron, pathTimeConstant, pi, shortPeriodDampingFactor, shortPeriodGain, shortPeriodResonantFrequency, and velocity.
Referenced by calculateEvaluation(), and saveResults().
double Flood::AircraftLandingProblem::calculatePitchAngleDot (double time, double pitchAngleRate, double pitchAngle, double altitudeRate, double altitude)
This method depicts the state equation for the pitch angle in the aircraft landing problem. It returns the derivative of the pitch angle with respect to the time as a function of time, pitch angle rate pitch angle, altitude rate and altitude.
Parameters:
time Actual time.
pitchAngleRate Actual pitch angle rate.
pitchAngle Actual pitch angle.
altitudeRate Actual altitude rate.
altitude Actual altitude.
Definition at line 516 of file AircraftLandingProblem.cpp.
Referenced by calculateEvaluation(), and saveResults().
double Flood::AircraftLandingProblem::calculateAltitudeRateDot (double time, double pitchAngleRate, double pitchAngle, double altitudeRate, double altitude)
This method depicts the state equation for the altitude rate in the aircraft landing problem. It returns the derivative of the altitude rate with respect to the time as a function of time, pitch angle rate, pitch angle, altitude rate and altitude.
Parameters:
time Actual time.
pitchAngleRate Actual pitch angle rate.
pitchAngle Actual pitch angle.
altitudeRate Actual altitude rate.
altitude Actual altitude.
Definition at line 537 of file AircraftLandingProblem.cpp.
References pathTimeConstant, and velocity.
Referenced by calculateEvaluation(), and saveResults().
double Flood::AircraftLandingProblem::calculateAltitudeDot (double time, double pitchAngleRate, double pitchAngle, double altitudeRate, double altitude)
This method depicts the state equation for the altitude in the aircraft landing problem. It returns the derivative of the altitude with respect to the time as a function of time, pitch angle rate, pitch angle, altitude rate and altitude.
Parameters:
time Actual time.
pitchAngleRate Actual pitch angle rate.
pitchAngle Actual pitch angle.
altitudeRate Actual altitude rate.
altitude Actual altitude.
Definition at line 564 of file AircraftLandingProblem.cpp.
Referenced by calculateEvaluation(), and saveResults().
double Flood::AircraftLandingProblem::getPitchAngleGoal (double time)
This method returns the desired behavior for the pith angle variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 595 of file AircraftLandingProblem.cpp.
References pi.
Referenced by saveResults().
double Flood::AircraftLandingProblem::getPitchAngleRateGoal (double time)
This method returns the desired behavior for the pith angle rate variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 580 of file AircraftLandingProblem.cpp.
Referenced by saveResults().
double Flood::AircraftLandingProblem::getAltitudeGoal (double time)
This method returns the desired behavior for the altitude variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 639 of file AircraftLandingProblem.cpp.
Referenced by calculateEvaluation(), and saveResults().
double Flood::AircraftLandingProblem::getAltitudeRateGoal (double time)
This method returns the desired behavior for the altitude rate variable as a function of time in the aircraft landing problem.
Parameters:
time Time.
Definition at line 615 of file AircraftLandingProblem.cpp.
Referenced by saveResults().
double Flood::AircraftLandingProblem::calculateEvaluation (void) [virtual]
This method returns the performance of a multilayer perceptron for the aircraft landing problem.
Implements Flood::ObjectiveFunctional.
Definition at line 881 of file AircraftLandingProblem.cpp.
References calculateAltitudeDot(), calculateAltitudeRateDot(), Flood::MultilayerPerceptron::calculateOutput(), calculatePitchAngleDot(), calculatePitchAngleRateDot(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), Flood::IntegrationOfFunctions::calculateSimpsonIntegral(), getAltitudeGoal(), initialAltitude, initialAltitudeRate, initialPitchAngle, initialPitchAngleRate, integrationOfFunctions, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, ordinaryDifferentialEquations, and pi.
void Flood::AircraftLandingProblem::saveResults (char * filename)
This method saves the behavior goal, the trajectory and the control signal for the aircraft landing problem to a data file.
Time.
Pitch angle rate goal.
Pitch angle goal.
Altitude rate goal.
Altitude goal.
Pitch angle rate.
Pitch angle.
Altitude rate.
Altitude.
Elevator deflection.
Parameters:
filename Filename.
Definition at line 988 of file AircraftLandingProblem.cpp.
References calculateAltitudeDot(), calculateAltitudeRateDot(), Flood::MultilayerPerceptron::calculateOutput(), calculatePitchAngleDot(), calculatePitchAngleRateDot(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), Flood::ObjectiveFunctional::display, getAltitudeGoal(), getAltitudeRateGoal(), getAltitudeRateWeight(), getAltitudeWeight(), getElevatorWeight(), getLandingAltitudeRateWeight(), getLandingAltitudeWeight(), getLandingPitchAngleRateWeight(), getLandingPitchAngleWeight(), getPitchAngleGoal(), getPitchAngleRateGoal(), getPitchAngleRateWeight(), getPitchAngleWeight(), initialAltitude, initialAltitudeRate, initialPitchAngle, initialPitchAngleRate, landingTime, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, and pi.
Member Data Documentation
double Flood::AircraftLandingProblem::pi [private]
Pi value.
Definition at line 41 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), calculatePitchAngleRateDot(), getPitchAngleGoal(), and saveResults().
double Flood::AircraftLandingProblem::shortPeriodGain [private]
Short period gain aircraf property value.
Definition at line 45 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculatePitchAngleRateDot(), getShortPeriodGain(), and setShortPeriodGain().
double Flood::AircraftLandingProblem::shortPeriodResonantFrequency [private]
Shor period resonant frequency aircraft property value.
Definition at line 49 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculatePitchAngleRateDot(), getShortPeriodResonantFrequency(), and setShortPeriodResonantFrequency().
double Flood::AircraftLandingProblem::shortPeriodDampingFactor [private]
Short period damping factor aircraft property value.
Definition at line 53 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculatePitchAngleRateDot(), getShortPeriodDampingFactor(), and setShortPeriodDampingFactor().
double Flood::AircraftLandingProblem::pathTimeConstant [private]
Path time constant aircraft property value.
Definition at line 57 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateAltitudeRateDot(), calculatePitchAngleRateDot(), getPathTimeConstant(), and setPathTimeConstant().
double Flood::AircraftLandingProblem::velocity [private]
Velocity of the aircraft, assumed to be constant.
Definition at line 61 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateAltitudeRateDot(), calculatePitchAngleRateDot(), getVelocity(), and setVelocity().
double Flood::AircraftLandingProblem::initialPitchAngle [private]
Initial value for the pitch angle.
Definition at line 65 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), getInitialPitchAngle(), saveResults(), and setInitialPitchAngle().
double Flood::AircraftLandingProblem::initialPitchAngleRate [private]
Initial value for the pitch angle rate.
Definition at line 69 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), getInitialPitchAngleRate(), saveResults(), and setInitialPitchAngleRate().
double Flood::AircraftLandingProblem::initialAltitude [private]
Initial value for the altitude.
Definition at line 73 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), getInitialAltitude(), saveResults(), and setInitialAltitude().
double Flood::AircraftLandingProblem::initialAltitudeRate [private]
Initial value for the altitude rate.
Definition at line 77 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), getInitialAltitudeRate(), saveResults(), and setInitialAltitudeRate().
double Flood::AircraftLandingProblem::landingTime [private]
Landing time.
Definition at line 81 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getLandingTime(), saveResults(), and setLandingTime().
double Flood::AircraftLandingProblem::pitchAngleWeight [private]
Weight factor for the pitch angle history term in the objective functional.
Definition at line 85 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getPitchAngleWeight(), and setStateVariableWeights().
double Flood::AircraftLandingProblem::pitchAngleRateWeight [private]
Weight factor for the pitch angle rate history term in the objective functional.
Definition at line 89 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getPitchAngleRateWeight(), and setStateVariableWeights().
double Flood::AircraftLandingProblem::altitudeWeight [private]
Weight factor for the altitude history term in the objective functional.
Definition at line 93 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getAltitudeWeight(), and setStateVariableWeights().
double Flood::AircraftLandingProblem::altitudeRateWeight [private]
Weight factor for the altitude rate history term in the objective functional.
Definition at line 97 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getAltitudeRateWeight(), and setStateVariableWeights().
double Flood::AircraftLandingProblem::landingPitchAngleWeight [private]
Weight factor for the pitch angle at the moment of landing term.
Definition at line 101 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getLandingPitchAngleWeight(), and setLandingVariablesWeights().
double Flood::AircraftLandingProblem::landingPitchAngleRateWeight [private]
Weight factor for the pitch angle rate at the moment of landing term.
Definition at line 105 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getLandingPitchAngleRateWeight(), and setLandingVariablesWeights().
double Flood::AircraftLandingProblem::landingAltitudeWeight [private]
Weight factor for the altitude at the moment of landing term.
Definition at line 109 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getLandingAltitudeWeight(), and setLandingVariablesWeights().
double Flood::AircraftLandingProblem::landingAltitudeRateWeight [private]
Weight factor for the altitude rate at the moment of landing term.
Definition at line 113 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getLandingAltitudeRateWeight(), and setLandingVariablesWeights().
double Flood::AircraftLandingProblem::elevatorWeight [private]
Weight factor for the elevator deflection angle term.
Definition at line 117 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getElevatorWeight(), and setControlWeight().
OrdinaryDifferentialEquations Flood::AircraftLandingProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 121 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), calculateEvaluation(), and saveResults().
IntegrationOfFunctions Flood::AircraftLandingProblem::integrationOfFunctions [private]
Integration of functions object.
Definition at line 125 of file AircraftLandingProblem.h.
Referenced by calculateEvaluation().
double Flood::AircraftLandingProblem::tolerance [private]
Tolerance in the Runge-Kutta-Fehlberg method.
Definition at line 129 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getTolerance(), and setTolerance().
int Flood::AircraftLandingProblem::initialSize [private]
Initial number of points to be reserved in the Runge-Kutta-Fehlberg method.
Definition at line 133 of file AircraftLandingProblem.h.
Referenced by AircraftLandingProblem(), getInitialSize(), and setInitialSize().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/AircraftLandingProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/AircraftLandingProblem.cpp