Flood: Flood::Matrix< Type > Class Template Reference
Flood::Matrix< Type > Class Template Reference
#include <Matrix.h>
Public Member Functions
Matrix (void)
Default constructor. It creates a matrix with zero rows and zero columns.
Matrix (int, int)
Matrix (int, int, const Type &)
Matrix (int, int, const Type *)
Matrix (const Matrix &)
Matrix & operator= (const Matrix &)
Type * operator[] (const int)
Reference operator.
const Type * operator[] (const int) const
Reference operator.
int getNumberOfRows (void) const
This method returns the number of rows in the matrix.
int getNumberOfColumns (void) const
This method returns the number of columns in the matrix.
void resize (int, int)
Vector< Type > getRow (int)
This method returns the row i of the matrix.
Vector< Type > getColumn (int)
This method returns the column j of the matrix.
Matrix< Type > getTranspose (void)
This method returns the transpose of the matrix.
void setRow (int, Vector< Type >)
void setColumn (int, Vector< Type >)
Matrix< Type > operator+ (Type)
Sum matrix+scalar arithmetic operator.
Matrix< Type > operator+ (Matrix< Type >)
Sum matrix+matrix arithmetic operator.
Matrix< Type > operator- (Type)
Difference matrix-scalar arithmetic operator.
Matrix< Type > operator- (Matrix< Type >)
Difference matrix-matrix arithmetic operator.
Matrix< Type > operator* (Type)
Product matrix*scalar arithmetic operator.
Vector< Type > operator* (Vector< Type >)
Product matrix*vector arithmetic operator.
Matrix< Type > operator* (Matrix< Type >)
Product matrix*matrix arithmetic operator.
Matrix< Type > operator/ (Type)
Cocient Matrix/scalar arithmetic operator.
void fillAtRandom (void)
This method fills all the elements in the matrix with random values comprised between -1 and 1.
void fillAtRandom (double, double)
void setToIdentity (void)
Type calculateDeterminant (void)
This method returns the determinant of a square matrix.
Matrix< Type > calculateInverse (void)
void load (char *)
void save (char *)
~Matrix ()
Destructor.
Private Attributes
int numberOfRows
Number of rows in matrix.
int numberOfColumns
Number of columns in matrix.
Type ** matrix
Double pointer to a Type.
Detailed Description
template<class Type>
class Flood::Matrix< Type >
This template class defines a matrix for general purpose use.
See also:
Vector.
Definition at line 38 of file Matrix.h.
Constructor & Destructor Documentation
template<class Type> Flood::Matrix< Type >::Matrix (void) [inline]
Default constructor. It creates a matrix with zero rows and zero columns.
Definition at line 133 of file Matrix.h.
template<class Type> Flood::Matrix< Type >::Matrix (int newNumberOfRows, int newNumberOfColumns) [inline]
Constructor. It creates a matrix with n rows and m columns, containing n*m copies of the default value for Type.
Parameters:
newNumberOfRows Number of rows in Matrix.
newNumberOfColumns Number of columns in Matrix.
Definition at line 146 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Flood::Matrix< Type >::Matrix (int newNumberOfRows, int newNumberOfColumns, const Type & type) [inline]
Constructor. It creates a matrix with n rows and m columns, containing n*m copies of the type value of Type.
Parameters:
newNumberOfRows Number of rows in Matrix.
newNumberOfColumns Number of columns in Matrix.
type Value of Type.
Definition at line 166 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Flood::Matrix< Type >::Matrix (int newNumberOfRows, int newNumberOfColumns, const Type * type) [inline]
Constructor. It creates a matrix with n rows and m columns, containing n*m copies of the type value of Type.
Parameters:
newNumberOfRows Number of rows in Matrix.
newNumberOfColumns Number of columns in Matrix.
type Value of Type.
Definition at line 195 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Flood::Matrix< Type >::Matrix (const Matrix< Type > & oldMatrix) [inline]
Copy constructor. It creates a copy of an existing matrix.
Parameters:
oldMatrix Matrix to be copied.
Definition at line 225 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Flood::Matrix< Type >::~Matrix () [inline]
Destructor.
Definition at line 1096 of file Matrix.h.
References Flood::Matrix< Type >::matrix.
Member Function Documentation
template<class Type> Matrix< Type > & Flood::Matrix< Type >::operator= (const Matrix< Type > & oldMatrix) [inline]
Assignment operator. It assigns to self a copy of an existing Matrix.
Parameters:
oldMatrix Matrix to be assigned.
Definition at line 257 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Type * Flood::Matrix< Type >::operator[] (const int) [inline]
Reference operator.
Definition at line 305 of file Matrix.h.
References Flood::Matrix< Type >::matrix, and Flood::Matrix< Type >::numberOfRows.
template<class Type> const Type * Flood::Matrix< Type >::operator[] (const int) const [inline]
Reference operator.
Definition at line 333 of file Matrix.h.
References Flood::Matrix< Type >::matrix, and Flood::Matrix< Type >::numberOfRows.
template<class Type> int Flood::Matrix< Type >::getNumberOfRows (void) const [inline]
This method returns the number of rows in the matrix.
Definition at line 365 of file Matrix.h.
References Flood::Matrix< Type >::numberOfRows.
Referenced by Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation(), Flood::MultilayerPerceptron::initFreeParametersNormal(), Flood::MultilayerPerceptron::initFreeParametersUniform(), Flood::MultilayerPerceptron::initIndependentParametersNormal(), Flood::MultilayerPerceptron::initIndependentParametersUniform(), Flood::MultilayerPerceptron::initNeuralParametersNormal(), Flood::MultilayerPerceptron::initNeuralParametersUniform(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::Vector< Type >::operator*(), Flood::Matrix< Type >::operator+(), Flood::Matrix< Type >::operator-(), Flood::operator>>(), Flood::InputTargetDataSet::setInputAndTargetData(), Flood::InputTargetDataSet::setInputData(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfIndependentParameters(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfOutputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfIndependentParameters(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfOutputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfIndependentParameters(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfInputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfOutputVariables(), Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters(), Flood::EvolutionaryAlgorithm::setPopulation(), and Flood::InputTargetDataSet::setTargetData().
template<class Type> int Flood::Matrix< Type >::getNumberOfColumns (void) const [inline]
This method returns the number of columns in the matrix.
Definition at line 376 of file Matrix.h.
References Flood::Matrix< Type >::numberOfColumns.
Referenced by Flood::ObjectiveFunctional::calculateBFGSInverseHessianApproximation(), Flood::ObjectiveFunctional::calculateDFPInverseHessianApproximation(), Flood::MultilayerPerceptron::initFreeParametersNormal(), Flood::MultilayerPerceptron::initFreeParametersUniform(), Flood::MultilayerPerceptron::initIndependentParametersNormal(), Flood::MultilayerPerceptron::initIndependentParametersUniform(), Flood::MultilayerPerceptron::initNeuralParametersNormal(), Flood::MultilayerPerceptron::initNeuralParametersUniform(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::Vector< Type >::operator*(), Flood::Matrix< Type >::operator*(), Flood::Matrix< Type >::operator+(), Flood::Matrix< Type >::operator-(), Flood::operator>>(), Flood::InputTargetDataSet::setInputAndTargetData(), Flood::InputTargetDataSet::setInputData(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfIndependentParameters(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfOutputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfOutputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfIndependentParameters(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfInputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfOutputVariables(), Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters(), Flood::EvolutionaryAlgorithm::setPopulation(), and Flood::InputTargetDataSet::setTargetData().
template<class Type> void Flood::Matrix< Type >::resize (int newNumberOfRows, int newNumberOfColumns) [inline]
This method sets new numbers of rows and columns in the vector. It does not initialize the new matrix with the previous values.
Parameters:
newNumberOfRows New number of rows.
newNumberOfColumns New number of columns.
Definition at line 391 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
Referenced by Flood::EvolutionaryAlgorithm::EvolutionaryAlgorithm(), Flood::Matrix< Type >::load(), Flood::RandomSearch::resizeTrainingHistory(), Flood::QuasiNewtonMethod::resizeTrainingHistory(), Flood::NewtonMethod::resizeTrainingHistory(), Flood::GradientDescent::resizeTrainingHistory(), Flood::ConjugateGradient::resizeTrainingHistory(), Flood::InputTargetDataSet::setInputTargetDataSet(), and Flood::EvolutionaryAlgorithm::setPopulationSize().
template<class Type> Vector< Type > Flood::Matrix< Type >::getRow (int i) [inline]
This method returns the row i of the matrix.
Definition at line 433 of file Matrix.h.
References Flood::Matrix< Type >::matrix, and Flood::Matrix< Type >::numberOfColumns.
Referenced by Flood::InputTargetDataSet::calculateAllStatistics(), Flood::CorrectPredictionsAnalysis::calculateCorrectPredictionsRatio(), Flood::SumSquaredError::calculateEvaluation(), Flood::RootMeanSquaredError::calculateEvaluation(), Flood::RegularizedMinkowskiError::calculateEvaluation(), Flood::NormalizedSquaredError::calculateEvaluation(), Flood::MinkowskiError::calculateEvaluation(), Flood::MeanSquaredError::calculateEvaluation(), Flood::SumSquaredError::calculateGradient(), Flood::RootMeanSquaredError::calculateGradient(), Flood::RegularizedMinkowskiError::calculateGradient(), Flood::NormalizedSquaredError::calculateGradient(), Flood::MinkowskiError::calculateGradient(), Flood::MeanSquaredError::calculateGradient(), Flood::SumSquaredError::calculateSquaredErrors(), Flood::EvolutionaryAlgorithm::getIndividual(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::MultilayerPerceptron::initFreeParametersNormal(), Flood::MultilayerPerceptron::initFreeParametersUniform(), Flood::MultilayerPerceptron::initIndependentParametersNormal(), Flood::MultilayerPerceptron::initIndependentParametersUniform(), Flood::MultilayerPerceptron::initNeuralParametersNormal(), Flood::MultilayerPerceptron::initNeuralParametersUniform(), Flood::EvolutionaryAlgorithm::initPopulationNormal(), Flood::EvolutionaryAlgorithm::initPopulationUniform(), Flood::NormalizedSquaredError::NormalizedSquaredError(), Flood::InputTargetDataSet::postprocessMeanAndStandardDeviation(), Flood::InputTargetDataSet::postprocessMinimumAndMaximum(), Flood::InputTargetDataSet::preprocessMeanAndStandardDeviation(), Flood::InputTargetDataSet::preprocessMinimumAndMaximum(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::setInputTargetDataSet(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfIndependentParameters(), Flood::MultilayerPerceptron::setLowerAndUpperBoundsOfOutputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfIndependentParameters(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::setMeanAndStandardDeviationOfOutputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfIndependentParameters(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfInputVariables(), Flood::MultilayerPerceptron::setMinimumAndMaximumOfOutputVariables(), and Flood::RandomSearch::setMinimumAndMaximumValuesOfFreeParameters().
template<class Type> Vector< Type > Flood::Matrix< Type >::getColumn (int j) [inline]
This method returns the column j of the matrix.
Definition at line 451 of file Matrix.h.
References Flood::Matrix< Type >::matrix, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Matrix< Type > Flood::Matrix< Type >::getTranspose (void) [inline]
This method returns the transpose of the matrix.
Definition at line 412 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> void Flood::Matrix< Type >::setRow (int rowIndex, Vector< Type > newRow) [inline]
This method sets new values of a single row in the matrix.
Parameters:
rowIndex Index of row.
newRow New values of single row.
Definition at line 472 of file Matrix.h.
References Flood::Vector< Type >::getSize(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
Referenced by Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfInputData(), Flood::InputTargetDataSet::calculateMeanAndStandardDeviationOfTargetData(), Flood::InputTargetDataSet::calculateMinimumAndMaximumOfInputData(), Flood::InputTargetDataSet::calculateMinimumAndMaximumOfTargetData(), Flood::MultilayerPerceptron::getLowerAndUpperBoundsOfIndependentParameters(), Flood::MultilayerPerceptron::getLowerAndUpperBoundsOfOutputVariables(), Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfIndependentParameters(), Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfInputVariables(), Flood::MultilayerPerceptron::getMeanAndStandardDeviationOfOutputVariables(), Flood::MultilayerPerceptron::getMinimumAndMaximumOfIndependentParameters(), Flood::MultilayerPerceptron::getMinimumAndMaximumOfInputVariables(), Flood::MultilayerPerceptron::getMinimumAndMaximumOfOutputVariables(), Flood::RandomSearch::getMinimumAndMaximumValuesOfFreeParameters(), Flood::LinearRegressionAnalysis::getOutputData(), Flood::CorrectPredictionsAnalysis::getOutputData(), Flood::EvolutionaryAlgorithm::performIntermediateRecombination(), Flood::EvolutionaryAlgorithm::performLineRecombination(), Flood::SumSquaredError::saveInputTargetAndOutput(), Flood::RootMeanSquaredError::saveInputTargetAndOutput(), Flood::RegularizedMinkowskiError::saveInputTargetAndOutput(), Flood::NormalizedSquaredError::saveInputTargetAndOutput(), Flood::MinkowskiError::saveInputTargetAndOutput(), Flood::MeanSquaredError::saveInputTargetAndOutput(), Flood::EvolutionaryAlgorithm::setIndividual(), Flood::RandomSearch::train(), Flood::QuasiNewtonMethod::train(), Flood::GradientDescent::train(), and Flood::ConjugateGradient::train().
template<class Type> void Flood::Matrix< Type >::setColumn (int columnIndex, Vector< Type > newColumn) [inline]
This method sets new values of a single column in the matrix.
Parameters:
columnIndex Index of column.
newColumn New values of single column.
Definition at line 521 of file Matrix.h.
References Flood::Vector< Type >::getSize(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator+ (Type scalar) [inline]
Sum matrix+scalar arithmetic operator.
Definition at line 857 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator+ (Matrix< Type > otherMatrix) [inline]
Sum matrix+matrix arithmetic operator.
Definition at line 878 of file Matrix.h.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator- (Type scalar) [inline]
Difference matrix-scalar arithmetic operator.
Definition at line 919 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator- (Matrix< Type > otherMatrix) [inline]
Difference matrix-matrix arithmetic operator.
Definition at line 940 of file Matrix.h.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator* (Type scalar) [inline]
Product matrix*scalar arithmetic operator.
Definition at line 981 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Vector< Type > Flood::Matrix< Type >::operator* (Vector< Type > vector) [inline]
Product matrix*vector arithmetic operator.
Definition at line 1002 of file Matrix.h.
References Flood::Vector< Type >::getSize(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator* (Matrix< Type > otherMatrix) [inline]
Product matrix*matrix arithmetic operator.
Definition at line 1047 of file Matrix.h.
References Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<typename Type> Matrix< Type > Flood::Matrix< Type >::operator/ (Type scalar) [inline]
Cocient Matrix/scalar arithmetic operator.
Definition at line 1075 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> void Flood::Matrix< Type >::fillAtRandom (void) [inline]
This method fills all the elements in the matrix with random values comprised between -1 and 1.
Definition at line 567 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> void Flood::Matrix< Type >::fillAtRandom (double minimum, double maximum) [inline]
This method fills all the elements in the matrix with random values comprised between a minimum and a maximum values.
Parameters:
minimum Minimum possible value.
maximum Maximum possible value.
Definition at line 592 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> void Flood::Matrix< Type >::setToIdentity (void) [inline]
This method sets the diagonal elements in the matrix with ones and the rest elements with zeros. The matrix must be square.
Definition at line 631 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
template<class Type> Type Flood::Matrix< Type >::calculateDeterminant (void) [inline]
This method returns the determinant of a square matrix.
Definition at line 673 of file Matrix.h.
References Flood::Matrix< Type >::calculateDeterminant(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
Referenced by Flood::Matrix< Type >::calculateDeterminant(), and Flood::Matrix< Type >::calculateInverse().
template<class Type> Matrix< Type > Flood::Matrix< Type >::calculateInverse (void) [inline]
This method returns the inverse of a square matrix. An error message is printed if the matrix is singular.
Definition at line 749 of file Matrix.h.
References Flood::Matrix< Type >::calculateDeterminant(), Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
Referenced by Flood::ObjectiveFunctional::calculateInverseHessian().
template<class Type> void Flood::Matrix< Type >::load (char * filename) [inline]
This method loads the numbers of rows and columns and the values of the matrix from a data file.
Parameters:
filename Filename.
Definition at line 1158 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, Flood::Matrix< Type >::numberOfRows, and Flood::Matrix< Type >::resize().
template<class Type> void Flood::Matrix< Type >::save (char * filename) [inline]
This method saves the numbers of rows and columns and the values of the matrix to a data file.
Parameters:
filename Filename.
Definition at line 1204 of file Matrix.h.
References Flood::Matrix< Type >::matrix, Flood::Matrix< Type >::numberOfColumns, and Flood::Matrix< Type >::numberOfRows.
Member Data Documentation
template<class Type> int Flood::Matrix< Type >::numberOfRows [private]
Number of rows in matrix.
Definition at line 45 of file Matrix.h.
Referenced by Flood::Matrix< Type >::calculateDeterminant(), Flood::Matrix< Type >::calculateInverse(), Flood::Matrix< Type >::fillAtRandom(), Flood::Matrix< Type >::getColumn(), Flood::Matrix< Type >::getNumberOfRows(), Flood::Matrix< Type >::getTranspose(), Flood::Matrix< Type >::load(), Flood::Matrix< Type >::Matrix(), Flood::Matrix< Type >::operator*(), Flood::Matrix< Type >::operator+(), Flood::Matrix< Type >::operator-(), Flood::Matrix< Type >::operator/(), Flood::operator<<(), Flood::Matrix< Type >::operator=(), Flood::operator>>(), Flood::Matrix< Type >::operator[](), Flood::Matrix< Type >::resize(), Flood::Matrix< Type >::save(), Flood::Matrix< Type >::setColumn(), Flood::Matrix< Type >::setRow(), and Flood::Matrix< Type >::setToIdentity().
template<class Type> int Flood::Matrix< Type >::numberOfColumns [private]
Number of columns in matrix.
Definition at line 49 of file Matrix.h.
Referenced by Flood::Matrix< Type >::calculateDeterminant(), Flood::Matrix< Type >::calculateInverse(), Flood::Matrix< Type >::fillAtRandom(), Flood::Matrix< Type >::getNumberOfColumns(), Flood::Matrix< Type >::getRow(), Flood::Matrix< Type >::getTranspose(), Flood::Matrix< Type >::load(), Flood::Matrix< Type >::Matrix(), Flood::Matrix< Type >::operator*(), Flood::Matrix< Type >::operator+(), Flood::Matrix< Type >::operator-(), Flood::Matrix< Type >::operator/(), Flood::operator<<(), Flood::Matrix< Type >::operator=(), Flood::operator>>(), Flood::Matrix< Type >::resize(), Flood::Matrix< Type >::save(), Flood::Matrix< Type >::setColumn(), Flood::Matrix< Type >::setRow(), and Flood::Matrix< Type >::setToIdentity().
template<class Type> Type** Flood::Matrix< Type >::matrix [private]
Double pointer to a Type.
Definition at line 53 of file Matrix.h.
Referenced by Flood::Matrix< Type >::calculateDeterminant(), Flood::Matrix< Type >::calculateInverse(), Flood::Matrix< Type >::fillAtRandom(), Flood::Matrix< Type >::getColumn(), Flood::Matrix< Type >::getRow(), Flood::Matrix< Type >::getTranspose(), Flood::Matrix< Type >::load(), Flood::Matrix< Type >::Matrix(), Flood::Matrix< Type >::operator*(), Flood::Matrix< Type >::operator+(), Flood::Matrix< Type >::operator-(), Flood::Matrix< Type >::operator/(), Flood::Matrix< Type >::operator=(), Flood::Matrix< Type >::operator[](), Flood::Matrix< Type >::resize(), Flood::Matrix< Type >::save(), Flood::Matrix< Type >::setColumn(), Flood::Matrix< Type >::setRow(), Flood::Matrix< Type >::setToIdentity(), and Flood::Matrix< Type >::~Matrix().
The documentation for this class was generated from the following file:
G:/Documents/Flood/Flood/Utilities/Matrix.h