Flood: Flood::PrecipitateDissolutionModeling Class Reference
Flood::PrecipitateDissolutionModeling Class Reference
#include <PrecipitateDissolutionModeling.h>
Public Member Functions
PrecipitateDissolutionModeling (MultilayerPerceptron *)
PrecipitateDissolutionModeling (void)
virtual ~PrecipitateDissolutionModeling (void)
Destructor.
double getMinimumVickersHardness (void)
double getMaximumVickersHardness (void)
double getReferenceTemperature (void)
double getReferenceTime (void)
double getMinkowskiParameter (void)
This method returns the Minkowski parameter (R-exponent) in the objective functional expression.
double getMinkowskiErrorWeight (void)
This method returns the weight of the Minkowski error term in the objective functional expression.
double getRegularizationWeight (void)
void setMinimumVickersHardness (double)
void setMaximumVickersHardness (double)
void setReferenceTemperature (double)
void setReferenceTime (double)
void setMinkowskiParameter (double)
void setMinkowskiErrorWeight (double)
void setRegularizationWeight (double)
void loadVickersHardnessTest (char *)
double getFullDissolutionTime (double)
double getVolumetricFraction (double)
double getVickersHardness (double)
Vector< double > getVolumetricFractionData (void)
Vector< double > getNormalizedTimeData (void)
double calculateEvaluation (void)
void print (void)
void printVickersHardnessTest (void)
void savePrecipitateDissolutionModel (char *)
void saveVickersHardnessModel (char *)
void saveInverseVickersHardnessTest (char *)
Private Attributes
int numberOfSamples
Number of samples in Vickers hardness test.
Vector< double > timeData
Vector containing the time measurements for each sample in the test.
Vector< double > temperatureData
Vector containing the temperature measurements for each sample in the test.
Vector< double > vickersHardnessData
Vector containing the Vickers hardness measurements for each sample in the test.
double universalGasConstant
Universal gas constant R.
double referenceTemperature
Reference temperature of aluminium alloy.
double referenceTime
Reference time of aluminium alloy.
double minimumVickersHardness
Minimum Vickers hardness of aluminium alloy.
double maximumVickersHardness
Maximum Vickers hardness of aluminium alloy.
double minkowskiParameter
Minkowski parameter in the objective functional expression.
double minkowskiErrorWeight
Weight value of the Minkowski error term in the objective functional expression.
double regularizationWeight
Weight value of the regularization term in the objective functional expression.
Detailed Description
This class represents the objective functional of a multilayer perceptron for modeling the dissolution rate of hardening precipitates in aluminium alloys.
See also:
ObjectiveFunctional.
Definition at line 32 of file PrecipitateDissolutionModeling.h.
Constructor & Destructor Documentation
Flood::PrecipitateDissolutionModeling::PrecipitateDissolutionModeling (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a dissolution modeling objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Number of samples = 0;
Reference time = 16.0; // s
Universal gas constant = 8.314e-3; // kJ / mol K
Reference temperature = 623.0; // K
Minimum Vickers hardness = 73.8;
Maximum Vickers Hardness = 203.1;
Minkowski parameter = 2.0;
Minkowski error weight = 1.0;
Regularization weight = 0.0;
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 48 of file PrecipitateDissolutionModeling.cpp.
References Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), maximumVickersHardness, minimumVickersHardness, minkowskiErrorWeight, minkowskiParameter, Flood::ObjectiveFunctional::multilayerPerceptron, numberOfSamples, referenceTemperature, referenceTime, regularizationWeight, and universalGasConstant.
Flood::PrecipitateDissolutionModeling::PrecipitateDissolutionModeling (void)
Default constructor. It creates a thermal properties of metals estimation problem objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Number of samples = 0;
Reference time = 16.0; // s
Universal gas constant = 8.314e-3; // kJ / mol K
Reference temperature = 623.0; // K
Minimum Vickers hardness = 73.8;
Maximum Vickers Hardness = 203.1;
Minkowski parameter = 2.0;
Minkowski error weight = 1.0;
Regularization weight = 0.0;
Definition at line 103 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness, minimumVickersHardness, minkowskiErrorWeight, minkowskiParameter, numberOfSamples, referenceTemperature, referenceTime, regularizationWeight, and universalGasConstant.
Flood::PrecipitateDissolutionModeling::~PrecipitateDissolutionModeling (void) [virtual]
Destructor.
Definition at line 125 of file PrecipitateDissolutionModeling.cpp.
Member Function Documentation
double Flood::PrecipitateDissolutionModeling::getMinimumVickersHardness (void)
This method returns the final hardness after complete dissolution of precipitates of an aluminium alloy.
See also:
getMaximumVickersHardness.
Definition at line 140 of file PrecipitateDissolutionModeling.cpp.
References minimumVickersHardness.
double Flood::PrecipitateDissolutionModeling::getMaximumVickersHardness (void)
This method returns the initial in the hardened state of an aluminium alloy.
See also:
getMaximumVickersHardness.
Definition at line 152 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness.
double Flood::PrecipitateDissolutionModeling::getReferenceTemperature (void)
This method returns the temperature of reference associated to the time of reference for complete dissolution.
See also:
getReferenceTime.
Definition at line 164 of file PrecipitateDissolutionModeling.cpp.
References referenceTemperature.
double Flood::PrecipitateDissolutionModeling::getReferenceTime (void)
This method returns the reference time for complete dissolution of the precipitates at the reference temperature.
See also:
getReferenceTemperature.
Definition at line 177 of file PrecipitateDissolutionModeling.cpp.
References referenceTime.
double Flood::PrecipitateDissolutionModeling::getMinkowskiParameter (void)
This method returns the Minkowski parameter (R-exponent) in the objective functional expression.
Definition at line 187 of file PrecipitateDissolutionModeling.cpp.
References minkowskiParameter.
double Flood::PrecipitateDissolutionModeling::getMinkowskiErrorWeight (void)
This method returns the weight of the Minkowski error term in the objective functional expression.
Definition at line 197 of file PrecipitateDissolutionModeling.cpp.
References minkowskiErrorWeight.
double Flood::PrecipitateDissolutionModeling::getRegularizationWeight (void)
This method returns the weight of the regularization term (biases and synaptic weights decay) in the objective functional expression.
Definition at line 208 of file PrecipitateDissolutionModeling.cpp.
References regularizationWeight.
void Flood::PrecipitateDissolutionModeling::setMinimumVickersHardness (double newMinimumVickersHardness)
This method sets a new final hardness after complete dissolution of precipitates of an aluminium alloy.
Parameters:
newMinimumVickersHardness Minimum Vickers hardness value.
See also:
setMaximumVickersHardness.
Definition at line 222 of file PrecipitateDissolutionModeling.cpp.
References minimumVickersHardness.
void Flood::PrecipitateDissolutionModeling::setMaximumVickersHardness (double newMaximumVickersHardness)
This method sets a new initial in the hardened state of an aluminium alloy.
Parameters:
newMaximumVickersHardness Maximum Vickers hardness value.
See also:
getMaximumVickersHardness.
Definition at line 236 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness.
void Flood::PrecipitateDissolutionModeling::setReferenceTemperature (double newReferenceTemperature)
This method sets a new temperature of reference associated to the time of reference for complete dissolution.
Parameters:
newReferenceTemperature Reference temperature value.
See also:
setReferenceTime.
Definition at line 250 of file PrecipitateDissolutionModeling.cpp.
References referenceTemperature.
void Flood::PrecipitateDissolutionModeling::setReferenceTime (double newReferenceTime)
This method sets a new reference time for complete dissolution of the precipitates at the reference temperature.
Parameters:
newReferenceTime Reference time value.
See also:
setReferenceTemperature.
Definition at line 265 of file PrecipitateDissolutionModeling.cpp.
References referenceTime.
void Flood::PrecipitateDissolutionModeling::setMinkowskiParameter (double newMinkowskiParameter)
This method sets a new Minkowski parameter (R-exponent) in the objective functional expression. This value must be comprised between 1 and 2.
Parameters:
newMinkowskiParameter Minkowski R-exponent value.
Definition at line 278 of file PrecipitateDissolutionModeling.cpp.
References minkowskiParameter.
void Flood::PrecipitateDissolutionModeling::setMinkowskiErrorWeight (double newMinkowskiErrorWeight)
This method sets a new weight value for the Minkowski error term in the objective functional expression.
Parameters:
newMinkowskiErrorWeight Minkowski R-value.
Definition at line 305 of file PrecipitateDissolutionModeling.cpp.
References minkowskiErrorWeight.
void Flood::PrecipitateDissolutionModeling::setRegularizationWeight (double newRegularizationWeight)
This method sets a new weight value for the regularization term (biases and synaptic weights decay) in the objective functional expression.
Parameters:
newRegularizationWeight Regularization term weight value.
Definition at line 333 of file PrecipitateDissolutionModeling.cpp.
References regularizationWeight.
void Flood::PrecipitateDissolutionModeling::loadVickersHardnessTest (char * filename)
This method loads the material properties and the Vickers hardness test of an aluminium alloy from a data file:
Minimum Vickers hardness.
Maximum Vickers hardness.
Reference time (s).
Reference temperature (ºC).
Experimental data (Temperature (ºC) - Time (s) - Vickers hardness).
Please mind about the file format.
Parameters:
filename Filename.
See also:
save(char*).
Definition at line 373 of file PrecipitateDissolutionModeling.cpp.
References Flood::ObjectiveFunctional::display, maximumVickersHardness, minimumVickersHardness, numberOfSamples, referenceTemperature, referenceTime, temperatureData, timeData, and vickersHardnessData.
double Flood::PrecipitateDissolutionModeling::getFullDissolutionTime (double temperature)
This method returns the time for complete dissolution of an aluminium alloy at a given temperature.
Parameters:
temperature Temperature value at which the full dissolution time is to be obtained.
Definition at line 467 of file PrecipitateDissolutionModeling.cpp.
References Flood::MultilayerPerceptron::getSingleIndependentParameter(), Flood::ObjectiveFunctional::multilayerPerceptron, referenceTemperature, referenceTime, and universalGasConstant.
Referenced by getNormalizedTimeData(), and saveInverseVickersHardnessTest().
double Flood::PrecipitateDissolutionModeling::getVolumetricFraction (double vickersHardness)
This method returns the volume fraction of precipitates as a function of the actual Vickers hardness.
Parameters:
vickersHardness Vickers hardness value.
Definition at line 486 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness, and minimumVickersHardness.
Referenced by getVolumetricFractionData().
double Flood::PrecipitateDissolutionModeling::getVickersHardness (double volumetricFraction)
This method returns the Vickers hardness as a function of the actual volume fraction of precipitates.
Parameters:
volumetricFraction Volumetric fraction value.
Definition at line 501 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness, and minimumVickersHardness.
Referenced by saveInverseVickersHardnessTest(), and saveVickersHardnessModel().
Vector< double > Flood::PrecipitateDissolutionModeling::getVolumetricFractionData (void)
This method returns a vector containing the volume fraction of hardening precipitates (1-f/f0) for the data samples in the Vickers hardness test.
Definition at line 537 of file PrecipitateDissolutionModeling.cpp.
References getNormalizedTimeData(), getVolumetricFraction(), numberOfSamples, and vickersHardnessData.
Referenced by calculateEvaluation(), savePrecipitateDissolutionModel(), and saveVickersHardnessModel().
Vector< double > Flood::PrecipitateDissolutionModeling::getNormalizedTimeData (void)
This method returns a vector containing the normalized time (log(t/t*)) for the data samples in the Vickers hardness test.
Definition at line 515 of file PrecipitateDissolutionModeling.cpp.
References getFullDissolutionTime(), numberOfSamples, temperatureData, and timeData.
Referenced by calculateEvaluation(), getVolumetricFractionData(), savePrecipitateDissolutionModel(), and saveVickersHardnessModel().
double Flood::PrecipitateDissolutionModeling::calculateEvaluation (void) [virtual]
This method returns the evaluation of a multilayer perceptron for modeling the hardening precipitates dissolution in fully hardened aluminium alloys. The objective functional here is composed by a Minkowski error term and a regularization term consisting on the norm of the bias and synaptic weights vector.
Implements Flood::ObjectiveFunctional.
Definition at line 563 of file PrecipitateDissolutionModeling.cpp.
References Flood::Vector< Type >::calculateNorm(), Flood::MultilayerPerceptron::calculateOutput(), Flood::MultilayerPerceptron::getNeuralParameters(), getNormalizedTimeData(), getVolumetricFractionData(), minkowskiErrorWeight, minkowskiParameter, Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, numberOfSamples, and regularizationWeight.
void Flood::PrecipitateDissolutionModeling::print (void) [virtual]
This method prints to the screen the actual effective activation energy of an aluminium alloy when training.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 665 of file PrecipitateDissolutionModeling.cpp.
References Flood::MultilayerPerceptron::getSingleIndependentParameter(), and Flood::ObjectiveFunctional::multilayerPerceptron.
void Flood::PrecipitateDissolutionModeling::printVickersHardnessTest (void)
This method prints the material properties and the Vickers hardness test of an aluminium alloy to the screen:
Minimum Vickers hardness.
Maximum Vickers hardness.
Reference time (s).
Reference temperature (ºC).
Experimental data (Temperature (ºC) - Time (s) - Vickers hardness).
See also:
load(char*).
save(char*).
Definition at line 630 of file PrecipitateDissolutionModeling.cpp.
References maximumVickersHardness, minimumVickersHardness, numberOfSamples, referenceTemperature, referenceTime, temperatureData, timeData, and vickersHardnessData.
void Flood::PrecipitateDissolutionModeling::savePrecipitateDissolutionModel (char * filename)
This method saves the volumetric fraction against the normalized time model to a data file. It also saves the related data.
Parameters:
filename Precipitate dissolution model filename.
See also:
saveVickersHardnessModel.
Definition at line 684 of file PrecipitateDissolutionModeling.cpp.
References Flood::Vector< Type >::begin(), Flood::MultilayerPerceptron::calculateOutput(), Flood::Vector< Type >::end(), getNormalizedTimeData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getSingleIndependentParameter(), getVolumetricFractionData(), Flood::ObjectiveFunctional::multilayerPerceptron, and numberOfSamples.
void Flood::PrecipitateDissolutionModeling::saveVickersHardnessModel (char * filename)
This method saves the Vickers hardness against the normalized time model to a data file. It also saves the related data.
Parameters:
filename Vickers hardness model filename.
See also:
saveVickersHardnessModel.
Definition at line 791 of file PrecipitateDissolutionModeling.cpp.
References Flood::Vector< Type >::begin(), Flood::MultilayerPerceptron::calculateOutput(), Flood::Vector< Type >::end(), getNormalizedTimeData(), Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), Flood::MultilayerPerceptron::getNumbersOfHiddenNeurons(), Flood::MultilayerPerceptron::getSingleIndependentParameter(), getVickersHardness(), getVolumetricFractionData(), Flood::ObjectiveFunctional::multilayerPerceptron, numberOfSamples, and vickersHardnessData.
void Flood::PrecipitateDissolutionModeling::saveInverseVickersHardnessTest (char * filename)
This method saves to a file a Vickers hardness test generated by the precipitate dissolution model in order to compare it to the experimental data.
Parameters:
filename Inverse Vickers hardness test filename.
Definition at line 895 of file PrecipitateDissolutionModeling.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), getFullDissolutionTime(), getVickersHardness(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Member Data Documentation
int Flood::PrecipitateDissolutionModeling::numberOfSamples [private]
Number of samples in Vickers hardness test.
Definition at line 39 of file PrecipitateDissolutionModeling.h.
Referenced by calculateEvaluation(), getNormalizedTimeData(), getVolumetricFractionData(), loadVickersHardnessTest(), PrecipitateDissolutionModeling(), printVickersHardnessTest(), savePrecipitateDissolutionModel(), and saveVickersHardnessModel().
Vector<double> Flood::PrecipitateDissolutionModeling::timeData [private]
Vector containing the time measurements for each sample in the test.
Definition at line 43 of file PrecipitateDissolutionModeling.h.
Referenced by getNormalizedTimeData(), loadVickersHardnessTest(), and printVickersHardnessTest().
Vector<double> Flood::PrecipitateDissolutionModeling::temperatureData [private]
Vector containing the temperature measurements for each sample in the test.
Definition at line 47 of file PrecipitateDissolutionModeling.h.
Referenced by getNormalizedTimeData(), loadVickersHardnessTest(), and printVickersHardnessTest().
Vector<double> Flood::PrecipitateDissolutionModeling::vickersHardnessData [private]
Vector containing the Vickers hardness measurements for each sample in the test.
Definition at line 51 of file PrecipitateDissolutionModeling.h.
Referenced by getVolumetricFractionData(), loadVickersHardnessTest(), printVickersHardnessTest(), and saveVickersHardnessModel().
double Flood::PrecipitateDissolutionModeling::universalGasConstant [private]
Universal gas constant R.
Definition at line 55 of file PrecipitateDissolutionModeling.h.
Referenced by getFullDissolutionTime(), and PrecipitateDissolutionModeling().
double Flood::PrecipitateDissolutionModeling::referenceTemperature [private]
Reference temperature of aluminium alloy.
Definition at line 59 of file PrecipitateDissolutionModeling.h.
Referenced by getFullDissolutionTime(), getReferenceTemperature(), loadVickersHardnessTest(), PrecipitateDissolutionModeling(), printVickersHardnessTest(), and setReferenceTemperature().
double Flood::PrecipitateDissolutionModeling::referenceTime [private]
Reference time of aluminium alloy.
Definition at line 63 of file PrecipitateDissolutionModeling.h.
Referenced by getFullDissolutionTime(), getReferenceTime(), loadVickersHardnessTest(), PrecipitateDissolutionModeling(), printVickersHardnessTest(), and setReferenceTime().
double Flood::PrecipitateDissolutionModeling::minimumVickersHardness [private]
Minimum Vickers hardness of aluminium alloy.
Definition at line 67 of file PrecipitateDissolutionModeling.h.
Referenced by getMinimumVickersHardness(), getVickersHardness(), getVolumetricFraction(), loadVickersHardnessTest(), PrecipitateDissolutionModeling(), printVickersHardnessTest(), and setMinimumVickersHardness().
double Flood::PrecipitateDissolutionModeling::maximumVickersHardness [private]
Maximum Vickers hardness of aluminium alloy.
Definition at line 71 of file PrecipitateDissolutionModeling.h.
Referenced by getMaximumVickersHardness(), getVickersHardness(), getVolumetricFraction(), loadVickersHardnessTest(), PrecipitateDissolutionModeling(), printVickersHardnessTest(), and setMaximumVickersHardness().
double Flood::PrecipitateDissolutionModeling::minkowskiParameter [private]
Minkowski parameter in the objective functional expression.
Definition at line 75 of file PrecipitateDissolutionModeling.h.
Referenced by calculateEvaluation(), getMinkowskiParameter(), PrecipitateDissolutionModeling(), and setMinkowskiParameter().
double Flood::PrecipitateDissolutionModeling::minkowskiErrorWeight [private]
Weight value of the Minkowski error term in the objective functional expression.
Definition at line 79 of file PrecipitateDissolutionModeling.h.
Referenced by calculateEvaluation(), getMinkowskiErrorWeight(), PrecipitateDissolutionModeling(), and setMinkowskiErrorWeight().
double Flood::PrecipitateDissolutionModeling::regularizationWeight [private]
Weight value of the regularization term in the objective functional expression.
Definition at line 83 of file PrecipitateDissolutionModeling.h.
Referenced by calculateEvaluation(), getRegularizationWeight(), PrecipitateDissolutionModeling(), and setRegularizationWeight().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/PrecipitateDissolutionModeling.h
G:/Documents/Flood/Flood/ObjectiveFunctional/PrecipitateDissolutionModeling.cpp