Flood: Flood::IsoperimetricProblem Class Reference
Flood::IsoperimetricProblem Class Reference
#include <IsoperimetricProblem.h>
Public Member Functions
IsoperimetricProblem (MultilayerPerceptron *)
IsoperimetricProblem (void)
virtual ~IsoperimetricProblem (void)
Destructor.
double getPerimeterGoal (void)
This method returns the closed curve perimeter goal for the isoperimetric problem.
double getAreaWeight (void)
This method returns the weight of the area term in the objective functional expression.
double getPerimeterErrorWeight (void)
This method returns the weight of the perimeter error term in the objective functional expression.
double getTolerance (void)
int getInitialSize (void)
void setPerimeterGoal (double)
void setAreaWeight (double)
void setPerimeterErrorWeight (double)
void setTolerance (double)
void setInitialSize (int)
Vector< double > calculateParticularSolution (Vector< double >)
Vector< double > calculateHomogeneousSolution (Vector< double >)
Vector< double > calculateParticularSolutionDerivative (Vector< double >)
Vector< double > calculateHomogeneousSolutionDerivative (Vector< double >)
double calculateAreaIntegrand (double, double)
double calculateArea (void)
double calculatePerimeterIntegrand (double, double)
double calculatePerimeter (void)
double calculatePerimeterError (void)
double calculateEvaluation (void)
void saveResults (char *)
void print (void)
Private Attributes
double perimeterGoal
Closed curve perimeter goal.
double perimeterErrorWeight
Perimeter error term weight in the objective functional.
double areaWeight
Area term weight in the objective functional.
double tolerance
Tolerance in the Runge-Kutta-Fehlberg method.
int initialSize
Number of points to reserve for the Runge-Kutta-Fehlberg method.
OrdinaryDifferentialEquations ordinaryDifferentialEquations
Ordinary differential equations object.
Detailed Description
This class represents the objective functional of a multilayer perceptron for the isoperimetric problem with parametric equations. This is a variational problem with one input and two output variables, four boundary conditions and one constraint in the objective functional, which is evaluated by integrating two functions.
See also:
ObjectiveFunctional.
OrdinaryDifferentialEquations.
Definition at line 33 of file IsoperimetricProblem.h.
Constructor & Destructor Documentation
Flood::IsoperimetricProblem::IsoperimetricProblem (MultilayerPerceptron * newMultilayerPerceptron)
General constructor. It creates a isoperimetric problem with parametric equations objective functional associated to a multilayer perceptron. It also initializes all the problem parameters to their default values:
Perimeter goal: 1.0.
Perimeter error weight: 1.0.
Area weight: 1.0e-3.
Tolerance: 1.0e-15.
Initial size: 5e3.
Parameters:
newMultilayerPerceptron Pointer to a multilayer perceptron object.
Definition at line 42 of file IsoperimetricProblem.cpp.
References areaWeight, Flood::MultilayerPerceptron::getNumberOfInputs(), Flood::MultilayerPerceptron::getNumberOfOutputs(), initialSize, Flood::ObjectiveFunctional::multilayerPerceptron, ordinaryDifferentialEquations, perimeterErrorWeight, perimeterGoal, Flood::OrdinaryDifferentialEquations::setInitialSize(), Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
Flood::IsoperimetricProblem::IsoperimetricProblem (void)
Default constructor. It creates a isoperimetric problem with parametric equations objective functional not associated to any multilayer perceptron. It also initializes all the problem parameters to their default values:
Perimeter goal: 1.0.
Perimeter error weight: 1.0.
Area weight: 1.0e-3.
Tolerance: 1.0e-15.
Initial size: 5e3.
Definition at line 90 of file IsoperimetricProblem.cpp.
References areaWeight, initialSize, perimeterErrorWeight, perimeterGoal, and tolerance.
Flood::IsoperimetricProblem::~IsoperimetricProblem (void) [virtual]
Destructor.
Definition at line 106 of file IsoperimetricProblem.cpp.
Member Function Documentation
double Flood::IsoperimetricProblem::getPerimeterGoal (void)
This method returns the closed curve perimeter goal for the isoperimetric problem.
Definition at line 118 of file IsoperimetricProblem.cpp.
References perimeterGoal.
double Flood::IsoperimetricProblem::getAreaWeight (void)
This method returns the weight of the area term in the objective functional expression.
Definition at line 128 of file IsoperimetricProblem.cpp.
References areaWeight.
double Flood::IsoperimetricProblem::getPerimeterErrorWeight (void)
This method returns the weight of the perimeter error term in the objective functional expression.
Definition at line 138 of file IsoperimetricProblem.cpp.
References perimeterErrorWeight.
double Flood::IsoperimetricProblem::getTolerance (void)
This method returns the tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the perimeter error and the area of the closed curve.
Definition at line 149 of file IsoperimetricProblem.cpp.
References tolerance.
int Flood::IsoperimetricProblem::getInitialSize (void)
This method returns the number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the perimeter error and the area of the closed curve.
Definition at line 160 of file IsoperimetricProblem.cpp.
References initialSize.
void Flood::IsoperimetricProblem::setPerimeterGoal (double newPerimeterGoal)
This method sets a new value for the closed curve perimeter goal in the isoperimetric problem.
Parameters:
newPerimeterGoal Closed curve perimeter goal value.
Definition at line 172 of file IsoperimetricProblem.cpp.
References perimeterGoal.
void Flood::IsoperimetricProblem::setAreaWeight (double newAreaWeight)
This method sets a new value for the weight of the area term in the objective functional expression.
Parameters:
newAreaWeight Area term weight value.
Definition at line 199 of file IsoperimetricProblem.cpp.
References areaWeight.
void Flood::IsoperimetricProblem::setPerimeterErrorWeight (double newPerimeterErrorWeight)
This method sets a new value for the weight of the perimeter error term in the objective functional expression.
Parameters:
newPerimeterErrorWeight Perimeter error term weight value.
Definition at line 227 of file IsoperimetricProblem.cpp.
References perimeterErrorWeight.
void Flood::IsoperimetricProblem::setTolerance (double newTolerance)
This method sets a new tolerance value to be used in the Runge-Kutta-Fehlberg method for evaluating the perimeter and the area of the closed curve.
Parameters:
newTolerance Tolerance in Runge-Kutta-Fehlberg method.
Definition at line 255 of file IsoperimetricProblem.cpp.
References ordinaryDifferentialEquations, Flood::OrdinaryDifferentialEquations::setTolerance(), and tolerance.
void Flood::IsoperimetricProblem::setInitialSize (int newInitialSize)
This method sets a new number of points to be reserved when using the Runge-Kutta-Fehlberg method for evaluating the perimeter and the area of the closed curve.
Parameters:
newInitialSize Number of points to reserve in Runge-Kutta-Fehlberg method.
Definition at line 285 of file IsoperimetricProblem.cpp.
References initialSize, ordinaryDifferentialEquations, and Flood::OrdinaryDifferentialEquations::setInitialSize().
Vector< double > Flood::IsoperimetricProblem::calculateParticularSolution (Vector< double > input)
This method returns the particular solution term in order to satisfy the boundary conditions in the isoperimetric problem. It holds phi0(a)=ya if there is a condition y(a)=ya.
Parameters:
input Value of independent variable t.
See also:
calculateHomogeneousSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 305 of file IsoperimetricProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::IsoperimetricProblem::calculateHomogeneousSolution (Vector< double > input)
This method returns the homogeneous solution term in order to satisfy the boundary conditions in the isoperimetric problem. It must hold phi1(a)=0 if there is a condition y(a)=ya.
Parameters:
input Value of independent variable t.
See also:
calculateParticularSolution.
calculateParticularSolutionDerivative.
calculateHomogeneousSolutionDerivative.
Definition at line 344 of file IsoperimetricProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::IsoperimetricProblem::calculateParticularSolutionDerivative (Vector< double > input)
This method returns the derivative of the particular solution term for the boundary conditions. It is used to calculate the derivatives x'(t)=dx/dt and y'(t)=dy/dt.
Parameters:
input Value of independent variable t.
See also:
calculateParticularSolution.
calculateHomogeneousSolution.
calculateHomogeneousSolutionDerivative.
Definition at line 385 of file IsoperimetricProblem.cpp.
References Flood::Vector< Type >::getSize().
Vector< double > Flood::IsoperimetricProblem::calculateHomogeneousSolutionDerivative (Vector< double > input)
This method returns the derivative of the homogeneous solution term for the boundary conditions. It is used to calculate the derivatives x'(t)=dx/dt and y'(t)=dy/dt.
Parameters:
input Value of independent variable t.
See also:
calculateParticularSolution.
calculateHomogeneousSolution.
calculateParticularSolutionDerivative.
Definition at line 423 of file IsoperimetricProblem.cpp.
References Flood::Vector< Type >::getSize().
double Flood::IsoperimetricProblem::calculateAreaIntegrand (double t, double dummy)
This method returns the area integrand for a value of of the independent variable t.
Parameters:
t Value of independent variable.
dummy Dummy variable to allow integration with the Runge-Kutta-Fehlberg method.
See also:
calculateArea.
Definition at line 462 of file IsoperimetricProblem.cpp.
References Flood::MultilayerPerceptron::calculateJacobian(), Flood::MultilayerPerceptron::calculateOutput(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculateArea().
double Flood::IsoperimetricProblem::calculateArea (void)
This method integrates the area integrand function to obtain the area enclosed by the function represented by the neural network.
See also:
calculateAreaIntegrand.
Definition at line 514 of file IsoperimetricProblem.cpp.
References calculateAreaIntegrand(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), and ordinaryDifferentialEquations.
Referenced by calculateEvaluation(), and print().
double Flood::IsoperimetricProblem::calculatePerimeterIntegrand (double t, double dummy)
This method returns the perimeter integrand for a value of the independent variable t.
Parameters:
t Value of independent variable.
dummy Dummy variable to allow integration with the Runge-Kutta-Fehlberg method.
See also:
calculatePerimeter.
Definition at line 541 of file IsoperimetricProblem.cpp.
References Flood::MultilayerPerceptron::calculateJacobian(), and Flood::ObjectiveFunctional::multilayerPerceptron.
Referenced by calculatePerimeter().
double Flood::IsoperimetricProblem::calculatePerimeter (void)
This method integrates the perimeter integrand function to obtain the arc length of the function represented by the neural network.
See also:
calculatePerimeterIntegrand.
Definition at line 586 of file IsoperimetricProblem.cpp.
References calculatePerimeterIntegrand(), Flood::OrdinaryDifferentialEquations::calculateRungeKuttaFehlbergIntegral(), and ordinaryDifferentialEquations.
Referenced by calculatePerimeterError().
double Flood::IsoperimetricProblem::calculatePerimeterError (void)
This method returns the error between the perimeter goal and the arc lenght of the function represented by the neural network.
Definition at line 609 of file IsoperimetricProblem.cpp.
References calculatePerimeter(), and perimeterGoal.
Referenced by calculateEvaluation(), and print().
double Flood::IsoperimetricProblem::calculateEvaluation (void) [virtual]
This method returns the evaluation of a multilayer perceptron for the isoperimetric problem with parametric equations.
Implements Flood::ObjectiveFunctional.
Definition at line 624 of file IsoperimetricProblem.cpp.
References areaWeight, calculateArea(), calculatePerimeterError(), Flood::ObjectiveFunctional::multilayerPerceptron, Flood::ObjectiveFunctional::numberOfEvaluations, and perimeterErrorWeight.
void Flood::IsoperimetricProblem::saveResults (char * filename)
This method saves the values of the independent and dependent variables for the isoperimetric problem with parametric equations to a data file.
Value of independent variable (t).
Value of dependent variable x.
Value of dependent variable y.
Parameters:
filename Filename.
Definition at line 668 of file IsoperimetricProblem.cpp.
References Flood::MultilayerPerceptron::calculateOutput(), Flood::ObjectiveFunctional::display, and Flood::ObjectiveFunctional::multilayerPerceptron.
void Flood::IsoperimetricProblem::print (void) [virtual]
This method prints to the screen useful information about the isoperimetric problem with parametric equations objective functional of a multilayer perceptron:
Perimeter error.
Area.
Reimplemented from Flood::ObjectiveFunctional.
Definition at line 750 of file IsoperimetricProblem.cpp.
References calculateArea(), and calculatePerimeterError().
Member Data Documentation
double Flood::IsoperimetricProblem::perimeterGoal [private]
Closed curve perimeter goal.
Definition at line 40 of file IsoperimetricProblem.h.
Referenced by calculatePerimeterError(), getPerimeterGoal(), IsoperimetricProblem(), and setPerimeterGoal().
double Flood::IsoperimetricProblem::perimeterErrorWeight [private]
Perimeter error term weight in the objective functional.
Definition at line 44 of file IsoperimetricProblem.h.
Referenced by calculateEvaluation(), getPerimeterErrorWeight(), IsoperimetricProblem(), and setPerimeterErrorWeight().
double Flood::IsoperimetricProblem::areaWeight [private]
Area term weight in the objective functional.
Definition at line 48 of file IsoperimetricProblem.h.
Referenced by calculateEvaluation(), getAreaWeight(), IsoperimetricProblem(), and setAreaWeight().
double Flood::IsoperimetricProblem::tolerance [private]
Tolerance in the Runge-Kutta-Fehlberg method.
Definition at line 52 of file IsoperimetricProblem.h.
Referenced by getTolerance(), IsoperimetricProblem(), and setTolerance().
int Flood::IsoperimetricProblem::initialSize [private]
Number of points to reserve for the Runge-Kutta-Fehlberg method.
Definition at line 56 of file IsoperimetricProblem.h.
Referenced by getInitialSize(), IsoperimetricProblem(), and setInitialSize().
OrdinaryDifferentialEquations Flood::IsoperimetricProblem::ordinaryDifferentialEquations [private]
Ordinary differential equations object.
Definition at line 60 of file IsoperimetricProblem.h.
Referenced by calculateArea(), calculatePerimeter(), IsoperimetricProblem(), setInitialSize(), and setTolerance().
The documentation for this class was generated from the following files:
G:/Documents/Flood/Flood/ObjectiveFunctional/IsoperimetricProblem.h
G:/Documents/Flood/Flood/ObjectiveFunctional/IsoperimetricProblem.cpp